act_code: '76947'
requisite: Совместный приказ Председателя Агентства Республики Казахстан по регулированию естественных монополий от 30 декабря 2013 года № 404-ОД и Министра нефти и газа Республики Казахстан от 30 декабря 2013 года № 244. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 декабря 2013 года № 9054. Утратил силу совместным приказом Министра национальной экономики Республики Казахстан от 24 февраля 2020 года № 12 и Министра энергетики Республики Казахстан от 25 февраля 2020 года № 60 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня видов деятельности, технологически связанных с регулируемыми услугами (товарами, работами) в сфере по транспортировке нефти и (или) нефтепродуктов по магистральным трубопроводам, за исключением их транспортировки в целях транзита через территорию Республики Казахстан и экспорта за пределы Республики Казахстан
  kaz: Қазақстан Республикасының аумағы арқылы транзиттеу және Қазақстан Республикасының шегінен тыс жерге экспорттау мақсатында мұнайды және (немесе) мұнай өнімдерін тасымалдауды қоспағанда, оларды магистральдық құбырлар арқылы тасымалдау саласындағы реттеліп көрсетілетін қызметтермен (тауарлармен, жұмыстармен) технологиялық байланысты қызмет түрлерінің тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2013-12-30
approved_by:
- '103018000000'
- '113000000000'
version_date:
  kaz: 2013-12-30
  rus: 2013-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/76947/kaz/30.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76947/rus/30.12.2013
