act_code: '93070'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 12 июня 2015 года № 7-1/529. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 августа 2015 года № 11893
title:
  rus: Об утверждении цен на работы, услуги, производимые и (или) реализуемые субъектом государственной монополии в области ветеринарии
  kaz: Ветеринария саласындағы мемлекеттік монополия субъектісі өндіретін және (немесе) өткізетін жұмыстардың, көрсетілетін қызметтердің бағаларын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2015-06-12
approved_by:
- '103012000000'
version_date:
  kaz: 2024-03-13
  rus: 2024-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/93070/kaz/13.03.2024
  rus: https://zan.gov.kz/client/#!/doc/93070/rus/13.03.2024
caused_by:
  code: '194406'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 13 марта 2024 года № 95
  title:
    rus: О внесении изменений в приказ Министра сельского хозяйства Республики Казахстан от 12 июня 2015 года № 7-1/529 «Об утверждении цен на работы, услуги, производимые и (или) реализуемые субъектом государственной монополии в области ветеринарии»
    kaz: «Ветеринария саласындағы мемлекеттік монополия субъектісі өндіретін және (немесе) өткізетін жұмыстардың, көрсетілетін қызметтердің бағаларын бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің 2015 жылғы 12 маусымдағы № 7-1/529 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194406/rus
