act_code: '132325'
requisite: Приказ Министра национальной экономики Республики Казахстан от 31 мая 2019 года № 48. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 июня 2019 года № 18771
title:
  rus: Об утверждении Типовых правил погребения и организации дела по уходу за могилами
  kaz: Жерлеудің және зираттарды күтіп ұстау ісін ұйымдастырудың үлгілік қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2019-05-31
approved_by:
- '103033000000'
version_date:
  kaz: 2024-02-23
  rus: 2024-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/132325/kaz/23.02.2024
  rus: https://zan.gov.kz/client/#!/doc/132325/rus/23.02.2024
caused_by:
  code: '193672'
  requisite: Приказ Заместителя Премьер-Министра - Министра национальной экономики Республики Казахстан от 23 февраля 2024 года № 6. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 февраля 2024 года № 34049
  title:
    rus: О внесении изменений в приказ Министра национальной экономики Республики Казахстан от 31 мая 2019 года № 48 «Об утверждении Типовых правил погребения и организации дела по уходу за могилами»
    kaz: «Жерлеудің және зираттарды күтіп ұстау ісін ұйымдастырудың үлгілік қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық экономика министрінің 2019 жылғы 31 мамырдағы № 48 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193672/rus
