act_code: '12167'
requisite: Приказ Министра государственных доходов Республики Казахстан от 18 апреля 2002 года N 445. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 мая 2002 года N 1857. Утратил силу приказом Министра финансов Республики Казахстан от 9 января 2009 года № 5
title:
  rus: Об утверждении Правил проведения хронометражных обследований
  kaz: Хронометраждық зерттеулер өткізу ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2002-04-17
approved_by:
- '103019000000'
version_date:
  kaz: 2002-04-17
  rus: 2002-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/12167/kaz/17.04.2002
  rus: https://zan.gov.kz/client/#!/doc/12167/rus/17.04.2002
