act_code: '199847'
requisite: Приказ Министра промышленности и строительства Республики Казахстан от 19 августа 2024 года № 304. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 августа 2024 года № 34954. Утратил силу приказом Министра промышленности и строительства Республики Казахстан от 21 октября 2024 года № 370 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О некоторых вопросах регулирования вывоза лома и отходов черных металлов
  kaz: Қара металдардың сынықтары мен қалдықтарын әкетуді реттеудің кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2024-08-19
approved_by:
- '103052000000'
version_date:
  kaz: 2024-08-19
  rus: 2024-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/199847/kaz/19.08.2024
  rus: https://zan.gov.kz/client/#!/doc/199847/rus/19.08.2024
