act_code: '13286'
requisite: Приказ Министра финансов Республики Казахстан от 18 сентября 2002 года N 438. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 октября 2002 года N 1992. Утратил силу приказом Министра финансов Республики Казахстан от 23 мая 2007 года N 185 (вводится в действие с 1 января 2008 года)
title:
  rus: Об утверждении Типового плана счетов бухгалтерского учета
  kaz: Бухгалтерлiк есепке алу шоттарының үлгi жоспарын бекiту туралы
form: ПРИК
type_codes:
- ПЛАН
- ПРИК
approved_on: 2002-09-17
approved_by:
- '103002000000'
version_date:
  kaz: 2003-10-20
  rus: 2003-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/13286/kaz/20.10.2003
  rus: https://zan.gov.kz/client/#!/doc/13286/rus/20.10.2003
caused_by:
  code: '17429'
  requisite: Приказ Министра финансов Республики Казахстан от 21 октября 2003 года N 372. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 ноября 2003 года N 2554. Утратил силу - приказом Министра финансов Республики Казахстан от 23 мая 2007 года N 185 (вводится в действие с 1 января 2008 года)
  title:
    rus: О внесении изменений в приказ Министра финансов Республики Казахстан от 18 сентября 2002 года N 438 "Об утверждении Типового плана счетов бухгалтерского учета" зарегистрирован в Министерстве юстиции Республики Казахстан 2 октября 2002 года N 1992
    kaz: Қазақстан Республикасының Әділет министрлінде 2002 жылғы 2 қазанда N 1992 тіркелген "Бухгалтерлік есеп шоттарының үлгілік жоспарын бекіту туралы" Қазақстан Республикасы Қаржы министрінің 2002 жылғы 18.09.2002ж. N 438 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/17429/rus
