act_code: '88030'
requisite: Приказ Министра национальной экономики Республики Казахстан от 17 марта 2015 года № 212. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 марта 2015 года № 10467
title:
  rus: Об утверждении Правил передачи государственного имущества в имущественный наем (аренду)
  kaz: Мемлекеттік мүлікті мүліктік жалдауға (жалға алуға) беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-03-17
approved_by:
- '103033000000'
version_date:
  kaz: 2026-04-27
  rus: 2026-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/88030/kaz/27.04.2026
  rus: https://zan.gov.kz/client/#!/doc/88030/rus/27.04.2026
caused_by:
  code: '224679'
  requisite: Приказ и.о. Министра национальной экономики Республики Казахстан от 27 апреля 2026 года № 33. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 апреля 2026 года № 38572
  title:
    rus: О внесении изменения в приказ Министра национальной экономики Республики Казахстан от 17 марта 2015 года № 212 «Об утверждении Правил передачи государственного имущества в имущественный наем (аренду)»
    kaz: «Мемлекеттік мүлікті мүліктік жалдауға (жалға алуға) беру қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық экономика министрінің 2015 жылғы 17 наурыздағы № 212 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224679/rus
