act_code: '48428'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 28 сентября 2009 года № 554. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 октября 2009 года № 5832. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 25 июня 2014 года № 7-1/322
title:
  rus: Об утверждении Инструкции по осуществлению ветеринарно-санитарного контроля объектов государственного ветеринарно-санитарного контроля
  kaz: Мемлекеттік ветеринариялық-санитариялық бақылау объектілерінде ветеринариялық-санитариялық бақылауды жүзеге асыру туралы нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2009-09-28
approved_by:
- '103012000000'
version_date:
  kaz: 2009-09-28
  rus: 2009-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/48428/kaz/28.09.2009
  rus: https://zan.gov.kz/client/#!/doc/48428/rus/28.09.2009
