act_code: '133711'
requisite: Приказ и.о. Министра торговли и интеграции Республики Казахстан от 25 июля 2019 года № 9
title:
  rus: Об утверждении положений Республиканского государственного учреждения «Комитет технического регулирования и метрологии Министерства торговли и интеграции Республики Казахстан» и его территориальных подразделений
  kaz: «Қазақстан Республикасы Сауда және интеграция министрлігі Техникалық peттеу және метрология комитеті» республикалық мемлекеттік мекемесінің және оның aумақтық бөлімшелерінің ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2019-07-25
approved_by:
- '103046000000'
version_date:
  kaz: 2021-11-08
  rus: 2021-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/133711/kaz/08.11.2021
  rus: https://zan.gov.kz/client/#!/doc/133711/rus/08.11.2021
caused_by:
  code: '160274'
  requisite: Приказ Министра торговли и интеграции Республики Казахстан от 8 ноября 2021 года № 588-НҚ
  title:
    rus: О внесении изменений и дополнений в приказ исполняющего обязанности Министра торговли и интеграции Республики Казахстан от 25 июля 2019 года № 9 «Об утверждении положений Республиканского государственного учреждения «Комитет технического регулирования и метрологии Министерства торговли и интеграции Республики Казахстан» и его территориальных подразделений»
    kaz: «Қазақстан Республикасы Сауда және интеграция министрлігінің Техникалық реттеу және метрология комитеті республикалық мемлекеттік мекемесінің және оның аумақтық бөлімшелерінің ережелерін бекіту туралы» Қазақстан Республикасы Сауда және интеграция министрінің міндетін атқарушының 2019 жылғы 25 шілдедегі № 9 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160274/rus
