act_code: '62502'
requisite: Приказ Генерального Прокурора Республики Казахстан от 16 ноября 2011 года № 107. Зарегистрировано в Министерстве юстиции Республики Казахстан от 13 декабря 2011 года № 7338. Утратил силу приказом Генерального прокурора Республики Казахстан от 1 июля 2014 года № 67
title:
  rus: Об утверждении регламента государственной услуги "Выдача архивных справок и/или копий архивных документов в пределах архивов Комитета по правовой статистике и специальным учетам Генеральной прокуратуры Республики Казахстан и его территориальных управлений"
  kaz: '"Қазақстан Республикасы Бас прокуратурасы Құқықтық статистика және арнайы есепке алу жөніндегі комитетінің және оның аумақтық басқармаларының мұрағаттары шеңберінде мұрағаттық анықтамаларды және/немесе мұрағаттық құжат көшірмелерін беру" мемлекеттік қызмет көрсету регламентін бекіту туралы'
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2011-11-16
approved_by:
- '107000000000'
version_date:
  kaz: 2011-11-16
  rus: 2011-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/62502/kaz/16.11.2011
  rus: https://zan.gov.kz/client/#!/doc/62502/rus/16.11.2011
