act_code: '13038'
requisite: Приказ Министра транспорта и коммуникаций Республики Казахстан от 17 июля 2002 года № 251-I. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 августа 2002 года № 1956
title:
  rus: Об утверждении Правил выдачи Свидетельства о страховании или ином финансовом обеспечении гражданской ответственности за ущерб от загрязнения нефтью
  kaz: Мұнайдан болатын ластанудан залал үшін азаматтық жауапкершілікті сақтандыру немесе өзге де қаржылық қамтамасыз ету туралы куәлік беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2002-07-17
approved_by:
- '103013000000'
version_date:
  kaz: 2025-06-29
  rus: 2025-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/13038/kaz/29.06.2025
  rus: https://zan.gov.kz/client/#!/doc/13038/rus/29.06.2025
caused_by:
  code: '209547'
  requisite: Приказ и.о. Министра транспорта Республики Казахстан от 21 апреля 2025 года № 129. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 апреля 2025 года № 36025
  title:
    rus: О внесении изменений в приказы Министра транспорта и коммуникаций Республики Казахстан и Министра индустрии и инфраструктурного развития Республики Казахстан
    kaz: Қазақстан Республикасы Көлік және коммуникация министрінің және Қазақстан Республикасы Индустрия және инфрақұрылымдық даму министрінің бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209547/rus
