act_code: '150073'
requisite: Приказ Министра здравоохранения Республики Казахстан от 15 декабря 2020 года № ҚР ДСМ-268/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 декабря 2020 года № 21812
title:
  rus: Об утверждении перечня декретированной группы населения, подлежащей гигиеническому обучению
  kaz: Гигиеналық оқытуға жататын халықтың декреттелген тобының тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2020-12-15
approved_by:
- '103010000000'
version_date:
  kaz: 2020-12-15
  rus: 2020-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/150073/kaz/15.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150073/rus/15.12.2020
