act_code: '92019'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 20 апреля 2015 года № 7-1/347. Зарегистрирован в Министерстве юстиции Республики Казахстан 9 июля 2015 года № 11608.  Утратил силу приказом и.о. Министра сельского хозяйства Республики Казахстан от 24 мая 2024 года № 178 (вводится в действие с 8 июня 2024 года)
title:
  rus: Об утверждении Правил осуществления государственного ветеринарно-санитарного  контроля и надзора, а также определения соответствия животных, продукции и сырья животного происхождения ветеринарным нормативам в объектах производства, осуществляющих выращивание животных, заготовку (убой), хранение, переработку и реализацию животных, продукции и сырья животного происхождения, включая экспортеров (импортеров)
  kaz: Экспорттаушыларды (импорттаушыларды) қоса алғанда, жануарлар өсіруді, жануарларды және жануарлардан алынатын өнімдер мен шикізатты дайындауды (союды), сақтауды, қайта өңдеуді және өткізуді жүзеге асыратын өндіріс объектілерінде мемлекеттік ветеринариялық-санитариялық бақылауды және қадағалауды жүзеге асыру, сондай-ақ жануарлардың, жануарлардан алынатын өнімдер мен шикізаттың ветеринариялық нормативтерге сәйкестігін айқындау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-04-20
approved_by:
- '103012000000'
version_date:
  kaz: 2015-04-20
  rus: 2015-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/92019/kaz/20.04.2015
  rus: https://zan.gov.kz/client/#!/doc/92019/rus/20.04.2015
