act_code: '200415'
requisite: Приказ Министра культуры и информации Республики Казахстан от 5 сентября 2024 года № 408-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 сентября 2024 года № 35036
title:
  rus: Об утверждении Правил проведения конкурса по формированию перечня теле-, радиоканалов свободного доступа, распространяемых национальным оператором телерадиовещания
  kaz: Телерадио хабарларын таратудың ұлттық операторы тарататын еркін қолжетімді теле-, радиоарналардың тізбесін қалыптастыру бойынша конкурс өткізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2024-09-05
approved_by:
- '103053000000'
version_date:
  kaz: 2024-09-05
  rus: 2024-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/200415/kaz/05.09.2024
  rus: https://zan.gov.kz/client/#!/doc/200415/rus/05.09.2024
