act_code: '92699'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 26 июня 2015 года № 15-07/572. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 июля 2015 года № 11810. Утратил силу приказом и.о. Министра сельского хозяйства Республики Казахстан от 15 апреля 2025 года № 108 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об утверждении натуральных норм обеспечения государственных организаций, осуществляющих фитосанитарный мониторинг
  kaz: Фитосанитариялық мониторингті жүзеге асыратын мемлекеттік ұйымдарды қамтамасыз етудің заттай нормаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2015-06-26
approved_by:
- '103012000000'
version_date:
  kaz: 2024-02-13
  rus: 2024-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/92699/kaz/13.02.2024
  rus: https://zan.gov.kz/client/#!/doc/92699/rus/13.02.2024
caused_by:
  code: '193260'
  requisite: Приказ и.о. Министра сельского хозяйства Республики Казахстан от 13 февраля 2024 года № 58. Утратил силу приказом и.о. Министра сельского хозяйства Республики Казахстан от 15 апреля 2025 года № 108 (вводится в действие после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра сельского хозяйства Республики Казахстан от 26 июня 2015 года № 15-07/572 «Об утверждении натуральных норм обеспечения государственных организаций, осуществляющих фитосанитарный мониторинг»
    kaz: «Фитосанитариялық мониторингті жүзеге асыратын мемлекеттік ұйымдарды қамтамасыз етудің заттай нормаларын бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің 2015 жылғы 26 маусымдағы № 15-07/572 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193260/rus
