act_code: '81101'
requisite: Қазақстан Республикасы Көлік және коммуникация министрінің 2014 жылғы 25 сәуірдегі № 276 және Қазақстан Республикасы Премьер-Министрінің орынбасары - Қазақстан Республикасы Қаржы министрінің 2014 жылғы 30 сәуірдегі № 198 Бірлескен бұйрығы. Қазақстан Республикасының Әділет министрлігінде 2014 жылы 9 маусымда № 9489 тіркелді. Күші жойылды - Қазақстан Республикасы Инвестициялар және даму министрінің 2015 жылғы 29 мамырдағы № 672 және Қазақстан Республикасы Қаржы министрінің 2015 жылғы 31 желтоқсандағы № 739 бірлескен бұйрығымен
title:
  rus: Об утверждении Регламента государственной услуги "Выдача специального разрешения на проезд тяжеловесных и (или) крупногабаритных транспортных средств (включая иностранные) по территории Республики Казахстан
  kaz: Қазақстан Республикасының аумағы арқылы ауыр салмақты және (немесе) iрi көлемді көлiк құралдарының (шетелдiктердi қоса алғанда) жүрiп өтуі үшін арнайы рұқсат беру" мемлекеттік көрсетілетін қызмет регламентін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2014-04-25
approved_by:
- '103013000000'
version_date:
  rus: 2015-05-29
source:
  rus: https://zan.gov.kz/client/#!/doc/81101/rus/29.05.2015
caused_by:
  code: '102696'
  requisite: Совместный приказ Министра по инвестициям и развитию Республики Казахстан от 29 мая 2015 года № 672 и Министра финансов Республики Казахстан от 31 декабря 2015 года № 739. Зарегистрирован в Министерстве юстиции Республики Казахстан 9 февраля 2016 года № 13029. Утратил силу совместным приказом и.о. Министра индустрии и инфраструктурного развития Республики Казахстан от 7 октября 2020 года № 518 и Министра финансов Республики Казахстан от 12 октября 2020 года № 992 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: Об утверждении регламента государственной услуги «Выдача специального разрешения на проезд тяжеловесных и (или) крупногабаритных транспортных средств (включая иностранные) по территории Республики Казахстан»
    kaz: «Қазақстан Республикасының аумағы арқылы ауыр салмақты және (немесе) ірі көлемді көлік құралдарының (шетелдік көліктерді қоса алғанда) жүріп өтуі үшін арнайы рұқсат беру» мемлекеттік көрсетілетін қызмет регламентін бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/102696/rus
