act_code: '78816'
requisite: Приказ Министра транспорта и коммуникаций Республики Казахстан от 18 декабря 2013 года № 1012. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 марта 2014 года № 9282. Утратил силу приказом Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 5 февраля 2021 года № 40/НҚ (вводится в действие по истечении десяти календарного дня после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил установления причины несоответствия подлинности электронных цифровых подписей электронных документов
  kaz: Электрондық құжаттардың электрондық цифрлық қолтаңбасы түпнұсқалығының сәйкессіздігі себептерін анықтаудың қағидасын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2013-12-18
approved_by:
- '103013000000'
version_date:
  kaz: 2013-12-18
  rus: 2013-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/78816/kaz/18.12.2013
  rus: https://zan.gov.kz/client/#!/doc/78816/rus/18.12.2013
