act_code: '93636'
requisite: Приказ и.о. Министра по инвестициям и развитию Республики Казахстан от 26 июня 2015 года № 730. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 июля 2015 года № 11764. Утратил силу приказом Министра торговли и интеграции Республики Казахстан от 14 сентября 2020 года № 197-НҚ (вводится в действие по истечении двадцати одного календарного дня после дня его первого официального опубликования)
title:
  rus: Об утверждении стандартов государственных услуг в области технического регулирования и метрологии
  kaz: Техникалық реттеу және метрология саласындағы мемлекеттік көрсетілетін қызметтер стандарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2015-06-26
approved_by:
- '103035000000'
version_date:
  kaz: 2015-06-26
  rus: 2015-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/93636/kaz/26.06.2015
  rus: https://zan.gov.kz/client/#!/doc/93636/rus/26.06.2015
