act_code: '2833'
requisite: Приказ Таможенного комитета Министерства государственных доходов Республики Казахстан от 10 марта 1999 года N 53-П. Зарегистрирован в Министерстве юстиции Республики Казахстан 28.04.1999 г. за N 744. Утратил силу - приказом Таможенного Комитета МГД РК от 15 февраля 2001 г. N 51
title:
  rus: О местах таможенного оформления природного газа, перемещаемого трубопроводным транспортом
  kaz: Құбырлы көлік арқылы өткізілетін табиғи газдарды кедендік ресімдеудің жерлері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 1999-03-10
approved_by:
- '103002004000'
version_date:
  rus: 1999-03-10
source:
  rus: https://zan.gov.kz/client/#!/doc/2833/rus/10.03.1999
