act_code: '90235'
requisite: Приказ Министра национальной экономики Республики Казахстан от 30 января 2015 года № 67. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 мая 2015 года № 11074
title:
  rus: Об утверждении квалификационных требований, предъявляемых к деятельности по лицензированию экспорта и импорта товаров, перечня документов, подтверждающих соответствие им, форм заявлений для получения лицензии и (или) приложения к лицензии, форм лицензий и (или) приложения к лицензии
  kaz: Тауарлар экспорты мен импортын лицензиялау жөніндегі қызметке қойылатын біліктілік талаптары мен оларға сәйкестікті растайтын құжаттар тізбесін, лицензияны және (немесе) лицензияға қосымшаны алуға арналған өтініштердің нысандарын, лицензия және (немесе) лицензияға қосымшаның нысандарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2015-01-30
approved_by:
- '103033000000'
version_date:
  kaz: 2024-12-23
  rus: 2024-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/90235/kaz/23.12.2024
  rus: https://zan.gov.kz/client/#!/doc/90235/rus/23.12.2024
caused_by:
  code: '204586'
  requisite: Приказ Министра торговли и интеграции Республики Казахстан от 23 декабря 2024 года № 414-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 декабря 2024 года № 35503
  title:
    rus: О внесении изменений и дополнений в приказ Министра национальной экономики Республики Казахстан от 30 января 2015 года № 67 «Об утверждении квалификационных требований, предъявляемых к деятельности по лицензированию экспорта и импорта товаров, перечня документов, подтверждающих соответствие им, форм заявлений для получения лицензии и (или) приложения к лицензии, форм лицензий и (или) приложения к лицензии»
    kaz: «Тауарлар экспорты мен импортын лицензиялау жөніндегі қызметке қойылатын біліктілік талаптары мен оларға сәйкестікті растайтын құжаттар тізбесін, лицензияны және (немесе) лицензияға қосымшаны алуға арналған өтініштердің нысандарын, лицензия және (немесе) лицензияға қосымшаның нысандарын бекіту туралы» Қазақстан Республикасы Ұлттық экономика министрінің 2015 жылғы 30 қаңтардағы № 67 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204586/rus
