act_code: '85701'
requisite: Приказ Министра финансов Республики Казахстан от 9 декабря 2014 года № 548. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 декабря 2014 года № 10046. Утратил силу приказом Министра финансов Республики Казахстан от 21 декабря 2015 года № 669
title:
  rus: Об утверждении перечня товаров, работ, услуг, по которым организация и проведение государственных закупок осуществляется единым организатором
  kaz: Мемлекеттік сатып алуды ұйымдастыруды және өткізуді бірыңғай ұйымдастырушы жүзеге асыратын тауарлардың, жұмыстардың, көрсетілетін қызметтердің тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2014-12-09
approved_by:
- '103002000000'
version_date:
  kaz: 2014-12-09
  rus: 2014-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/85701/kaz/09.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85701/rus/09.12.2014
