act_code: '81446'
requisite: Қазақстан Республикасы Премьер-Министрінің орынбасары - Қазақстан Республикасы Индустрия және жаңа технологиялар министрінің 2014 жылғы 17 наурыздағы № 89 бұйрығы. Қазақстан Республикасының Әділет министрлігінде 2014 жылы 13 мамырда № 9414 тіркелді. Күші жойылды - Қазақстан Республикасы Энергетика министрінің м.а. 2015 жылғы 9 желтоқсандағы № 704 бұйрығымен
title:
  rus: Об утверждении профессионального стандарта "Электрическое и электромеханическое оборудование (по видам)"
  kaz: '"Электр және электр механикалық жабдығы (түрлері бойынша)" кәсіби стандартты бекіту туралы'
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2014-03-17
approved_by:
- '103017000000'
version_date:
  kaz: 2014-03-17
  rus: 2014-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/81446/kaz/17.03.2014
  rus: https://zan.gov.kz/client/#!/doc/81446/rus/17.03.2014
