act_code: '154915'
requisite: Приказ и.о. Министра экологии, геологии и природных ресурсов Республики Казахстан от 14 апреля 2021 года № 104. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 апреля 2021 года № 22572
title:
  rus: Об утверждении лимитов изъятия объектов животного мира с 1 июля 2021 года по 1 июля 2022 года
  kaz: 2021 жылғы 1 шілдеден бастап 2022 жылғы 1 шілдеге дейінгі аралықта жануарлар дүниесі объектілерін алып қою лимиттерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2021-04-14
approved_by:
- '103047000000'
version_date:
  kaz: 2021-09-02
  rus: 2021-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/154915/kaz/02.09.2021
  rus: https://zan.gov.kz/client/#!/doc/154915/rus/02.09.2021
caused_by:
  code: '188792'
  requisite: Приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 2 сентября 2021 года № 350. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 сентября 2021 года № 24233
  title:
    rus: О внесении изменения в приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 14 апреля 2021 года № 104 «Об утверждении лимитов изъятия объектов животного мира с 1 июля 2021 года по 1 июля 2022 года»
    kaz: «2021 жылғы 1 шілдеден бастап 2022 жылғы 1 шілдеге дейінгі аралықта жануарлар дүниесі объектілерін алып қою лимиттерін бекіту туралы» Қазақстан Республикасы Экология, геология және табиғи ресурстар министрінің 2021 жылғы 14 сәуірдегі № 104 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188792/rus
