act_code: '202397'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 5 ноября 2024 года № 422
title:
  rus: Об утверждении Правил проведения аттестации на профессиональную компетентность работников центров трудовой мобильности (карьерных центров)
  kaz: Еңбек мобильділігі орталықтары (мансап орталықтары) жұмыскерлерінің кәсіптік құзыреттілігін аттестаттаудан өткізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2024-11-05
approved_by:
- '103016000000'
version_date:
  kaz: 2025-09-12
  rus: 2025-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/202397/kaz/12.09.2025
  rus: https://zan.gov.kz/client/#!/doc/202397/rus/12.09.2025
caused_by:
  code: '214322'
  requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 12 сентября 2025 года № 271
  title:
    rus: О внесении изменений и дополнений в приказ Министра труда и социальной защиты населения Республики Казахстан от 5 ноября 2024 года №422 «Об утверждении Правил проведения аттестации на профессиональную компетентность работников центров трудовой мобильности (карьерных центров)»
    kaz: «Еңбек мобильділігі орталықтары (мансап орталықтары) жұмыскерлерінің кәсіптік құзыреттілігін аттестаттаудан өткізу қағидаларын бекіту туралы» Қазақстан Республикасы Еңбек және халықты әлеуметтік қорғау министрінің 2024 жылғы 5 қарашадағы №422 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214322/rus
