act_code: '147056'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 2 октября 2020 года № 302. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 октября 2020 года № 21364
title:
  rus: Об утверждении Правил выдачи лицензии для занятия деятельностью в сфере ветеринарии
  kaz: Ветеринария саласындағы қызметпен айналысуға арналған лицензия беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-10-02
approved_by:
- '103012000000'
version_date:
  kaz: 2020-10-02
  rus: 2020-10-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/147056/kaz/02.10.2020
  rus: https://zan.gov.kz/client/#!/doc/147056/rus/02.10.2020
