act_code: '116836'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 29 августа 2017 года № 579. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 ноября 2017 года № 16014. Утратил силу приказом Министра индустрии и инфраструктурного развития Республики Казахстан от 10 декабря 2019 года № 919 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О некоторых вопросах предоставления долгосрочного лизингового финансирования в рамках Единой программы поддержки и развития бизнеса «Дорожная карта бизнеса 2020»
  kaz: «Бизнестің жол картасы 2020» бизнесті қолдау мен дамытудың бірыңғай бағдарламасының шеңберінде ұзақ мерзімді лизингтік қаржыландыруды ұсынудың кейбiр мәселелері туралы
form: ПРИК
type_codes:
- МЕТ
- ПРИК
approved_on: 2017-08-29
approved_by:
- '103035000000'
version_date:
  kaz: 2017-08-29
  rus: 2017-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/116836/kaz/29.08.2017
  rus: https://zan.gov.kz/client/#!/doc/116836/rus/29.08.2017
