act_code: '148988'
requisite: Приказ Министра здравоохранения Республики Казахстан от 25 ноября 2020 года № ҚР ДСМ-203/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 ноября 2020 года № 21680
title:
  rus: О некоторых вопросах оказания медико-социальной помощи в области психического здоровья
  kaz: Психикалық денсаулық саласында медициналық-әлеуметтік көмек көрсетудің кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2020-11-25
approved_by:
- '103010000000'
version_date:
  kaz: 2025-11-04
  rus: 2025-11-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/148988/kaz/04.11.2025
  rus: https://zan.gov.kz/client/#!/doc/148988/rus/04.11.2025
caused_by:
  code: '216508'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 4 ноября 2025 года № 135
  title:
    rus: О внесении изменения в приказ Министра здравоохранения Республики Казахстан от 25 ноября 2020 года № ҚР ДСМ-203/2020 «О некоторых вопросах оказания медико-социальной помощи в области психического здоровья»
    kaz: «Психикалық денсаулық саласында медициналық-әлеуметтік көмек көрсетудің кейбір мәселелері туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2020 жылғы 25 қарашадағы № ҚР ДСМ-203/2020 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/216508/rus
