act_code: '157093'
requisite: Приказ Министра здравоохранения Республики Казахстан от 16 июля 2021 года № ҚР ДСМ-61. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 июля 2021 года № 23589. Действие приостановлено до 31 декабря 2025 года приказом и.о. Министра здравоохранения Республики Казахстан от 1 августа 2023 года № 143 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил осуществления сооплаты
  kaz: Бірлесіп төлеуді жүзеге асыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2021-07-16
approved_by:
- '103010000000'
version_date:
  kaz: 2025-10-03
  rus: 2025-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/157093/kaz/03.10.2025
  rus: https://zan.gov.kz/client/#!/doc/157093/rus/03.10.2025
caused_by:
  code: '215251'
  requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 3 октября 2025 года № 104. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 октября 2025 года № 37057
  title:
    rus: О внесении изменений в приказ Министра здравоохранения Республики Казахстан от 16 июля 2021 года № ҚР ДСМ-61 «Об утверждении правил осуществления сооплаты»
    kaz: «Бірлесіп төлеуді жүзеге асыру қағидаларын бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2021 жылғы 16 шілдедегі № ҚР ДСМ-61 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215251/rus
