act_code: '208990'
requisite: Совместный приказ Председателя Комитета национальной безопасности Республики Казахстан от 21 февраля 2025 года № 10/ДСП-НПА и Министра транспорта Республики Казахстан от 31 марта 2025 года № 100/ДСП
title:
  rus: Об утверждении Правил обеспечения взаимодействия электронных информационных ресурсов Министерства транспорта Республики Казахстан и Комитета национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасы Көлік министрлігі мен Қазақстан Республикасы Ұлттық қауіпсіздік комитеті электрондық ақпараттық ресурстарының өзара іс-қимылын қамтамасыз ету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2025-02-21
approved_by:
- '103051000000'
- '108000000000'
version_date:
  kaz: 2025-02-21
  rus: 2025-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/208990/kaz/21.02.2025
  rus: https://zan.gov.kz/client/#!/doc/208990/rus/21.02.2025
