act_code: '22208'
requisite: Приказ и.о. Министра образования и науки Республики Казахстан от 22 октября 2004 года N 854. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 декабря 2004 года N 3231. Утратил силу приказом Министра образования и науки Республики Казахстан от 21 мая 2008 года N 291
title:
  rus: Об утверждении Правил проведения аттестации руководителей государственных организаций образования Республики Казахстан
  kaz: Қазақстан Республикасының мемлекеттік білім беру ұйымдары басшыларын аттестаттауды өткізу тәртібінің ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2004-10-21
approved_by:
- '103006000000'
version_date:
  kaz: 2004-10-21
  rus: 2004-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/22208/kaz/21.10.2004
  rus: https://zan.gov.kz/client/#!/doc/22208/rus/21.10.2004
