act_code: '109402'
requisite: Приказ и.о. Министра иностранных дел Республики Казахстан от 26 декабря 2016 года № 11-1-2/619. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 января 2017 года № 14748
title:
  rus: Об утверждении Правил реализации мероприятий по защите прав и интересов граждан Республики Казахстан, оказавшихся в затруднительном положении, в том числе вследствие форс-мажорных обстоятельств, а также принятия мер в отношении умерших граждан Республики Казахстан в государстве пребывания
  kaz: Болу мемлекетінде қиын жағдайға ұшыраған, оның ішінде форс-мажор жағдайлары салдарынан қиын жағдайға ұшыраған Қазақстан Республикасы азаматтарының құқықтары мен мүдделерін қорғау, сондай-ақ қайтыс болған Қазақстан Республикасы азаматтарына қатысты шаралар қабылдау бойынша іс-шараларды іске асыру қағидаларын бекіту туралыы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2016-12-26
approved_by:
- '103004000000'
version_date:
  kaz: 2025-12-31
  rus: 2025-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/109402/kaz/31.12.2025
  rus: https://zan.gov.kz/client/#!/doc/109402/rus/31.12.2025
caused_by:
  code: '220461'
  requisite: Приказ Министра иностранных дел Республики Казахстан от 31 декабря 2025 года № 11-1-4/810. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 декабря 2025 года № 37772
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра иностранных дел Республики Казахстан от 26 декабря 2016 года № 11-1-2/619 «Об утверждении Правил использования средств, предусмотренных в республиканском бюджете по программе «Представление интересов Республики Казахстан за рубежом»
    kaz: «Шетелде Қазақстан Республикасының мүдделерін білдіру» бағдарламасы бойынша республикалық бюджетте көзделген қаражатты пайдалану қағидаларын бекіту туралы» Қазақстан Республикасы Сыртқы істер министрінің міндетін атқарушының 2016 жылғы 26 желтоқсандағы № 11-1-2/619 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/220461/rus
