act_code: '183499'
requisite: Приказ Заместителя Премьер-Министра - Министра труда и социальной защиты населения Республики Казахстан от 30 июня 2023 года № 286. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 июня 2023 года № 32992
title:
  rus: Об утверждении Правил предоставления услуг специалиста жестового языка для лиц с инвалидностью по слуху в соответствии с индивидуальной программой абилитации и реабилитации лица с инвалидностью
  kaz: Мүгедектігі бар адамды абилитациялаудың және оңалтудың жеке бағдарламасына сәйкес есту кемістігі бар мүгедектігі бар адамдар үшін ымдау тілі маманының қызметтерін ұсыну қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2023-06-30
approved_by:
- '103016000000'
version_date:
  kaz: 2023-06-30
  rus: 2023-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/183499/kaz/30.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183499/rus/30.06.2023
