act_code: '166282'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 5 апреля 2022 года № 98. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 апреля 2022 года № 27508
title:
  rus: Об утверждении Правил переоформления договора временного возмездного землепользования (аренды) земельных участков сельскохозяйственного назначения при отчуждении права землепользования
  kaz: Жер пайдалану құқығын иеліктен шығарған кезде ауыл шаруашылығы мақсатындағы жер учаскелерін уақытша өтеулі жер пайдалану (жалға алу) шартын қайта ресімдеу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-04-05
approved_by:
- '103012000000'
version_date:
  kaz: 2022-04-05
  rus: 2022-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/166282/kaz/05.04.2022
  rus: https://zan.gov.kz/client/#!/doc/166282/rus/05.04.2022
