act_code: '85154'
requisite: Приказ и.о. Министра культуры и спорта Республики Казахстан от 21 ноября 2014 года № 103. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 декабря 2014 года № 9988
title:
  rus: Об утверждении Правил проведения президентских тестов физической подготовленности населения Республики Казахстан
  kaz: Қазақстан Республикасы халқының дене шынықтыру даярлығына президенттік тестілерін өткізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2014-11-21
approved_by:
- '103034000000'
version_date:
  kaz: 2025-06-12
  rus: 2025-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/85154/kaz/12.06.2025
  rus: https://zan.gov.kz/client/#!/doc/85154/rus/12.06.2025
caused_by:
  code: '211330'
  requisite: Приказ и.о. Министра туризма и спорта Республики Казахстан от 12 июня 2025 года № 89. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 июня 2025 года № 36289
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра культуры и спорта Республики Казахстан от 21 ноября 2014 года № 103 «Об утверждении Правил проведения тестов Первого Президента Республики Казахстан – Елбасы»
    kaz: «Қазақстан Республикасы Тұңғыш Президентінің – Елбасының тестілерін өткізу қағидаларын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің міндетін атқарушының 2014 жылғы 21 қарашадағы № 103 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211330/rus
