act_code: '141309'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 2 апреля 2020 года № 78. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 апреля 2020 года № 20307
title:
  rus: Об утверждении Правил выдачи охранных обязательств
  kaz: Қорғау міндеттемелерін беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-04-02
approved_by:
- '103034000000'
version_date:
  kaz: 2021-12-31
  rus: 2021-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/141309/kaz/31.12.2021
  rus: https://zan.gov.kz/client/#!/doc/141309/rus/31.12.2021
caused_by:
  code: '162913'
  requisite: Приказ Министра культуры и спорта Республики Казахстан от 31 декабря 2021 года № 419. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 января 2022 года № 26377
  title:
    rus: О внесении изменений в приказ Министра культуры и спорта Республики Казахстан от 2 апреля 2020 года № 78 «Об утверждении Правил выдачи охранных обязательств»
    kaz: «Қорғау міндеттемелерін беру қағидаларын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің 2020 жылғы 2 сәуірдегі № 78 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162913/rus
