act_code: '105795'
requisite: Приказ Министра информации и коммуникаций Республики Казахстан от 29 июля 2016 года № 71. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 августа 2016 года № 14157. Утратил силу приказом Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 28 мая 2024 года № 305/НҚ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил функционирования единой системы электронных абонентских почтовых ящиков и авторизации пользователей услуг оператора почты в единой системе электронных абонентских почтовых ящиков
  kaz: Электрондық абоненттік пошта жәшіктерінің бірыңғай жүйесінің жұмыс істеуі және электрондық абоненттік пошта жәшіктерінің бірыңғай жүйесінде пошта операторының көрсетілетін қызметтерін пайдаланушыларды авторландыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2016-07-29
approved_by:
- '103039000000'
version_date:
  kaz: 2022-09-26
  rus: 2022-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/105795/kaz/26.09.2022
  rus: https://zan.gov.kz/client/#!/doc/105795/rus/26.09.2022
caused_by:
  code: '172146'
  requisite: Приказ Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 26 сентября 2022 года № 344/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 сентября 2022 года № 29839. Утратил силу приказом Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 28 мая 2024 года № 305/НҚ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра информации и коммуникаций Республики Казахстан от 29 июля 2016 года № 71 «Об утверждении Правил функционирования единой системы электронных абонентских почтовых ящиков и авторизации пользователей услуг оператора почты в единой системе электронных абонентских почтовых ящиков
    kaz: «Электрондық абоненттік пошта жәшіктерінің бірыңғай жүйесінің жұмыс істеуі және электрондық абоненттік пошта жәшіктерінің бірыңғай жүйесінде пошта операторының көрсетілетін қызметтерін пайдаланушыларды авторландыру қағидаларын бекіту туралы» Қазақстан Республикасы Ақпарат және коммуникациялар министрінің 2016 жылғы 29 шілдедегі № 71 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172146/rus
