act_code: '117068'
requisite: Приказ Министра здравоохранения Республики Казахстан от 8 декабря 2017 года № 931. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 декабря 2017 года № 16141. Утратил силу приказом Министра здравоохранения Республики Казахстан от 18 мая 2021 года № ҚР ДСМ - 41 (вводится в действие после истечения десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Казахстанского национального лекарственного формуляра
  kaz: Қазақстандық ұлттық дәрілік формулярын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2017-12-08
approved_by:
- '103010000000'
version_date:
  kaz: 2020-04-21
  rus: 2020-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/117068/kaz/21.04.2020
  rus: https://zan.gov.kz/client/#!/doc/117068/rus/21.04.2020
caused_by:
  code: '142008'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 21 апреля 2020 года № ҚР ДСМ-40/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 апреля 2020 года № 20444. Утратил силу приказом Министра здравоохранения Республики Казахстан от 18 мая 2021 года № ҚР ДСМ - 41 (вводится в действие после истечения десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в приказ Министра здравоохранения Республики Казахстан от 8 декабря 2017 года № 931 «Об утверждении Казахстанского национального лекарственного формуляра»
    kaz: «Қазақстандық ұлттық дәрілік формулярын бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2017 жылғы 8 желтоқсандағы № 931 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142008/rus
