act_code: '201186'
requisite: Приказ Заместителя Премьер-Министра - Министра национальной экономики Республики Казахстан от 30 сентября 2024 года № 78. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 сентября 2024 года № 35170
title:
  rus: Об утверждении Правил ведения и использования реестра субъектов предпринимательства
  kaz: Кәсіпкерлік субъектілерінің тізілімін жүргізу және пайдалану қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2024-09-30
approved_by:
- '103033000000'
version_date:
  kaz: 2024-09-30
  rus: 2024-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/201186/kaz/30.09.2024
  rus: https://zan.gov.kz/client/#!/doc/201186/rus/30.09.2024
