act_code: '49042'
requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 10 ноября 2009 года № 685. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 ноября 2009 года № 5918. Утратил силу приказом Министра здравоохранения Республики Казахстан от 15 декабря 2020 года № ҚР ДСМ-264/2020 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении целевых групп лиц, подлежащих профилактическим медицинским осмотрам, а также правил и периодичности проведения данных осмотров
  kaz: Профилактикалық медициналық қарап-тексерулерге жататын адамдардың нысаналы топтарын, сондай-ақ осы қарап-тексерулерді өткізудің қағидалары мен кезеңділігін белгілеу туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2009-11-10
approved_by:
- '103010000000'
version_date:
  kaz: 2014-12-29
  rus: 2014-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/49042/kaz/29.12.2014
  rus: https://zan.gov.kz/client/#!/doc/49042/rus/29.12.2014
caused_by:
  code: '86580'
  requisite: Приказ Министра здравоохранения и социального развития Республики Казахстан от 29 декабря 2014 года № 361. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 февраля 2015 года № 10199. Утратил силу приказом Министра здравоохранения Республики Казахстан от 15 декабря 2020 года № ҚР ДСМ-264/2020 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра здравоохранения Республики Казахстан от 10 ноября 2009 года № 685 "Об утверждении Правил проведения профилактических медицинских осмотров целевых групп населения"
    kaz: '"Халықтың нысаналы топтарын профилактикалық медициналық тексеріп-қарауды жүргізу ережесін бекіту туралы" Қазақстан Республикасы Денсаулық сақтау Министрінің міндетін атқарушының 2009 жылғы 10 қарашадағы № 685 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/86580/rus
