act_code: '122151'
requisite: Приказ Заместителя Премьер-Министра Республики Казахстан - Министра сельского хозяйства Республики Казахстан от 5 мая 2018 года № 194. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 мая 2018 года № 16949. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 29 октября 2025 года № 397 (вводится в действие с 1 января 2026 года)
title:
  rus: Об утверждении Правил выявления земельных участков, не используемых в соответствующих целях или используемых с нарушением законодательства Республики Казахстан
  kaz: Тиісті мақсаттарда пайдаланылмайтын немесе Қазақстан Республикасының заңнамасы бұзыла отырып пайдаланылатын жер учаскелерін анықтау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-05-05
approved_by:
- '103012000000'
version_date:
  kaz: 2024-03-05
  rus: 2024-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/122151/kaz/05.03.2024
  rus: https://zan.gov.kz/client/#!/doc/122151/rus/05.03.2024
caused_by:
  code: '194109'
repealed_on: 2026-01-01
repealed_by:
  code: '216420'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 29 октября 2025 года № 397. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 октября 2025 года № 37267
  title:
    rus: Об утверждении Правил выявления земельных участков, не используемых в соответствующих целях или используемых с нарушением законодательства Республики Казахстан
    kaz: Тиісті мақсаттарда пайдаланылмайтын немесе Қазақстан Республикасының заңнамасы бұзыла отырып пайдаланылатын жер учаскелерін анықтау қағидаларын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/216420/rus
