act_code: '18251'
requisite: Приказ Председателя Налогового комитета Министерства финансов Республики Казахстан от 23 декабря 2003 года N 530. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 января 2004 года N 2672. Утратил силу приказом Министра финансов Республики Казахстан от 29 декабря 2008 года N 622.
title:
  rus: Об утверждении Правил ведения лицевых счетов
  kaz: Дербес шоттарды жүргізу ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2003-12-23
approved_by:
- '103002002000'
version_date:
  kaz: 2004-11-25
  rus: 2004-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/18251/kaz/25.11.2004
  rus: https://zan.gov.kz/client/#!/doc/18251/rus/25.11.2004
caused_by:
  code: '22338'
  requisite: Приказ Председателя Налогового комитета Министерства финансов Республики Казахстан от 25 ноября 2004 года N 606. Зарегистрирован Министерством юстиции Республики Казахстан 20 декабря 2004 года N 3288. Утратил силу приказом Министра финансов Республики Казахстан от 29 декабря 2008 года N 622
  title:
    rus: О внесении изменений и дополнения в приказ Председателя Налогового комитета Министерства финансов Республики Казахстан от 23 декабря 2003 года N 530 "Об утверждении Правил ведения лицевых счетов", зарегистрированный за N 2672
    kaz: N 2672 тіркелген, "Дербес шоттарды жүргізу ережелерін бекіту туралы" Қазақстан Республикасының Қаржы министрлігі Салық комитеті Төрағасының 2003 жылғы 23 желтоқсандағы N 530 бұйрығына өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/22338/rus
