act_code: '125647'
requisite: Приказ Министра образования и науки Республики Казахстан от 31 октября 2018 года № 604. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 ноября 2018 года № 17669. Утратил силу приказом Министра просвещения Республики Казахстан от 3 августа 2022 года № 348 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении государственных общеобязательных стандартов образования всех уровней образования
  kaz: Білім берудің барлық деңгейінің мемлекеттік жалпыға міндетті білім беру стандарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2018-10-31
approved_by:
- '103006000000'
version_date:
  kaz: 2021-07-23
  rus: 2021-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/125647/kaz/23.07.2021
  rus: https://zan.gov.kz/client/#!/doc/125647/rus/23.07.2021
caused_by:
  code: '157244'
  requisite: Приказ и.о. Министра образования и науки Республики Казахстан от 23 июля 2021 года № 362. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 июля 2021 года № 23692. Утратил силу приказом Министра просвещения Республики Казахстан от 3 августа 2022 года № 348 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра образования и науки Республики Казахстан от 31 октября 2018 года № 604 «Об утверждении государственных общеобязательных стандартов образования всех уровней образования»
    kaz: «Білім берудің барлық деңгейінің мемлекеттік жалпыға міндетті білім беру стандарттарын бекіту туралы» Қазақстан Республикасы Білім және ғылым министрінің 2018 жылғы 31 қазандағы № 604 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157244/rus
