act_code: '58961'
requisite: Приказ Министра транспорта и коммуникаций Республики Казахстан от 7 апреля 2011 года № 201. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 мая 2011 года № 6938
title:
  rus: Об утверждении Правил ремонта судов
  kaz: Кемелерді жөндеу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2011-04-07
approved_by:
- '103013000000'
version_date:
  kaz: 2021-03-09
  rus: 2021-03-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/58961/kaz/09.03.2021
  rus: https://zan.gov.kz/client/#!/doc/58961/rus/09.03.2021
caused_by:
  code: '153480'
  requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 9 марта 2021 года № 103. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 марта 2021 года № 22338
  title:
    rus: О внесении изменений в некоторые приказы Министерства транспорта и коммуникаций Республики Казахстан и Министерства по инвестициям и развитию Республики Казахстан
    kaz: Қазақстан Республикасы Көлік және коммуникациялар министрлігінің және Қазақстан Республикасы Инвестициялар және даму министрлігінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153480/rus
