act_code: '107207'
requisite: Приказ и.о. Председателя Комитета государственных доходов Министерства финансов Республики Казахстан от 21 октября 2016 года № 595
title:
  rus: Об утверждении положений государственных учреждений Комитета государственных доходов Министерства финансов Республики Казахстан
  kaz: Қазақстан Республикасы Қаржы министрлігі Мемлекеттік кірістер комитетінің мемлекеттік мекемелерінің ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2016-10-21
approved_by:
- '103002002000'
version_date:
  kaz: 2021-07-28
  rus: 2021-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/107207/kaz/28.07.2021
  rus: https://zan.gov.kz/client/#!/doc/107207/rus/28.07.2021
caused_by:
  code: '157371'
  requisite: Приказ Председателя Комитета государственных доходов Министерства финансов Республики Казахстан от 28 июля 2021 года № 468
  title:
    rus: О внесении дополнений в приказ исполняющего обязанности Председателя Комитета государственных доходов Министерства финансов Республики Казахстан от 21 октября 2016 года № 595 «Об утверждении положений государственных учреждений Комитета государственных доходов Министерства финансов Республики Казахстан»
    kaz: «Қазақстан Республикасы Қаржы министрлігі Мемлекеттік кірістер комитетінің мемлекеттік мекемелерінің ережелерін бекіту туралы» Қазақстан Республикасы Қаржы министрлігі Мемлекеттік кірістер комитеті төрағасының міндетін атқарушының 2016 жылғы 21 қазандағы № 595 бұйрығына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157371/rus
