act_code: '60332'
requisite: Приказ Министра обороны Республики Казахстан от 24 июня 2011 года № 276. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 августа 2011 года № 7124. Утратил силу приказом Министра обороны Республики Казахстан от 14 июля 2015 года № 410
title:
  rus: Об утверждении Правил приема в Республиканскую школу "Жас улан" имени генерала Нурмагамбетова С.К.
  kaz: Генерал С.Қ.Нұрмағамбетов атындағы «Жас ұлан» республикалық мектебіне қабылдау қағидасын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2011-06-24
approved_by:
- '103008000000'
version_date:
  kaz: 2011-06-24
  rus: 2011-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/60332/kaz/24.06.2011
  rus: https://zan.gov.kz/client/#!/doc/60332/rus/24.06.2011
