act_code: '59514'
requisite: Приказ Министра здравоохранения Республики Казахстан от 10 июня 2011 года № 383. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 июня 2011 года № 7048. Утратил силу приказом Министра здравоохранения Республики Казахстан от 8 декабря 2020 года № ҚР ДСМ-237/2020 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Положения о наркологической организации для принудительного лечения и Правил внутреннего распорядка в наркологической организации для принудительного лечения
  kaz: Мәжбүрлеп емдеуге арналған наркологиялық ұйым туралы ереже мен Мәжбүрлеп емдеуге арналған наркологиялық ұйымдағы ішкі тәртіп қағидасын бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2011-06-10
approved_by:
- '103010000000'
version_date:
  kaz: 2011-11-03
  rus: 2011-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/59514/kaz/03.11.2011
  rus: https://zan.gov.kz/client/#!/doc/59514/rus/03.11.2011
caused_by:
  code: '62105'
  requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 3 ноября 2011 года № 770. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 ноября 2011 года № 7316. Утратил силу приказом Министра здравоохранения Республики Казахстан от 8 декабря 2020 года № ҚР ДСМ-237/2020 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в приказ Министра здравоохранения Республики Казахстан от 10 июня 2011 года № 383 "Об утверждении Положения о наркологической организации для принудительного лечения и Правил внутреннего распорядка в наркологической организации для принудительного лечения"
    kaz: '"Мәжбүрлеп емдеуге арналған наркологиялық ұйым туралы ережені және Мәжбүрлеп емдеуге арналған наркологиялық ұйымдардағы ішкі тәртіп қағидасын бекіту туралы" Қазақстан Республикасы Денсаулық сақтау министрінің 2011 жылғы 10 маусымдағы № 383 бұйрығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/62105/rus
