act_code: '208877'
requisite: Приказ Министра финансов Республики Казахстан от 4 апреля 2025 года № 150. Действовал по 31 декабря 2025 года в соответствии с пунктом 4 настоящего приказа
title:
  rus: Об утверждении Таблицы распределения поступлений бюджета между уровнями бюджетов, контрольными счетами наличности Национального фонда Республики Казахстан, внебюджетных фондов, формируемых за счет неналоговых платежей, и бюджетами государств – членов Евразийского экономического союза
  kaz: Бюджет түсімдерін бюджеттердің деңгейлері, Қазақстан Республикасы Ұлттық қорының, салықтық емес төлемдер есебінен қалыптастырылатын бюджеттен тыс қорлардың қолма-қол ақшаны бақылау шоттары және Еуразиялық экономикалық одаққа мүше мемлекеттердің бюджеттері арасында бөлу кестесі
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-04-04
approved_by:
- '103002000000'
version_date:
  kaz: 2025-08-15
  rus: 2025-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/208877/kaz/15.08.2025
  rus: https://zan.gov.kz/client/#!/doc/208877/rus/15.08.2025
caused_by:
  code: '213304'
  requisite: Приказ Министра финансов Республики Казахстан от 15 августа 2025 года № 448
  title:
    rus: О внесении дополнений в приказы Министра финансов Республики Казахстан от 4 апреля 2025 года № 149 «Некоторые вопросы Единой бюджетной классификации Республики Казахстан» и от 4 апреля 2025 года № 150 «Об утверждении Таблицы распределения поступлений бюджета между уровнями бюджетов, контрольными счетами наличности Национального фонда Республики Казахстан, внебюджетных фондов, формируемых за счет неналоговых платежей, и бюджетами государств – членов Евразийского экономического союза»
    kaz: Қазақстан Республикасы Қаржы министрiнiң «Қазақстан Республикасының Бірыңғай бюджеттік сыныптамасының кейбір мәселелері» 2025 жылғы 4 сәуірдегі № 149 және «Бюджет түсімдерін бюджеттердің деңгейлері, Қазақстан Республикасы Ұлттық қорының, салықтық емес төлемдер есебінен қалыптастырылатын бюджеттен тыс қорлардың қолма-қол ақшаны бақылау шоттары және Еуразиялық экономикалық одаққа мүше мемлекеттердің бюджеттері арасында бөлу кестесі» 2025 жылғы 4 сәуірдегі № 150 бұйрықтарына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213304/rus
