act_code: '88978'
requisite: Приказ от 11.03.2015  № 40, Генеральная Прокуратура Республики Казахстан. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 апреля 2015 года № 10706. Утратил силу приказом Генерального Прокурора Республики Казахстан от 2 мая 2018 года № 60 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Инструкции об организации прокурорского надзора за законностью судебных актов по делам об административных правонарушениях
  kaz: Әкімшілк құқық бұзышылық туралы істер бойынша сот актілерінің заңдылығына прокурорлық қадағалауды ұйымдастыру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2015-03-11
approved_by:
- '107000000000'
version_date:
  kaz: 2015-03-11
  rus: 2015-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/88978/kaz/11.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88978/rus/11.03.2015
