act_code: '2716'
requisite: Приказ Министерства здравоохранения, образования и спорта Республики Казахстан от 2 апреля 1999 года N 172 Зарегистрирован в Министерстве юстиции Республики Казахстан 26 апреля 1999 г. за N 739. Утратил силу - приказом Председателя Агентства Республики Казахстан по делам здравоохранения от 18 апреля 2000 года N 225
title:
  rus: Об утверждении состава "Аптечки первой помощи (транспортной)"
  kaz: '"Алғашқы көмек дәрі қобдишасының (көліктік)" құралын бекіту туралы'
form: ПРИК
type_codes:
- ПРИК
approved_on: 1999-04-01
approved_by:
- '103006000000'
version_date:
  rus: 1999-04-01
source:
  rus: https://zan.gov.kz/client/#!/doc/2716/rus/01.04.1999
