act_code: '164038'
requisite: Приказ Министра образования и науки Республики Казахстан от 12 января 2022 года № 4. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 января 2022 года № 26618
title:
  rus: Об утверждении Правил и программ оценки особых образовательных потребностей
  kaz: Ерекше білім беру қажеттіліктерін бағалау қағидаларын және бағдарламаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-01-12
approved_by:
- '103006000000'
version_date:
  kaz: 2025-05-06
  rus: 2025-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/164038/kaz/06.05.2025
  rus: https://zan.gov.kz/client/#!/doc/164038/rus/06.05.2025
caused_by:
  code: '209880'
  requisite: Приказ Министра просвещения Республики Казахстан от 6 мая 2025 года № 104. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 мая 2025 года № 36082
  title:
    rus: О внесении изменений и дополнения в приказ Министра образования и науки Республики Казахстан от 12 января 2022 года № 4 «Об утверждении Правил оценки особых образовательных потребностей»
    kaz: «Ерекше білім беру қажеттіліктерін бағалау қағидаларын бекіту туралы» Қазақстан Республикасы Білім және ғылым министрінің 2022 жылғы 12 қаңтардағы № 4 бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209880/rus
