act_code: '51644'
requisite: Приказ Министра внутренних дел Республики Казахстан от 26 февраля 2010 года № 90. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 марта 2010 года № 6103. Утратил силу приказом Министра внутренних дел Республики Казахстан от 2 декабря 2014 года № 862
title:
  rus: Об утверждении Правил допуска лиц к экзаменам, их сдачи и выдачи удостоверений на право управления отдельными видами транспортных средств
  kaz: Көлік құралдарының жекелеген түрлерін басқару құқығына емтихандарға адамдарды жіберу, оларды тапсыру және куәліктер беру ережесін бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2010-02-26
approved_by:
- '103003000000'
version_date:
  kaz: 2013-06-04
  rus: 2013-06-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/51644/kaz/04.06.2013
  rus: https://zan.gov.kz/client/#!/doc/51644/rus/04.06.2013
caused_by:
  code: '73076'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 4 июня 2013 года № 371. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 июня 2013 года № 8511. Утратил силу приказом Министра внутренних дел Республики Казахстан от 2 декабря 2014 года № 862
  title:
    rus: О внесении изменений в приказ Министра внутренних дел Республики Казахстан от 26 февраля 2010 года № 90 "Об утверждении Правил государственной регистрации и учета отдельных видов транспортных средств и Правил приема экзаменов и выдачи удостоверений на право управления отдельными видами транспортных средств"
    kaz: '"Көлік құралдарының жекелеген түрлерін мемлекеттік тіркеу және есепке алу ережесін және Көлік құралдарының жекелеген түрлерін басқару құқығына емтихандар қабылдау және куәліктер беру ережесін бекіту туралы" Қазақстан Республикасы Ішкі істер министрінің 2010 жылғы 26 ақпандағы № 90 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/73076/rus
