act_code: '53752'
requisite: Совместный приказ Министра экономического развития и торговли Республики Казахстан от 1 июля 2010 года № 102 и Председателя Агентства Республики Казахстан по делам строительства и жилищно-коммунального хозяйства от 30 июня 2010 года № 276. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 июля 2010 года № 6345. Утратил силу совместным приказом Министра экономики и бюджетного планирования Республики Казахстан от 27 июня 2014 года № 184 и Министра регионального развития Республики Казахстан от 31 июля 2014 года № 226/НК
title:
  rus: Об утверждении требований к разработке или корректировке, а также проведению необходимых экспертиз технико-экономического обоснования бюджетного инвестиционного и концессионного проектов
  kaz: Бюджеттік инвестициялық және концессиялық жобалардың техникалық-экономикалық негіздемелерін әзірлеуге немесе түзетуге, сондай-ақ қажетті сараптамалар жүргізуге қойылатын талаптарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2010-07-01
approved_by:
- '103005000000'
- '123000000000'
version_date:
  kaz: 2012-02-01
  rus: 2012-02-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/53752/kaz/01.02.2012
  rus: https://zan.gov.kz/client/#!/doc/53752/rus/01.02.2012
caused_by:
  code: '64719'
  requisite: Совместный приказ Министра экономического развития и торговли Республики Казахстан от 1 февраля 2012 года № 37 и Председателя Агентства Республики Казахстан по делам строительства и жилищно-коммунального хозяйства от 31 января 2012 года № 31. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 марта 2012 года № 7469. Утратил силу совместным приказом Министра экономики и бюджетного планирования Республики Казахстан от 27 июня 2014 года № 184 и Министра регионального развития Республики Казахстан от 31 июля 2014 года № 226/НК
  title:
    rus: О внесении изменений в совместный приказ Министра экономического развития и торговли Республики Казахстан от 1 июля 2010 года № 102 и Председателя Агентства Республики Казахстан по делам строительства и жилищно-коммунального хозяйства от 30 июня 2010 года № 276 "Об утверждении требований к разработке или корректировке, а также проведению необходимых экспертиз технико-экономического обоснования бюджетного инвестиционного проекта"
    kaz: '"Бюджеттік инвестициялық жобаның техникалық-экономикалық негіздемесін әзірлеуге немесе түзетуге, сондай-ақ қажетті сараптамалар жүргізуге қойылатын талаптарды бекіту туралы" Қазақстан Республикасы Экономикалық даму және сауда министрінің 2010 жылғы 1 шілдедегі № 102 және Қазақстан Республикасы Құрылыс және тұрғын үй-коммуналдық шаруашылық істері агенттігі Төрағасының 2010 жылғы 30 маусымдағы № 276 бірлескен бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/64719/rus
