act_code: '18327'
requisite: Приказ Председателя Комитета по управлению архивами и документацией Министерства культуры Республики Казахстан от 29 декабря 2003 года № 93. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 января 2004 года № 2679. Утратил силу приказом Председателя Комитета информации и архивов Министерства культуры и информации Республики Казахстан от 24 сентября 2012 года № 165
title:
  rus: Об утверждении Основных правил работы ведомственных архивов
  kaz: Ведомстволық мұрағаттар қызметінің негізгі ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2003-12-29
approved_by:
- '103011000000'
version_date:
  kaz: 2003-12-29
  rus: 2003-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/18327/kaz/29.12.2003
  rus: https://zan.gov.kz/client/#!/doc/18327/rus/29.12.2003
