act_code: '91276'
requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 28 мая 2015 года № 42. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 июня 2015 года № 11504. Утратил силу приказом Председателя Комитета национальной безопасности Республики Казахстан от 20 апреля 2020 года № 26/қе (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг, оказываемых Пограничной службой Комитета национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасы Ұлттық қауіпсіздік комитетінің Шекара қызметі көрсететін мемлекеттік қызмет регламенттерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2015-05-28
approved_by:
- '108000000000'
version_date:
  kaz: 2015-05-28
  rus: 2015-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/91276/kaz/28.05.2015
  rus: https://zan.gov.kz/client/#!/doc/91276/rus/28.05.2015
