act_code: '41115'
requisite: Приказ Министра здравоохранения Республики Казахстан от 4 июля 2008 года N 392. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 августа 2008 года N 5276. Утратил силу приказом Министра здравоохранения Республики Казахстан от 24 ноября 2009 года № 774
title:
  rus: Об утверждении Номенклатуры медицинских и фармацевтических специальностей
  kaz: Медицина және фармацевтика мамандықтары номенклатурасын бекіту туралы
form: ПРИК
type_codes:
- НОМ
- ПРИК
approved_on: 2008-07-04
approved_by:
- '103010000000'
version_date:
  kaz: 2009-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/41115/kaz/24.10.2009
caused_by:
  code: '48953'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 24 ноября 2009 года № 774. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 ноября 2009 года № 5885. Утратил силу приказом Министра здравоохранения Республики Казахстан от 21 декабря 2020 года № ҚР ДСМ-305/2020 (вводится в действие по истечении двадцати одного календарного дня после дня его первого официального опубликования)
  title:
    rus: Об утверждении Номенклатуры медицинских и фармацевтических специальностей
    kaz: Медицина және фармацевтика мамандықтарының номенклатурасын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/48953/rus
