act_code: '133882'
requisite: Приказ Министра внутренних дел Республики Казахстан от 1 августа 2019 года № 669. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 августа 2019 года № 19211. Утратил силу приказом Министра внутренних дел Республики Казахстан от 7 октября 2025 года № 752 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении натуральных норм снабжения средствами индивидуальной бронезащиты, активной обороны, обеспечения специальных операций, инженерного вооружения, техническими средствами охраны, взрывчатыми веществами и средствами взрывания воинских частей и военных учебных заведений Национальной гвардии Республики Казахстан
  kaz: Қазақстан Республикасы Ұлттық ұланының әскери бөлімдері мен әскери оқу орындарын жеке броньды қорғау, белсенді қорғаныс, арнайы операцияларды қамтамасыз ету, инженерлік қару-жарақ құралдарымен, күзеттің техникалық құралдарымен, жарылғыш заттармен және жару құралдарымен жабдықтаудың заттай нормаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2019-08-01
approved_by:
- '103003000000'
version_date:
  kaz: 2021-11-03
  rus: 2021-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/133882/kaz/03.11.2021
  rus: https://zan.gov.kz/client/#!/doc/133882/rus/03.11.2021
caused_by:
  code: '160003'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 3 ноября 2021 года № 680. Утратил силу приказом Министра внутренних дел Республики Казахстан от 30 июля 2025 года № 570 (вступает в силу со дня его подписания)
  title:
    rus: О внесении изменения в приказ Министра внутренних дел Республики Казахстан от 1 августа 2019 года № 669 «Об утверждении натуральных норм снабжения средствами индивидуальной бронезащиты, активной обороны, обеспечения специальных операций, инженерного вооружения, техническими средствами охраны, взрывчатыми веществами и средствами взрывания воинских частей и военных учебных заведений Национальной гвардии Республики Казахстан»
    kaz: «Қазақстан Республикасы Ұлттық ұланының әскери бөлімдері мен әскери оқу орындарын жеке броньды қорғау, белсенді қорғаныс, арнайы операцияларды қамтамасыз ету, инженерлік қару-жарақ құралдарымен, күзеттің техникалық құралдарымен, жарылғыш заттармен және жару құралдарымен жабдықтаудың заттай нормаларын бекіту туралы» Қазақстан Республикасы Ішкі істер министрінің 2019 жылғы 1 тамыздағы № 669 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160003/rus
