act_code: '119210'
requisite: Приказ Министра финансов Республики Казахстан от 14 февраля 2018 года № 188. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 марта 2018 года № 16464
title:
  rus: Об утверждении Правил проведения таможенных досмотра и осмотра
  kaz: Кедендік жете тексеруді және қарап-тексеруді жүргізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-02-14
approved_by:
- '103002000000'
version_date:
  kaz: 2021-07-23
  rus: 2021-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/119210/kaz/23.07.2021
  rus: https://zan.gov.kz/client/#!/doc/119210/rus/23.07.2021
caused_by:
  code: '157272'
  requisite: Приказ и.о. Министра финансов Республики Казахстан от 23 июля 2021 года № 713. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 июля 2021 года № 23699
  title:
    rus: О внесении изменений в приказ Министра финансов Республики Казахстан от 14 февраля 2018 года № 188 «Об утверждении Правил проведения таможенных досмотра и осмотра»
    kaz: «Кедендік жете тексеруді және қарап-тексеруді жүргізу қағидаларын бекіту туралы» Қазақстан Республикасы Қаржы министрінің 2018 жылғы 14 ақпандағы № 188 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157272/rus
