act_code: '118790'
requisite: Приказ Министра иностранных дел Республики Казахстан от 4 января 2018 года № 11-1-4/1. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 февраля 2018 года № 16354
title:
  rus: Об утверждении Правил приема и направления документов граждан Республики Казахстан, выехавших за пределы Республики Казахстан по временным делам и изъявивших желание остаться там на постоянное место жительства
  kaz: Қазақстан Республикасынан тыс жерге уақытша жұмыстармен шыққан және онда тұрақты тұру үшін қалуға тілек білдірген Қазақстан Республикасы азаматтарының құжаттарын қабылдау және жолдау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-01-04
approved_by:
- '103004000000'
version_date:
  kaz: 2026-01-01
  rus: 2026-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/118790/kaz/01.01.2026
  rus: https://zan.gov.kz/client/#!/doc/118790/rus/01.01.2026
caused_by:
  code: '215049'
  requisite: Приказ Министра иностранных дел Республики Казахстан от 30 сентября 2025 года № 11-1-4/577. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 октября 2025 года № 37001
  title:
    rus: О внесении изменений в некоторые приказы Министерства иностранных дел Республики Казахстан
    kaz: Қазақстан Республикасы Сыртқы істер министрлігінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215049/rus
