act_code: '165158'
requisite: Приказ Министра финансов Республики Казахстан от 1 февраля 2022 года № 113. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 февраля 2022 года № 26715
title:
  rus: Об утверждении процедурного стандарта внутреннего государственного аудита и финансового контроля «Аудит соответствия»
  kaz: «Сәйкестік аудиті» ішкі мемлекеттік аудит және қаржылық бақылау рәсімдік стандартын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2022-02-01
approved_by:
- '103002000000'
version_date:
  kaz: 2022-02-01
  rus: 2022-02-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/165158/kaz/01.02.2022
  rus: https://zan.gov.kz/client/#!/doc/165158/rus/01.02.2022
