act_code: '99219'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 19 января 2016 года № 15. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 февраля 2016 года № 13102
title:
  rus: Об определении государственных органов, их подведомственных организаций и органов местного самоуправления, а также иных субъектов информатизации, использующих единую транспортную среду государственных органов для взаимодействия локальных (за исключением локальных сетей, имеющих доступ к Интернету), ведомственных и корпоративных сетей
  kaz: Мемлекеттік органдардың бірыңғай көліктік ортасын жергілікті (Интернетке қолжетімділігі бар жергілікті желілерді қоспағанда), ведомстволық және корпоративтік желілердің өзара іс-қимыл жасауы үшін пайдаланатын мемлекеттік органдарды, олардың ведомстволық бағынысты ұйымдарын және жергiлiктi өзiн-өзi басқару органдарын, сондай-ақ өзге де ақпараттандыру субъектілерін айқындау туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2016-01-19
approved_by:
- '103035000000'
version_date:
  kaz: 2023-02-23
  rus: 2023-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/99219/kaz/23.02.2023
  rus: https://zan.gov.kz/client/#!/doc/99219/rus/23.02.2023
caused_by:
  code: '178839'
  requisite: Приказ и.о. Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 23 февраля 2023 года № 63/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 февраля 2023 года № 31962
  title:
    rus: О внесении изменений и дополнений в приказ Министра по инвестициям и развитию Республики Казахстан от 19 января 2016 года № 15 «Об определении государственных органов, их подведомственных организаций и органов местного самоуправления, а также иных субъектов информатизации, использующих единую транспортную среду государственных органов для взаимодействия локальных (за исключением локальных сетей, имеющих доступ к Интернету), ведомственных и корпоративных сетей»
    kaz: «Мемлекеттік органдардың бірыңғай көліктік ортасын жергілікті (Интернетке қолжетімділігі бар жергілікті желілерді қоспағанда), ведомстволық және корпоративтік желілердің өзара іс-қимыл жасауы үшін пайдаланатын мемлекеттік органдардың, олардың ведомстволық бағынысты ұйымдарын және жергiлiктi өзiн-өзi басқару органдарын, сондай-ақ өзге де ақпараттандыру субъектілерін айқындау туралы» Қазақстан Республикасы Инвестициялар және даму министрінің 2016 жылғы 19 қаңтардағы № 15 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/178839/rus
