act_code: '89599'
requisite: Приказ Министра национальной экономики Республики Казахстан от 29 декабря 2014 года № 180. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 мая 2015 года № 10953
title:
  rus: Об утверждении перечня существенно важных товаров
  kaz: Елеулі маңызды тауарлар тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2014-12-29
approved_by:
- '103033000000'
version_date:
  kaz: 2014-12-29
  rus: 2014-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/89599/kaz/29.12.2014
  rus: https://zan.gov.kz/client/#!/doc/89599/rus/29.12.2014
