act_code: '221329'
requisite: Приказ Министра науки и высшего образования Республики Казахстан от 12 января 2026 года № 8
title:
  rus: Об утверждении перечня организаций, осуществляющих фундаментальные научные исследования на 2026-2028 годы
  kaz: Іргелі ғылыми зерттеулерді жүзеге асыратын ұйымдардың 2026-2028 жылдарға арналған тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2026-01-12
approved_by:
- '103049000000'
version_date:
  kaz: 2026-01-12
  rus: 2026-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/221329/kaz/12.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221329/rus/12.01.2026
