act_code: '90774'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 21 апреля 2015 года № 472. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 мая 2015 года № 11200
title:
  rus: Об утверждении положения о межрегиональных комиссиях по запасам полезных ископаемых
  kaz: Пайдалы қазбалар қорлары жөніндегі өңіраралық комиссиялар туралы ережені бекіту туралы
form: ПРИК
type_codes:
- ОПОЛ
- ПРИК
approved_on: 2015-04-21
approved_by:
- '103035000000'
version_date:
  kaz: 2016-07-05
  rus: 2016-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/90774/kaz/05.07.2016
  rus: https://zan.gov.kz/client/#!/doc/90774/rus/05.07.2016
caused_by:
  code: '105810'
  requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 5 июля 2016 года № 539. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 августа 2016 года № 14173. Утратил силу приказом Министра по инвестициям и развитию Республики Казахстан от 15 мая 2018 года № 330
  title:
    rus: О внесении изменения в приказ Министра по инвестициям и развитию Республики Казахстан от 21 апреля 2015 года № 472 "Об утверждении положений о Государственной комиссии по запасам полезных ископаемых Республики Казахстан и межрегиональных комиссиях по запасам полезных ископаемых"
    kaz: '"Қазақстан Республикасының пайдалы қазбалар қорлары жөніндегі мемлекеттік комиссия және пайдалы қазбалар қорлары жөніндегі өңіраралық комиссиялар туралы ережелерді бекіту туралы" Қазақстан Республикасы Инвестициялар және даму министрінің 2015 жылғы 21 сәуірдегі № 472 бұйрығына өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/105810/rus
