act_code: '93464'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 30 июня 2015 года № 18-02/596. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 августа 2015 года № 11894
title:
  rus: Об утверждении Правил рубок леса на участках государственного лесного фонда
  kaz: 'Мемлекеттік орман қоры учаскелерiнде ағаш кесу қағидаларын бекіту туралы '
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-06-30
approved_by:
- '103012000000'
version_date:
  kaz: 2015-06-30
  rus: 2015-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/93464/kaz/30.06.2015
  rus: https://zan.gov.kz/client/#!/doc/93464/rus/30.06.2015
