act_code: '229554'
requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 31 августа 2026 года № 106/қбп. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 августа 2026 года № 39759
title:
  rus: Об утверждении Инструкции по обязательной специальной проверке граждан Республики Казахстан, впервые поступающих на государственную службу или вновь поступающих на государственную службу после ее прекращения, а также претендующих на занятие должности судьи, служащего Национального Банка Республики Казахстан и его ведомств, служащего уполномоченного органа по регулированию, контролю и надзору финансового рынка и финансовых организаций, авиационного инспектора уполномоченной организации в сфере гражданской авиации, осуществляющего контрольные и надзорные функции в области авиационной безопасности
  kaz: Мемлекеттік қызметке алғаш рет кіретін немесе мемлекеттік қызметті тоқтатқаннан кейін оған қайта кіретін, сондай-ақ судья, Қазақстан Республикасы Ұлттық Банкінің және оның ведомстволарының қызметшісі, қаржы нарығы мен қаржы ұйымдарын реттеу, бақылау және қадағалау жөніндегі уәкілетті органның қызметшісі, азаматтық авиация саласындағы уәкілетті ұйымның авиациялық қауіпсіздік саласында бақылау мен қадағалау функцияларын жүзеге асыратын авиация инспекторы лауазымына орналасуға үміткер Қазақстан Республикасының азаматтарына міндетті арнаулы тексеру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2026-08-31
approved_by:
- '108000000000'
version_date:
  kaz: 2026-08-31
  rus: 2026-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/229554/kaz/31.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229554/rus/31.08.2026
