act_code: '90048'
requisite: Приказ Министра финансов Республики Казахстан от 31 марта 2015 года № 249. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 апреля 2015 года № 10884. Утратил силу приказами Министра финансов Республики Казахстан от 16 февраля 2018 года № 215 и от 16 февраля 2018 года № 216 (вводятся в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О некоторых вопросах таможенного транзита и временного хранения товаров и транспортных средств
  kaz: Тауарлар мен көлік кұралдарының кедендік транзитінің және оларды уақытша сақтаудың кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-03-31
approved_by:
- '103002000000'
version_date:
  kaz: 2015-03-31
  rus: 2015-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/90048/kaz/31.03.2015
  rus: https://zan.gov.kz/client/#!/doc/90048/rus/31.03.2015
