act_code: '91862'
requisite: Приказ Министра здравоохранения и социального развития Республики Казахстан от 29 мая 2015 года № 427. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 июня 2015 года № 11481. Утратил силу приказом Министра здравоохранения Республики Казахстан от 15 декабря 2020 года № ҚР ДСМ-273/2020 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил осуществления сервисного обслуживания медицинских изделий в Республике Казахстан
  kaz: Қазақстан Республикасында медициналық бұйымға сервистік қызмет көрсетуді жүзеге асыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-05-29
approved_by:
- '103037000000'
version_date:
  kaz: 2016-02-29
  rus: 2016-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/91862/kaz/29.02.2016
  rus: https://zan.gov.kz/client/#!/doc/91862/rus/29.02.2016
caused_by:
  code: '100925'
  requisite: Приказ Министра здравоохранения и социального развития Республики Казахстан от 29 февраля 2016 года № 166. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 апреля 2016 года № 13563. Утратил силу приказом Министра здравоохранения Республики Казахстан от 15 декабря 2020 года № ҚР ДСМ-273/2020 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра здравоохранения и социального развития Республики Казахстан от 29 мая 2015 года № 427 "Об утверждении Правил осуществления сервисного обслуживания медицинской техники в Республике Казахстан"
    kaz: '"Қазақстан Республикасында медициналық техникаға сервистік қызмет көрсетуді жүзеге асыру қағидаларын бекіту туралы" Қазақстан Республикасы Денсаулық сақтау және әлеуметтік даму министрінің 2015 жылғы 29 мамырдағы № 427 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/100925/rus
