act_code: '24798'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 30 июня 2005 года N 173-п. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 июля 2005 года N 3732. Утратил силу - приказом Министра труда и социальной защиты населения Республики Казахстан от 19 июля 2007 года N 165-п.
title:
  rus: Об утверждении Правил разработки и применения Единого тарифно-квалификационного справочника работ и профессий рабочих и Квалификационного справочника должностей руководителей, специалистов и других служащих
  kaz: Жұмысшылардың жұмыстары мен кәсіптерінің бірыңғай тарифтік-біліктілік анықтамалығын және Басшылардың, мамандардың және басқа да қызметшілер лауазымдарының біліктілік анықтамалығын әзірлеу және қолдану ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2005-06-30
approved_by:
- '103016000000'
version_date:
  kaz: 2005-06-30
  rus: 2005-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/24798/kaz/30.06.2005
  rus: https://zan.gov.kz/client/#!/doc/24798/rus/30.06.2005
