act_code: '79414'
requisite: Приказ Министра внутренних дел Республики Казахстан от 21 февраля 2014 года № 103. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 марта 2014 года № 9275. Утратил силу приказом Министра внутренних дел Республики Казахстан от 30 мая 2015 года № 500 (вводится в действие по истечении десяти календарных дней со дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг "Выдача пропуска на въезд в пограничную зону иностранцам и лицам без гражданства", "Оформление приглашений на въезд в Республику Казахстан по частным делам и с целью воссоединения семьи" и "Регистрация иностранцев и лиц без гражданства, временно пребывающих в Республике Казахстан"
  kaz: '"Шетелдіктердің және азаматтығы жоқ адамдардың шекаралық аймаққа кіруіне рұқсаттама беру", "Қазақстан Республикасына жеке істері бойынша және отбасын біріктіру мақсатында келуге шақыруларды ресімдеу" және "Қазақстан Республикасында уақытша болатын шетелдіктер мен азаматтығы жоқ адамдарды тіркеу" мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы'
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2014-02-21
approved_by:
- '103003000000'
version_date:
  kaz: 2014-06-19
  rus: 2014-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/79414/kaz/19.06.2014
  rus: https://zan.gov.kz/client/#!/doc/79414/rus/19.06.2014
caused_by:
  code: '82053'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 19 июня 2014 года № 359. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 июля 2014 года № 9617. Утратил силу приказом Министра внутренних дел Республики Казахстан от 30 мая 2015 года № 500 (вводится в действие по истечении десяти календарных дней со дня его первого официального опубликования)
  title:
    rus: О внесении дополнений в приказ Министра внутренних дел Республики Казахстан от 21 февраля 2014 года № 103 "Об утверждении регламентов государственных услуг "Выдача пропуска на въезд в пограничную зону иностранцам и лицам без гражданства", "Оформление приглашений на въезд в Республику Казахстан по частным делам и с целью воссоединения семьи" и "Регистрация иностранцев и лиц без гражданства, временно пребывающих в Республике Казахстан"
    kaz: «Шетелдіктердің және азаматтығы жоқ адамдардың шекаралық аймаққа кіруіне рұқсаттама беру», Қазақстан Республикасына жеке істері бойынша және отбасын біріктіру мақсатында келуге шақыруларды ресімдеу» және «Қазақстан Республикасында уақытша болатын шетелдіктер мен азаматтығы жоқ адамдарды тіркеу» мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы» Қазақстан Республикасы Ішкі істер министрінің 2014 жылғы 21 ақпандағы № 103 бұйрығына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/82053/rus
