act_code: '165518'
requisite: Совместный приказ Председателя Агентства Республики Казахстан по финансовому мониторингу от 15 марта 2022 года № 21 и Генерального Прокурора Республики Казахстан от 24 марта 2022 года № 54. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 марта 2022 года № 27194
title:
  rus: Об утверждении Правил и оснований получения уполномоченным органом по финансовому мониторингу из системы информационного обмена правоохранительных, специальных государственных и иных органов информации, необходимой для противодействия легализации (отмыванию) доходов, полученных преступным путем, финансированию терроризма и финансированию распространения оружия массового уничтожения
  kaz: Қаржы мониторингі жөніндегі уәкілетті органның құқық қорғау, арнаулы мемлекеттік және өзге де органдардың ақпарат алмасу жүйесінен қылмыстық жолмен алынған кірістерді заңдастыруға (жылыстатуға), терроризмді қаржыландыруға және жаппай қырып-жою қаруын таратуды қаржыландыруға қарсы іс-қимыл үшін қажетті ақпаратты алу қағидалары мен негіздерін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-03-15
approved_by:
- '107000000000'
- '183000000000'
version_date:
  kaz: 2025-11-28
  rus: 2025-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/165518/kaz/28.11.2025
  rus: https://zan.gov.kz/client/#!/doc/165518/rus/28.11.2025
caused_by:
  code: '217935'
  requisite: Совместный приказ и.о. Председателя Агентства Республики Казахстан по финансовому мониторингу от 28 ноября 2025 года № 16 и Генерального Прокурора Республики Казахстан от 2 декабря 2025 года № 152. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 декабря 2025 года № 37524
  title:
    rus: О внесении изменений в совместный приказ Председателя Агентства Республики Казахстан по финансовому мониторингу от 15 марта 2022 года № 21 и Генерального Прокурора Республики Казахстан от 24 марта 2022 года № 54 «Об утверждении Правил и оснований получения уполномоченным органом по финансовому мониторингу из системы информационного обмена правоохранительных, специальных государственных и иных органов информации, необходимой для противодействия легализации (отмыванию) доходов, полученных преступным путем, и финансированию терроризма»
    kaz: «Қаржылық мониторинг жөніндегі уәкілетті органның құқық қорғау, арнаулы мемлекеттік және өзге де органдардың ақпарат алмасу жүйесінен қылмыстық жолмен алынған кірістерді заңдастыруға (жылыстатуға) және терроризмді қаржыландыруға қарсы іс-қимыл үшін қажет ақпаратты алу қағидалары мен негіздерін бекіту туралы» Қазақстан Республикасы Қаржылық мониторинг агенттігі Төрағасының 2022 жылғы 15 наурыздағы № 21 және Қазақстан Республикасы Бас Прокурорының 2022 жылғы 24 наурыздағы № 54 бірлескен бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217935/rus
