act_code: '20886'
requisite: Приказ Председателя Налогового комитета Министерства финансов Республики Казахстан от 12 июля 2004 года N 347. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 августа 2004 года N 2992. Утратил силу приказом Министра финансов Республики Казахстан от 30 декабря 2008 года N 637
title:
  rus: О некоторых вопросах ограничения в распоряжении имуществом в счет налоговой и таможенной задолженности
  kaz: Мүлікті салық және кеден берешегі есебіне иеленуді шектеудің кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2004-07-11
approved_by:
- '103002002000'
version_date:
  kaz: 2005-02-28
  rus: 2005-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/20886/kaz/28.02.2005
  rus: https://zan.gov.kz/client/#!/doc/20886/rus/28.02.2005
caused_by:
  code: '23527'
  requisite: Приказ Председателя Налогового комитета Министерства финансов Республики Казахстан от 28 февраля 2005 года N 83. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 марта 2005 года N 3535. Утратил силу приказом Министра финансов Республики Казахстан от 30 декабря 2008 года N 637
  title:
    rus: О внесении изменений и дополнений в приказ Председателя Налогового комитета Министерства финансов Республики Казахстан от 12 июля 2004 года N 347 "О некоторых вопросах ограничения в распоряжении имуществом в счет налоговой и таможенной задолженности"
    kaz: '"Мүлікті салық және кеден берешегі есебіне иеленуді шектеудің кейбір мәселелері туралы" Қазақстан Республикасы Қаржы министрлігінің Салық комитеті Төрағасының 2004 жылғы 12 шілдедегі N 347 бұйрығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/23527/rus
