act_code: '11230'
requisite: Приказ Министра юстиции Республики Казахстан от 11 декабря 2001 года N 147. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 декабря 2001 года N 1714. Утратил силу - приказом Министра юстиции РК от 21 октября 20004 года N 305 (V043228)
title:
  rus: Об утверждении Инструкции об организации воспитательной работы с осужденными, отбывающими наказание в исправительных учреждениях Министерства юстиции Республики Казахстан
  kaz: Қазақстан Республикасы Әдiлет министрлiгiнiң түзеу мекемелерiнде жазасын өтеп жатқан сотталғандармен тәрбие жұмыстарын ұйымдастыру жөнiндегi нұсқаулықты бекiту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2001-12-11
approved_by:
- '103001000000'
version_date:
  kaz: 2001-12-11
  rus: 2001-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/11230/kaz/11.12.2001
  rus: https://zan.gov.kz/client/#!/doc/11230/rus/11.12.2001
