act_code: '158616'
requisite: Приказ Председателя Агентства Республики Казахстан по делам государственной службы от 10 сентября 2021 года № 158. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 сентября 2021 года № 24350
title:
  rus: О некоторых вопросах прохождения государственной службы
  kaz: Мемлекеттік қызметті өткерудің кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2021-09-10
approved_by:
- '120000000000'
version_date:
  kaz: 2025-05-16
  rus: 2025-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/158616/kaz/16.05.2025
  rus: https://zan.gov.kz/client/#!/doc/158616/rus/16.05.2025
caused_by:
  code: '210355'
  requisite: Приказ Председателя Агентства Республики Казахстан по делам государственной службы от 16 мая 2025 года № 86. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 мая 2025 года № 36124
  title:
    rus: О внесении изменений и дополнений в приказ Председателя Агентства Республики Казахстан по делам государственной службы от 10 сентября 2021 года № 158 «О некоторых вопросах прохождения государственной службы»
    kaz: «Мемлекеттік қызметті өткерудің кейбір мәселелері туралы» Қазақстан Республикасы Мемлекеттік қызмет істері агенттігі Төрағасының 2021 жылғы 10 қыркүйектегі № 158 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210355/rus
