act_code: '182332'
requisite: Приказ Министра национальной экономики Республики Казахстан от 29 мая 2023 года № 90. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 мая 2023 года № 32634. Утратил силу приказом Заместителя Премьер-Министра - Министра национальной экономики Республики Казахстан от 27 мая 2025 года № 34 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил поступлений от передачи в конкурентную среду активов национальных управляющих холдингов, национальных холдингов, национальных компаний и их дочерних, зависимых и иных юридических лиц, являющихся аффилированными с ними, в Национальный фонд Республики Казахстан
  kaz: Ұлттық басқарушы холдингтердің, ұлттық холдингтердің, ұлттық компаниялардың және олардың еншілес, тәуелді және олармен үлестес болып табылатын өзге де заңды тұлғалардың активтерін бәсекелес ортаға беруден Қазақстан Республикасының Ұлттық қорына түсетін түсімдердің қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2023-05-29
approved_by:
- '103033000000'
version_date:
  kaz: 2023-11-29
  rus: 2023-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/182332/kaz/29.11.2023
  rus: https://zan.gov.kz/client/#!/doc/182332/rus/29.11.2023
caused_by:
  code: '189613'
  requisite: Приказ Министра национальной экономики Республики Казахстан от 29 ноября 2023 года № 180. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 декабря 2023 года № 33726. Утратил силу приказом Заместителя Премьер-Министра - Министра национальной экономики Республики Казахстан от 27 мая 2025 года № 34 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра национальной экономики Республики Казахстан от 29 мая 2023 года № 90 «Об утверждении Правил поступлений от передачи в конкурентную среду активов национальных управляющих холдингов, национальных холдингов, национальных компаний и их дочерних, зависимых и иных юридических лиц, являющихся аффилированными с ними, в Национальный фонд Республики Казахстан»
    kaz: «Ұлттық басқарушы холдингтердің, ұлттық холдингтердің, ұлттық компаниялардың және олардың еншілес, тәуелді және олармен үлестес болып табылатын өзге де заңды тұлғалардың активтерін бәсекелес ортаға беруден Қазақстан Республикасының Ұлттық қорына түсетін түсімдердің қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық экономика министрінің 2023 жылғы 29 мамырдағы № 90 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189613/rus
