act_code: '97673'
requisite: Приказ Министра энергетики Республики Казахстан от 25 декабря 2015 года № 762. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 декабря 2015 года № 12753. Утратил силу приказом и.о. Министра экологии, геологии и природных ресурсов Республики Казахстан от 2 ноября 2021 года № 448 (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики расчета платы за организацию сбора, транспортировки, переработки, обезвреживания, использования и (или) утилизации отходов
  kaz: Қалдықтары жинауды, тасымалдауды, қайта өңдеуді, залалсыздандыруды, пайдалануды және (немесе) кәдеге жаратуды ұйымдастырғаны үшін төлемақыны есептеу әдістемесесін бекіту туралы
form: ПРИК
type_codes:
- МЕТ
- ПРИК
approved_on: 2015-12-25
approved_by:
- '103036000000'
version_date:
  kaz: 2021-04-20
  rus: 2021-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/97673/kaz/20.04.2021
  rus: https://zan.gov.kz/client/#!/doc/97673/rus/20.04.2021
caused_by:
  code: '156203'
  requisite: Приказ и.о. Министра экологии, геологии и природных ресурсов Республики Казахстан от 20 апреля 2021 года № 110. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 апреля 2021 года № 22594. Утратил силу приказом и.о. Министра экологии, геологии и природных ресурсов Республики Казахстан от 2 ноября 2021 года № 448 (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнений в приказ исполняющего обязанности Министра энергетики Республики Казахстан от 4 декабря 2015 года № 695 «Об утверждении перечня продукции (товаров), на которую (которые) распространяются расширенные обязательства производителей (импортеров)» и в приказ Министра энергетики Республики Казахстан от 25 декабря 2015 года № 762 «Об утверждении Методики расчета платы за организацию сбора, транспортировки, переработки, обезвреживания, использования и (или) утилизации отходов»
    kaz: «Өндірушілердің (импорттаушылардың) кеңейтілген міндеттемелері қолданылатын өнімнің (тауарлардың) тізбесін бекіту туралы» Қазақстан Республикасы Энергетика министрінің міндетін атқарушының 2015 жылғы 4 желтоқсандағы № 695 бұйрығына және «Қалдықтарды жинауды, тасымалдауды, қайта өңдеуді, залалсыздандыруды, пайдалануды және (немесе) кәдеге жаратуды ұйымдастырғаны үшін ақы төлеуді есептеу әдістемесін бекіту туралы» Қазақстан Республикасы Энергетика министрінің 2015 жылғы 25 желтоқсандағы № 762 бұйрығына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156203/rus
