act_code: '119420'
requisite: Приказ и.о. Министра национальной экономики Республики Казахстан от 21 февраля 2018 года № 67. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 марта 2018 года № 16509
title:
  rus: Об утверждении Перечня импортируемых товаров, по которым налог на добавленную стоимость уплачивается методом зачета и правил его формирования
  kaz: Қосылған құн салығы есепке алу әдісімен төленетін импортталатын тауарлардың тізбесін және оны қалыптастыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2018-02-21
approved_by:
- '103033000000'
version_date:
  kaz: 2020-05-05
  rus: 2020-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/119420/kaz/05.05.2020
  rus: https://zan.gov.kz/client/#!/doc/119420/rus/05.05.2020
caused_by:
  code: '142616'
  requisite: Приказ Министра национальной экономики Республики Казахстан от 5 мая 2020 года № 35. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 мая 2020 года № 20590
  title:
    rus: О внесении дополнений в приказ исполняющего обязанности Министра национальной экономики Республики Казахстан от 21 февраля 2018 года № 67 «Об утверждении Перечня импортируемых товаров, по которым налог на добавленную стоимость уплачивается методом зачета и правил его формирования»
    kaz: «Қосылған құн салығы есепке алу әдісімен төленетін импортталатын тауарлардың тізбесін және оны қалыптастыру қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық экономика министрінің міндетін атқарушының 2018 жылғы 21 ақпандағы № 67 бұйрығына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142616/rus
