act_code: '5736'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 11 марта 2000 года N 71-п. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 апреля 2000 года N 1110. Утратил силу приказом и.о. Министра труда и социальной защиты населения Республики Казахстан от 15 февраля 2005 года N 45-п (вводится в действие со дня его официального опубликования)
title:
  rus: Об утверждении "Списка производств, профессий и работ с тяжелыми, вредными и опасными условиями труда, на которых запрещается применение труда лиц моложе восемнадцати лет"
  kaz: '"Жасы он сегізге толмаған адамдардың еңбегін қолдануға тыйым салынатын еңбек жағдайлары ауыр, зиянды және қауіпті өндірістердің, кәсіптер мен жұмыстардың тізімін" бекіту туралы'
form: ПРИК
type_codes:
- ПРИК
approved_on: 2000-03-11
approved_by:
- '103016000000'
version_date:
  kaz: 2000-03-11
  rus: 2000-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/5736/kaz/11.03.2000
  rus: https://zan.gov.kz/client/#!/doc/5736/rus/11.03.2000
