act_code: '70133'
requisite: Приказ Министра юстиции Республики Казахстан от 29 ноября 2012 года № 390. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 декабря 2012 года № 8134
title:
  rus: Об утверждении регламентов государственных услуг в сфере регистрации актов гражданского состояния и о внесении изменений в приказ Министра юстиции Республики Казахстане от 27 июня 2011 года № 235 "Об утверждении регламентов государственных услуг"
  kaz: Қазақстан Республикасы Әділет министрінің 2011 жылғы 27 маусымдағы "Мемлекеттік қызмет регламентін бекіту туралы" № 235 бұйрығына өзгерістер мен түзетулер енгізу және азаматтық хал актілері саласы бойынша мемлекеттік қызметтер регламентін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2012-11-29
approved_by:
- '103001000000'
version_date:
  kaz: 2014-01-30
  rus: 2014-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/70133/kaz/30.01.2014
  rus: https://zan.gov.kz/client/#!/doc/70133/rus/30.01.2014
caused_by:
  code: '77986'
  requisite: Приказ Министра юстиции Республики Казахстан от 30 января 2014 года № 36. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 января 2014 года № 9114. Утратил силу приказом Министра юстиции Республики Казахстан от 30 июня 2015 года № 367
  title:
    rus: Об утверждении регламентов государственных услуг по вопросам регистрации актов гражданского состояния и апостилирования
    kaz: Азаматтық хал актілерін тіркеу және апостильдеу мәселелері бойынша мемлекеттік қызметтердің регламенттерін бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/77986/rus
