act_code: '124022'
requisite: Приказ Министра здравоохранения Республики Казахстан от 18 июля 2018 года № 434. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 августа 2018 года № 17264
title:
  rus: Об утверждении списка лекарственных средств, медицинских изделий в рамках гарантированного объема бесплатной медицинской помощи и в системе обязательного социального медицинского страхования, закупаемых у Единого дистрибьютора на 2019 год
  kaz: 2019 жылға арналған Бірыңғай дистрибьютордан сатып алынатын тегін медициналық көмектің кепілдік берілген көлемінің шеңберінде және әлеуметтік медициналық сақтандыру жүйесінде дәрілік заттардың, медициналық бұйымдардың тізімін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2018-07-18
approved_by:
- '103010000000'
version_date:
  kaz: 2018-07-18
  rus: 2018-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/124022/kaz/18.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124022/rus/18.07.2018
