act_code: '90657'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 28 апреля 2015 года № 494. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 июня 2015 года № 11272. Утратил силу приказом Министра культуры и информации Республики Казахстан от 5 сентября 2024 года № 408-НҚ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения конкурса по формированию перечня теле-, радиоканалов свободного доступа, распространяемых национальным оператором телерадиовещания
  kaz: Телерадио хабарларын таратудың ұлттық операторы тарататын еркін қолжетімді теле-, радиоарналардың тізбесін қалыптастыру бойынша конкурс өткізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-04-28
approved_by:
- '103035000000'
version_date:
  kaz: 2015-04-28
  rus: 2015-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/90657/kaz/28.04.2015
  rus: https://zan.gov.kz/client/#!/doc/90657/rus/28.04.2015
