act_code: '29434'
requisite: Приказ Министра финансов Республики Казахстан от 26 июля 2006 года № 273. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 августа 2006 года № 4354
title:
  rus: Об утверждении Правил проведения аттестации кандидатов в аудиторы
  kaz: Аудиторлыққа кандидаттарды аттестаттаудан өткізу қағидалары
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2006-07-26
approved_by:
- '103002000000'
version_date:
  kaz: 2023-04-24
  rus: 2023-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/29434/kaz/24.04.2023
  rus: https://zan.gov.kz/client/#!/doc/29434/rus/24.04.2023
caused_by:
  code: '180233'
  requisite: Приказ Заместителя Премьер-Министра - Министра финансов Республики Казахстан от 24 апреля 2023 года № 411. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 апреля 2023 года № 32362
  title:
    rus: О внесении изменений в приказ Заместителя Премьер-Министра – Министра финансов Республики Казахстан от 26 июля 2006 года № 273 «Об утверждении Правил проведения аттестации кандидатов в аудиторы»
    kaz: «Аудиторлыққа кандидаттарды аттестаттаудан өткізу қағидаларын бекіту туралы» Қазақстан Республикасы Премьер-Министрінің орынбасары – Қаржы министрінің 2006 жылғы 26 шілдедегі № 273 бұйрығына өзгерістер енгізу туралы»
  link: https://zan.gov.kz/client/#!/doc/180233/rus
