act_code: '117429'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 13 декабря 2017 года № 867. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 декабря 2017 года № 16165. Утратил силу приказом Министра промышленности и строительства Республики Казахстан от 20 марта 2026 года № 123 (вводится в действие с 1 июля 2026 года)
title:
  rus: Об утверждении Правил приемки построенного объекта в эксплуатацию собственником самостоятельно, а также формы акта приемки
  kaz: Меншік иесінің салынған объектіні пайдалануға дербес қабылдау қағидаларын, сондай-ақ қабылдау актісінің нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2017-12-13
approved_by:
- '103035000000'
version_date:
  kaz: 2024-10-08
  rus: 2024-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/117429/kaz/08.10.2024
  rus: https://zan.gov.kz/client/#!/doc/117429/rus/08.10.2024
caused_by:
  code: '201510'
repealed_on: 2026-07-01
repealed_by:
  code: '223280'
  requisite: Приказ Министра промышленности и строительства Республики Казахстан от 20 марта 2026 года № 123. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 марта 2026 года № 38184
  title:
    rus: Об утверждении Правил приемки, а также формы акта приемки строительного объекта в эксплуатацию заказчиком (собственником, инвестором) самостоятельно
    kaz: Тапсырыс берушінің (меншік иесінің, инвестордың) құрылыс объектісін пайдалануға өз бетінше қабылдау қағидаларын, сондай-ақ пайдалануға қабылдау актісінің нысанын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/223280/rus
