act_code: '85809'
requisite: Приказ и.о. Министра по инвестициям и развитию Республики Казахстан от 8 декабря 2014 года № 247. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 января 2015 года № 10069
title:
  rus: Об определении перечня социально значимых пассажирских межобластных сообщений
  kaz: Әлеуметтік маңызы бар облысаралық жолаушылар қатынастарының тізбесін айқындау туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2014-12-08
approved_by:
- '103035000000'
version_date:
  kaz: 2021-05-24
  rus: 2021-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/85809/kaz/24.05.2021
  rus: https://zan.gov.kz/client/#!/doc/85809/rus/24.05.2021
caused_by:
  code: '156171'
  requisite: Приказ и.о. Министра индустрии и инфраструктурного развития Республики Казахстан от 24 мая 2021 года № 256. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 мая 2021 года № 22840
  title:
    rus: О внесении изменения в приказ исполняющего обязанности Министра по инвестициям и развитию Республики Казахстан от 8 декабря 2014 года № 247 «Об определении перечня социально значимых пассажирских межобластных сообщений»
    kaz: «Әлеуметтік маңызы бар облысаралық жолаушылар қатынастарының тізбесін айқындау туралы» Қазақстан Республикасы Инвестициялар және даму министрінің міндетін атқарушының 2014 жылғы 8 желтоқсандағы № 247 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156171/rus
