act_code: '89246'
requisite: Приказ Министра юстиции Республики Казахстан от 26 декабря 2014 года № 382. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 января 2015 года № 10145. Утратил силу приказом Министра финансов Республики Казахстан от 5 мая 2018 года № 517 (вводится в действие с 13 июля 2018 года)
title:
  rus: Об утверждении Правил проведения квалификационного экзамена лиц, претендующих на право занятия оценочной деятельностью
  kaz: Бағалау қызметімен айналысу құқығына үміткер адамдарға біліктілік емтиханын өткізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2014-12-26
approved_by:
- '103001000000'
version_date:
  kaz: 2014-12-26
  rus: 2014-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/89246/kaz/26.12.2014
  rus: https://zan.gov.kz/client/#!/doc/89246/rus/26.12.2014
