act_code: '84379'
requisite: Приказ Генерального Прокурора Республики Казахстан от 10 октября 2014 года № 114. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 ноября 2014 года № 9869. Утратил силу приказом Генерального Прокурора Республики Казахстан от 24 декабря 2020 года № 159 (вводится в действие с 1 января 2021 года)
title:
  rus: Об утверждении Инструкции по формированию централизованного учета данных об административных правонарушениях и лицах, их совершивших
  kaz: Әкімшілік құқық бұзушылықтар және оларды жасаған адамдар туралы орталықтандырылған деректер есебін жүргізу жөніндегі нұсқаулығын бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2014-10-10
approved_by:
- '107000000000'
version_date:
  kaz: 2014-10-10
  rus: 2014-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/84379/kaz/10.10.2014
  rus: https://zan.gov.kz/client/#!/doc/84379/rus/10.10.2014
