act_code: '77990'
requisite: Приказ Председателя Агентства Республики Казахстан по защите прав потребителей от 18 февраля 2014 года № 5. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 февраля 2014 года № 9177. Утратил силу приказом Министра национальной экономики Республики Казахстан от 27 мая 2016 года № 223
title:
  rus: Об утверждении квалификационных требований к административным государственным должностям корпуса "Б" центрального аппарата Агентства Республики Казахстан по защите прав потребителей
  kaz: Қазақстан Республикасы Тұтынушылардың құқықтарын қорғау агенттігінің орталық аппараты "Б" корпусының әкімшілік мемлекеттік лауазымдарына қойылатын біліктілік талаптарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2014-02-18
approved_by:
- '132000000000'
version_date:
  kaz: 2014-02-18
  rus: 2014-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/77990/kaz/18.02.2014
  rus: https://zan.gov.kz/client/#!/doc/77990/rus/18.02.2014
