act_code: '12836'
requisite: Приказ Министра внутренних дел Республики Казахстан от 11 июля 2002 года N 487. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 августа 2002 года N 1934. Утратил силу - приказом Министра внутренних дел Республики Казахстан от 13 апреля 2004 года N 221 (V042864)
title:
  rus: Об утверждении Правил отбора и приема на факультет подготовки руководящих кадров органов внутренних дел и специалистов воспитательных аппаратов (факультет N 1) Академии Министерства внутренних дел Республики Казахстан
  kaz: Қазақстан Республикасы Ішкі істер министрлігі Академиясының ішкі істер органдарының басшы кадрларын және тәрбие аппараттарының мамандарын даярлау факультетіне (N 1 факультет) іріктеу мен қабылдау ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2002-07-10
approved_by:
- '103003000000'
version_date:
  kaz: 2003-11-19
  rus: 2003-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/12836/kaz/19.11.2003
  rus: https://zan.gov.kz/client/#!/doc/12836/rus/19.11.2003
caused_by:
  code: '17513'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 19 ноября 2003 года N 650. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 ноября 2003 года N 2567. Утратил силу - приказом Министра внутренних дел Республики Казахстан от 13 апреля 2004 года N 221 (V042864)
  title:
    rus: О внесении изменений в приказ Министра внутренних дел Республики Казахстан от 11 июля 2002 года N 487 "Об утверждении Правил отбора и приема на факультет подготовки руководящих кадров органов внутренних дел и специалистов воспитательных аппаратов (факультет N 1) Академии Министерства внутренних дел Республики Казахстан", зарегистрированный за N 1934
    kaz: Қазақстан Республикасының Әдiлет министрлiгiнде N 1934 тiркелген "Қазақстан Республикасы Iшкi iстер министрлiгi Академиясының iшкi iстер органдарының басшы кадрларын және тәрбие аппараттарының мамандарын даярлау факультетiне (N 1 факультет) iрiктеу мен қабылдау ережелерiн бекiту туралы" Қазақстан Республикасы Iшкi iстер министрiнiң 2002 жылғы 11 шiлдедегi N 487 бұйрығына өзгерiстер енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/17513/rus
