act_code: '98306'
requisite: Приказ Министра национальной экономики Республики Казахстан от 9 декабря 2015 года № 758. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 января 2016 года № 12846. Утратил силу приказом Министра здравоохранения Республики Казахстан от 1 сентября 2021 года № ҚР ДСМ – 95 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Санитарных правил "Санитарно-эпидемиологические требования к системам вентиляции и кондиционирования воздуха, их очистке и дезинфекции"
  kaz: '"Желдету мен ауаны баптау жүйелеріне, оларды тазалау мен дезинфекциялауға қойылатын санитариялық-эпидемиологиялық талаптар" санитариялық қағидаларын бекіту туралы'
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-12-09
approved_by:
- '103033000000'
version_date:
  kaz: 2015-12-09
  rus: 2015-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/98306/kaz/09.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98306/rus/09.12.2015
