act_code: '26405'
requisite: Приказ Генерального Прокурора Республики Казахстан от 4 января 2006 года № 1. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 января 2006 года № 4016. Утратил силу приказом Генерального Прокурора Республики Казахстан от 27 августа 2008 года № 47
title:
  rus: Об утверждении Инструкции об организации надзора за законностью следствия и дознания
  kaz: Тергеу және анықтау заңдылығын прокурорлық қадағалауды ұйымдастыру туралы нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2006-01-04
approved_by:
- '107000000000'
version_date:
  kaz: 2006-01-04
  rus: 2006-01-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/26405/kaz/04.01.2006
  rus: https://zan.gov.kz/client/#!/doc/26405/rus/04.01.2006
