act_code: '2888'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 19.03.99 г. № 44-п. Зарегистрирован в Министерстве юстиции Республики Казахстан 26.04.1999г. № 741. Утратил приказом Министра труда и социальной защиты населения Республики Казахстан от 19 апреля 2007 года № 90-п
title:
  rus: Об утверждении Инструкции по осуществлению выплаты пенсий за выслугу лет, государственной базовой пенсионной выплаты и государственных социальных пособий военнослужащим, сотрудникам органов внутренних дел, Комитета уголовно-исполнительной системы Министерства юстиции Республики Казахстан, органов финансовой полиции и государственной противопожарной службы из Государственного центра по выплате пенсий
  kaz: Әскери қызметшілерге, Ішкі істер органдары, Қазақстан Республикасының Әдiлет министрлiгi Қылмыстық-атқару жүйесi комитетiнiң, қаржы полициясы және мемлекеттiк өртке қарсы қызмет органдарының қызметкерлеріне Зейнетақы төлеу жөніндегі мемлекеттік орталықтан еңбек сіңірген жылдары үшін зейнетақы, мемлекеттік базалық зейнетақы және мемлекеттік әлеуметтік жәрдемақы төлеуді жүзеге асыру жөніндегі Нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 1999-03-19
approved_by:
- '103016000000'
version_date:
  kaz: 1999-03-19
  rus: 1999-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/2888/kaz/19.03.1999
  rus: https://zan.gov.kz/client/#!/doc/2888/rus/19.03.1999
