act_code: '36235'
requisite: Приказ и.о. Министра образования и науки Республики Казахстан от 22 ноября 2007 года N 574. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 декабря 2007 года N 5038. Утратил силу приказом Министра науки и высшего образования Республики Казахстан от 1 апреля 2025 года № 157 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Типовых правил деятельности Ученого совета высшего учебного заведения и порядок его избрания
  kaz: Жоғары оқу орнының Ғылыми Кеңесі қызметінің үлгі ережесін және оны сайлау тәртібін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2007-11-22
approved_by:
- '103006000000'
version_date:
  kaz: 2007-11-22
  rus: 2007-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/36235/kaz/22.11.2007
  rus: https://zan.gov.kz/client/#!/doc/36235/rus/22.11.2007
