act_code: '77674'
requisite: Приказ Министра здравоохранения Республики Казахстан от 27 декабря 2013 года № 759. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 января 2014 года № 9108. Утратил силу приказом Министра здравоохранения Республики Казахстан от 7 апреля 2023 года № 65 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении стандарта организации оказания медицинской реабилитации населению Республики Казахстан
  kaz: Қазақстан Республикасының халқына медициналық оңалту көрсетуді ұйымдастыру стандартын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2013-12-27
approved_by:
- '103010000000'
version_date:
  kaz: 2016-12-21
  rus: 2016-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/77674/kaz/21.12.2016
  rus: https://zan.gov.kz/client/#!/doc/77674/rus/21.12.2016
caused_by:
  code: '109128'
  requisite: Приказ Министра здравоохранения и социального развития Республики Казахстан от 21 декабря 2016 года № 1083. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 января 2017 года № 14686. Утратил силу приказом Министра здравоохранения Республики Казахстан от 7 апреля 2023 года № 65 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра здравоохранения Республики Казахстан от 27 декабря 2013 года № 759 «Об утверждении стандарта организации оказания медицинской реабилитации населению Республики Казахстан»
    kaz: «Қазақстан Республикасының Халқына медициналық оңалту көрсетуді ұйымдастыру стандартын бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2013 жылғы 27 желтоқсандағы № 759 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/109128/rus
