act_code: '131703'
requisite: Приказ Министра здравоохранения Республики Казахстан от 8 мая 2019 года № 207. Утратил силу приказом Министра здравоохранения Республики Казахстан от 8 октября 2020 года № 644 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении положений республиканского государственного учреждения «Комитет контроля качества и безопасности товаров и услуг Министерства здравоохранения Республики Казахстан» и его территориальных подразделений
  kaz: «Қазақстан Республикасы Денсаулық сақтау министрлігінің Тауарлар мен көрсетілетін қызметтердің сапасы мен қауіпсіздігін бақылау комитеті» республикалық мемлекеттік мекемесінің және оның аумақтық бөлімшелерінің ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2019-05-08
approved_by:
- '103010000000'
version_date:
  kaz: 2020-01-29
  rus: 2020-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/131703/kaz/29.01.2020
  rus: https://zan.gov.kz/client/#!/doc/131703/rus/29.01.2020
caused_by:
  code: '139299'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 29 января 2020 года № 43. Утратил силу приказом Министра здравоохранения Республики Казахстан от 9 апреля 2025 года № 235 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменения в приказ Министра здравоохранения Республики Казахстан от 8 мая 2019 года № 207 «Об утверждении положений республиканского государственного учреждения «Комитет контроля качества и безопасности товаров и услуг Министерства здравоохранения Республики Казахстан» и его территориальных подразделений»
    kaz: «Қазақстан Республикасы Денсаулық сақтау министрлігінің Тауарлар мен көрсетілетін қызметтердің сапасы мен қауіпсіздігін бақылау комитеті» республикалық мемлекеттік мекемесінің және оның аумақтық бөлімшелерінің ережелерін бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2019 жылғы 8 мамырдағы № 207 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/139299/rus
