act_code: '169880'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 14 июля 2022 года № 188. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 июля 2022 года № 28823. Утратил силу приказом Министра туризма и спорта Республики Казахстан от 1 июля 2025 года № 115 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил определения стоимости исследований, консалтинговых услуг и государственного задания Министерства туризма и спорта Республики Казахстан
  kaz: Қазақстан Республикасы Туризм және спорт министрлігінің зерттеулердің, консалтингтік көрсетілетін қызметтердің және мемлекеттік тапсырманың құнын айқындау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-07-14
approved_by:
- '103034000000'
version_date:
  kaz: 2024-06-20
  rus: 2024-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/169880/kaz/20.06.2024
  rus: https://zan.gov.kz/client/#!/doc/169880/rus/20.06.2024
caused_by:
  code: '197974'
  requisite: Приказ Министра туризма и спорта Республики Казахстан от 20 июня 2024 года № 122. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 июня 2024 года № 34548. Утратил силу приказом Министра туризма и спорта Республики Казахстан от 1 июля 2025 года № 115 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра культуры и спорта Республики Казахстан от 14 июля 2022 года № 188 «Об утверждении Правил определения стоимости исследований, консалтинговых услуг и государственного задания Министерства культуры и спорта Республики Казахстан»
    kaz: «Қазақстан Республикасы Мәдениет және спорт министрлігінің зерттеулердің, консалтингтік көрсетілетін қызметтердің және мемлекеттік тапсырманың құнын айқындау қағидаларын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің 2022 жылғы 14 шілдедегі № 188 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/197974/rus
