act_code: '87027'
requisite: Приказ и.о. Министра по инвестициям и развитию Республики Казахстан от 26 декабря 2014 года № 300. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 февраля 2015 года № 10242
title:
  rus: Об утверждении Правил определения общего уровня опасности опасного производственного объекта
  kaz: Қауіпті өндірістік объектінің қауіптілігінің жалпы деңгейін айқындау қағидаларын туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2014-12-26
approved_by:
- '103035000000'
version_date:
  kaz: 2014-12-26
  rus: 2014-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/87027/kaz/26.12.2014
  rus: https://zan.gov.kz/client/#!/doc/87027/rus/26.12.2014
