act_code: '213977'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 5 сентября 2025 года № 283. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 сентября 2025 года № 36810
title:
  rus: Об утверждении типовой формы Плана развития субъектов аквакультуры
  kaz: Аквашаруашылық субъектілерін дамыту жоспарының үлгілік нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-09-05
approved_by:
- '103012000000'
version_date:
  kaz: 2025-09-05
  rus: 2025-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/213977/kaz/05.09.2025
  rus: https://zan.gov.kz/client/#!/doc/213977/rus/05.09.2025
