act_code: '26823'
requisite: Приказ Председателя Комитета по водным ресурсам Министерства сельского хозяйства Республики Казахстан от 17 февраля 2006 года № 29. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 марта 2006 года № 4124. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 18 апреля 2012 года № 19-02/183
title:
  rus: Об утверждении правил регистрации водных объектов, используемых юридическими и физическими лицами при нецентрализованном питьевом и хозяйственно-бытовом водоснабжении населения
  kaz: Халықты орталықтандырылмаған ауыз су және шаруашылық-тұрмыстық сумен жабдықтау кезiнде заңды және жеке тұлғалармен пайдаланылатын су объектiлерiн тiркеу ережелерiн бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2006-02-17
approved_by:
- '103012002000'
version_date:
  rus: 2006-02-17
source:
  rus: https://zan.gov.kz/client/#!/doc/26823/rus/17.02.2006
