act_code: '88161'
requisite: Приказ Министра национальной экономики Республики Казахстан от 25 февраля 2015 года № 130. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 марта 2015 года № 10527. Утратил силу приказом Министра здравоохранения Республики Казахстан от 21 декабря 2020 года № ҚР ДСМ-293/2020 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Перечня инфекционных заболеваний, при угрозе возникновения и распространения которых вводятся ограничительные мероприятия, в том числе карантин
  kaz: Пайда болу және таралу қаупі төнген кезде шектеу іс-шаралары, оның ішінде карантин енгізілетін инфекциялық аурулар тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2015-02-25
approved_by:
- '103033000000'
version_date:
  kaz: 2015-02-25
  rus: 2015-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/88161/kaz/25.02.2015
  rus: https://zan.gov.kz/client/#!/doc/88161/rus/25.02.2015
