act_code: '6126'
requisite: Приказ Министра образования и науки Республики Казахстан от 31 мая 2000 года N 529  Зарегистрирован в Министерстве юстиции Республики Казахстан 6.06.2000 г. за N 1145. Утратил силу приказом Министра образования и науки Республики Казахстан от 10 марта 2005 года N 145.
title:
  rus: О квоте приема граждан, окончивших сельские школы, в высшие учебные заведения Республики Казахстан в 2000 году
  kaz: 2000 жылы ауыл мектептерін бітірген азаматтарды Қазақстан Республикасы жоғары оқу орындарына қабылдау квотасы туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2000-05-30
approved_by:
- '103006000000'
version_date:
  kaz: 2000-05-30
  rus: 2000-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/6126/kaz/30.05.2000
  rus: https://zan.gov.kz/client/#!/doc/6126/rus/30.05.2000
