act_code: '119442'
requisite: Приказ Министра финансов Республики Казахстан от 20 февраля 2018 года № 241. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 марта 2018 года № 16496. Утратил силу приказом Министра финансов Республики Казахстан от 10 ноября 2025 года № 685 (вводится в действие с 1 января 2026 года)
title:
  rus: Об утверждении Правил, формы и сроков уведомления органов государственных доходов о получении денег и (или) иного имущества от иностранных государств, международных и иностранных организаций, иностранцев, лиц без гражданства
  kaz: Шет мемлекеттерден, халықаралық және шетелдік ұйымдардан, шетелдіктерден, азаматтығы жоқ адамдардан ақша және (немесе) өзге де мүлік алғаны туралы мемлекеттік кірістер органдарына хабарлау қағидаларын, нысанын және мерзімдерін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-02-20
approved_by:
- '103002000000'
version_date:
  kaz: 2019-05-23
  rus: 2019-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/119442/kaz/23.05.2019
  rus: https://zan.gov.kz/client/#!/doc/119442/rus/23.05.2019
caused_by:
  code: '131944'
  requisite: Приказ Первого заместителя Премьер-Министра Республики Казахстан – Министра финансов Республики Казахстан от 23 мая 2019 года № 476. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 мая 2019 года № 18747. Утратил силу приказом Министра финансов Республики Казахстан от 10 ноября 2025 года № 685 (вводится в действие с 1 января 2026 года)
  title:
    rus: О внесении изменений и дополнения в приказы Министра финансов Республики Казахстан от 20 февраля 2018 года № 241 «Об утверждении Правил, формы и сроков уведомления органов государственных доходов о получении денег и (или) иного имущества от иностранных государств, международных и иностранных организаций, иностранцев, лиц без гражданства» и № 242 «Об утверждении Правил, сроков и формы представления в орган государственных доходов сведений о получении и расходовании денег и (или) иного имущества, полученных от иностранных государств, международных и иностранных организаций, иностранцев, лиц без гражданства»
    kaz: «Шет мемлекеттерден, халықаралық және шетелдік ұйымдардан, шетелдіктерден, азаматтығы жоқ адамдардан ақша және (немесе) өзге де мүлік алғаны туралы мемлекеттік кірістер органдарына хабарлау қағидаларын, нысанын және мерзімдерін бекіту туралы» Қазақстан Республикасы Қаржы министрінің 2018 жылғы 20 ақпандағы № 241 және «Шет мемлекеттерден, халықаралық және шетелдік ұйымдардан, шетелдіктерден, азаматтығы жоқ адамдардан алынған ақшаны және (немесе) өзге де мүлікті алғаны және жұмсағаны туралы мәліметтерді мемлекеттік кірістер органдарына ұсыну қағидаларын, мерзімін және нысанын бекіту туралы» Қазақстан Республикасы Қаржы министрінің 2018 жылғы 20 ақпандағы № 242 бұйрықтарына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131944/rus
