act_code: '152938'
requisite: Приказ Руководителя Бюро национальной статистики Агентства по стратегическому планированию и реформам Республики Казахстан от 15 февраля 2021 года № 6. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 февраля 2021 года № 22227
title:
  rus: Об утверждении статистической формы общегосударственного статистического наблюдения «Уровень доверия населения к правоохранительным органам и судебной системе» (индекс УДН, периодичность два раза в год) и инструкции по ее заполнению
  kaz: «Халықтың құқық қорғау органдарына және сот жүйесіне деген сенімділік деңгейі» (индексі УДН, кезеңділігі жылына екі рет) жалпымемлекеттік статистикалық байқаудың статистикалық нысаны мен оны толтыру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2021-02-15
approved_by:
- '136001000000'
version_date:
  kaz: 2021-02-15
  rus: 2021-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/152938/kaz/15.02.2021
  rus: https://zan.gov.kz/client/#!/doc/152938/rus/15.02.2021
