act_code: '228057'
requisite: Приказ и.о. Министра транспорта Республики Казахстан от 23 июля 2026 года № 189. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 июля 2026 года № 39385
title:
  rus: О приостановлении действий некоторых структурных элементов приказа исполняющего обязанности Министра по инвестициям и развитию Республики Казахстан от 26 марта 2015 года № 349 «Об утверждении Правил перевозок пассажиров и багажа автомобильным транспортом, за исключением городов республиканского значения, столицы» и приказа Министра по инвестициям и развитию Республики Казахстан от 30 апреля 2015 года № 546 «Об утверждении Правил перевозок грузов автомобильным транспортом»
  kaz: «Республикалық маңызы бар қалаларды, астананы қоспағанда, автомобиль көлігімен жолаушылар мен багажды тасымалдау қағидаларын бекіту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің міндетін атқарушының 2015 жылғы 26 наурыздағы № 349 бұйрығының және «Автомобиль көлігімен жүктерді тасымалдау қағидаларын бекіту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің 2015 жылғы 30 сәуірдегі № 546 бұйрығының кейбір құрылымдық элементтерінің әрекеттерін тоқтата тұру туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2026-07-23
approved_by:
- '103051000000'
version_date:
  kaz: 2026-07-23
  rus: 2026-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/228057/kaz/23.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228057/rus/23.07.2026
