act_code: '68267'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 14 сентября 2012 года № 25-02/457. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 октября 2012 года № 8015
title:
  rus: Об утверждении образцов и Правил ношения форменной одежды со знаками различия (без погон) должностных лиц государственной лесной инспекции Республики Казахстан и государственной лесной охраны Республики Казахстан
  kaz: Қазақстан Республикасының мемлекеттік орман инспекциясы мен Қазақстан Республикасы мемлекеттік орман күзетінің лауазымды адамдарының айырым белгілері бар нысанды киім (погонсыз) үлгілерін және оны киіп жүру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2012-09-14
approved_by:
- '103012000000'
version_date:
  kaz: 2012-09-14
  rus: 2012-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/68267/kaz/14.09.2012
  rus: https://zan.gov.kz/client/#!/doc/68267/rus/14.09.2012
