act_code: '5419'
requisite: Приказ Министра финансов Республики Казахстан от 30 декабря 1999 года N 715. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 февраля 2000 года N 1058. Утратил силу - приказом Министра финансов РК от 26.09.2002г. № 453 (извлечение из приказа см.ниже)
title:
  rus: Об утверждении Единой бюджетной классификации
  kaz: Бірыңғай бюджеттік сыныптаманы бекіту туралы
form: ПРИК
type_codes:
- КЛАС
- ПРИК
approved_on: 1999-12-30
approved_by:
- '103002000000'
version_date:
  rus: 2000-07-14
source:
  rus: https://zan.gov.kz/client/#!/doc/5419/rus/14.07.2000
caused_by:
  code: '6587'
  requisite: Приказ Министра финансов Республики Казахстан от 15.07.2000г. N 326. Зарегистрирован в Министерстве юстиции Республики Казахстан 29.07.2000г. за N 1203. Утратил силу - приказом Министра экономики и бюджетного планирования РК от 02.06.2005г. N 75
  title:
    rus: О внесении дополнения N 18 в Единую бюджетную классификацию на 2000 год
    kaz: 2000 жылға арналған Бірыңғай бюджеттік сыныптамаға N 18 толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/6587/rus
