act_code: '92043'
requisite: Приказ Министра образования и науки Республики Казахстан от 17 июня 2015 года № 391. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 июля 2015 года № 11716. Утратил силу приказом Министра науки и высшего образования Республики Казахстан от 5 января 2024 года № 4 (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении квалификационных требований, предъявляемых к образовательной деятельности организаций, предоставляющих высшее и (или) послевузовское образование, и перечня документов, подтверждающих соответствие им
  kaz: Жоғары және (немесе) жоғары білімнен кейінгі білім беру білім беру ұйымдарының білім беру қызметіне қойылатын біліктілік талаптарын және оларға сәйкестікті растайтын құжаттардың тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2015-06-17
approved_by:
- '103006000000'
version_date:
  kaz: 2021-09-20
  rus: 2021-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/92043/kaz/20.09.2021
  rus: https://zan.gov.kz/client/#!/doc/92043/rus/20.09.2021
caused_by:
  code: '157029'
  requisite: Приказ и.о. Министра образования и науки Республики Казахстан от 14 июля 2021 года № 339. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 июля 2021 года № 23542. Утратил силу приказом Министра науки и высшего образования Республики Казахстан от 5 января 2024 года № 4 (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в приказ Министра образования и науки Республики Казахстан от 17 июня 2015 года № 391 «Об утверждении квалификационных требований, предъявляемых к образовательной деятельности, и перечня документов, подтверждающих соответствие им»
    kaz: «Білім беру қызметіне қойылатын біліктілік талаптарын және оларға сәйкестікті растайтын құжаттардың тізбесін бекіту туралы» Қазақстан Республикасы Білім және ғылым министрінің 2015 жылғы 17 маусымдағы № 391 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157029/rus
