act_code: '92043'
requisite: Приказ Министра образования и науки Республики Казахстан от 17 июня 2015 года № 391. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 июля 2015 года № 11716. Утратил силу приказом Министра науки и высшего образования Республики Казахстан от 5 января 2024 года № 4 (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении квалификационных требований, предъявляемых к образовательной деятельности организаций, предоставляющих высшее и (или) послевузовское образование, и перечня документов, подтверждающих соответствие им
  kaz: Жоғары және (немесе) жоғары білімнен кейінгі білім беру білім беру ұйымдарының білім беру қызметіне қойылатын біліктілік талаптарын және оларға сәйкестікті растайтын құжаттардың тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2015-06-17
approved_by:
- '103006000000'
version_date:
  kaz: 2023-03-27
  rus: 2023-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/92043/kaz/27.03.2023
  rus: https://zan.gov.kz/client/#!/doc/92043/rus/27.03.2023
caused_by:
  code: '178210'
repealed_on: 2024-03-12
repealed_by:
  code: '191925'
  requisite: Приказ Министра науки и высшего образования Республики Казахстан от 5 января 2024 года № 4. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 января 2024 года № 33892
  title:
    rus: Об утверждении квалификационных требований, предъявляемых к образовательной деятельности организаций, предоставляющих высшее и (или) послевузовское образование, и перечня документов, подтверждающих соответствие им
    kaz: Жоғары және (немесе) жоғары оқу орнынан кейінгі білім беру ұйымдарының білім беру қызметіне қойылатын біліктілік талаптарын және оларға сәйкестікті растайтын құжаттардың тізбесін бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/191925/rus
