act_code: '86309'
requisite: Приказ Министра финансов Республики Казахстан от 25 декабря 2014 года № 585. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 января 2015 года № 10152. Утратил силу приказом Министра финансов Республики Казахстан от 13 февраля 2018 года № 172 (вводятся в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении уполномоченного юридического лица в сфере реализации имущества, заложенного налогоплательщиком и (или) третьим лицом, а также ограниченного в распоряжении имущества налогоплательщика (налогового агента), плательщика и (или) товаров, задержанных органами государственных доходов
  kaz: Салық төлеушінің және (немесе) үшінші тұлғаның кепілге салынған мүлкін, сонымен қатар салық төлеушінің (салық агентінің), төлеушінің билік етуі шектелген мүлкін және (немесе) мемлекеттік кірістер органдары ұстаған тауарларды өткізу саласындағы уәкілетті заңды тұлғаны айқындау туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2014-12-25
approved_by:
- '103002000000'
version_date:
  kaz: 2014-12-25
  rus: 2014-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/86309/kaz/25.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86309/rus/25.12.2014
