act_code: '143569'
requisite: Приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 2 июня 2020 года № 130. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 июня 2020 года № 20823
title:
  rus: Об утверждении Правил оказания государственных услуг в области охраны окружающей среды
  kaz: «Қоршаған ортаны қорғау саласындағы мемлекеттік көрсетілетін қызметтер қағидаларын бекіту туралы»
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-06-02
approved_by:
- '103047000000'
version_date:
  kaz: 2022-06-22
  rus: 2022-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/143569/kaz/22.06.2022
  rus: https://zan.gov.kz/client/#!/doc/143569/rus/22.06.2022
caused_by:
  code: '169248'
  requisite: Приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 22 июня 2022 года № 231. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 июня 2022 года № 28600
  title:
    rus: О внесении изменений в приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 2 июня 2020 года № 130 «Об утверждении Правил оказания государственных услуг в области охраны окружающей среды»
    kaz: «Қоршаған ортаны қорғау саласындағы мемлекеттік көрсетілетін қызметтер қағидаларын бекіту туралы» Қазақстан Республикасы Экология, геология және табиғи ресурстар министрінің 2020 жылғы 2 маусымдағы № 130 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169248/rus
