act_code: '14113'
requisite: Приказ Министра внутренних дел Республики Казахстан от 14 декабря 2002 года N 787. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 января 2003 года N 2123. Утратил силу приказом Министра внутренних дел Республики Казахстан от 5 октября 2004 года N 564
title:
  rus: Об утверждении Правил по организации работы участковых инспекторов полиции и их помощников
  kaz: Полиция учаскелiк инспекторлары мен олардың көмекшілерiнiң жұмысын ұйымдастыру жөнiндегi тәртiптi бекiту туралы
form: ПРИК
type_codes:
- ПОР
- ПРАВ
- ПРИК
approved_on: 2002-12-14
approved_by:
- '103003000000'
version_date:
  kaz: 2002-12-14
  rus: 2002-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/14113/kaz/14.12.2002
  rus: https://zan.gov.kz/client/#!/doc/14113/rus/14.12.2002
