act_code: '151290'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 31 декабря 2020 года № 560. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 января 2021 года № 22030
title:
  rus: Об установлении квоты на привлечение иностранной рабочей силы для осуществления трудовой деятельности на территории Республики Казахстан на 2021 год
  kaz: Қазақстан Республикасының аумағында еңбек қызметін жүзеге асыру үшін шетелдік жұмыс күшін тартуға 2021 жылға арналған квотаны белгілеу туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2020-12-31
approved_by:
- '103016000000'
version_date:
  kaz: 2020-12-31
  rus: 2020-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/151290/kaz/31.12.2020
  rus: https://zan.gov.kz/client/#!/doc/151290/rus/31.12.2020
