act_code: '3437'
requisite: Приказ Таможенного комитета Республики Казахстан от 1 сентября 1996 года N 175-п зарегистрировано в Министерстве юстиции Республики Казахстан 31.10.1996 г. № 213
title:
  rus: Об утверждении Порядка происхождения товаров развивающихся стран при предоставлении тарифных преференций в рамках общей системы преференций
  kaz: Преференциялардың жалпы жүйесiнiң аясында тарифтiк преференцияларды беру кезiнде дамушы елдерден тауарлардың шығуын анықтаудың тәртiбi
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 1996-08-31
approved_by:
- '103002004000'
version_date:
  rus: 1996-08-31
source:
  rus: https://zan.gov.kz/client/#!/doc/3437/rus/31.08.1996
