act_code: '194507'
requisite: Приказ Министра по чрезвычайным ситуациям Республики Казахстан от 14 марта 2024 года № 93
title:
  rus: Об утверждении Инструкции по организации учета, эксплуатации и хранения средств радиационной, химической и биологической защиты в воинских частях гражданской обороны
  kaz: Азаматтық қорғаныс әскери бөлімдерінде радиациялық, химиялық және биологиялық қорғау құралдарын есепке алуды, пайдалануды және сақтауды ұйымдастыру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2024-03-14
approved_by:
- '103007000000'
version_date:
  kaz: 2024-03-14
  rus: 2024-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/194507/kaz/14.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194507/rus/14.03.2024
