act_code: '57226'
requisite: Совместный приказ Министра труда и социальной защиты населения Республики Казахстан от 7 декабря 2010 года № 399-ө, Министра здравоохранения Республики Казахстан от 13 декабря 2010 года № 961 и Министра образования и науки Республики Казахстан от 27 декабря 2010 года № 581. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 января 2011 года № 6742. Утратил силу совместным приказом Министра труда и социальной защиты населения Республики Казахстан от 30 апреля 2013 года № 190-Ө-М и Министра образования и науки Республики Казахстан от 28 мая 2013 года № 202, Министра здравоохранения Республики Казахстан от 29 мая 2013 года № 314
title:
  rus: Об утверждении Инструкции по комплексной реабилитации детей-инвалидов с психоневрологическими патологиями
  kaz: Психоневрологиялық патологиясы бар мүгедек балаларды кешенді оңалту жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2010-12-07
approved_by:
- '103006000000'
- '103010000000'
- '103016000000'
version_date:
  kaz: 2010-12-07
  rus: 2010-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/57226/kaz/07.12.2010
  rus: https://zan.gov.kz/client/#!/doc/57226/rus/07.12.2010
