act_code: '225507'
requisite: Приказ Министра промышленности и строительства Республики Казахстан от 20 мая 2026 года № 250. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 мая 2026 года № 38767
title:
  rus: Об утверждении Правил и разрешительных требований по аккредитации юридических лиц, осуществляющих инжиниринговые услуги и экспертные работы по техническому надзору и техническому обследованию надежности и устойчивости зданий и сооружений на объектах первого и второго уровней ответственности
  kaz: Бірінші және екінші жауапкершілік деңгейіндегі объектілердегі ғимараттардың және құрылысжайлардың сенімділігі мен орнықтылығын техникалық қадағалау жөніндегі инжинирингтік көрсетілетін қызметтерді және техникалық зерттеп-қарау жөніндегі сараптама жұмыстарын жүзеге асыратын заңды тұлғаларды аккредиттеу жөніндегі қағидалар мен рұқсат беру талаптарын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
- ТРЕБ
approved_on: 2026-05-20
approved_by:
- '103052000000'
version_date:
  kaz: 2026-05-20
  rus: 2026-05-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/225507/kaz/20.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225507/rus/20.05.2026
