act_code: '89038'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 30 января 2015 года № 99. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 апреля 2015 года № 10733
title:
  rus: Об утверждении перечня товаров, произведенных на территории свободного склада и реализуемых с данной территории на остальную часть территории Республики Казахстан, обороты по реализации которых освобождаются от налога на добавленную стоимость
  kaz: Еркін қойма аумағында өндірілген және осы аумақтан Қазақстан Республикасы аумағының қалған бөлігіне өткізілетін, өткізу бойынша айналымдары қосылған құн салығынан босатылатын тауарлардың тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2015-01-30
approved_by:
- '103035000000'
version_date:
  kaz: 2015-01-30
  rus: 2015-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/89038/kaz/30.01.2015
  rus: https://zan.gov.kz/client/#!/doc/89038/rus/30.01.2015
