act_code: '72222'
requisite: Приказ Министра юстиции Республики Казахстан от 19 апреля 2013 года № 127. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 апреля 2013 года № 8429. Утратил силу приказом Министра юстиции Республики Казахстан от 26 декабря 2018 года № 1627 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Типовых форм постановлений государственных судебных исполнителей
  kaz: Мемлекеттік сот орындаушылары қаулыларының үлгі нысандарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2013-04-19
approved_by:
- '103001000000'
version_date:
  kaz: 2015-11-30
  rus: 2015-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/72222/kaz/30.11.2015
  rus: https://zan.gov.kz/client/#!/doc/72222/rus/30.11.2015
caused_by:
  code: '96037'
  requisite: Приказ Министра юстиции Республики Казахстан от 30 ноября 2015 года № 600. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 декабря 2015 года № 12367. Утратил силу приказом Министра юстиции Республики Казахстан от 26 декабря 2018 года № 1627 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра юстиции Республики Казахстан от 19 апреля 2013 года № 127 «Об утверждении Типовых форм постановлений государственных судебных исполнителей»
    kaz: «Мемлекеттік сот орындаушыларының қаулыларының үлгілік нысандарын бекіту туралы» Қазақстан Республикасы Әділет Министрінің 2013 жылғы 19 сәуірдегі № 127 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/96037/rus
