act_code: '152548'
requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 18 января 2021 года № 4/қбп. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 января 2021 года № 22129
title:
  rus: Об утверждении Правил деятельности представителей Пограничной службы Комитета национальной безопасности Республики Казахстан по подготовке, согласованию технической и иной документации пограничных кораблей, катеров и судов, контролю их производства и приемке в соответствии с законодательством Республики Казахстан об оборонной промышленности и государственном оборонном заказе
  kaz: Қорғаныс өнеркәсібі және мемлекеттік қорғаныстық тапсырыс туралы Қазақстан Республикасының заңнамасына сәйкес шекаралық корабльдердің, катерлер мен кемелердің техникалық және өзге де құжаттамасын дайындау, келісу, оларды өндіруді бақылау және қабылдау жөніндегі Қазақстан Республикасы Ұлттық қауіпсіздік комитеті Шекара қызметі өкілдерінің іс-қимылы қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2021-01-18
approved_by:
- '108000000000'
version_date:
  kaz: 2021-01-18
  rus: 2021-01-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/152548/kaz/18.01.2021
  rus: https://zan.gov.kz/client/#!/doc/152548/rus/18.01.2021
