act_code: '150174'
requisite: Приказ Министра здравоохранения Республики Казахстан от 20 декабря 2020 года № ҚР ДСМ-282/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 декабря 2020 года № 21836
title:
  rus: Об утверждении правил проведения оценки качества лекарственных средств и медицинских изделий, зарегистрированных в Республике Казахстан
  kaz: Қазақстан Республикасында тіркелген дәрілік заттар мен медициналық бұйымдардың сапасына бағалау жүргізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-12-20
approved_by:
- '103010000000'
version_date:
  kaz: 2022-09-14
  rus: 2022-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/150174/kaz/14.09.2022
  rus: https://zan.gov.kz/client/#!/doc/150174/rus/14.09.2022
caused_by:
  code: '171708'
  requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 14 сентября 2022 года № ҚР ДСМ-99. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 сентября 2022 года № 29636
  title:
    rus: О внесении изменений в приказ Министра здравоохранения Республики Казахстан от 20 декабря 2020 года № ҚР ДСМ-282/2020 «Об утверждении правил проведения оценки качества лекарственных средств и медицинских изделий, зарегистрированных в Республике Казахстан»
    kaz: «Қазақстан Республикасында тіркелген дәрілік заттар мен медициналық бұйымдардың сапасына бағалау жүргізу қағидаларын бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2020 жылғы 20 желтоқсандағы № ҚР ДСМ-282/2020 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171708/rus
