act_code: '212385'
requisite: Приказ и.о. Министра науки и высшего образования Республики Казахстан от 14 мая 2025 года № 238
title:
  rus: О размещении государственного образовательного заказа на подготовку кадров с высшим образованием на 2025-2026 учебный год
  kaz: 2025-2026 оқу жылына жоғары білімі бар кадрларды даярлауға арналған мемлекеттік білім беру тапсырысын орналастыру туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-05-14
approved_by:
- '103049000000'
version_date:
  kaz: 2025-07-14
  rus: 2025-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/212385/kaz/14.07.2025
  rus: https://zan.gov.kz/client/#!/doc/212385/rus/14.07.2025
caused_by:
  code: '213009'
  requisite: Приказ Министра науки и высшего образования Республики Казахстан от 14 июля 2025 года № 374
  title:
    rus: О внесении изменений в некоторые приказы Министра науки и высшего образования Республики Казахстан
    kaz: Қазақстан Республикасы Ғылым және жоғары білім министрінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213009/rus
