act_code: '97183'
requisite: Приказ Министра внутренних дел Республики Казахстан от 5 декабря 2015 года № 995. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 декабря 2015 года № 12553
title:
  rus: Об утверждении Типового положения о Консультативно-совещательных органах при территориальных органах внутренних дел
  kaz: Аумақтық ішкі істер органдары жанындағы Консультативтік-кеңесші органдар туралы үлгі ережені бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2015-12-05
approved_by:
- '103003000000'
version_date:
  kaz: 2024-01-23
  rus: 2024-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/97183/kaz/23.01.2024
  rus: https://zan.gov.kz/client/#!/doc/97183/rus/23.01.2024
caused_by:
  code: '192915'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 23 января 2024 года № 64. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 января 2024 года № 33938
  title:
    rus: О внесении изменений в приказ Министра внутренних дел Республики Казахстан от 5 декабря 2015 года № 995 «Об утверждении Типового положения о Консультативно-совещательных органах при территориальных органах внутренних дел»
    kaz: «Аумақтық ішкі істер органдары жанындағы консультативтік-кеңесші органдар туралы үлгілік ережені бекіту туралы» Қазақстан Республикасының Ішкі істер министрінің 2015 жылғы 5 желтоқсандағы № 995 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/192915/rus
