act_code: '158121'
requisite: Приказ Министра по чрезвычайным ситуациям Республики Казахстан от 19 августа 2021 года № 409. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 августа 2021 года № 24091
title:
  rus: Об утверждении Правил организации и осуществления учебного процесса, учебно-методической и научно-методической деятельности в специальном учебном заведении Министерства по чрезвычайным ситуациям Республики Казахстан
  kaz: Қазақстан Республикасы Төтенше жағдайлар министрілігінің арнаулы оқу орнында оқу процесін, оқу-әдістемелік және ғылыми-әдістемелік қызметті ұйымдастыру және жүзеге асыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2021-08-19
approved_by:
- '103007000000'
version_date:
  kaz: 2023-10-13
  rus: 2023-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/158121/kaz/13.10.2023
  rus: https://zan.gov.kz/client/#!/doc/158121/rus/13.10.2023
caused_by:
  code: '187272'
  requisite: Приказ Министра по чрезвычайным ситуациям Республики Казахстан от 13 октября 2023 года № 554. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 октября 2023 года № 33548
  title:
    rus: О внесении изменений в некоторые приказы
    kaz: Кейбір бұйрықтарға өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187272/rus
