act_code: '143761'
requisite: Приказ Министра образования и науки Республики Казахстан от 11 июня 2020 года № 242. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 июня 2020 года № 20852
title:
  rus: Об утверждении Правил оказания государственной услуги «Прием работ на соискание премий в области науки, государственных научных стипендий»
  kaz: «Ғылым саласындағы сыйлықтарды, мемлекеттік ғылыми стипендияларды алуға ұсынылған жұмыстарды қабылдау» мемлекеттік қызметін көрсету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-06-11
approved_by:
- '103006000000'
version_date:
  kaz: 2020-06-11
  rus: 2020-06-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/143761/kaz/11.06.2020
  rus: https://zan.gov.kz/client/#!/doc/143761/rus/11.06.2020
