act_code: '93914'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 29 июня 2015 года № 7-1/587. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 августа 2015 года № 11940
title:
  rus: Об утверждении Ветеринарных (ветеринарно-санитарных) правил
  kaz: Ветеринариялық (ветеринариялық-санитариялық) қағидаларды бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-06-29
approved_by:
- '103012000000'
version_date:
  kaz: 2025-01-01
  rus: 2025-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/93914/kaz/01.01.2025
  rus: https://zan.gov.kz/client/#!/doc/93914/rus/01.01.2025
caused_by:
  code: '201403'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 4 октября 2024 года № 340. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 октября 2024 года № 35216
  title:
    rus: О внесении изменения и дополнения в приказ Министра сельского хозяйства Республики Казахстан от 29 июня 2015 года № 7-1/587 «Об утверждении Ветеринарных (ветеринарно-санитарных) правил»
    kaz: «Ветеринариялық (ветеринариялық-санитариялық) қағидаларды бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің 2015 жылғы 29 маусымдағы № 7-1/587 бұйрығына өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201403/rus
