act_code: '68657'
requisite: Совместный приказ Министра здравоохранения Республики Казахстан от 3 сентября 2012 года № 609 и Министра экономического развития и торговли Республики Казахстан от 3 октября 2012 года № 282. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 ноября 2012 года № 8067. Утратил силу совместным приказом Министра здравоохранения и социального развития Республики Казахстан от 29 июня 2015 года № 538 и и.о. Министра национальной экономики Республики Казахстан от 30 июня 2015 года № 490
title:
  rus: Об утверждении критериев оценки степени риска в сфере частного предпринимательства по оказанию медицинских услуг, обращению лекарственных средств, изделий медицинского назначения и медицинской техники
  kaz: Медициналық қызметтерді көрсету, дәрілік заттардың, медициналық мақсаттағы бұйымдар мен медициналық техниканың айналысы бойынша жеке кәсіпкерлік саласындағы тәуекел дәрежесін бағалау критерийлерін бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПРИК
approved_on: 2012-09-03
approved_by:
- '103005000000'
- '103010000000'
version_date:
  kaz: 2012-09-03
  rus: 2012-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/68657/kaz/03.09.2012
  rus: https://zan.gov.kz/client/#!/doc/68657/rus/03.09.2012
