act_code: '91560'
requisite: Приказ и.о. Министра по инвестициям и развитию Республики Казахстан от 26 марта 2015 года № 345. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 июня 2015 года № 11285. Утратил силу приказом Министра по инвестициям и развитию Республики Казахстан от 29 июня 2017 года № 402 (вводится в действие по истечении двадцати одного календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил радиотехнического обеспечения полетов и авиационной радиосвязи в гражданской авиации
  kaz: Азаматтық авиацияда ұшуды және авиациялық радиобайланысты радиотехникалық қамтамасыз ету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-03-26
approved_by:
- '103035000000'
version_date:
  kaz: 2015-03-26
  rus: 2015-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/91560/kaz/26.03.2015
  rus: https://zan.gov.kz/client/#!/doc/91560/rus/26.03.2015
