act_code: '60074'
requisite: Приказ и.о. Министра транспорта и коммуникаций Республики Казахстан от 13 мая 2011 года № 276. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 июня 2011 года № 6993
title:
  rus: Об утверждении Правил технического наблюдения за постройкой судов и изготовлением материалов и изделий
  kaz: Кемелерді жасауды және материалдар мен бұйымдарды дайындауды техникалық байқау қағидасын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2011-05-13
approved_by:
- '103013000000'
version_date:
  kaz: 2024-10-20
  rus: 2024-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/60074/kaz/20.10.2024
  rus: https://zan.gov.kz/client/#!/doc/60074/rus/20.10.2024
caused_by:
  code: '199798'
  requisite: Приказ Министра транспорта Республики Казахстан от 16 августа 2024 года № 283. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 августа 2024 года № 34938
  title:
    rus: О внесении изменений в некоторые приказы исполняющего обязанности Министра транспорта и коммуникаций Республики Казахстан, исполняющего обязанности Министра по инвестициям и развитию Республики Казахстан и Министерства индустрии и инфраструктурного развития Республики Казахстан
    kaz: Қазақстан Республикасы Көлік және коммуникация министрінің міндетін атқарушының, Қазақстан Республикасы Инвестициялар және даму министрінің міндетін атқарушының және Қазақстан Республикасы Индустрия және инфрақұрылымдық даму министрлігінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199798/rus
