act_code: '30707'
requisite: Приказ Министра финансов Республики Казахстан от 9 ноября 2006 года N 438. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 декабря 2006 года N 4491. Отменен приказом Министра финансов Республики Казахстан от 8 августа 2007 года N 284
title:
  rus: Об утверждении Правил лицензирования аудиторской деятельности
  kaz: Аудиторлық қызметті лицензиялау ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2006-11-09
approved_by:
- '103002000000'
version_date:
  kaz: 2006-11-09
  rus: 2006-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/30707/kaz/09.11.2006
  rus: https://zan.gov.kz/client/#!/doc/30707/rus/09.11.2006
