act_code: '91360'
requisite: Приказ Министра национальной экономики Республики Казахстан от 27 мая 2015 года № 405. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 июня 2015 года № 11473. Утратил силу приказом Министра национальной экономики Республики Казахстан от 17 февраля 2016 года № 81
title:
  rus: Об утверждении Перечня товаров, в отношении которых применяются вывозные таможенные пошлины, размер ставок и срок их действия
  kaz: Әкету кедендік баждары қолданылатын тауарлар тізбесін, мөлшерлемелер көлемін және олардың қолданылу мерзімін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2015-05-27
approved_by:
- '103033000000'
version_date:
  kaz: 2015-12-08
  rus: 2015-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/91360/kaz/08.12.2015
  rus: https://zan.gov.kz/client/#!/doc/91360/rus/08.12.2015
caused_by:
  code: '96139'
  requisite: Приказ Министра национальной экономики Республики Казахстан от 8 декабря 2015 года № 755. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 декабря 2015 года № 12388. Утратил силу приказом Министра национальной экономики Республики Казахстан от 17 февраля 2016 года № 81
  title:
    rus: О внесении изменений и дополнения в приказ Министра национальной экономики Республики Казахстан от 27 мая 2015 года № 405 "Об утверждении Перечня товаров, в отношении которых применяются вывозные таможенные пошлины, размер ставок и срок их действия"
    kaz: '"Әкету кедендік баждары қолданылатын тауарлар тізбесін, мөлшерлемелер көлемін және олардың қолданылу мерзімін бекіту туралы" Қазақстан Республикасы Ұлттық экономика министрінің 2015 жылғы 27 мамырдағы № 405 бұйрығына өзгерістер мен толықтыру енгізу туралы"'
  link: https://zan.gov.kz/client/#!/doc/96139/rus
