act_code: '86050'
requisite: Приказ Министра энергетики Республики Казахстан от 29 октября 2014 года № 84. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 января 2015 года № 10107
title:
  rus: Об утверждении Правил эксплуатации магистральных нефтепроводов
  kaz: Магистральдық мұнай құбырларын пайдалану қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2014-10-29
approved_by:
- '103036000000'
version_date:
  kaz: 2021-04-02
  rus: 2021-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/86050/kaz/02.04.2021
  rus: https://zan.gov.kz/client/#!/doc/86050/rus/02.04.2021
caused_by:
  code: '154307'
  requisite: Приказ Министра энергетики Республики Казахстан от 2 апреля 2021 года № 115. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 апреля 2021 года № 22498
  title:
    rus: О внесении изменений и дополнений в приказ Министра энергетики Республики Казахстан от 29 октября 2014 года № 84 «Об утверждении Правил эксплуатации магистральных нефтепроводов»
    kaz: «Магистральдық мұнай құбырларын пайдалану қағидаларын бекіту туралы» Қазақстан Республикасы Энергетика министрінің 2014 жылғы 29 қазандағы № 84 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154307/rus
