act_code: '53646'
requisite: Приказ Министра финансов Республики Казахстан от 25 июня 2010 года № 303. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 июля 2010 года № 6339. Утратил силу приказом Министра финансов Республики Казахстан от 30 октября 2013 года № 500
title:
  rus: Об утверждении Правил составления администраторами бюджетных программ консолидированной финансовой отчетности
  kaz: Бюджеттік бағдарламалардың әкімшілерімен шоғырландырылған қаржы есептілігін жасау ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2010-06-25
approved_by:
- '103002000000'
version_date:
  kaz: 2012-09-12
  rus: 2012-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/53646/kaz/12.09.2012
  rus: https://zan.gov.kz/client/#!/doc/53646/rus/12.09.2012
caused_by:
  code: '68023'
  requisite: Приказ Министра финансов Республики Казахстан от 12 сентября 2012 года № 417. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 октября 2012 года № 7987. Утратил силу приказом Министра финансов Республики Казахстан от 30 октября 2013 года № 500
  title:
    rus: О внесении изменений и дополнений в приказ Министра финансов Республики Казахстан от 25 июня 2010 года № 303 "Об утверждении Правил составления администраторами бюджетных программ консолидированной финансовой отчетности"
    kaz: '"Бюджеттiк бағдарламалардың әкiмшiлерiмен шоғырландырылған қаржы есептiлiгiн жасау ережесiн бекiту туралы" Қазақстан Республикасы Қаржы министрiнiң 2010 жылғы 25 маусымдағы № 303 бұйрығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/68023/rus
