act_code: '54519'
requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 23 июля 2010 года № 537. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 августа 2010 года № 6437. Отменен приказом Министра здравоохранения Республики Казахстан от 18 мая 2012 года № 362
title:
  rus: Об утверждении санитарных правил "Санитарно-эпидемиологические требования к содержанию и эксплуатации детских молочных кухонь"
  kaz: '"Балалар сүт асханасын күтіп-ұстауға және пайдалануға қойылатын санитариялық-эпидемиологиялық талаптар" санитариялық ережесін бекіту туралы'
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2010-07-23
approved_by:
- '103010000000'
version_date:
  kaz: 2010-07-23
  rus: 2010-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/54519/kaz/23.07.2010
  rus: https://zan.gov.kz/client/#!/doc/54519/rus/23.07.2010
