act_code: '93406'
requisite: Приказ и.о. Министра по инвестициям и развитию Республики Казахстан от 17 июня 2015 года № 705. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 августа 2015 года № 11928
title:
  rus: Об утверждении нормативов финансирования на ремонт, содержание автомобильных дорог общего пользования международного и республиканского значения и управление дорожной деятельностью
  kaz: Халықаралық және республикалық маңызы бар жалпыға ортақ пайдаланылатын автомобиль жолдарын жөндеуді, күтіп-ұстауды және жол қызметін басқаруды қаржыландыру нормативтерін бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2015-06-17
approved_by:
- '103035000000'
version_date:
  kaz: 2025-08-04
  rus: 2025-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/93406/kaz/04.08.2025
  rus: https://zan.gov.kz/client/#!/doc/93406/rus/04.08.2025
caused_by:
  code: '213228'
  requisite: Приказ и.о. Министра транспорта Республики Казахстан от 4 августа 2025 года № 255
  title:
    rus: О внесении изменения в приказ исполняющего обязанности Министра по инвестициям и развитию Республики Казахстан от 17 июня 2015 года № 705 «Об утверждении нормативов финансирования на ремонт, содержание автомобильных дорог общего пользования международного и республиканского значения и управление дорожной деятельностью»
    kaz: «Халықаралық және республикалық маңызы бар жалпыға ортақ пайдаланылатын автомобиль жолдарын жөндеуді, күтіп-ұстауды және жол қызметін басқаруды қаржыландыру нормативтерін бекіту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің міндетін атқарушының 2015 жылғы 17 маусымдағы № 705 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213228/rus
