act_code: '123595'
requisite: Приказ Министра информации и коммуникаций Республики Казахстан от 3 июля 2018 года № 304. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 июля 2018 года № 17191. Утратил силу приказом Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 11 ноября 2022 года № 428/НҚ (вводится в действие с 1 января 2023 года)
title:
  rus: Об утверждении Типовой архитектуры «электронного акимата»
  kaz: «Электрондық әкімдіктің» үлгілік архитектурасын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2018-07-03
approved_by:
- '103039000000'
version_date:
  kaz: 2022-01-01
  rus: 2022-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/123595/kaz/01.01.2022
  rus: https://zan.gov.kz/client/#!/doc/123595/rus/01.01.2022
caused_by:
  code: '155155'
  requisite: Приказ Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 21 апреля 2021 года № 142/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 апреля 2021 года № 22606. Утратил силу приказом Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 11 ноября 2022 года № 428/НҚ (вводится в действие с 1 января 2023 года)
  title:
    rus: О внесении изменений в приказ Министра информации и коммуникаций Республики Казахстан от 3 июля 2018 года № 304 «Об утверждении Типовой архитектуры «электронного акимата»
    kaz: «Электрондық әкімдіктің» үлгілік архитектурасын бекіту туралы» Қазақстан Республикасы Ақпарат және коммуникациялар министрінің 2018 жылғы 3 шілдедегі № 304 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155155/rus
