act_code: '25843'
requisite: Приказ Министра охраны окружающей среды Республики Казахстан от 9 ноября 2005 года № 304-п. Зарегистрирован Министерством юстиции Республики Казахстан от 17 ноября 2005 года № 3933. Утратил силу приказом Министра охраны окружающей среды Республики Казахстан от 2 апреля 2010 года № 81-Ө
title:
  rus: Об утверждении правил работы квалификационной комиссии по аттестации экологических аудиторов и правил аттестации экологических аудиторов
  kaz: Экологиялық аудиторларды аттестаттау жөніндегі біліктілік комиссиясының құрамы мен жұмыс ережесін және экологиялық аудиторларды аттестаттау ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2005-11-09
approved_by:
- '103015000000'
version_date:
  kaz: 2005-11-09
  rus: 2005-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/25843/kaz/09.11.2005
  rus: https://zan.gov.kz/client/#!/doc/25843/rus/09.11.2005
