act_code: '118853'
requisite: Приказ Министра финансов Республики Казахстан от 23 января 2018 года № 45. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 февраля 2018 года № 16362. Утратил силу приказом Министра финансов Республики Казахстан от 21 апреля 2021 года № 376 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил и сроков вручения проверяемому лицу предварительного акта выездной таможенной проверки, предоставления письменного возражения к предварительному акту выездной таможенной проверки, рассмотрения органом государственных доходов такого возражения, а также категории проверяемых лиц, в отношении которых применяются нормы по предварительному акту выездной таможенной проверки
  kaz: Көшпелі кедендік тексерудің алдын ала актісін тексерілетін тұлғаға табыс ету, көшпелі кедендік тексерудің алдын ала актісіне жазбаша қарсылықты ұсыну, мемлекеттік кірістер органының мұндай қарсылықты қарау қағидалары мен мерзімдерін, сондай-ақ оларға қатысты көшпелі кедендік тексерудің алдын ала актісі бойынша нормалар қолданылатын тексерілетін тұлғалардың санаттарын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-01-23
approved_by:
- '103002000000'
version_date:
  kaz: 2020-09-09
  rus: 2020-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/118853/kaz/09.09.2020
  rus: https://zan.gov.kz/client/#!/doc/118853/rus/09.09.2020
caused_by:
  code: '146224'
  requisite: Приказ Министра финансов Республики Казахстан от 9 сентября 2020 года № 840. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 сентября 2020 года № 21193. Утратил силу приказом Министра финансов Республики Казахстан от 21 апреля 2021 года № 376 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра финансов Республики Казахстан от 23 января 2018 года № 45 «Об утверждении Правил и сроков вручения проверяемому лицу предварительного акта выездной таможенной проверки, предоставления письменного возражения к предварительному акту выездной таможенной проверки, рассмотрения органом государственных доходов такого возражения, а также категорий проверяемых лиц, в отношении которых применяются нормы по предварительному акту выездной таможенной проверки»
    kaz: «Көшпелі кедендік тексерудің алдын ала актісін тексерілетін тұлғаға табыс ету, көшпелі кедендік тексерудің алдын ала актісіне жазбаша қарсылықты ұсыну, мемлекеттік кірістер органының мұндай қарсылықты қарау қағидалары мен мерзімдерін, сондай-ақ оларға қатысты көшпелі кедендік тексерудің алдын ала актісі бойынша нормалар қолданылатын тексерілетін тұлғалардың санаттарын бекіту туралы» Қазақстан Республикасы Қаржы министрінің 2018 жылғы 23 қаңтардағы № 45 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146224/rus
