act_code: '74046'
requisite: Приказ Министра юстиции Республики Казахстан от 15 августа 2013 года № 273. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 августа 2013 года № 8632. Утратил силу приказом Министра юстиции Республики Казахстан от 27 сентября 2018 года № 1453 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении формы соглашения об оказании гарантированной государством юридической помощи
  kaz: Мемлекет кепілдік берген заң көмегін көрсету туралы келісімнің нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2013-08-15
approved_by:
- '103001000000'
version_date:
  kaz: 2013-08-15
  rus: 2013-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/74046/kaz/15.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74046/rus/15.08.2013
