act_code: '59509'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 27 мая 2011 года № 08-2/291. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 июня 2011 года № 7034.
title:
  rus: Об утверждении распределения предусмотренных в республиканском бюджете средств на субсидирование повышения продуктивности и качества продукции животноводства по областям и направлениям субсидирования
  kaz: Облыстар және субсидиялау бағыттары бойынша мал шаруашылығы өнімдерінің өнімділігін және сапасын арттыруды субсидиялауға республикалық бюджетте көзделген қаражатты бөлуін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2011-05-27
approved_by:
- '103012000000'
version_date:
  kaz: 2011-11-01
  rus: 2011-11-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/59509/kaz/01.11.2011
  rus: https://zan.gov.kz/client/#!/doc/59509/rus/01.11.2011
caused_by:
  code: '61363'
  requisite: Приказ и.о. Министра сельского хозяйства Республики Казахстан от 1 ноября 2011 года № 08-2/624. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 ноября 2011 года № 7290
  title:
    rus: О внесении изменения в приказ Министра сельского хозяйства Республики Казахстан от 27 мая 2011 года № 08-2/291 "Об утверждении распределения предусмотренных в республиканском бюджете средств на субсидирование повышения продуктивности и качества продукции животноводства по областям и направлениям субсидирования"
    kaz: '"Облыстар және cубсидиялау бағыттары бойынша мал шаруашылығы өнімдерінің өнімділігін және сапасын арттыруды субсидиялауға республикалық бюджетте көзделген қаражатты бөлуін бекіту туралы" Қазақстан Республикасы Ауыл шаруашылығы министрінің 2011 жылғы 27 мамырдағы № 08-2/291 бұйрығына өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/61363/rus
