act_code: '100195'
requisite: Совместный приказ и.о. Министра по инвестициям и развитию Республики Казахстан от 14 декабря 2015 года № 1199 и Министра национальной экономики Республики Казахстан от 29 декабря 2015 года № 826. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 декабря 2015 года № 12735
title:
  rus: Об утверждении критериев оценки степени риска и проверочных листов в области технического регулирования
  kaz: Техникалық реттеу саласындағы тәуекел дәрежесін бағалау өлшемшарттарын және тексеру парақтарын бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПРИК
approved_on: 2015-12-14
approved_by:
- '103033000000'
- '103035000000'
version_date:
  kaz: 2024-06-26
  rus: 2024-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/100195/kaz/26.06.2024
  rus: https://zan.gov.kz/client/#!/doc/100195/rus/26.06.2024
caused_by:
  code: '198167'
  requisite: Совместный приказ и.о. Министра торговли и интеграции Республики Казахстан от 26 июня 2024 года № 267-НҚ и и.о. Министра национальной экономики Республики Казахстан от 26 июня 2024 года № 41. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 июня 2024 года № 34604
  title:
    rus: О внесении изменений и дополнений в совместный приказ исполняющего обязанности Министра по инвестициям и развитию Республики Казахстан от 14 декабря 2015 года № 1199 и Министра национальной экономики Республики Казахстан от 29 декабря 2015 года № 826 «Об утверждении критериев оценки степени риска и проверочных листов в области технического регулирования»
    kaz: «Техникалық реттеу саласындағы тәуекел дәрежесін бағалау өлшемшарттарын және тексеру парақтарын бекіту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің міндетін атқарушының 2015 жылғы 14 желтоқсандағы № 1199 және Қазақстан Республикасы Ұлттық экономика министрінің 2015 жылғы 29 желтоқсандағы № 826 бірлескен бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198167/rus
