act_code: '65964'
requisite: Приказ Министра охраны окружающей среды Республики Казахстан от 11 мая 2012 года № 151-ө. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 июня 2012 года № 7711. Утратил силу приказом Министра экологии, геологии и природных ресурсов Республики Казахстан от 10 июня 2021 года № 193 (вводится в действие с 1 июля 2021 года)
title:
  rus: Об утверждении Правил торговли квотами на выбросы парниковых газов и углеродными единицами
  kaz: Парниктік газдар шығарындыларына квоталармен және көміртегі бірліктерімен сауда жасау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2012-05-11
approved_by:
- '103015000000'
version_date:
  kaz: 2014-02-28
  rus: 2014-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/65964/kaz/28.02.2014
  rus: https://zan.gov.kz/client/#!/doc/65964/rus/28.02.2014
caused_by:
  code: '78718'
  requisite: Приказ и.о. Министра окружающей среды и водных ресурсов Республики Казахстан от 28 февраля 2014 года № 69-ө. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 апреля 2014 года № 9286. Утратил силу приказом Министра экологии, геологии и природных ресурсов Республики Казахстан от 10 июня 2021 года № 193 (вводится в действие с 1 июля 2021 года)
  title:
    rus: О внесении изменений и дополнений в приказ Министра охраны окружающей среды Республики Казахстан от 11 мая 2012 года № 151-п "Об утверждении правил торговли квотами на выбросы парниковых газов и углеродными единицами"
    kaz: '"Парниктік газдар шығарындыларына квоталармен және көміртегі бірліктерімен сауда жасау қағидаларын бекіту туралы" Қазақстан Республикасының Қоршаған ортаны қорғау министрінің 2012 жылғы № 11 мамырдағы № 151-ө бұйрығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/78718/rus
