act_code: '94306'
requisite: Приказ Министра энергетики Республики Казахстан от 27 апреля 2015 года № 317. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 октября 2015 года № 12138. Утратил силу приказом и.о. Министра экологии и природных ресурсов Республики Казахстан от 27 апреля 2023 года № 135
title:
  rus: Об утверждении натуральных норм обеспечения территориальных органов, находящихся в ведении Комитета экологического регулирования и контроля Министерства энергетики Республики Казахстан, специальными транспортными средствами
  kaz: Қазақстан Республикасы Энергетика министрлігі Экологиялық реттеу және бақылау комитетінің қарамағындағы аумақтық органдарды арнайы көлік құралдарымен қамтамасыз етудің заттай нормаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2015-04-27
approved_by:
- '103036000000'
version_date:
  kaz: 2015-04-27
  rus: 2015-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/94306/kaz/27.04.2015
  rus: https://zan.gov.kz/client/#!/doc/94306/rus/27.04.2015
