act_code: '183340'
requisite: Приказ Заместителя Премьер-Министра - Министра торговли и интеграции Республики Казахстан от 22 июня 2023 года № 240-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 июня 2023 года № 32908
title:
  rus: Об утверждении Правил взаимодействия государственных органов Республики Казахстан в случае проведения расследований, предшествующих применению торговых мер и мер по соображениям безопасности третьей стороной в отношении товаров, происходящих из Республики Казахстан
  kaz: Үшінші тараптың Қазақстан Республикасынан шығатын тауарларға қатысты сауда шараларын және қауіпсіздік пайымдаулары бойынша шараларды қолдануы алдында тергеп-тексеру жүргізілген жағдайда, Қазақстан Республикасы мемлекеттік органдарының өзара іс-қимыл жасау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2023-06-22
approved_by:
- '103046000000'
version_date:
  kaz: 2023-06-22
  rus: 2023-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/183340/kaz/22.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183340/rus/22.06.2023
