act_code: '90715'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 31 марта 2015 года № 412. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 мая 2015 года № 11167. Утратил силу приказом Министра по инвестициям и развитию Республики Казахстан от 11 мая 2018 года № 325 (вводится в действие с 29 июня 2018 года)
title:
  rus: Об утверждении модельных контрактов по видам недропользования
  kaz: Жер қойнауын пайдалану түрлері бойынша модельдік келісімшарттарды бекіту туралы
form: ПРИК
type_codes:
- КОНТ
- ПРИК
approved_on: 2015-03-31
approved_by:
- '103035000000'
version_date:
  kaz: 2015-03-31
  rus: 2015-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/90715/kaz/31.03.2015
  rus: https://zan.gov.kz/client/#!/doc/90715/rus/31.03.2015
