act_code: '71095'
requisite: Приказ и.о. Министра индустрии и новых технологий Республики Казахстан от 29 декабря 2012 года № 510. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 февраля 2013 года № 8323. Утратил силу приказом и.о. Министра по инвестициям и развитию Республики Казахстан от 6 февраля 2015 года № 116
title:
  rus: Об утверждении Правил подготовки, переподготовки, повышения квалификации экспертов-аудиторов по подтверждению соответствия, аккредитации, определению страны происхождения товара, статуса товара Таможенного союза или иностранного товара и их аттестации, и квалификационных требований к ним
  kaz: Тауарды шығарған елді, Кеден одағы тауарының немесе шетел тауарының мәртебесін айқындау, сәйкестігін растау, аккредиттеу жөніндегі сарапшы-аудиторларды даярлау, қайта даярлау, біліктілігін арттыру және оларды аттестаттау қағидасын, және оларға қойылатын біліктілік талаптарын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
- ТРЕБ
approved_on: 2012-12-29
approved_by:
- '103017000000'
version_date:
  kaz: 2013-08-28
  rus: 2013-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/71095/kaz/28.08.2013
  rus: https://zan.gov.kz/client/#!/doc/71095/rus/28.08.2013
caused_by:
  code: '74627'
  requisite: Приказ Заместителя Премьер-Министра Республики Казахстан - Министра индустрии и новых технологий Республики Казахстан от 28 августа 2013 года № 263. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 сентября 2013 года № 8737. Утратил силу приказом и.о. Министра по инвестициям и развитию Республики Казахстан от 6 февраля 2015 года № 116
  title:
    rus: О внесении дополнения в приказ исполняющего обязанности Министра индустрии и новых технологий Республики Казахстан от 29 декабря 2012 года № 510 "Об утверждении Правил подготовки, переподготовки, повышения квалификации экспертов-аудиторов по подтверждению соответствия, аккредитации, определению страны происхождения товара, статуса товара Таможенного союза или иностранного товара и их аттестации, и квалификационных требований к ним"
    kaz: '"Тауарды шығарған елді, Кеден одағы тауарының немесе шетел тауарының мәртебесін айқындау, сәйкестігін растау, аккредиттеу жөніндегі сарапшы-аудиторларды даярлау, қайта даярлау, біліктілігін арттыру және оларды аттестаттау қағидасын, және оларға қойылатын біліктілік талаптарын бекіту туралы" Қазақстан Республикасы Индустрия және жаңа технологиялар министрінің міндетін атқарушының 2012 жылғы 29 желтоқсандағы № 510 бұйрығына толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/74627/rus
