act_code: '88168'
requisite: Приказ Министра национальной экономики Республики Казахстан от 20 февраля 2015 года № 115. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 марта 2015 года № 10499
title:
  rus: Об утверждении Правил оценки деятельности членов наблюдательного совета и определения лимита выплаты вознаграждения членам наблюдательного совета
  kaz: Байқау кеңесі мүшелерінің қызметін бағалау және байқау кеңесінің мүшелеріне сыйақы төлеу лимитін айқындау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-02-20
approved_by:
- '103033000000'
version_date:
  kaz: 2024-07-12
  rus: 2024-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/88168/kaz/12.07.2024
  rus: https://zan.gov.kz/client/#!/doc/88168/rus/12.07.2024
caused_by:
  code: '198716'
  requisite: Приказ Заместителя Премьер-Министра - Министра национальной экономики Республики Казахстан от 12 июля 2024 года № 58. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 июля 2024 года № 34730
  title:
    rus: О внесении изменений и дополнений в некоторые приказы Министра национальной экономики Республики Казахстан
    kaz: Қазақстан Республикасы Ұлттық экономика министрінің кейбір бұйрықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198716/rus
