act_code: '15971'
requisite: Приказ Министра экономики и бюджетного планирования Республики Казахстан от 30 апреля 2003 года N 75. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 июня 2003 года N 2364. Утратил силу приказом Министра экономики и бюджетного планирования Республики Казахстан от 1 апреля 2009 года N 72
title:
  rus: Об утверждении Правил составления и представления бюджетной заявки администраторами бюджетных программ
  kaz: Бюджеттiк бағдарламалар әкiмшілерiнiң бюджеттiк өтінімдi жасау және ұсыну ережесiн бекiту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2003-04-29
approved_by:
- '103005000000'
version_date:
  kaz: 2003-04-29
  rus: 2003-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/15971/kaz/29.04.2003
  rus: https://zan.gov.kz/client/#!/doc/15971/rus/29.04.2003
