act_code: '38609'
requisite: Приказ и.о. Министра образования и науки Республики Казахстан от 5 марта 2008 года № 109. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 мата 2008 года № 5172. Утратил силу приказом Министра образования и науки Республики Казахстан от 4 июля 2013 года № 257
title:
  rus: Об утверждении нормативных правовых актов по организации и проведению государственной аттестации организаций образования и аккредитации
  kaz: Білім беру ұйымын мемлекеттік аттестаттау мен аккредиттеуден өткізуді ұйымдастыру бойынша нормативтік құқықтық актілерді бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2008-03-05
approved_by:
- '103006000000'
version_date:
  kaz: 2008-03-05
  rus: 2008-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/38609/kaz/05.03.2008
  rus: https://zan.gov.kz/client/#!/doc/38609/rus/05.03.2008
