act_code: '96470'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 30 апреля 2015 года № 546. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 декабря 2015 года № 12463
title:
  rus: Об утверждении Правил перевозок грузов автомобильным транспортом
  kaz: Автомобиль көлігімен жүктерді тасымалдау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-04-30
approved_by:
- '103035000000'
version_date:
  kaz: 2023-04-10
  rus: 2023-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/96470/kaz/10.04.2023
  rus: https://zan.gov.kz/client/#!/doc/96470/rus/10.04.2023
caused_by:
  code: '178525'
  requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 30 января 2023 года № 58. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 февраля 2023 года № 31855
  title:
    rus: О внесении изменений и дополнения в некоторые приказы Министра транспорта и коммуникаций Республики Казахстан и Министерства по инвестициям и развитию Республики Казахстан
    kaz: Қазақстан Республикасы Көлік және коммуникация министрінің және Қазақстан Республикасы Инвестициялар және даму министрлігінің кейбір бұйрықтарына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/178525/rus
