act_code: '90036'
requisite: Приказ Министра финансов Республики Казахстан от 31 марта 2015 года № 240. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 мая 2015 года № 11013. Утратил силу приказом Министра финансов Республики Казахстан от 23 февраля 2018 года № 263 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил представления обязательства о вывозе (ввозе) продуктов переработки и его исполнения, формы представления обязательства о вывозе (ввозе) продуктов переработки
  kaz: Қайта өңдеу өнімдерін әкету (әкелу) жөнінде міндеттемені табыс ету және оны орындау қағидаларын, қайта өңдеу өнімдерін әкету (әкелу) жөнінде міндеттемені табыс ету нысандарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2015-03-31
approved_by:
- '103002000000'
version_date:
  kaz: 2015-03-31
  rus: 2015-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/90036/kaz/31.03.2015
  rus: https://zan.gov.kz/client/#!/doc/90036/rus/31.03.2015
