act_code: '88246'
requisite: Приказ Министра внутренних дел Республики Казахстан от 25 февраля 2015 года № 152. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 апреля 2015 года № 10620
title:
  rus: Об утверждении Инструкции прохождения воинской службы в Национальной гвардии Республики Казахстан
  kaz: Қазақстан Республикасының Ұлттық ұланында әскери қызмет өткеру нұсқаулығын бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2015-02-25
approved_by:
- '103003000000'
version_date:
  kaz: 2026-06-26
  rus: 2026-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/88246/kaz/26.06.2026
  rus: https://zan.gov.kz/client/#!/doc/88246/rus/26.06.2026
caused_by:
  code: '227262'
  requisite: Приказ и.о. Министра внутренних дел Республики Казахстан от 26 июня 2026 года № 445. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 июня 2026 года № 39162
  title:
    rus: О внесении изменения в приказ Министра внутренних дел Республики Казахстан от 25 февраля 2015 года № 152 «Об утверждении Инструкции прохождения воинской службы в Национальной гвардии Республики Казахстан»
    kaz: «Қазақстан Республикасының Ұлттық ұланында әскери қызмет өткеру нұсқаулығын бекіту туралы» Қазақстан Республикасы Ішкі істер министрінің 2015 жылғы 25 ақпандағы № 152 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/227262/rus
