act_code: '7169'
requisite: Приказ Министра внутренних дел Республики Казахстан от 27 сентября 2000 года N 519. Зарегистрирован в Министерстве юстиции Республики Казахстан 23.10.2000 г. за N 1269. Утратил силу за иключением пункта 6 - приказом Министра внутренних дел Республики Казахстан от 24 ноября 2005 года N 652 (V053990). Утратил силу приказом Министра внутренних дел Республики Казахстан от 1 февраля 2007 года N 35
title:
  rus: О мерах по совершенствованию контроля за автоперевозками и искоренению фактов поборов и вымогательства на автомобильных дорогах Республики Казахстан
  kaz: '"Қазақстан Республикасының автомобиль жолдарындағы автотасымалдауларға бақылау жасауды жетілдіру және алымдар мен бопсалау фактілерін жою шаралары туралы"'
form: ПРИК
type_codes:
- ПРИК
approved_on: 2000-09-26
approved_by:
- '103003000000'
version_date:
  kaz: 2003-09-28
  rus: 2003-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/7169/kaz/28.09.2003
  rus: https://zan.gov.kz/client/#!/doc/7169/rus/28.09.2003
caused_by:
  code: '42617'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 31 октября 2008 года N 578. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 ноября 2008 года N 5382. Утратил силу приказом Министра здравоохранения Республики Казахстан от 13 июля 2017 года № 504 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в приказ Министра здравоохранения Республики Казахстан от 11 июня 2003 года № 446 "Об утверждении Инструкции по проведению медицинского освидетельствования для установления факта употребления психоактивного вещества и состояния опьянения"
    kaz: '"Психикалық белсенді затты пайдалану фактісін және мас болу жағдайын анықтау үшін медициналық куәландыруды жүргізу жөніндегі нұсқаулықты бекіту туралы" Қазақстан Республикасының Денсаулық сақтау министрінің 2003 жылғы 11 маусымдағы N 446 бұйрығына өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/42617/rus
