act_code: '188156'
requisite: Приказ Министра промышленности и строительства Республики Казахстан от 7 ноября 2023 года № 59. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 ноября 2023 года № 33621
title:
  rus: О некоторых вопросах регулирования вывоза угля и лигнита
  kaz: Көмір мен лигнитті әкетуді реттеудің кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2023-11-07
approved_by:
- '103052000000'
version_date:
  kaz: 2023-11-07
  rus: 2023-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/188156/kaz/07.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188156/rus/07.11.2023
