act_code: '94083'
requisite: Приказ Министра финансов Республики Казахстан от 5 июня 2015 года № 421 Зарегистрирован в Министерстве юстиции Республики Казахстан 19 августа 2015 года № 11904. Утратил силу приказом Министра здравоохранения Республики Казахстан от 25 ноября 2020 года № ҚР ДСМ-202/2020 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Перечня сведений, необходимых для осуществления камерального контроля, а также Правил их представления уполномоченными органами в сфере таможенного дела и в области технического регулирования, органами по подтверждению соответствия и испытательными лабораториями (центрами)
  kaz: Камералдық бақылауды жүзеге асыру үшін қажетті мәліметтердің тізбесін, сондай-ақ Кеден ісі саласындағы және техникалық реттеу саласындағы уәкілетті органдардың, сәйкестікті растау жөніндегі органдардың және сынақ зертханаларының (орталықтарының) оларды табыс ету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2015-06-05
approved_by:
- '103033000000'
version_date:
  kaz: 2015-06-05
  rus: 2015-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/94083/kaz/05.06.2015
  rus: https://zan.gov.kz/client/#!/doc/94083/rus/05.06.2015
