act_code: '60527'
requisite: Приказ и.о. Министра юстиции Республики Казахстан от 29 июля 2011 года № 271. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 сентября 2011 года № 7188. Утратил силу приказом Министра юстиции Республики Казахстан от 15 мая 2018 года № 747 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Инструкции о прохождении стажировки по оценочной деятельности
  kaz: Бағалау қызметі бойынша тағылымдамадан өту жөніндегі Нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2011-07-29
approved_by:
- '103001000000'
version_date:
  kaz: 2013-06-27
  rus: 2013-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/60527/kaz/27.06.2013
  rus: https://zan.gov.kz/client/#!/doc/60527/rus/27.06.2013
caused_by:
  code: '73946'
  requisite: Приказ Министра юстиции Республики Казахстан от 27 июня 2013 года № 236. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 июля 2013 года № 8589. Утратил силу приказом Министра юстиции Республики Казахстан от 15 мая 2018 года № 747 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнения в приказ и.о. Министра юстиции Республики Казахстан от 29 июля 2011 года № 271 "Об утверждении инструкции о прохождении стажировки по оценочной деятельности"
    kaz: '"Бағалау қызметі бойынша тағылымдамадан өту жөніндегі нұсқаулықты бекіту туралы" Қазақстан Республикасы Әділет министрінің міндетін атқарушының 2011 жылғы 29 шілдедегі № 271 бұйрығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/73946/rus
