act_code: '135005'
requisite: Приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 30 сентября 2019 года № 43-П
title:
  rus: Об отмене некоторых приказов Заместителя Премьер–Министра Республики Казахстан – Министра сельского хозяйства Республики Казахстан
  kaz: Қазақстан Республикасы Премьер–Министрінің Орынбасары – Қазақстан Республикасы Ауыл шаруашылығы министрінің кейбір бұйрықтарын жоққа шығару туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2019-09-30
approved_by:
- '103047000000'
version_date:
  kaz: 2019-09-30
  rus: 2019-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/135005/kaz/30.09.2019
  rus: https://zan.gov.kz/client/#!/doc/135005/rus/30.09.2019
