act_code: '115031'
requisite: Приказ Министра обороны Республики Казахстан от 24 августа 2017 года № 476. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 сентября 2017 года № 15803
title:
  rus: Об утверждении Правил ношения военной формы одежды и знаков различия Вооруженных Сил, других войск и воинских формирований Республики Казахстан, а также других знаков
  kaz: Қазақстан Республикасы Қарулы Күштерінің, басқа да әскерлері мен әскери құралымдарының әскери киім нысанын киіп жүру және айырым белгілерін, сондай-ақ басқа да белгілерді тағып жүру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2017-08-24
approved_by:
- '103008000000'
version_date:
  kaz: 2025-08-29
  rus: 2025-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/115031/kaz/29.08.2025
  rus: https://zan.gov.kz/client/#!/doc/115031/rus/29.08.2025
caused_by:
  code: '213920'
  requisite: Приказ Министра обороны Республики Казахстан от 29 августа 2025 года № 1182
  title:
    rus: О внесении изменений в приказ Министра обороны Республики Казахстан от 24 августа 2017 года № 476 «Об утверждении Правил ношения военной формы одежды и знаков различия Вооруженных Сил, других войск и воинских формирований Республики Казахстан, а также других знаков»
    kaz: «Қазақстан Республикасы Қарулы Күштерінің, басқа да әскерлері мен әскери құралымдарының әскери киім нысанын киіп жүру және айырым белгілерін, сондай-ақ басқа да белгілерді тағып жүру қағидаларын бекіту туралы» Қазақстан Республикасы Қорғаныс министрінің 2017 жылғы 24 тамыздағы № 476 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213920/rus
