act_code: '157511'
requisite: Приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 30 июля 2021 года № 280. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 августа 2021 года № 23809
title:
  rus: Об утверждении Инструкции по организации и проведению экологической оценки
  kaz: Экологиялық бағалауды ұйымдастыру және өткізу жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2021-07-30
approved_by:
- '103047000000'
version_date:
  kaz: 2021-10-26
  rus: 2021-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/157511/kaz/26.10.2021
  rus: https://zan.gov.kz/client/#!/doc/157511/rus/26.10.2021
caused_by:
  code: '159809'
  requisite: Приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 26 октября 2021 года № 424. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 октября 2021 года № 24933
  title:
    rus: О внесении изменений в приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 30 июля 2021 года № 280 «Об утверждении Инструкции по организации и проведению экологической оценки»
    kaz: «Экологиялық бағалауды ұйымдастыру және өткізу жөніндегі нұсқаулықты бекіту туралы» Қазақстан Республикасы Экология, геология және табиғи ресурстар министрінің 2021 жылғы 30 шілдедегі № 280 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159809/rus
