act_code: '67464'
requisite: Приказ Министра образования и науки Республики Казахстан от 24 июля 2012 года № 344. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 августа 2012 года № 7876
title:
  rus: Об утверждении Правил по подготовке, экспертизе, апробации и проведению мониторинга, изданию учебников для организаций среднего образования и учебно-методических комплексов для дошкольных организаций, организаций среднего образования
  kaz: Орта білім беру ұйымдарына арналған оқулықтарды және мектепке дейінгі ұйымдарға, орта білім беру ұйымдарына арналған оқу-әдістемелік кешендерді дайындау, сараптау, сынақтан өткізу және мониторинг жүргізу, басып шығару жөніндегі қағидаларды бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2012-07-24
approved_by:
- '103006000000'
version_date:
  kaz: 2024-09-24
  rus: 2024-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/67464/kaz/24.09.2024
  rus: https://zan.gov.kz/client/#!/doc/67464/rus/24.09.2024
caused_by:
  code: '200938'
  requisite: Приказ и.о. Министра просвещения Республики Казахстан от 24 сентября 2024 года № 272. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 сентября 2024 года № 35108
  title:
    rus: О внесении изменения в приказ Министра образования и науки Республики Казахстан от 24 июля 2012 года № 344 «Об утверждении Правил по подготовке, экспертизе, апробации и проведению мониторинга, изданию учебников для организаций среднего образования и учебно-методических комплексов для дошкольных организаций, организаций среднего образования»
    kaz: «Орта білім беру ұйымдарына арналған оқулықтарды және мектепке дейінгі ұйымдарға, орта білім беру ұйымдарына арналған оқу-әдістемелік кешендерді дайындау, сараптау, сынақтан өткізу және мониторинг жүргізу, басып шығару жөніндегі қағидаларды бекіту туралы» Қазақстан Республикасы Білім және ғылым министрінің 2012 жылғы 24 шілдедегі № 344 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200938/rus
