act_code: '15530'
requisite: Совместный приказ Министра юстиции Республики Казахстан от 15 апреля 2003 года № 66 и Министра внутренних дел Республики Казахстан от 31 марта 2003 года № 164. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 мая 2003 года № 2287. Утратил силу совместным приказом Министра юстиции Республики Казахстан от 19 мая 2011 года № 191 и Министра внутренних дел Республики Казахстан от 18 марта 2011 года № 118
title:
  rus: Об утверждении Инструкции по взаимодействию органов внутренних дел Республики Казахстан и органов уголовно-исполнительной системы Министерства юстиции Республики Казахстан по обеспечению контроля за прибытием к месту проживания лиц, освобожденных из мест лишения свободы
  kaz: Бас бостандығынан айыру орындарынан босатылған адамдардың тұрғылықты жерiне келiп жетуiн бақылауды қамтамасыз ету жөнiндегi Қазақстан Республикасының iшкi iстер органдары мен Қазақстан Республикасы Әдiлет министрлiгiнiң қылмыстық-атқару жүйесi органдарының өзара iс-қимылы туралы нұсқаулықты бекiту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2003-04-14
approved_by:
- '103001000000'
- '103003000000'
version_date:
  kaz: 2003-04-14
  rus: 2003-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/15530/kaz/14.04.2003
  rus: https://zan.gov.kz/client/#!/doc/15530/rus/14.04.2003
