act_code: '3397'
requisite: Утверждена приказом Таможенного комитета Республики Казахстан от 28 мая 1996 г. N 114-П Зарегистрирован в Министерстве юстиции Республики Казахстан 12.07.1996 г. за N 180
title:
  rus: у.с. - приказом Таможенного Комитета МГД РК от 15.02.2001г. N 51 ~V011441 Инструкция о таможенном оформлении товаров, перемещаемых через таможенную границу Республики Казахстан трубопроводным транспортом и по линиям электропередач
  kaz: Құбыр жүргiзетiн транспортпен және электр берiлiсiнiң желiлерiмен өткiзiлетiн тауарларды кедендiк ресiмдеу туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 1996-05-27
approved_by:
- '103002004000'
version_date:
  rus: 1996-05-27
source:
  rus: https://zan.gov.kz/client/#!/doc/3397/rus/27.05.1996
