act_code: '94592'
requisite: Приказ Министра обороны Республики Казахстан от 21 августа 2015 года № 478ДСП. Зарегистрирован в Министерстве юстиции Республики Казахстан от 14 октября 2015 года № 12170
title:
  rus: Об утверждении норм снабжения программным обеспечением и техническими средствами обеспечения безопасности информации Вооруженных Сил Республики Казахстан
  kaz: Қазақстан Республикасының Қарулы Күштерін бағдарламалық қамтамасыз етумен және ақпарат қауіпсіздігін қамтамасыз етудің техникалық құралдарымен  жабдықтау нормаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2015-08-21
approved_by:
- '103008000000'
version_date:
  kaz: 2015-08-21
  rus: 2015-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/94592/kaz/21.08.2015
  rus: https://zan.gov.kz/client/#!/doc/94592/rus/21.08.2015
