act_code: '110389'
requisite: Приказ Министра внутренних дел Республики Казахстан от 4 февраля 2017 года № 90. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 марта 2017 года № 14876
title:
  rus: Об утверждении Методики проведения психосоциального тестирования личности подозреваемого, обвиняемого на стадии досудебной пробации и Методики подготовки досудебного доклада
  kaz: Сотқа дейінгі пробация сатысында күдіктінің, айыпталушының жеке басын психологиялық-әлеуметтік тестіден өткізу әдістемесін және Сотқа дейінгі баяндаманы дайындау әдістемесін бекіту туралы
form: ПРИК
type_codes:
- МЕТ
- ПРИК
approved_on: 2017-02-04
approved_by:
- '103003000000'
version_date:
  kaz: 2022-03-25
  rus: 2022-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/110389/kaz/25.03.2022
  rus: https://zan.gov.kz/client/#!/doc/110389/rus/25.03.2022
caused_by:
  code: '166935'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 25 марта 2022 года № 148. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 апреля 2022 года № 27367
  title:
    rus: О внесении изменений в некоторые приказы Министра внутренних дел Республики Казахстан
    kaz: Қазақстан Республикасы Ішкі істер министрінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166935/rus
