act_code: '69031'
requisite: Приказ Председателя Агентства Республики Казахстан по делам религий от 30 октября 2012 года № 112. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 ноября 2012 года № 8116. Утратил силу приказом Министра культуры и спорта Республики Казахстан от 30 декабря 2014 года № 162
title:
  rus: Об утверждении Инструкции по отбору экспертов для проведения религиоведческой экспертизы
  kaz: Дінтану сараптамасын жүргізетін сарапшыларды іріктеу жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2012-10-30
approved_by:
- '128000000000'
version_date:
  kaz: 2013-12-23
  rus: 2013-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/69031/kaz/23.12.2013
  rus: https://zan.gov.kz/client/#!/doc/69031/rus/23.12.2013
caused_by:
  code: '77343'
  requisite: Приказ Председателя Агентства Республики Казахстан по делам религий от 23 декабря 2013 года № 50. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 января 2014 года № 9103. Утратил силу приказом Министра культуры и спорта Республики Казахстан от 30 декабря 2014 года № 162
  title:
    rus: О внесении изменений в приказ Председателя Агентства Республики Казахстан по делам религий от 30 октября 2012 года № 112 "Об утверждении Инструкции по отбору экспертов для проведения религиоведческой экспертизы"
    kaz: '"Дінтану сараптамасын жүргізетін сарапшыларды іріктеу жөніндегі нұсқаулықты бекіту туралы" Қазақстан Республикасы Дін істері агенттігі Төрағасының 2012 жылғы 30 қазандағы № 112 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/77343/rus
