act_code: '146673'
requisite: Приказ Министра энергетики Республики Казахстан от 23 сентября 2020 года № 327. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 сентября 2020 года № 21269
title:
  rus: Об утверждении Правил технологического присоединения к электрическим сетям энергопередающих организаций
  kaz: Энергия беруші ұйымдардың электр желілеріне технологиялық қосу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-09-23
approved_by:
- '103036000000'
version_date:
  kaz: 2024-12-23
  rus: 2024-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/146673/kaz/23.12.2024
  rus: https://zan.gov.kz/client/#!/doc/146673/rus/23.12.2024
caused_by:
  code: '204698'
  requisite: Приказ и.о. Министра энергетики Республики Казахстан от 23 декабря 2024 года № 483. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 декабря 2024 года № 35513
  title:
    rus: О внесении изменений и дополнений в некоторые приказы Министерства энергетики Республики Казахстан
    kaz: Қазақстан Республикасы Энергетика министрлігінің кейбір бұйрықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204698/rus
