act_code: '227299'
requisite: Приказ Заместителя Премьер-Министра – Министра искусственного интеллекта и цифрового развития Республики Казахстан от 1 июля 2026 года № 368/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 июля 2026 года № 39199
title:
  rus: Об утверждении Правил интеграции цифровых объектов «цифрового правительства»
  kaz: «Цифрлық үкіметтің» цифрлық объектілерін интеграциялау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2026-07-01
approved_by:
- '103054000000'
version_date:
  kaz: 2026-07-01
  rus: 2026-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/227299/kaz/01.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227299/rus/01.07.2026
