act_code: '110334'
requisite: Приказ Министра национальной экономики Республики Казахстан от 31 января 2017 года № 35. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 февраля 2017 года № 14765
title:
  rus: Об утверждении Правил субсидирования ставки вознаграждения по выдаваемым кредитам банками второго уровня субъектам частного предпринимательства для целей жилищного строительства
  kaz: Тұрғын үй құрылысы мақсаттары үшін жеке кәсіпкерлік субъектілеріне екінші деңгейдегі банктер беретін кредиттер бойынша сыйақы мөлшерлемелерін субсидиялау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2017-01-31
approved_by:
- '103033000000'
version_date:
  kaz: 2020-10-28
  rus: 2020-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/110334/kaz/28.10.2020
  rus: https://zan.gov.kz/client/#!/doc/110334/rus/28.10.2020
caused_by:
  code: '147001'
  requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 30 сентября 2020 года № 503. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 октября 2020 года № 21357
  title:
    rus: О внесении изменений в приказ Министра национальной экономики Республики Казахстан от 31 января 2017 года № 35 «Об утверждении Правил субсидирования ставки вознаграждения по выдаваемым кредитам банками второго уровня субъектам частного предпринимательства для целей жилищного строительства»
    kaz: «Тұрғын үй құрылысы мақсаттары үшін жеке кәсіпкерлік субъектілеріне екінші деңгейдегі банктер беретін кредиттер бойынша сыйақы мөлшерлемелерін субсидиялау қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық экономикпра министрінің 2017 жылғы 31 қаңтардағы № 35 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147001/rus
