act_code: '124371'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 10 августа 2018 года № 347. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 августа 2018 года № 17319. Утратил силу приказом Министра труда и социальной защиты населения Республики Казахстан от 24 мая 2023 года № 168 (вводится в действие с 1 июля 2023 года)
title:
  rus: Об утверждении форм отчетной документации в области адресной социальной помощи
  kaz: Атаулы әлеуметтік көмек саласындағы есепті құжаттамалардың нысандарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2018-08-10
approved_by:
- '103016000000'
version_date:
  kaz: 2022-07-20
  rus: 2022-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/124371/kaz/20.07.2022
  rus: https://zan.gov.kz/client/#!/doc/124371/rus/20.07.2022
caused_by:
  code: '169999'
  requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 20 июля 2022 года № 264. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 июля 2022 года № 28867. Утратил силу приказом Министра труда и социальной защиты населения Республики Казахстан от 24 мая 2023 года № 168 (вводится в действие с 1 июля 2023 года)
  title:
    rus: О внесении изменений в приказ Министра труда и социальной защиты населения Республики Казахстан от 10 августа 2018 года № 347 «Об утверждении форм отчетной документации в области адресной социальной помощи»
    kaz: «Атаулы әлеуметтік көмек саласындағы есепті құжаттамалардың нысандарын бекіту туралы» Қазақстан Республикасы Еңбек және халықты әлеуметтік қорғау министрінің 2018 жылғы 10 тамыздағы № 347 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169999/rus
