act_code: '141647'
requisite: Приказ Председателя Агентства Республики Казахстан по делам государственной службы от 13 апреля 2020 года № 67. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 апреля 2020 года № 20391
title:
  rus: Об утверждении Типовых квалификационных требований к категориям должностей правоохранительных органов
  kaz: Құқық қорғау органдары лауазымдарының санаттарына қойылатын үлгілік біліктілік талаптарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2020-04-13
approved_by:
- '120000000000'
version_date:
  kaz: 2025-07-30
  rus: 2025-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/141647/kaz/30.07.2025
  rus: https://zan.gov.kz/client/#!/doc/141647/rus/30.07.2025
caused_by:
  code: '212998'
  requisite: Приказ Председателя Агентства Республики Казахстан по делам государственной службы от 30 июля 2025 года № 124. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 августа 2025 года № 36562
  title:
    rus: О внесении изменения в приказ Председателя Агентства Республики Казахстан по делам государственной службы от 13 апреля 2020 года № 67 «Об утверждении Типовых квалификационных требований к категориям должностей правоохранительных органов»
    kaz: «Құқық қорғау органдары лауазымдарының санаттарына қойылатын үлгілік біліктілік талаптарын бекіту туралы» Қазақстан Республикасының Мемлекеттік қызмет істері агенттігі Төрағасының 2020 жылғы 13 сәуірдегі № 67 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212998/rus
