act_code: '169546'
requisite: Приказ Министра обороны Республики Казахстан от 1 июля 2022 года № 484дсп
title:
  rus: Об утверждении Инструкции по организации эксплуатации военного имущества Вооруженных Сил Республики Казахстан (вооружения и средств радиационной, химической и биологической защиты)
  kaz: Қазақстан Республикасы Қарулы Күштерінің әскери мүлкін (радиациялық, химиялық және биологиялық қорғау қару-жарағы мен құралдарын) пайдалануды ұйымдастыру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2022-07-01
approved_by:
- '103008000000'
version_date:
  kaz: 2022-07-01
  rus: 2022-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/169546/kaz/01.07.2022
  rus: https://zan.gov.kz/client/#!/doc/169546/rus/01.07.2022
