act_code: '83942'
requisite: Приказ Председателя агентства Республики Казахстан по делам государственной службы и противодействию коррупции от 7 октября 2014 года № 10. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 октября 2014 года № 9784. Утратил силу приказом Министра по делам государственной службы Республики Казахстан от 27 января 2016 года № 17
title:
  rus: О некоторых вопросах организации работы с кадрами в органах по делам государственной службы и противодействию коррупции Республики Казахстан
  kaz: Қазақстан Республикасының Мемлекеттік қызмет істері және сыбайлас жемқорлыққа қарсы іс-қимыл органдарындағы кадрлармен жұмысты ұйымдастырудың кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2014-10-07
approved_by:
- '133000000000'
version_date:
  kaz: 2015-04-02
  rus: 2015-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/83942/kaz/02.04.2015
  rus: https://zan.gov.kz/client/#!/doc/83942/rus/02.04.2015
caused_by:
  code: '90110'
  requisite: Приказ Председателя Агентства Республики Казахстан по делам государственной службы и противодействию коррупции от 2 апреля 2015 года № 99. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 мая 2015 года № 11020. Утратил силу приказом Министра по делам государственной службы Республики Казахстан от 27 января 2016 года № 17
  title:
    rus: О внесении изменений и дополнений в приказ Агентства Республики Казахстан по делам государственной службы и противодействию коррупции от 7 октября 2014 года № 10 «О некоторых вопросах организации работы с кадрами в органах по делам государственной службы и  противодействию коррупции Республики Казахстан»
    kaz: «Қазақстан Республикасының Мемлекеттік қызмет істері және сыбайлас жемқорлыққа қарсы іс-қимыл органдарындағы кадрлармен жұмысты ұйымдастырудың кейбір мәселелері туралы» Қазақстан Республикасы Мемлекеттік қызмет істері және сыбайлас жемқорлыққа қарсы іс-қимыл агнеттігінің 2014 жылғы 7 қазандағы № 10 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/90110/rus
