act_code: '17608'
requisite: Приказ Генерального прокурора Республики Казахстан от 31 октября 2003 года № 62. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 ноября 2003 года № 2576. Утратил силу приказом Генерального Прокурора Ресублики Казахстан от 8 октября 2014 года № 111
title:
  rus: Об утверждении отчета формы № 1-М "О зарегистрированных преступлениях и результатах деятельности органов уголовного преследования" и Инструкции по его составлению
  kaz: '"Тіркелген қылмыстар мен қылмыстық қудалау органдары қызметінің нәтижелері туралы" № 1-М нысанды есепті және оны құрастыру жөніндегі Нұсқаулықты бекіту'
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2003-10-31
approved_by:
- '107000000000'
version_date:
  kaz: 2010-01-20
  rus: 2010-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/17608/kaz/20.01.2010
  rus: https://zan.gov.kz/client/#!/doc/17608/rus/20.01.2010
caused_by:
  code: '50295'
  requisite: Приказ Генерального Прокурора Республики Казахстан от 20 января 2010 года № 3. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 января 2010 года № 6016. Утратил силу приказом Генерального Прокурора Республики Казахстан от 26 декабря 2017 года № 165 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в некоторые нормативные правовые акты Генерального Прокурора Республики Казахстан
    kaz: Қазақстан Республикасы Бас Прокурорының кейбір нормативтік құқықтық актілеріне толықтырулар мен өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/50295/rus
