act_code: '198296'
requisite: Приказ Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 28 июня 2024 года № 378/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 июня 2024 года № 34643
title:
  rus: Об утверждении Правил деятельности контакт-центра «111» по вопросам семьи, защиты прав женщин и детей и его взаимодействия с центральными государственными органами, местными исполнительными органами
  kaz: Отбасы, әйелдер мен балалардың құқықтарын қорғау мәселелері бойынша «111» байланыс орталығы қызметінің және оның орталық мемлекеттік органдармен, жергілікті атқарушы органдармен өзара іс-қимыл жасау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2024-06-28
approved_by:
- '103045000000'
version_date:
  kaz: 2026-07-12
  rus: 2026-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/198296/kaz/12.07.2026
  rus: https://zan.gov.kz/client/#!/doc/198296/rus/12.07.2026
caused_by:
  code: '226379'
  requisite: Приказ Заместителя Премьер-Министра – Министра искусственного интеллекта и цифрового развития Республики Казахстан от 11 июня 2026 года № 309/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 июня 2026 года № 38952
  title:
    rus: О внесении изменений в приказ Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 28 июня 2024 года № 378/НҚ «Об утверждении Правил деятельности контакт-центра «111» по вопросам семьи, защиты прав женщин и детей и его взаимодействия с центральными государственными органами, местными исполнительными органами»
    kaz: «Отбасы, әйелдер мен балалардың құқықтарын қорғау мәселелері бойынша «111» байланыс орталығы қызметінің және оның орталық мемлекеттік органдармен, жергілікті атқарушы органдармен өзара іс-қимыл жасау қағидаларын бекіту туралы» Қазақстан Республикасы Цифрлық даму, инновациялар және аэроғарыш өнеркәсібі министрінің 2024 жылғы 28 маусымдағы № 378/НҚ бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/226379/rus
