act_code: '150027'
requisite: Приказ Министра здравоохранения Республики Казахстан от 15 декабря 2020 года № ҚР ДСМ-276/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 декабря 2020 года № 21804
title:
  rus: Об утверждении Правил ведения реестра потенциально опасных химических, биологических веществ, запрещенных к применению в Республике Казахстан
  kaz: Қазақстан Республикасында қолдануға тыйым салынған әлеуетті қауіпті химиялық, биологиялық заттардың тізілімін жүргізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-12-15
approved_by:
- '103010000000'
version_date:
  kaz: 2020-12-15
  rus: 2020-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/150027/kaz/15.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150027/rus/15.12.2020
