act_code: '119401'
requisite: Приказ Министра финансов Республики Казахстан от 19 февраля 2018 года № 229. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 марта 2018 года № 16527
title:
  rus: Об утверждении Правил изъятия таможенных, транспортных (перевозочных), коммерческих и иных документов, средств идентификации для проведения таможенной экспертизы и формы акта об изъятии документов, средств идентификации документов и товаров
  kaz: Кедендік сараптама жүргізу үшін кедендік, көліктік (тасымалдау), коммерциялық және өзге де құжаттарды, сәйкестендіру құралдарды алу қағидалары мен құжаттар, құжаттар мен тауарлардың сәйкестендіру құралдарын алу туралы акт нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-02-19
approved_by:
- '103002000000'
version_date:
  kaz: 2022-12-28
  rus: 2022-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/119401/kaz/28.12.2022
  rus: https://zan.gov.kz/client/#!/doc/119401/rus/28.12.2022
caused_by:
  code: '176498'
  requisite: Приказ и.о. Министра финансов Республики Казахстан от 28 декабря 2022 года № 1336. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 декабря 2022 года № 31419
  title:
    rus: О внесении изменений в некоторые приказы Министра финансов Республики Казахстан
    kaz: Қазақстан Республикасы Қаржы министрінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/176498/rus
