act_code: '91941'
requisite: Приказ Министра национальной экономики Республики Казахстан от 30 мая 2015 года № 414. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 июля 2015 года № 11658. Утратил силу приказом и.о. Министра здравоохранения Республики Казахстан от 17 ноября 2017 года № 836 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня продукции и эпидемически значимых объектов, подлежащих государственному санитарно-эпидемиологическому контролю и надзору
  kaz: Мемлекеттік санитариялық-эпидемиологиялық бақылауға және қадағалауға жататын өнім мен эпидемиялық маңызы бар объектілердің тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2015-05-30
approved_by:
- '103033000000'
version_date:
  kaz: 2015-05-30
  rus: 2015-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/91941/kaz/30.05.2015
  rus: https://zan.gov.kz/client/#!/doc/91941/rus/30.05.2015
