act_code: '5810'
requisite: Приказ Министра образования и науки Республики Казахстан от 25.03.2000г. N 247. Зарегистрирован в Министерстве юстиции Республики Казахстан 22.04.2000г. N 1118. Утратил силу приказом Министра образования и науки Республики Казахстан от 19 декабря 2007 года N 638.№
title:
  rus: Об утверждении Типовых правил приема в высшие учебные заведения Республики Казахстан
  kaz: Қазақстан Республикасы жоғары оқу-орындарына қабылдаудың Yлгi ережелерiн бекiту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2000-03-25
approved_by:
- '103006000000'
version_date:
  kaz: 2004-03-23
  rus: 2004-03-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/5810/kaz/23.03.2004
  rus: https://zan.gov.kz/client/#!/doc/5810/rus/23.03.2004
caused_by:
  code: '20222'
  requisite: Приказ Министра образования и науки Республики Казахстан от 23 марта 2004 года N 241. Зарегистрирован Министерством юстиции Республики Казахстан 16 апреля 2004 года N 2808. Утратил силу приказом Министра образования и науки РК от 19 декабря 2007 года  N 638
  title:
    rus: О внесении изменений и дополнений в приказ Министра образования и науки Республики Казахстан от 25 марта 2000 года N 247 "Об утверждении Типовых правил приема в высшие учебные заведения Республики Казахстан", зарегистрированный в Министерстве юстиции Республики Казахстан за N 1118
    kaz: Қазақстан Республикасының Әдiлет министрлiгінде N 1118 тiркелген "Қазақстан Республикасының жоғары оқу орындарына қабылдаудың типтiк ережелерiн бекiту туралы" Қазақстан Республикасы Бiлiм және ғылым министрінің 2000 жылғы 25 наурыздағы N 247 бұйрығына өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/20222/rus
