act_code: '96520'
requisite: Приказ Министра внутренних дел Республики Казахстан от 16 ноября 2015 года № 925. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 декабря 2015 года № 12432. Утратил силу приказом Министра внутренних дел Республики Казахстан от 21 февраля 2024 года № 151 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О некоторых вопросах исчисления выслуги лет службы военнослужащих внутренних войск, Национальной гвардии Республики Казахстан и сотрудников органов внутренних дел Республики Казахстан на льготных условиях для назначения пенсионных выплат за выслугу лет
  kaz: Еңбек сіңірген жылдары үшін зейнетақы төлемдерін тағайындау үшін Ішкі әскерлер, Қазақстан Республикасының Ұлттық ұланы әскери қызметшілерінің және Қазақстан Республикасының ішкі істер органдары қызметкерлерінің еңбек сіңірген жылдарын жеңілдік жағдайларында есептеудің кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2015-11-16
approved_by:
- '103003000000'
version_date:
  kaz: 2017-01-31
  rus: 2017-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/96520/kaz/31.01.2017
  rus: https://zan.gov.kz/client/#!/doc/96520/rus/31.01.2017
caused_by:
  code: '110202'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 31 января 2017 года № 75. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 марта 2017 года № 14859. Утратил силу приказом Министра внутренних дел Республики Казахстан от 21 февраля 2024 года № 151 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра внутренних дел Республики Казахстан от 16 ноября 2015 года № 925 «О некоторых вопросах исчисления выслуги лет для назначения пенсий на льготных условиях военнослужащим внутренних войск, Национальной гвардии Республики Казахстан и сотрудникам органов внутренних дел»
    kaz: «Ішкі әскерлер, Қазақстан Республикасының Ұлттық ұланы әскери қызметшілерінің және ішкі істер органдары қызметкерлерінің жеңілдік жағдайларында зейнетақы тағайындау үшін еңбек сіңірген жылдарын есептеудің кейбір мәселелері туралы» Қазақстан Республикасы Ішкі істер министрінің 2015 жылғы 16 қарашадағы № 925 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/110202/rus
