act_code: '22982'
requisite: Приказ Председателя Агентства Республики Казахстан по делам государственной службы от 5 февраля 2005 года N 02-01-02/15. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 февраля 2005 года за N 3449. Утратил силу приказом Министра по делам государственной службы Республики Казахстан от 29 декабря 2015 года № 10
title:
  rus: Об утверждении Правил проведения конкурса по отбору государственных служащих, направляемых на повышение квалификации за рубеж
  kaz: Шет елге біліктілігін арттыруға жіберілетін мемлекеттік қызметшілерді іріктеу жөнінде конкурс өткізу ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2005-02-05
approved_by:
- '120000000000'
version_date:
  kaz: 2007-09-03
  rus: 2007-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/22982/kaz/03.09.2007
  rus: https://zan.gov.kz/client/#!/doc/22982/rus/03.09.2007
caused_by:
  code: '34998'
  requisite: Приказ Председателя Агентства Республики Казахстан по делам государственной службы от 3 сентября 2007 года № 02-01-02/113. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 сентября 2007 года № 4920. Утратил силу приказом Председателя Агентства РК по делам государственной службы от 19 марта 2013 года № 06-7/32
  title:
    rus: О внесении дополнений и изменений в некоторые приказы Председателя Агентства Республики Казахстан по делам государственной службы
    kaz: Қазақстан Республикасы Мемлекеттік қызмет істері агенттігі Төрағасының кейбір бұйрықтарына толықтырулар мен өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/34998/rus
