act_code: '141983'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 20 апреля 2020 года № 98. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 апреля 2020 года № 20439
title:
  rus: Об утверждении Правил и условий проведения научно-реставрационных работ на памятниках истории и культуры
  kaz: Тарих және мәдениет ескерткіштеріндегі ғылыми-реставрациялық жұмыстарды жүргізу қағидалары мен шарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-04-20
approved_by:
- '103034000000'
version_date:
  kaz: 2025-04-11
  rus: 2025-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/141983/kaz/11.04.2025
  rus: https://zan.gov.kz/client/#!/doc/141983/rus/11.04.2025
caused_by:
  code: '209334'
  requisite: Приказ Министра культуры и информации Республики Казахстан от 11 апреля 2025 года № 161-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 апреля 2025 года № 36003
  title:
    rus: О внесении изменений и дополнений в приказ Министра культуры и спорта Республики Казахстан от 20 апреля 2020 года № 98 «Об утверждении Правил и условий проведения научно-реставрационных работ на памятниках истории и культуры»
    kaz: «Тарих және мәдениет ескерткіштеріндегі ғылыми-реставрациялық жұмыстарды жүргізу қағидалары мен шарттарын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің 2020 жылғы 20 сәуірдегі № 98 бұйрығына өзгеріс пен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209334/rus
