act_code: '203609'
requisite: Совместный приказ и.о. Министра энергетики Республики Казахстан от 4 декабря 2024 года № 440, Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 4 декабря 2024 года № 759/НҚ, и.о. Министра труда и социальной защиты населения от 4 декабря 2024 года № 446 и Заместителя Премьер-Министра - Министра национальной экономики Республики Казахстан от 5 декабря 2024 года № 107. Действовал по 30 апреля 2025 года в соответствии с пунктом 8 настоящего совместного приказа
title:
  rus: О запуске пилотного проекта по оказанию услуги «Предоставление ваучеров на товарный газ получателям государственной адресной социальной и жилищной помощи»
  kaz: «Мемлекеттік атаулы әлеуметтік көмек алушыларға және тұрғын үй көмегін алушыларға тауарлық газға ваучерлер беру» қызметін көрсету жөніндегі пилоттық жобаны іске қосу туралы
form: ПРИК
type_codes:
- ПРИК
- ПРОЕ
approved_on: 2024-12-04
approved_by:
- '103016000000'
- '103033000000'
- '103036000000'
- '103045000000'
version_date:
  kaz: 2024-12-04
  rus: 2024-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/203609/kaz/04.12.2024
  rus: https://zan.gov.kz/client/#!/doc/203609/rus/04.12.2024
repealed_on: 2025-04-30
repealed_by:
  code: '203609'
  requisite: Совместный приказ и.о. Министра энергетики Республики Казахстан от 4 декабря 2024 года № 440, Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 4 декабря 2024 года № 759/НҚ, и.о. Министра труда и социальной защиты населения от 4 декабря 2024 года № 446 и Заместителя Премьер-Министра - Министра национальной экономики Республики Казахстан от 5 декабря 2024 года № 107. Действовал по 30 апреля 2025 года в соответствии с пунктом 8 настоящего совместного приказа
  title:
    rus: О запуске пилотного проекта по оказанию услуги «Предоставление ваучеров на товарный газ получателям государственной адресной социальной и жилищной помощи»
    kaz: «Мемлекеттік атаулы әлеуметтік көмек алушыларға және тұрғын үй көмегін алушыларға тауарлық газға ваучерлер беру» қызметін көрсету жөніндегі пилоттық жобаны іске қосу туралы
  link: https://zan.gov.kz/client/#!/doc/203609/rus
