act_code: '134003'
requisite: Приказ и.о. Министра энергетики Республики Казахстан от 8 августа 2019 года № 275. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 августа 2019 года № 19232
title:
  rus: Об утверждении Положения о центральной комиссии по разработке месторождений урана Республики Казахстан
  kaz: Қазақстан Республикасының уран кен орындарын әзірлеу жөніндегі орталық комиссиясы туралы ережені бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2019-08-08
approved_by:
- '103036000000'
version_date:
  kaz: 2023-05-03
  rus: 2023-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/134003/kaz/03.05.2023
  rus: https://zan.gov.kz/client/#!/doc/134003/rus/03.05.2023
caused_by:
  code: '181139'
  requisite: Приказ Министра энергетики Республики Казахстан от 3 мая 2023 года № 168. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 мая 2023 года № 32472
  title:
    rus: О внесении изменений в некоторые приказы Министерства энергетики Республики Казахстан
    kaz: Қазақстан Республикасы Энергетика министрлігінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181139/rus
