act_code: '91880'
requisite: Приказ и.о. Министра по инвестициям и развитию Республики Казахстан от 28 мая 2015 года № 644. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 июля 2015 года № 11590. Утратил силу приказом Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 20 ноября 2023 года № 558/НҚ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в области связи
  kaz: Байланыс саласындағы мемлекеттiк көрсетілетін қызметтердiң регламенттерін бекiту туралы
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2015-05-28
approved_by:
- '103035000000'
version_date:
  kaz: 2016-02-12
  rus: 2016-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/91880/kaz/12.02.2016
  rus: https://zan.gov.kz/client/#!/doc/91880/rus/12.02.2016
caused_by:
  code: '100458'
  requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 12 февраля 2016 года № 182. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 марта 2016 года № 13465. Утратил силу приказом Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 20 ноября 2023 года № 558/НҚ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра по инвестициям и развитию Республики Казахстан от 28 мая 2015 года № 644 «Об утверждении регламентов государственных услуг в области связи»
    kaz: «Байланыс саласындағы мемлекеттiк көрсетілетін қызметтердің регламенттерін бекiту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің міндетін атқарушының 2015 жылғы 28 мамырдағы № 644 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/100458/rus
