act_code: '144783'
requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 7 июля 2020 года № 385. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 июля 2020 года № 20968
title:
  rus: О приостановлении действия абзаца второго пункта 1 приказа Министра индустрии и инфраструктурного развития Республики Казахстан от 19 февраля 2019 года № 89 «О некоторых вопросах регулирования вывоза регенерируемой бумаги, картона, макулатуры и отходов, необработанных шкур крупного рогатого скота»
  kaz: «Қалпына келтірілетін қағазды, картонды, макулатура мен қалдықтарды, өңделмеген ірі қара малдың терісін әкетуді реттеудің кейбір мәселелері туралы» Қазақстан Республикасы Индустрия және инфрақұрылымдық даму министрінің 2019 жылғы 19 ақпандағы № 89 бұйрығының 1-тармағының екінші абзацының қолданылуын тоқтата тұру туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2020-07-07
approved_by:
- '103042000000'
version_date:
  kaz: 2020-07-07
  rus: 2020-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/144783/kaz/07.07.2020
  rus: https://zan.gov.kz/client/#!/doc/144783/rus/07.07.2020
