act_code: '122437'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 23 мая 2018 года № 365. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 июня 2018 года № 17003
title:
  rus: Об утверждении Правил подачи и рассмотрения заявлений на выдачу лицензий на разведку твердых полезных ископаемых
  kaz: Пайдалы қатты қазбаларды барлауға арналған лицензияларды беруге өтініштерді беру және оларды қарау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-05-23
approved_by:
- '103035000000'
version_date:
  kaz: 2023-09-14
  rus: 2023-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/122437/kaz/14.09.2023
  rus: https://zan.gov.kz/client/#!/doc/122437/rus/14.09.2023
caused_by:
  code: '186389'
  requisite: Приказ и.о. Министра промышленности и строительства Республики Казахстан от 14 сентября 2023 года № 6. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 сентября 2023 года № 33426
  title:
    rus: О внесении изменений в приказ Министра по инвестициям и развитию Республики Казахстан от 23 мая 2018 года № 365 «Об утверждении Правил подачи и рассмотрения заявлений на выдачу лицензий на разведку твердых полезных ископаемых»
    kaz: «Пайдалы қатты қазбаларды барлауға арналған лицензияларды беруге өтініштерді беру және оларды қарау қағидаларын бекіту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің 2018 жылғы 23 мамырдағы № 365 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186389/rus
