act_code: '54411'
requisite: Приказ Министра здравоохранения Республики Казахстан от 30 июля 2010 года № 576. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 августа 2010 года № 6442. Утратил силу приказом Министра здравоохранения Республики Казахстан от 25 сентября 2017 года № 720 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил доплаты за квалификационную категорию и Перечня организаций и должностей работников, которым устанавливается доплата за условия труда
  kaz: Біліктілік санаты үшін үстеме ақы төлеу ережесін және Еңбек жағдайы үшін үстеме ақы белгіленетін ұйымдар мен қызметкерлер лауазымдарының тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2010-07-30
approved_by:
- '103010000000'
version_date:
  kaz: 2010-07-30
  rus: 2010-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/54411/kaz/30.07.2010
  rus: https://zan.gov.kz/client/#!/doc/54411/rus/30.07.2010
