act_code: '199931'
requisite: Приказ Министра культуры и информации Республики Казахстан от 20 августа 2024 года № 367-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 августа 2024 года № 34967
title:
  rus: Об утверждении Типовых правил аккредитации журналистов (представителей средств массовой информации)
  kaz: Журналистерді (бұқаралық ақпарат құралдарының өкілдері) аккредиттеудің үлгілік қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2024-08-20
approved_by:
- '103053000000'
version_date:
  kaz: 2024-08-20
  rus: 2024-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/199931/kaz/20.08.2024
  rus: https://zan.gov.kz/client/#!/doc/199931/rus/20.08.2024
