act_code: '230303'
requisite: Приказ Министра юстиции Республики Казахстан от 22 сентября 2026 года № 937. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 сентября 2026 года № 39955
title:
  rus: Об утверждении Правил пользования единой цифровой системой судебно-экспертной деятельности
  kaz: Сот-сараптама қызметінің бірыңғай цифрлық жүйесін пайдалану қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2026-09-22
approved_by:
- '103001000000'
version_date:
  kaz: 2026-09-22
  rus: 2026-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/230303/kaz/22.09.2026
  rus: https://zan.gov.kz/client/#!/doc/230303/rus/22.09.2026
