act_code: '60758'
requisite: Приказ Председателя Агентства Республики Казахстан по делам строительства и жилищно-коммунального хозяйства от 26 августа 2011 года № 306. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 октября 2011 года № 7232
title:
  rus: Об утверждении Методики расчета размера платы за пользование жилищем из государственного жилищного фонда
  kaz: Мемлекеттік тұрғын үй қорындағы тұрғын үйді пайдаланғаны үшін төлемақы мөлшерін есептеу әдістемесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2011-08-26
approved_by:
- '123000000000'
version_date:
  kaz: 2025-10-07
  rus: 2025-10-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/60758/kaz/07.10.2025
  rus: https://zan.gov.kz/client/#!/doc/60758/rus/07.10.2025
caused_by:
  code: '215410'
  requisite: Приказ Министра промышленности и строительства Республики Казахстан от 7 октября 2025 года № 420. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 октября 2025 года № 37087
  title:
    rus: О внесении изменений в приказ Председателя Агентства Республики Казахстан по делам строительства и жилищно-коммунального хозяйства от 26 августа 2011 года № 306 «Об утверждении Методики расчета размера платы за пользование жилищем из государственного жилищного фонда»
    kaz: «Мемлекеттік тұрғын үй қорындағы тұрғын үйді пайдаланғаны үшін төлемақы мөлшерін есептеу әдістемесін бекіту туралы» Қазақстан Республикасы Құрылыс және Тұрғын үй-коммуналдық шаруашылық істері агенттігі төрағасының 2011 жылғы 26 тамыздағы № 306 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215410/rus
