act_code: '169472'
requisite: Приказ Министра здравоохранения Республики Казахстан от 30 июня 2022 года № ҚР ДСМ-61. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 июля 2022 года № 28669
title:
  rus: Об утверждении Правил оказания медицинской помощи лицам, содержащимся в следственных изоляторах и учреждениях уголовно-исполнительной (пенитенциарной) системы
  kaz: Қылмыстық-атқару (пенитенциарлық) жүйесінің тергеу изоляторлары мен мекемелерінде ұсталатын адамдарға медициналық көмек көрсету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-06-30
approved_by:
- '103010000000'
version_date:
  kaz: 2024-02-05
  rus: 2024-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/169472/kaz/05.02.2024
  rus: https://zan.gov.kz/client/#!/doc/169472/rus/05.02.2024
caused_by:
  code: '193080'
  requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 5 февраля 2024 года № 5. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 февраля 2024 года № 33971
  title:
    rus: О внесении изменений и дополнений в приказ Министра здравоохранения Республики Казахстан от 30 июня 2022 года № ҚР ДСМ-61 «Об утверждении Правил оказания медицинской помощи лицам, содержащимся в следственных изоляторах и учреждениях уголовно-исполнительной (пенитенциарной) системы»
    kaz: «Қылмыстық-атқару (пенитенциарлық) жүйесінің тергеу изоляторлары мен мекемелерінде ұсталатын адамдарға медициналық көмек көрсету қағидаларын бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2022 жылғы 30 маусымдағы № ҚР ДСМ-61 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/193080/rus
