act_code: '214872'
requisite: Приказ Министра промышленности и строительства Республики Казахстан от 25 сентября 2025 года № 392
title:
  rus: Об утверждении условий производства, производственных и технологических операций
  kaz: Өндіріс, өндірістік және технологиялық операциялар шарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- УСЛ
approved_on: 2025-09-25
approved_by:
- '103052000000'
version_date:
  kaz: 2026-01-14
  rus: 2026-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/214872/kaz/14.01.2026
  rus: https://zan.gov.kz/client/#!/doc/214872/rus/14.01.2026
caused_by:
  code: '221380'
  requisite: Приказ и.о. Министра промышленности и строительства Республики Казахстан от 14 января 2026 года № 10
  title:
    rus: О внесении изменений в приказ Министра промышленности и строительства Республики Казахстан от 25 сентября 2025 года № 392 «Об утверждении условий производства, производственных и технологических операций»
    kaz: «Өндіріс, өндірістік және технологиялық операциялар шарттарын бекіту туралы» Қазақстан Республикасы Өнеркәсіп және құрылыс Министрінің 2025 жылғы 25 қыркүйектегі № 392 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/221380/rus
