act_code: '2159'
requisite: Приказ Министра юстиции Республики Казахстан от 15 января 1999 года N 3. Зарегистрирован в Министерстве юстиции РК 21.01.1999г. N 667. Утратил силу приказом Министра юстиции Республики Казахстан от 12 апреля 2007 года N 115
title:
  rus: Вопросы государственной регистрации юридических лиц
  kaz: Заңды тұлғаларды мемлекеттік тіркеу мәселелері
form: ПРИК
type_codes:
- ПРИК
approved_on: 1999-01-15
approved_by:
- '103001000000'
version_date:
  kaz: 2004-09-12
  rus: 2004-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/2159/kaz/12.09.2004
  rus: https://zan.gov.kz/client/#!/doc/2159/rus/12.09.2004
caused_by:
  code: '21230'
  requisite: Приказ Министра юстиции Республики Казахстан от 13 сентября 2004 года N 265. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 сентября 2004 года N 3060. Утратил силу приказом Министра юстиции Республики Казахстан от 12 апреля 2007 года N 115
  title:
    rus: О внесении изменений и дополнений в приказ Министра юстиции Республики Казахстан от 15 января 1999 года N 3 "Вопросы государственной регистрации юридических лиц", зарегистрированный за N 667
    kaz: N 667 тіркелген, "Заңды тұлғаларды мемлекеттік тіркеу мәселелері" туралы Қазақстан Республикасы Әділет министрінің 1999 жылғы 15 қаңтардағы N 3 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/21230/rus
