act_code: '189820'
requisite: Приказ Министра промышленности и строительства Республики Казахстан от 8 декабря 2023 года № 117. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 декабря 2023 года № 33763
title:
  rus: Об утверждении Правил предоставления жилищной помощи
  kaz: Тұрғын үй көмегін беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2023-12-08
approved_by:
- '103052000000'
version_date:
  kaz: 2024-09-09
  rus: 2024-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/189820/kaz/09.09.2024
  rus: https://zan.gov.kz/client/#!/doc/189820/rus/09.09.2024
caused_by:
  code: '200572'
  requisite: Приказ и.о. Министра промышленности и строительства Республики Казахстан от 9 сентября 2024 года № 319. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 сентября 2024 года № 35047
  title:
    rus: О внесении изменений в некоторые приказы
    kaz: Кейбір бұйрықтарға өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200572/rus
