act_code: '179616'
requisite: Приказ Министра здравоохранения Республики Казахстан от 7 апреля 2023 года № 62. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 апреля 2023 года № 32276
title:
  rus: Об утверждении Санитарных правил «Санитарно-эпидемиологические требования к осуществлению производственного контроля»
  kaz: «Өндірістік бақылауды жүзеге асыруға қойылатын санитариялық-эпидемиологиялық талаптар» санитариялық қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2023-04-07
approved_by:
- '103010000000'
version_date:
  kaz: 2026-03-03
  rus: 2026-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/179616/kaz/03.03.2026
  rus: https://zan.gov.kz/client/#!/doc/179616/rus/03.03.2026
caused_by:
  code: '222737'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 3 марта 2026 года № 22. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 марта 2026 года № 38086
  title:
    rus: О внесении изменений и дополнения в приказ Министра здравоохранения Республики Казахстан от 7 апреля 2023 года № 62 «Об утверждении Санитарных правил «Санитарно-эпидемиологические требования к осуществлению производственного контроля»
    kaz: «Өндірістік бақылауды жүзеге асыруға қойылатын санитариялық-эпидемиологиялық талаптар» санитариялық қағидаларын бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2023 жылғы 7 сәуірдегі № 62 бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222737/rus
