act_code: '37873'
requisite: Приказ Министра образования и науки Республики Казахстан от 10 января 2008 года N 8. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 февраля 2008 года N 5135. Утратил силу приказом и.о. Министра образования и науки Республики Казахстан от 19 июля 2021 года № 352 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил признания и нострификации документов об образовании
  kaz: Білім туралы құжаттарды тану және нострификациялау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2008-01-10
approved_by:
- '103006000000'
version_date:
  kaz: 2015-11-11
  rus: 2015-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/37873/kaz/11.11.2015
  rus: https://zan.gov.kz/client/#!/doc/37873/rus/11.11.2015
caused_by:
  code: '98051'
  requisite: Приказ Министра образования и науки Республики Казахстан от 11 ноября 2015 года № 639. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 декабря 2015 года № 12424. Утратил силу приказом и.о. Министра образования и науки Республики Казахстан от 19 июля 2021 года № 352 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра образования и науки Республики Казахстан от 10 января 2008 года № 8 "Об утверждении Правил признания и нострификации документов об образовании"
    kaz: '"Білім туралы құжаттарды тану және нострификациялау ережесін бекіту туралы" Қазақстан Республикасы Білім және ғылым министрінің 2008 жылғы 10 қаңтардағы № 8 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/98051/rus
