act_code: '148607'
requisite: Приказ Министра внутренних дел Республики Казахстан от 13 ноября 2020 года № 775. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 ноября 2020 года № 21646
title:
  rus: Об утверждении Требований, предъявляемых к состоянию здоровья лиц для прохождения службы в правоохранительных органах, органах гражданской защиты и Государственной фельдъегерской службе Республики Казахстан
  kaz: Қазақстан Республикасының құқық қорғау органдарында, азаматтық қорғау органдарында және Мемлекеттік фельдъегерлік қызметінде қызмет өткеру үшін адамдардың денсаулық жағдайына қойылатын талаптарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2020-11-13
approved_by:
- '103003000000'
version_date:
  kaz: 2025-08-06
  rus: 2025-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/148607/kaz/06.08.2025
  rus: https://zan.gov.kz/client/#!/doc/148607/rus/06.08.2025
caused_by:
  code: '213201'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 6 августа 2025 года № 584. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 августа 2025 года № 36604
  title:
    rus: О внесении изменений в приказ Министра внутренних дел Республики Казахстан от 13 ноября 2020 года № 775 «Об утверждении Требований, предъявляемых к состоянию здоровья лиц для прохождения службы в правоохранительных органах и Государственной фельдъегерской службе Республики Казахстан»
    kaz: «Қазақстан Республикасының құқық қорғау органдарында және Мемлекеттік фельдъегерлік қызметінде қызмет өткеру үшін адамдардың денсаулық жағдайына қойылатын талаптарды бекіту туралы» Қазақстан Республикасы Ішкі істер министрінің 2020 жылғы 13 қарашадағы № 775 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213201/rus
