act_code: '215271'
requisite: Приказ Министра торговли и интеграции Республики Казахстан от 30 сентября 2025 года № 282-НҚ
title:
  rus: Об утверждении требований к формированию, методике расчета страховых резервов по договорам страхования, перестрахования, заключаемым Экспортно-кредитным агентством Казахстана, их структуре
  kaz: Қазақстанның Экспорттық-кредиттік агенттігі жасасатын сақтандыру, қайта сақтандыру шарттары бойынша cақтандыру резервтерін қалыптастыруға, есептеу әдiстемесiне және олардың құрылымына қойылатын талаптарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2025-09-30
approved_by:
- '103046000000'
version_date:
  kaz: 2025-09-30
  rus: 2025-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/215271/kaz/30.09.2025
  rus: https://zan.gov.kz/client/#!/doc/215271/rus/30.09.2025
