act_code: '218111'
requisite: Совместный приказ Министра юстиции Республики Казахстан от 24 ноября 2025 года № 691 и Министра внутренних дел Республики Казахстан от 24 ноября 2025 года № 950
title:
  rus: О взаимодействии судебных исполнителей с сотрудниками органов внутренних дел при осуществлении привода должников по исполнительным производствам для возбуждения административного производства
  kaz: Сот орындаушыларының ішкі істер органдарының қызметкерлерімен атқарушылық іс жүргізулер бойынша борышкерлерді әкімшілік іс қозғау үшін күштеп әкелуді жүзеге асыру кезіндегі өзара іс-қимылы туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-11-24
approved_by:
- '103001000000'
- '103003000000'
version_date:
  kaz: 2025-11-24
  rus: 2025-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/218111/kaz/24.11.2025
  rus: https://zan.gov.kz/client/#!/doc/218111/rus/24.11.2025
