act_code: '93933'
requisite: Приказ и.о. Министра сельского хозяйства Республики Казахстан от 31 июля 2015 года № 16-05/715. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 сентября 2015 года № 12013
title:
  rus: Об утверждении Положения о Комитете ветеринарного контроля и надзора Министерства сельского хозяйства Республики Казахстан
  kaz: Қазақстан Республикасы Ауыл шаруашылығы министрлігінің Ветеринариялық бақылау және қадағалау комитеті туралы ережені бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2015-07-31
approved_by:
- '103012000000'
version_date:
  kaz: 2021-11-15
  rus: 2021-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/93933/kaz/15.11.2021
  rus: https://zan.gov.kz/client/#!/doc/93933/rus/15.11.2021
caused_by:
  code: '160502'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 15 ноября 2021 года № 329
  title:
    rus: О внесении изменений и дополнений в приказ исполняющего обязанности Министра сельского хозяйства Республики Казахстан от 31 июля 2015 года № 16-05/715 «Об утверждении положения о Комитете ветеринарного контроля и надзора Министерства сельского хозяйства Республики Казахстан»
    kaz: «Қазақстан Республикасы Ауыл шаруашылығы министрлігінің Ветеринариялық бақылау және қадағалау комитеті туралы ережені бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің міндетін атқарушының 2015 жылғы 31 шілдедегі № 16-05/715 бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160502/rus
