act_code: '198464'
requisite: Приказ Министра обороны Республики Казахстан от 27 июня 2024 года № 681дсп
title:
  rus: Об утверждении Инструкции по эвакуации, обеспечению сохранности и уничтожению секретных документов и изделий в Вооруженных Силах Республики Казахстан при возникновении кризисной ситуации
  kaz: Қазақстан Республикасының Қарулы Күштерінде дағдарысты жағдай туындаған кезде құпия құжаттар мен бұйымды эвакуациялау, олардың сақталуын қамтамасыз ету және жою жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2024-06-27
approved_by:
- '103008000000'
version_date:
  kaz: 2024-06-27
  rus: 2024-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/198464/kaz/27.06.2024
  rus: https://zan.gov.kz/client/#!/doc/198464/rus/27.06.2024
