act_code: '139297'
requisite: Приказ Председателя Комитета по статистике Министерства национальной экономики Республики Казахстан от 29 января 2020 года № 11. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 февраля 2020 года № 19970
title:
  rus: Об утверждении статистических форм общегосударственных статистических наблюдений по статистике транспорта и инструкций по их заполнению
  kaz: Көлік статистикасы бойынша жалпымемлекеттік статистикалық байқаудың статистикалық нысандары мен оларды толтыру жөніндегі нұсқаулықтарды бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2020-01-29
approved_by:
- '103033003000'
version_date:
  kaz: 2020-01-29
  rus: 2020-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/139297/kaz/29.01.2020
  rus: https://zan.gov.kz/client/#!/doc/139297/rus/29.01.2020
