act_code: '73400'
requisite: Приказ Министра охраны окружающей среды Республики Казахстан от 12 июня 2013 года № 162-Ө. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 июля 2013 года № 8559. Утратил силу приказом и.о. Министра экологии, геологии и природных ресурсов Республики Казахстан от 9 августа 2021 года № 319 (вводится в действие по истечении шестидесяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Типового перечня мероприятий по охране окружающей среды
  kaz: Қоршаған ортаны қорғау жөніндегі іс-шаралардың үлгілі тізімін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2013-06-12
approved_by:
- '103015000000'
version_date:
  kaz: 2013-06-12
  rus: 2013-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/73400/kaz/12.06.2013
  rus: https://zan.gov.kz/client/#!/doc/73400/rus/12.06.2013
