act_code: '91671'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 30 апреля 2015 года № 555. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 июня 2015 года № 11428. Утратил силу приказом Министра индустрии и инфраструктурного развития Республики Казахстан от 5 октября 2020 года № 514 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении стандартов государственных услуг в сфере железнодорожного транспорта
  kaz: Теміржол көлігі саласында мемлекеттік көрсетілетін қызметтер стандарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2015-04-30
approved_by:
- '103035000000'
version_date:
  kaz: 2017-07-12
  rus: 2017-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/91671/kaz/12.07.2017
  rus: https://zan.gov.kz/client/#!/doc/91671/rus/12.07.2017
caused_by:
  code: '115161'
  requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 12 июля 2017 года № 465. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 сентября 2017 года № 15774
  title:
    rus: О внесении изменений и дополнений в некоторые приказы Министерства индустрии и новых технологий Республики Казахстан и Министерства по инвестициям и развитию Республики Казахстан по вопросам оказания государственных услуг
    kaz: Қазақстан Республикасы Индустрия және жаңа технологиялар министрлігінің және Қазақстан Республикасы Инвестициялар және даму министрлігінің кейбір бұйрықтарына мемлекеттік қызметтерді көрсету мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/115161/rus
