act_code: '66400'
requisite: Приказ Министра индустрии и новых технологий Республики Казахстан от 1 июня 2012 года № 184. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 июня 2012 года № 7760. Утратил силу приказом Министра по инвестициям и развитию Республики Казахстан от 30 ноября 2015 года № 1133
title:
  rus: О некоторых вопросах государственной поддержки инвестиций
  kaz: Инвестицияларды мемлекеттiк қолдаудың кейбiр мәселелерi туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2012-06-01
approved_by:
- '103017000000'
version_date:
  kaz: 2012-09-19
  rus: 2012-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/66400/kaz/19.09.2012
  rus: https://zan.gov.kz/client/#!/doc/66400/rus/19.09.2012
caused_by:
  code: '67886'
  requisite: Приказ Министра индустрии и новых технологий Республики Казахстан от 19 сентября 2012 года № 325. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 сентября 2012 года № 7947. Утратил силу приказом Заместителя Премьер-Министра Республики Казахстан - Министра индустрии и новых технологий Республики Казахстан от 26 июля 2013 года № 229
  title:
    rus: О внесении изменений в приказ Министра индустрии и новых технологий Республики Казахстан от 1 июня 2012 года № 184 "О некоторых вопросах государственной поддержки инвестиций"
    kaz: '"Инвестицияларды мемлекеттік қолдаудың кейбір мәселелері туралы" Қазақстан Республикасы Индустрия және жаңа технологиялар министрінің 2012 жылғы 1 маусымдағы № 184 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/67886/rus
