act_code: '84967'
requisite: Приказ Министра внутренних дел Республики Казахстан от 7 ноября 2014 года № 783. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 декабря 2014 года № 9942
title:
  rus: Об утверждении разрешительных требований, предъявляемых к профессиональным противопожарным службам
  kaz: Кәсіби өртке қарсы қызметтерге қойылатын рұқсат беру талаптарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2014-11-07
approved_by:
- '103003000000'
version_date:
  kaz: 2018-09-04
  rus: 2018-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/84967/kaz/04.09.2018
  rus: https://zan.gov.kz/client/#!/doc/84967/rus/04.09.2018
caused_by:
  code: '124045'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 13 июля 2018 года № 513. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 августа 2018 года № 17275
  title:
    rus: О внесении изменений в некоторые приказы Министра внутренних дел Республики Казахстан
    kaz: Қазақстан Республикасы Ішкі істер министрінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124045/rus
