act_code: '64718'
requisite: Приказ Министра внутренних дел Республики Казахстан от 29 декабря 2011 года № 690. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 апреля 2012 года № 7558. Утратил силу приказом Министра внутренних дел Республики Казахстан от 8 декабря 2017 года № 823 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Инструкции по организации органами внутренних дел Республики Казахстан борьбы с незаконным оборотом наркотических средств, психотропных веществ и прекурсоров
  kaz: Есірткі құралдарының, психотроптық заттардың және прекурсорлардың заңсыз айналымына қарсы күресте Қазақстан Республикасы ішкі істер органдарын ұйымдастыру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2011-12-29
approved_by:
- '103003000000'
version_date:
  kaz: 2015-04-10
  rus: 2015-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/64718/kaz/10.04.2015
  rus: https://zan.gov.kz/client/#!/doc/64718/rus/10.04.2015
caused_by:
  code: '92372'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 10 апреля 2015 года № 330. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 июля 2015 года № 11693. Утратил силу приказом Министра внутренних дел Республики Казахстан от 8 декабря 2017 года № 823 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в приказ Министра внутренних дел Республики Казахстан от 29 декабря 2011 года № 690 "Об утверждении Инструкции по организации органами внутренних дел Республики Казахстан борьбы с незаконным оборотом наркотических средств, психотропных веществ и прекурсоров"
    kaz: '"Есірткі құралдарының, психотроптық заттардың және прекурсорлардың заңсыз айналымына қарсы күресте Қазақстан Республикасы ішкі істер органдарын ұйымдастыру жөніндегі нұсқаулықты бекіту туралы" Қазақстан Республикасы Ішкі істер Министрінің 2011 жылғы 29 желтоқсандағы № 690 бұйрығына өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/92372/rus
