act_code: '458'
requisite: Приказ Министерства труда и социальной защиты населения Республики Казахстан от 2 апреля 1997 г. N 2 Зарегистрировано в Министерстве юстиции Республики Казахстан 13 мая 1997 г. N 306. Утратил силу - приказом Министра труда и социальной защиты населения Республики Казахстан от 13.02.2002г. № 31-п ~V021782
title:
  rus: Об утверждении Инструкции "О порядке исчисления совокупного дохода"
  kaz: Жиынтық табысты есептеудiң тәртiбi туралы Нұсқаманы бекiту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 1997-04-01
approved_by:
- '103016000000'
version_date:
  rus: 1997-04-01
source:
  rus: https://zan.gov.kz/client/#!/doc/458/rus/01.04.1997
