act_code: '16917'
requisite: Приказ Председателя Налогового комитета Министерства финансов Республики Казахстан от 26 августа 2003 года N 344. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 сентября 2003 года за N 2491. Утратил силу приказом Министра финансов Республики Казахстан от 9 января 2009 года № 5
title:
  rus: Об утверждении форм квитанций и других приравненных к чекам документов строгой отчетности, выдаваемых населению при оказании услуг без применения контрольно-кассовых машин с фискальной памятью
  kaz: Квитанциялардың және фискальдық жады бар бақылау-касса машиналарын қолданбай қызмет көрсету кезінде тұрғындарға берілетін чектерге теңестірілген басқа да қатаң есептілік құжаттарының нысандарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2003-08-25
approved_by:
- '103002002000'
version_date:
  kaz: 2004-09-15
  rus: 2004-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/16917/kaz/15.09.2004
  rus: https://zan.gov.kz/client/#!/doc/16917/rus/15.09.2004
caused_by:
  code: '21540'
  requisite: Приказ Председателя Налогового комитета Министерства финансов Республики Казахстан от 16 сентября 2004 года N 445. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 октября 2004 года N 3134. Утратил силу приказом Министра финансов Республики Казахстан от 9 января 2009 года № 5
  title:
    rus: О внесении изменений в приказ Председателя Налогового комитета Министерства финансов Республики Казахстан от 26 августа 2003 года N 344 "Об утверждении форм квитанций и других приравненных к чекам документов строгой отчетности, выдаваемых населению при оказании услуг без применения контрольно-кассовых машин с фискальной памятью", зарегистрированный за N 2491
    kaz: N 2491 болып тіркелген "Квитанциялардың және фискальдық жады бар бақылау-касса машиналарын қолданбай қызмет көрсету кезінде тұрғындарға берілетін чектерге теңестірілген басқа да қатаң есептілік құжаттарының нысандарын бекіту туралы" Қазақстан Республикасы Қаржы министрлігінің Салық комитеті Төрағасының 2003 жылғы 26 тамыздағы N 344 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/21540/rus
