act_code: '98803'
requisite: Совместный приказ Министра по инвестициям и развитию Республики Казахстан от 29 декабря 2015 года № 1264 и и.о. Министра национальной экономики Республики Казахстан от 31 декабря 2015 года № 842. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 февраля 2016 года № 12991
title:
  rus: Об утверждении критериев оценки степени риска и проверочных листов за соблюдением законодательства Республики Казахстан о туристской деятельности
  kaz: Қазақстан Республикасының туристік қызмет туралы заңнамасының сақталуына тәуекел дәрежесін бағалау өлшемшарттарын және тексеру парақтарын бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПРИК
approved_on: 2015-12-29
approved_by:
- '103033000000'
- '103035000000'
version_date:
  kaz: 2021-08-02
  rus: 2021-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/98803/kaz/02.08.2021
  rus: https://zan.gov.kz/client/#!/doc/98803/rus/02.08.2021
caused_by:
  code: '157572'
  requisite: Совместный приказ и.о. Министра культуры и спорта Республики Казахстан от 2 августа 2021 года № 243 и Министра национальной экономики Республики Казахстан от 2 августа 2021 года № 77. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 августа 2021 года № 23832
  title:
    rus: О внесении изменений в совместный приказ Министра по инвестициям и развитию Республики Казахстан от 29 декабря 2015 года № 1264 и исполняющего обязанности Министра национальной экономики Республики Казахстан от 31 декабря 2015 года № 842 «Об утверждении критериев оценки степени риска и проверочных листов за соблюдением законодательства Республики Казахстан о туристкой деятельности»
    kaz: «Қазақстан Республикасының туристік қызмет туралы заңнамасының сақталуына тәуекел дәрежесін бағалау өлшемшарттарын және тексеру парақтарын бекіту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің 2015 жылғы 29 желтоқсандағы № 1264 және Қазақстан Республикасы Ұлттық экономика министрінің міндетін атқарушының 2015 жылғы 31 желтоқсандағы № 842 бірлескен бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157572/rus
