act_code: '143795'
requisite: Приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 10 июня 2020 года № 138. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 июня 2020 года № 20856
title:
  rus: Об утверждении Правил выдачи административным органом разрешений на импорт на территорию Республики Казахстан, экспорт и (или) реэкспорт с территории Республики Казахстан объектов растительного мира, их частей и дериватов, подпадающих под действие Конвенции о международной торговле видами дикой фауны и флоры, находящимися под угрозой исчезновения
  kaz: Әкімшілік органның құрып кету қаупі төнген жабайы фауна мен флора түрлерімен халықаралық сауда туралы конвенцияның күші қолданылатын өсімдіктер дүниесі объектілерін, олардың бөліктері мен дериваттарын Қазақстан Республикасының аумағына импорттауға, Қазақстан Республикасының аумағынан экспорттауға және (немесе) кері экспорттауға арналған рұқсаттар беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-06-10
approved_by:
- '103047000000'
version_date:
  kaz: 2024-09-05
  rus: 2024-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/143795/kaz/05.09.2024
  rus: https://zan.gov.kz/client/#!/doc/143795/rus/05.09.2024
caused_by:
  code: '198433'
  requisite: Приказ Министра экологии и природных ресурсов Республики Казахстан от 1 июля 2024 года № 149. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 июля 2024 года № 34690
  title:
    rus: О внесении изменений в приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 10 июня 2020 года № 138 «Об утверждении Правил выдачи административным органом разрешений на импорт на территорию Республики Казахстан, экспорт и (или) реэкспорт с территории Республики Казахстан объектов растительного мира, их частей и дериватов, подпадающих под действие Конвенции о международной торговле видами дикой фауны и флоры, находящимися под угрозой исчезновения»
    kaz: «Әкімшілік органның құрып кету қаупі төнген жабайы фауна мен флора түрлерімен халықаралық сауда туралы конвенцияның күші қолданылатын өсімдіктер дүниесі объектілерін, олардың бөліктері мен дериваттарын Қазақстан Республикасының аумағына импорттауға, Қазақстан Республикасының аумағынан экспорттауға және (немесе) кері экспорттауға арналған рұқсаттар беру қағидаларын бекіту туралы» Қазақстан Республикасы Экология, геология және табиғи ресурстар министрінің 2020 жылғы 10 маусымдағы № 138 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198433/rus
