act_code: '174909'
requisite: Приказ Министра обороны Республики Казахстан от 29 ноября 2022 года № 1141. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 декабря 2022 года № 30965
title:
  rus: Об утверждении Правил оказания государственной услуги «Заключение и продление договора найма служебного жилища Вооруженных Сил Республики Казахстан»
  kaz: «Қазақстан Республикасы Қарулы Күштерінің қызметтік баспанасын жалға алу шартын жасасу және ұзарту» мемлекеттік қызметін көрсету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-11-29
approved_by:
- '103008000000'
version_date:
  kaz: 2025-06-12
  rus: 2025-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/174909/kaz/12.06.2025
  rus: https://zan.gov.kz/client/#!/doc/174909/rus/12.06.2025
caused_by:
  code: '211328'
  requisite: Приказ Министра обороны Республики Казахстан от 12 июня 2025 года № 687. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 июня 2025 года № 36287
  title:
    rus: О внесении изменений в некоторые приказы Министра обороны Республики Казахстан
    kaz: Қазақстан Республикасы Қорғаныс министрінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211328/rus
