act_code: '48667'
requisite: Приказ Министра здравоохранения Республики Казахстан от 19 октября 2009 года № 546. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 ноября 2009 года № 5858. Утратил силу приказом Министра национальной экономики Республики Казахстан от 4 июня 2015 года № 420
title:
  rus: Об установлении Правил государственной регистрации и отзыва решения о государственной регистрации продуктов детского питания, пищевых и биологически активных добавок к пище, генетически модифицированных объектов, красителей, средств дезинфекции, дезинсекции и дератизации, материалов и изделий, контактирующих с водой и продуктами питания, химических веществ, отдельных видов продукции и веществ, оказывающих вредное воздействие на здоровье человека
  kaz: Балалардың тамағы өнімдерін, тағамға тағамдық және биологиялық активті қоспаларды, генетикалық түрлендірілген объектілерді, бояғыштарды, дезинфекциялау, дезинсекциялау және дератизациялау құралдарын, сумен және тағам өнімдерімен жанасатын материалдар мен бұйымдарды, химиялық заттарды, адамның денсаулығына зиянды әсер ететін өнімдер мен заттардың жекелеген түрлерін мемлекеттік тіркеу және мемлекеттік тіркеу туралы шешімді кері қайтарып алу ережесін белгілеу туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2009-10-19
approved_by:
- '103010000000'
version_date:
  kaz: 2011-02-15
  rus: 2011-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/48667/kaz/15.02.2011
  rus: https://zan.gov.kz/client/#!/doc/48667/rus/15.02.2011
caused_by:
  code: '58135'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 15 февраля 2011 года № 87. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 марта 2011 года № 6838. Утратил силу приказом Министра национальной экономики Республики Казахстан от 4 июня 2015 года № 420
  title:
    rus: О внесении дополнения в приказ Министра здравоохранения Республики Казахстан от 19 октября 2009 года № 546 "Об установлении Правил государственной регистрации, перерегистрации и отзыва решения о государственной регистрации продуктов детского питания, пищевых и биологически активных добавок к пище, генетически модифицированных объектов, красителей, средств дезинфекции, дезинсекции и дератизации, материалов и изделий, контактирующих с водой и продуктами питания, химических веществ, отдельных видов продукции и веществ, оказывающих вредное воздействие на здоровье человека"
    kaz: '"Балалардың тамағы өнімдерін, тағамға тағамдық және биологиялық активті қоспаларды, генетикалық түрлендірілген объектілерді, бояғыштарды, дезинфекциялау, дезинсекциялау және дератизациялау құралдарын, сумен және тағам өнімдерімен жанасатын материалдар мен бұйымдарды, химиялық заттарды, адамның денсаулығына зиянды әсер ететін өнімдер мен заттардың жекелеген түрлерін мемлекеттік тіркеу, қайта тіркеу және мемлекеттік тіркеу туралы шешімді кері қайтарып алу ережесін белгілеу туралы" Қазақстан Республикасының Денсаулық сақтау министрінің 2009 жылғы 19 қазандағы № 546 бұйрығына толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/58135/rus
