act_code: '22455'
requisite: Приказ Председателя Агентства Республики Казахстан по регулированию естественных монополий от 24 ноября 2004 года № 459-ОД. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 декабря 2004 года № 3302. Утратил силу приказом и.о. Председателя Агентства Республики Казахстан по регулированию естественных монополий от 31 июля 2013 года № 239-ОД (вводится в действие по истечении десяти календарных дней после дня его официального опубликования)
title:
  rus: Об утверждении Правил ведения раздельного учета доходов, затрат и задействованных активов субъектами естественной монополии, оказывающими услуги в сфере аэропортов
  kaz: Әуежайлар саласында қызметтер көрсететін табиғи монополия субъектілерінің табыстарды, шығындар мен іске қосылған активтерді бөлектеп есепке алуды жүргізу ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2004-11-24
approved_by:
- '113000000000'
version_date:
  kaz: 2009-02-13
  rus: 2009-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/22455/kaz/13.02.2009
  rus: https://zan.gov.kz/client/#!/doc/22455/rus/13.02.2009
caused_by:
  code: '44991'
  requisite: Приказ Председателя Агентства Республики Казахстан по регулированию естественных монополий от 13 февраля 2009 года N 42-ОД. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 марта 2009 года N 5595
  title:
    rus: О внесении изменений и дополнений в некоторые приказы уполномоченного органа, осуществляющего руководство в сферах естественных монополий и регулируемых рынках
    kaz: Табиғи монополиялар салаларындағы және реттелетін нарықтардағы басшылықты жүзеге асыратын уәкілетті органның кейбір бұйрықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/44991/rus
