act_code: '114826'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 31 августа 2017 года № 597. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 сентября 2017 года № 15745
title:
  rus: Об утверждении Правил применения поощрения государственных служащих Министерства индустрии и инфраструктурного развития Республики Казахстан
  kaz: Қазақстан Республикасы Индустрия және инфрақұрылымдық даму министрлігінің мемлекеттік қызметшілерін көтермелеуді қолдану қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2017-08-31
approved_by:
- '103035000000'
version_date:
  kaz: 2021-04-02
  rus: 2021-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/114826/kaz/02.04.2021
  rus: https://zan.gov.kz/client/#!/doc/114826/rus/02.04.2021
caused_by:
  code: '156668'
  requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 2 апреля 2021 года № 154. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 апреля 2021 года № 22494
  title:
    rus: О внесении изменений в приказ Министра по инвестициям и развитию Республики Казахстан от 31 августа 2017 года № 597 «Об утверждении Правил применения поощрения государственных служащих Министерства по инвестициям и развитию Республики Казахстан»
    kaz: «Қазақстан Республикасы Инвестициялар және даму министрлігінің мемлекеттік қызметшілерін көтермелеуді қолдану қағидаларын бекіту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің 2017 жылғы 31 тамыздағы № 597 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156668/rus
