act_code: '126904'
requisite: Приказ Министра энергетики Республики Казахстан от 10 декабря 2018 года № 489. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 декабря 2018 года № 17923
title:
  rus: Об утверждении Правил формирования и ведения Реестра групп лиц
  kaz: Тұлғалар тобының тізілімін қалыптастыру және жүргізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-12-10
approved_by:
- '103036000000'
version_date:
  kaz: 2018-12-10
  rus: 2018-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/126904/kaz/10.12.2018
  rus: https://zan.gov.kz/client/#!/doc/126904/rus/10.12.2018
