act_code: '89566'
requisite: Приказ от 27.03.2015 № 262, Министерство национальной экономики Республики Казахстан
title:
  rus: Об утверждении Правил включения и исключения субъектов рынка из Государственного реестра субъектов рынка, занимающих доминирующее или монопольное положение
  kaz: Нарық субъектілерін Үстем немесе монополиялық жағдайға ие нарық субъектілерінің мемлекеттік тізіліміне енгізу және одан шығару қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-03-27
approved_by:
- '103033000000'
version_date:
  kaz: 2015-07-21
  rus: 2015-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/89566/kaz/21.07.2015
  rus: https://zan.gov.kz/client/#!/doc/89566/rus/21.07.2015
caused_by:
  code: '93131'
  requisite: Приказ от 21.07.2015 № 552, Министерство национальной экономики Республики Казахстан. Утратил силу приказом Министра национальной экономики РК от 30.11.2015 № 740
  title:
    rus: О внесении изменения в приказ исполняющего обязанности Министра национальной экономики Республики Казахстан от 27 марта 2015 года № 262 «Об утверждении Правил включения и исключения субъектов рынка из Государственного реестра субъектов рынка, занимающих доминирующее или монопольное положение»
    kaz: «Нарық субъектілерін Үстем немесе монополиялық жағдайға ие нарық субъектілерінің мемлекеттік тізіліміне енгізу және одан шығару қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық экономика Министрі міндетін атқарушысының 2015 жылғы 27 наурыздағы № 262 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93131/rus
