act_code: '64602'
requisite: Приказ и.о. Министра образования и науки Республики Казахстан от 6 апреля 2012 года № 149. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 апреля 2012 года № 7549. Утратил силу приказом и.о. Министра образования и науки Республики Казахстан от 22 мая 2015 года № 318
title:
  rus: О некоторых мерах по реализации международной стипендии "Болашак"
  kaz: '"Болашақ" халықаралық стипендиясын іске асыру жөніндегі кейбір шаралар туралы'
form: ПРИК
type_codes:
- МРП
- ПРИК
approved_on: 2012-04-06
approved_by:
- '103006000000'
version_date:
  kaz: 2012-04-06
  rus: 2012-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/64602/kaz/06.04.2012
  rus: https://zan.gov.kz/client/#!/doc/64602/rus/06.04.2012
