act_code: '96043'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 23 сентября 2015 года № 15-05/844. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 ноября 2015 года № 12332
title:
  rus: Об утверждении норматива запаса по видам пестицидов и Правил его использования
  kaz: Пестицидтердің түрлері бойынша қор нормативін және оны пайдалану қағидаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРАВ
- ПРИК
approved_on: 2015-09-23
approved_by:
- '103012000000'
version_date:
  kaz: 2021-03-17
  rus: 2021-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/96043/kaz/17.03.2021
  rus: https://zan.gov.kz/client/#!/doc/96043/rus/17.03.2021
caused_by:
  code: '153682'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 17 марта 2021 года № 82. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 марта 2021 года № 22359
  title:
    rus: О внесении изменений в некоторые приказы Министра сельского хозяйства Республики Казахстан
    kaz: Қазақстан Республикасы Ауыл шаруашылығы министрінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153682/rus
