act_code: '229382'
requisite: Приказ Министра здравоохранения Республики Казахстан от 21 августа 2026 года № 419
title:
  rus: Об утверждении положений республиканского государственного учреждения «Комитет медицинского контроля Министерства здравоохранения Республики Казахстан» и его территориальных подразделений
  kaz: «Қазақстан Республикасы Денсаулық сақтау министрлігінің Медициналық бақылау комитеті» республикалық мемлекеттік мекемесінің және оның аумақтық бөлімшелерінің ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2026-08-21
approved_by:
- '103010000000'
version_date:
  kaz: 2026-08-21
  rus: 2026-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/229382/kaz/21.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229382/rus/21.08.2026
