act_code: '213914'
requisite: Приказ Министра обороны Республики Казахстан от 28 августа 2025 года № 1173дсп
title:
  rus: Правила обеспечения и содержания территориальных органов территориальных войск Вооруженных Сил Республики Казахстан
  kaz: Қазақстан Республикасы Қарулы Күштері аумақтық әскерлерінің аумақтық органдарын қамтамасыз ету және ұстау қағидалары
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-08-28
approved_by:
- '103008000000'
version_date:
  kaz: 2025-08-28
  rus: 2025-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/213914/kaz/28.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213914/rus/28.08.2025
