act_code: '87523'
requisite: Приказ Министра внутренних дел Республики Казахстан от 8 января 2015 года № 5. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 февраля 2015 года № 10352
title:
  rus: Об утверждении квалификационных требований и перечня документов, подтверждающих соответствие им, для деятельности по разработке, производству, ремонту, торговле, коллекционированию, экспонированию гражданского и служебного оружия и патронов к нему
  kaz: Азаматтық және қызметтік қару мен оның патрондарын әзірлеу, өндіру, жөндеу, сату, коллекцияға жинау, экспонаттау жөніндегі қызметке қойылатын біліктілік талаптары мен оларға сәйкестікті растайтын құжаттар тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
- ТРЕБ
approved_on: 2015-01-08
approved_by:
- '103003000000'
version_date:
  kaz: 2023-09-02
  rus: 2023-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/87523/kaz/02.09.2023
  rus: https://zan.gov.kz/client/#!/doc/87523/rus/02.09.2023
caused_by:
  code: '183449'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 27 июня 2023 года № 515. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 июня 2023 года № 32948
  title:
    rus: О внесении изменений и дополнения в некоторые приказы Министра внутренних дел Республики Казахстан
    kaz: Қазақстан Республикасы Ішкі істер министрінің кейбір бұйрықтарына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183449/rus
