act_code: '91004'
requisite: Приказ Председателя Агентства Республики Казахстан по делам государственной службы и противодействию коррупции от 8 мая 2015 года № 154. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 июня 2015 года № 11377. Утратил силу приказом Председателя Агентства Республики Казахстан по противодействию коррупции (Антикоррупционной службы) от 28 июня 2024 года № 138 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении натуральных норм площадей для специфических помещений органов по делам государственной службы и противодействию коррупции
  kaz: Мемлекеттік қызмет істері және сыбайлас жемқорлыққа қарсы іс-қимыл органдарының ерекше үй-жайларына арналған алаңдардың заттай нормаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2015-05-08
approved_by:
- '133000000000'
version_date:
  kaz: 2015-05-08
  rus: 2015-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/91004/kaz/08.05.2015
  rus: https://zan.gov.kz/client/#!/doc/91004/rus/08.05.2015
