act_code: '142797'
requisite: Приказ Министра образования и науки Республики Казахстан от 11 мая 2020 года № 192. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 мая 2020 года № 20618. Утратил силу приказом Министра образования и науки Республики Казахстан от 12 ноября 2021 года № 561 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил присвоения (подтверждения) квалификационных категорий педагогам
  kaz: Педагогтерге біліктілік санаттарын беру (растау) қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-05-11
approved_by:
- '103006000000'
version_date:
  kaz: 2020-05-11
  rus: 2020-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/142797/kaz/11.05.2020
  rus: https://zan.gov.kz/client/#!/doc/142797/rus/11.05.2020
