act_code: '150007'
requisite: Приказ Министра здравоохранения Республики Казахстан от 15 декабря 2020 года № ҚР ДСМ-270/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 декабря 2020 года № 21802
title:
  rus: Об утверждении правил размещения государственного заказа, приема на обучение и подготовки медицинских кадров в резидентуре
  kaz: Резидентурада мемлекеттік тапсырысты орналастыру, оқуға қабылдау және медицина кадрларын даярлау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-12-15
approved_by:
- '103010000000'
version_date:
  kaz: 2025-08-28
  rus: 2025-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/150007/kaz/28.08.2025
  rus: https://zan.gov.kz/client/#!/doc/150007/rus/28.08.2025
caused_by:
  code: '213805'
  requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 28 августа 2025 года № 85. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 августа 2025 года № 36766
  title:
    rus: О внесении изменений и дополнений в приказ Министра здравоохранения Республики Казахстан от 15 декабря 2020 года № ҚР ДСМ-270/2020 «Об утверждении правил размещения государственного заказа, приема на обучение и подготовки медицинских кадров в резидентуре»
    kaz: «Резидентурада мемлекеттік тапсырысты орналастыру, оқуға қабылдау және медицина кадрларын даярлау қағидаларын бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2020 жылғы 15 желтоқсандағы № ҚР ДСМ-270/2020 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213805/rus
