act_code: '151404'
requisite: Приказ Министра здравоохранения Республики Казахстан от 5 января 2021 года № ҚР ДСМ-1. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 января 2021 года № 22040
title:
  rus: Об утверждении методики осуществления экспертной оценки оптимальных технических характеристик и клинико-технического обоснования медицинских изделий
  kaz: Медициналық бұйымдардың оңтайлы техникалық сипаттамалары мен клиникалық-техникалық негіздемесіне сараптамалық бағалауды жүзеге асыру әдістемесін бекіту туралы
form: ПРИК
type_codes:
- МЕТ
- ПРИК
approved_on: 2021-01-05
approved_by:
- '103010000000'
version_date:
  kaz: 2024-08-01
  rus: 2024-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/151404/kaz/01.08.2024
  rus: https://zan.gov.kz/client/#!/doc/151404/rus/01.08.2024
caused_by:
  code: '199699'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 1 августа 2024 года № 59. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 августа 2024 года № 34882
  title:
    rus: О внесении изменений и дополнений в приказ Министра здравоохранения Республики Казахстан от 5 января 2021 года № ҚР ДСМ-1 «Об утверждении методики осуществления экспертной оценки оптимальных технических характеристик и клинико-технического обоснования медицинских изделий»
    kaz: «Медициналық бұйымдардың оңтайлы техникалық сипаттамалары мен клиникалық-техникалық негіздемесіне сараптамалық бағалауды жүзеге асыру әдістемесін бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2021 жылғы 5 қаңтардағы № ҚР ДСМ-1 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199699/rus
