act_code: '151404'
requisite: Приказ Министра здравоохранения Республики Казахстан от 5 января 2021 года № ҚР ДСМ-1. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 января 2021 года № 22040
title:
  rus: Об утверждении методики осуществления экспертной оценки оптимальных технических характеристик и клинико-технического обоснования медицинских изделий
  kaz: Медициналық бұйымдардың оңтайлы техникалық сипаттамалары мен клиникалық-техникалық негіздемесіне сараптамалық бағалауды жүзеге асыру әдістемесін бекіту туралы
form: ПРИК
type_codes:
- МЕТ
- ПРИК
approved_on: 2021-01-05
approved_by:
- '103010000000'
version_date:
  kaz: 2021-01-05
  rus: 2021-01-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/151404/kaz/05.01.2021
  rus: https://zan.gov.kz/client/#!/doc/151404/rus/05.01.2021
