act_code: '85543'
requisite: Приказ Министра энергетики Республики Казахстан от 31 октября 2014 года № 92. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 декабря 2014 года № 9957
title:
  rus: Об утверждении Правил представления сведений по мониторингу производства, транспортировки (перевозки), хранения, отгрузки и реализации товарного, сжиженного нефтяного и сжиженного природного газа
  kaz: Тауарлық, сұйытылған мұнай және сұйытылған табиғи газды өндіру, тасымалдау (тасу), сақтау, тиеп-жөнелту және өткізу мониторингі бойынша мәліметтер ұсыну қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2014-10-31
approved_by:
- '103036000000'
version_date:
  kaz: 2017-08-10
  rus: 2017-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/85543/kaz/10.08.2017
  rus: https://zan.gov.kz/client/#!/doc/85543/rus/10.08.2017
caused_by:
  code: '114749'
  requisite: Приказ Министра энергетики Республики Казахстан от 10 августа 2017 года № 282. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 сентября 2017 года № 15667
  title:
    rus: О внесении изменений и дополнения в приказ Министра энергетики Республики Казахстан от 31 октября 2014 года № 92 «Об утверждении Правил представления сведений по мониторингу производства, транспортировки (перевозки), хранения и реализации товарного, сжиженного нефтяного и сжиженного природного газа»
    kaz: «Тауарлық, сұйытылған мұнай және сұйытылған табиғи газды өндіру, тасымалдау (тасу), сақтау және өткізу мониторингі бойынша мәліметтер ұсынудың қағидаларын бекіту туралы» Қазақстан Республикасы Энергетика министрінің 2014 жылғы 31 қазандағы № 92 бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/114749/rus
