act_code: '216356'
requisite: Приказ и.о. Министра финансов Республики Казахстан от 31 октября 2025 года № 654. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 октября 2025 года № 37312
title:
  rus: О некоторых вопросах исполнения налогового обязательства при ликвидации, реорганизации и прекращении деятельности налогоплательщиками (налоговыми агентами)
  kaz: Салық төлеушілердің (салық агенттерінің) қызметін тарату, қайта ұйымдастыру және тоқтату кезінде салықтық міндеттемені орындаудың кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-10-31
approved_by:
- '103002000000'
version_date:
  kaz: 2026-02-20
  rus: 2026-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/216356/kaz/20.02.2026
  rus: https://zan.gov.kz/client/#!/doc/216356/rus/20.02.2026
caused_by:
  code: '222326'
  requisite: Приказ Министра финансов Республики Казахстан от 20 февраля 2026 года № 117. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 февраля 2026 года № 38022
  title:
    rus: О внесении изменений и дополнения в приказ исполняющего обязанности Министра финансов Республики Казахстан от 31 октября 2025 года № 654 «О некоторых вопросах исполнения налогового обязательства при ликвидации, реорганизации и прекращении деятельности налогоплательщиками (налоговыми агентами)»
    kaz: «Салық төлеушілердің (салық агенттерінің) қызметін тарату, қайта ұйымдастыру және тоқтату кезінде салықтық міндеттемені орындаудың кейбір мәселелері туралы» Қазақстан Республикасы Қаржы министрінің міндетін атқарушы 2025 жылғы 31 қазандағы № 654 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222326/rus
