act_code: '188071'
requisite: Приказ и.о. Министра науки и высшего образования Республики Казахстан от 6 ноября 2023 года № 563. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 ноября 2023 года № 33613
title:
  rus: Об утверждении Правил базового и программно-целевого финансирования научной и (или) научно-технической деятельности, грантового финансирования научной и (или) научно-технической деятельности и коммерциализации результатов научной и (или) научно-технической деятельности, финансирования научных организаций, осуществляющих фундаментальные научные исследования
  kaz: Ғылыми және (немесе) ғылыми-техникалық қызметті базалық және бағдарламалық-нысаналы қаржыландыру, ғылыми және (немесе) ғылыми-техникалық қызметті гранттық қаржыландыру және ғылыми және (немесе) ғылыми-техникалық қызмет нәтижелерін коммерцияландыру, іргелі ғылыми зерттеулерді жүзеге асыратын ғылыми ұйымдарды қаржыландыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2023-11-06
approved_by:
- '103049000000'
version_date:
  kaz: 2026-04-24
  rus: 2026-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/188071/kaz/24.04.2026
  rus: https://zan.gov.kz/client/#!/doc/188071/rus/24.04.2026
caused_by:
  code: '224619'
  requisite: Приказ Министра науки и высшего образования Республики Казахстан от 24 апреля 2026 года № 213. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 апреля 2026 года № 38555
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра науки и высшего образования Республики Казахстан от 6 ноября 2023 года № 563 «Об утверждении Правил базового и программно-целевого финансирования научной и (или) научно-технической деятельности, грантового финансирования научной и (или) научно-технической деятельности и коммерциализации результатов научной и (или) научно-технической деятельности, финансирования научных организаций, осуществляющих фундаментальные научные исследования»
    kaz: «Ғылыми және (немесе) ғылыми-техникалық қызметті базалық және бағдарламалық-нысаналы қаржыландыру, ғылыми және (немесе) ғылыми-техникалық қызметті гранттық қаржыландыру және ғылыми және (немесе) ғылыми-техникалық қызмет нәтижелерін коммерцияландыру, іргелі ғылыми зерттеулерді жүзеге асыратын ғылыми ұйымдарды қаржыландыру қағидаларын бекіту туралы» Қазақстан Республикасы Ғылым және жоғары білім министрінің міндетін атқарушының 2023 жылғы 6 қарашадағы № 563 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224619/rus
