act_code: '107946'
requisite: Приказ Председателя Агенства Республики Казахстан по делам государственной службы и противодействию коррупции от 21 октября 2016 года № 17. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 ноября 2016 года № 14451. Утратил силу приказом Председателя Агентства Республики Казахстан по противодействию коррупции (Антикоррупционной службы) от 30 октября 2019 года № 272 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Некоторые вопросы прохождения правоохранительной службы в Национальном бюро по противодействию коррупции (Антикоррупционной службе) Агентства Республики Казахстан по делам государственной службы и противодействию коррупции
  kaz: Қазақстан Республикасы Мемлекеттік қызмет істері және сыбайлас жемқорлыққа  қарсы іс-қимыл агенттігінің Сыбайлас жемқорлыққа қарсы іс-қимыл ұлттық бюросында (Сыбайлас жемқорлыққа қарсы қызмет) құқық қорғау қызметін өткерудің кейбір мәселелері
form: ПРИК
type_codes:
- ПРИК
approved_on: 2016-10-21
approved_by:
- '133000000000'
version_date:
  kaz: 2016-10-21
  rus: 2016-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/107946/kaz/21.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107946/rus/21.10.2016
