act_code: '113532'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 29 июня 2017 года № 194. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 июля 2017 года № 15344
title:
  rus: Об утверждении Правил подготовки, переподготовки и повышения квалификации специалистов в области физической культуры и спорта
  kaz: Дене шынықтыру және спорт саласындағы мамандарды даярлау, қайта даярлау мен олардың біліктілігін арттыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2017-06-29
approved_by:
- '103034000000'
version_date:
  kaz: 2025-07-18
  rus: 2025-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/113532/kaz/18.07.2025
  rus: https://zan.gov.kz/client/#!/doc/113532/rus/18.07.2025
caused_by:
  code: '212637'
  requisite: Приказ Министра туризма и спорта Республики Казахстан от 18 июля 2025 года № 136. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 июля 2025 года № 36491
  title:
    rus: О внесении изменений в приказ Министра культуры и спорта Республики Казахстан от 29 июня 2017 года № 194 «Об утверждении Правил подготовки, переподготовки и повышения квалификации кадров в области физической культуры и спорта»
    kaz: «Дене шынықтыру және спорт саласындағы кадрларды даярлау, қайта даярлау мен олардың біліктілігін арттыру қағидаларын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің 2017 жылғы 29 маусымдағы № 194 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212637/rus
