act_code: '146658'
requisite: Приказ Министра здравоохранения Республики Казахстан от 23 сентября 2020 года № ҚР ДСМ-109/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 сентября 2020 года № 21262
title:
  rus: Об утверждении перечня хронических заболеваний, подлежащих динамическому наблюдению
  kaz: Динамикалық байқауға жататын созылмалы аурулардың тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2020-09-23
approved_by:
- '103010000000'
version_date:
  kaz: 2025-08-07
  rus: 2025-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/146658/kaz/07.08.2025
  rus: https://zan.gov.kz/client/#!/doc/146658/rus/07.08.2025
caused_by:
  code: '213443'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 7 августа 2025 года № 517
  title:
    rus: О внесении изменений в приказ Министра здравоохранения Республики Казахстан от 23 сентября 2020 года № ҚР ДСМ-109/2020 «Об утверждении перечня хронических заболеваний, подлежащих динамическому наблюдению»
    kaz: «Динамикалық байқауға жататын созылмалы аурулардың тізбесін бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2020 жылғы 23 қыркүйектегі № ҚР ДСМ-109/2020 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213443/rus
