act_code: '12660'
requisite: Приказ Министра внутренних дел Республики Казахстан от 1 июня 2002 года N 386. Зарегистрирован в Министерстве юстиции Республики Казахстан от 12 июня 2002 года N 1878. Утратил силу приказом Министра внутренних дел Республики Казахстан от 9 марта 2017 года № 166 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Инструкции по организации несения службы, обеспечению охраны подозреваемых и обвиняемых, содержащихся в изоляторах временного содержания
  kaz: Қызмет атқаруды, уақытша ұстау изоляторларында ұсталатын сезіктілер мен айыпталушыларды күзету жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2002-05-31
approved_by:
- '103003000000'
version_date:
  kaz: 2002-05-31
  rus: 2002-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/12660/kaz/31.05.2002
  rus: https://zan.gov.kz/client/#!/doc/12660/rus/31.05.2002
