act_code: '21417'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 2 сентября 2004 года № 470. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 сентября 2004 года № 3111. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 13 февраля 2012 года № 10-1/52
title:
  rus: Об утверждении Инструкции по осуществлению государственного фитосанитарного контроля
  kaz: Мемлекеттік фитосанитарлық бақылауды жүзеге асыру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2004-09-01
approved_by:
- '103012000000'
version_date:
  kaz: 2005-09-06
  rus: 2005-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/21417/kaz/06.09.2005
  rus: https://zan.gov.kz/client/#!/doc/21417/rus/06.09.2005
caused_by:
  code: '25249'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 6 сентября 2005 года № 526. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 сентября 2005 года № 3830. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 13 февраля 2012 года № 10-1/52
  title:
    rus: О внесении изменения в приказ Министра сельского хозяйства Республики Казахстан от 2 сентября 2004 года N 470 "Об утверждении Инструкции по осуществлению государственного фитосанитарного контроля"
    kaz: '"Мемлекеттік фитосанитарлық бақылауды жүзеге асыру жөніндегі нұсқаулықты бекіту туралы" Қазақстан Республикасы Ауыл шаруашылығы министрінің 2004 жылғы 2 қыркүйектегі N 470 бұйрығына өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/25249/rus
