act_code: '144366'
requisite: Приказ и.о. Министра финансов Республики Казахстан от 1 июля 2020 года № 648. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 июля 2020 года № 20916
title:
  rus: Об утверждении Правил проведения пилотного проекта по горизонтальному мониторингу
  kaz: Деңгейлес мониторинг жөніндегі пилоттық жобаны жүргізудің қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-07-01
approved_by:
- '103002000000'
version_date:
  kaz: 2020-07-01
  rus: 2020-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/144366/kaz/01.07.2020
  rus: https://zan.gov.kz/client/#!/doc/144366/rus/01.07.2020
