act_code: '95689'
requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 4 августа 2015 года № 67 ДСП. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 ноября 2015 года № 12294. Утратил силу приказом Председателя Комитета национальной безопасности Республики Казахстан от 8 января 2019 года № 3/қбп
title:
  rus: Об утверждении натуральных норм снабжения полиграфическим оборудованием и расходными материалами Научно-исследовательского института КНБ РК
  kaz: ҚР ҰҚК Ғылыми-зерттеу институтын полиграфиялық құрал-жабдықтар және шаған материалдарымен жабдықтаудың заттай нормаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2015-08-04
approved_by:
- '108000000000'
version_date:
  kaz: 2015-08-04
  rus: 2015-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/95689/kaz/04.08.2015
  rus: https://zan.gov.kz/client/#!/doc/95689/rus/04.08.2015
