act_code: '121344'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 12 января 2018 года № 26. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 апреля 2018 года № 16833. Утратил силу приказом Министра индустрии и инфраструктурного развития Республики Казахстан от 8 сентября 2020 года № 457 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении стандарта государственной услуги «Возмещение затрат на разработку и/или экспертизу комплексного плана индустриально-инновационного проекта»
  kaz: «Индустриялық-инновациялық жобаның кешенді жоспарын әзірлеу және/немесе сараптама жасау шығындарын өтеу» мемлекеттік көрсетілетін қызмет стандартын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2018-01-12
approved_by:
- '103035000000'
version_date:
  kaz: 2019-08-29
  rus: 2019-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/121344/kaz/29.08.2019
  rus: https://zan.gov.kz/client/#!/doc/121344/rus/29.08.2019
caused_by:
  code: '134504'
  requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 29 августа 2019 года № 683. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 сентября 2019 года № 19352. Утратил силу приказом Министра индустрии и инфраструктурного развития Республики Казахстан от 8 сентября 2020 года № 457 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в приказ Министра по инвестициям и развитию Республики Казахстан от 12 января 2018 года № 26 «Об утверждении стандарта государственной услуги «Возмещение затрат на разработку и/или экспертизу комплексного плана индустриально-инновационного проекта»
    kaz: «Индустриялық-инновациялық жобаның кешенді жоспарын әзірлеу және/немесе сараптама жасау шығындарын өтеу» мемлекеттік көрсетілетін қызмет стандартын бекіту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің 2018 жылғы 12 қаңтардағы № 26 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134504/rus
