act_code: '22763'
requisite: Приказ Министра экономики и бюджетного планирования Республики Казахстан от 15 декабря 2004 года № 165. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 января 2005 года № 3361. Утратил силу приказом Министра экономики и бюджетного планирования Республики Казахстан от 22 мая 2009 года № 115
title:
  rus: Об утверждении Правил составления и предоставления отчета по оценке эффективности бюджетных инвестиций, а также сроков и форм предоставления информации, предусматриваемой в рамках осуществления мониторинга реализации бюджетных инвестиций
  kaz: Бюджеттiк инвестициялардың тиiмдiлiгiн бағалау жөнiндегi есептi жасау мен табыс ету ережесiн, сондай-ақ бюджеттiк инвестицияларды iске асыру мониторингiн жүзеге асыру шеңберiнде көзделетiн ақпаратты ұсыну мерзiмдерi мен нысандарын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2004-12-15
approved_by:
- '103005000000'
version_date:
  kaz: 2004-12-15
  rus: 2004-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/22763/kaz/15.12.2004
  rus: https://zan.gov.kz/client/#!/doc/22763/rus/15.12.2004
