act_code: '32'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 3 марта 2003 года N 105. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 апреля 2003 года N 2229. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 28 ноября 2014 года № 7-1/625
title:
  rus: Об утверждении Инструкции по согласованию научно-технической документации, представляемой физическими и юридическими лицами на новые, усовершенствованные ветеринарные препараты, корма и кормовые добавки
  kaz: Об утверждении Инструкции по согласованию научно-технической документации, представляемой физическими и юридическими лицами на новые, усовершенствованные ветеринарные препараты, корма и кормовые добавки
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2003-03-03
approved_by:
- '103012000000'
version_date:
  rus: 2014-11-28
source:
  rus: https://zan.gov.kz/client/#!/doc/32/rus/28.11.2014
caused_by:
  code: '86820'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 28 ноября 2014 года № 7-1/625. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 февраля 2015 года № 10298
  title:
    rus: Об утверждении Правил согласования нормативно-технической документации на новые, усовершенствованные ветеринарные препараты, кормовые добавки
    kaz: Жаңа, жетілдірілген ветеринариялық препараттарға, жемшөп қоспаларына нормативтік-техникалық құжаттаманы келісу қағидаларын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/86820/rus
