act_code: '32'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 3 марта 2003 года N 105. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 апреля 2003 года N 2229. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 28 ноября 2014 года № 7-1/625
title:
  rus: Об утверждении Инструкции по согласованию научно-технической документации, представляемой физическими и юридическими лицами на новые, усовершенствованные ветеринарные препараты, корма и кормовые добавки
  kaz: Об утверждении Инструкции по согласованию научно-технической документации, представляемой физическими и юридическими лицами на новые, усовершенствованные ветеринарные препараты, корма и кормовые добавки
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2003-03-03
approved_by:
- '103012000000'
version_date:
  rus: 2007-10-19
source:
  rus: https://zan.gov.kz/client/#!/doc/32/rus/19.10.2007
caused_by:
  code: '35685'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 19 октября 2007 года N 633. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 ноября 2007 года N 4987. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 28 ноября 2014 года № 7-1/625
  title:
    rus: О внесении дополнений в приказ Заместителя Премьер-Министра Республики Казахстан - Министра сельского хозяйства Республики Казахстан от 3 марта 2003 года N 105 "Об утверждении инструкции по согласованию научно-технической документации, представляемой физическими и юридическими лицами на новые, усовершенствованные ветеринарные препараты"
    kaz: Қазақстан Республикасы Премьер-Министрінің орынбасары - Ауыл шаруашылығы Министрінің 2003 жылы 3 наурыздағы N 105 "Жеке және заңды тұлалармен ұсынылған жаңа, жетілдірілген ветеринариялық препараттардың ғылыми-техникалық құжаттарына келісім Нұсқауышын бекіту туралы" бұйрығына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/35685/rus
