act_code: '124623'
requisite: Приказ и.о. Министра образования и науки Республики Казахстан от 14 сентября 2018 года № 464. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 сентября 2018 года № 17379
title:
  rus: Об утверждении Правил размещения государственного заказа на обеспечение студентов технического и профессионального, послесреднего образования местами в общежитиях
  kaz: Техникалық және кәсіптік, орта білімнен кейінгі білім беру студенттерін жатақханалардағы орындармен қамтамасыз етуге мемлекеттік тапсырысты орналастыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-09-14
approved_by:
- '103006000000'
version_date:
  kaz: 2026-04-07
  rus: 2026-04-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/124623/kaz/07.04.2026
  rus: https://zan.gov.kz/client/#!/doc/124623/rus/07.04.2026
caused_by:
  code: '223775'
  requisite: Приказ Министра просвещения Республики Казахстан от 7 апреля 2026 года № 79-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 апреля 2026 года № 38367
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра образования и науки Республики Казахстан от 14 сентября 2018 года № 464 «Об утверждении Правил размещения государственного заказа на обеспечение студентов технического и профессионального, послесреднего образования местами в общежитиях» и в приказ Министра просвещения Республики Казахстан от 31 августа 2022 года № 385 «Об утверждении Типовых правил деятельности организаций образования соответствующих типов и видов, за исключением организаций высшего и послевузовского образования»
    kaz: «Техникалық және кәсіптік, орта білімнен кейінгі білім беру студенттерін жатақханалардағы орындармен қамтамасыз етуге мемлекеттік тапсырысты орналастыру қағидаларын бекіту туралы» Қазақстан Республикасы Білім және ғылым министрінің міндетін атқарушының 2018 жылғы 14 қыркүйектегі № 464 бұйрығына және «Жоғары және жоғары оқу орнынан кейінгі білім беру ұйымдарын қоспағанда, тиісті типтердегі және түрлердегі білім беру ұйымдары қызметінің үлгілік қағидаларын бекіту туралы» Қазақстан Республикасы Оқу-ағарту министрінің 2022 жылғы 31 тамыздағы № 385 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223775/rus
