act_code: '226317'
requisite: Приказ Министра финансов Республики Казахстан от 10 июня 2026 года № 390
title:
  rus: Об утверждении цен на услуги по использованию (доступу) веб-портала государственных закупок, реализуемые акционерным обществом  «Центр электронных финансов»
  kaz: «Электрондық қаржы орталығы» акционерлік қоғамы іске асыратын мемлекеттік сатып алу веб-порталын пайдалану (қол жеткізу) қызметтерінің бағаларын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2026-06-10
approved_by:
- '103002000000'
version_date:
  kaz: 2026-06-10
  rus: 2026-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/226317/kaz/10.06.2026
  rus: https://zan.gov.kz/client/#!/doc/226317/rus/10.06.2026
