act_code: '11763'
requisite: Приказ Министра юстиции Республики Казахстан от 3 апреля 2002 года № 48.  Зарегистрирован в Министерстве юстиции Республики Казахстан 4 апреля 2002 года № 1813. Утратил силу приказом и.о. Министра юстиции Республики Казахстан от 8 января 2013 года № 6
title:
  rus: Об утверждении Инструкции по проведению проверок государственных органов Республики Казахстан органами юстиции по соблюдению законодательства, регулирующего издание, применение, государственную регистрацию и опубликование нормативных правовых актов
  kaz: Әдiлет органдарының Қазақcтан Республикасының мемлекеттiк органдарын нормативтiк құқықтық актiлердi шығаруды, қолдануды, мемлекеттiк тiркеу мен жариялауды реттейтiн заңнаманы сақтау бойынша тексерулердi жүргiзу жөнiндегi нұсқаулықты бекiту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2002-04-02
approved_by:
- '103001000000'
version_date:
  kaz: 2010-04-13
  rus: 2010-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/11763/kaz/13.04.2010
  rus: https://zan.gov.kz/client/#!/doc/11763/rus/13.04.2010
caused_by:
  code: '51910'
  requisite: Приказ Министра юстиции Республики Казахстан от 13 апреля 2010 года № 113. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 апреля 2010 года № 6177. Утратил силу приказом и.о. Министра юстиции Республики Казахстан от 8 января 2013 года № 6
  title:
    rus: О внесении изменений и дополнений в приказ Министра юстиции Республики Казахстан от 3 апреля 2002 года № 48 "Об утверждении Инструкции по проведению проверок государственных органов Республики Казахстан органами юстиции по соблюдению законодательства, регулирующего издание, применение, государственную регистрацию и опубликование нормативных правовых актов"
    kaz: Қазақстан Республикасы Әділет министрінің 2002 жылғы 3 сәуірдегі № 48 "Әдiлет органдарының Қазақcтан Республикасының мемлекеттiк органдарын нормативтiк құқықтық актiлердi шығаруды, қолдануды, мемлекеттiк тiркеу мен жариялауды реттейтiн заңнаманы сақтау бойынша тексерулердi жүргiзу жөнiндегi нұсқаулықты бекiту туралы" бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/51910/rus
