act_code: '74045'
requisite: Приказ Министра образования и науки Республики Казахстан от 19 июля 2013 года № 289. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 августа 2013 года № 8621. Утратил силу приказом и.о. Министра образования и науки Республики Казахстан от 29 декабря 2021 года № 614 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении типовых правил деятельности видов специализированных организаций образования
  kaz: Мамандандырылған білім беру ұйымдарының түрлері қызметінің үлгілік қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2013-07-19
approved_by:
- '103006000000'
version_date:
  kaz: 2013-07-19
  rus: 2013-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/74045/kaz/19.07.2013
  rus: https://zan.gov.kz/client/#!/doc/74045/rus/19.07.2013
