act_code: '189582'
requisite: Приказ Министра просвещения Республики Казахстан от 1 декабря 2023 года № 355
title:
  rus: Об утверждении государственного образовательного заказа на подготовку кадров с техническим и профессиональным, послесредним образованием в организациях образования, финансируемых из республиканского бюджета (за исключением организаций образования, осуществляющих подготовку специалистов для Вооруженных Сил, других войск и воинских формирований, а также специальных государственных органов), с учетом потребностей рынка труда на 2023 – 2024 учебный год
  kaz: Еңбек нарығының қажеттіліктерін ескере отырып, республикалық бюджеттен қаржыландырылатын білім беру ұйымдарында (Қарулы Күштер, басқа да әскерлер мен әскери құралымдар, сондай-ақ арнаулы мемлекеттік органдар үшін мамандар даярлауды жүзеге асыратын білім беру ұйымдарын қоспағанда), техникалық және кәсіптік, орта білімнен кейінгі білімі бар кадрларды даярлауға 2023 – 2024 оқу жылына арналған мемлекеттік білім беру тапсырысын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2023-12-01
approved_by:
- '103048000000'
version_date:
  kaz: 2023-12-01
  rus: 2023-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/189582/kaz/01.12.2023
  rus: https://zan.gov.kz/client/#!/doc/189582/rus/01.12.2023
