act_code: '119877'
requisite: Приказ Министра финансов Республики Казахстан от 15 марта 2018 года № 364. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 марта 2018 года № 16631
title:
  rus: Об утверждении Перечня отдельных таможенных операций, Правил и мест совершения отдельных таможенных операций, а также случаев совершения отдельных таможенных операций органами государственных доходов вне места нахождения и (или) вне времени работы органов государственных доходов
  kaz: Жекелеген кедендік операциялардың тізбесін, Жекелеген кедендік операцияларды жасау қағидалары мен орындарын, сондай-ақ мемлекеттік кірістер органдары жекелеген кедендік операцияларды мемлекеттік кірістер органдары орналасқан орыннан тыс және (немесе) жұмыс уақытынан тыс жасау жағдайларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
- ПРЧ
approved_on: 2018-03-15
approved_by:
- '103002000000'
version_date:
  kaz: 2018-03-15
  rus: 2018-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/119877/kaz/15.03.2018
  rus: https://zan.gov.kz/client/#!/doc/119877/rus/15.03.2018
