act_code: '50803'
requisite: Совместный приказ Министра финансов Республики Казахстан от 3 февраля 2010 года № 37 и Министра экономики и бюджетного планирования Республики Казахстан от 10 февраля 2010 года № 45. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 февраля 2010 года № 6065. Утратил силу совместным приказом Министра финансов Республики Казахстан от 30 ноября 2010 года № 601 и Министра экономического развития и торговли Республики Казахстан от 17 января 2011 года № 8
title:
  rus: Об утверждении формы проверочного листа по проверкам проводимым таможенными органами
  kaz: Кеден органдары жүргізетін тексерулер бойынша тексеру парағының нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2010-02-03
approved_by:
- '103002000000'
- '103005000000'
version_date:
  kaz: 2010-02-03
  rus: 2010-02-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/50803/kaz/03.02.2010
  rus: https://zan.gov.kz/client/#!/doc/50803/rus/03.02.2010
