act_code: '156209'
requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 19 мая 2021 года № 56/қбп. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 мая 2021 года № 22820
title:
  rus: Об утверждении Правил содержания и применения лошадей в Пограничной службе Комитета национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасы Ұлттық қауіпсіздік комитетінің Шекара қызметінде жылқыларды ұстау және пайдалану қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2021-05-19
approved_by:
- '108000000000'
version_date:
  kaz: 2021-05-19
  rus: 2021-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/156209/kaz/19.05.2021
  rus: https://zan.gov.kz/client/#!/doc/156209/rus/19.05.2021
