act_code: '208634'
requisite: Совместный приказ Министра просвещения Республики Казахстан от 31 марта 2025 года № 57 и Министра труда и социальной защиты населения Республики Казахстан от 31 марта 2025 года № 96. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 марта 2025 года № 35900
title:
  rus: Об утверждении правил назначения на должности, освобождения от должностей первых руководителей и педагогов государственных организаций образования
  kaz: Мемлекеттік білім беру ұйымдарының бірінші басшылары мен педагогтерін лауазымға тағайындау, лауазымнан босату қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2025-03-31
approved_by:
- '103016000000'
- '103048000000'
version_date:
  kaz: 2025-03-31
  rus: 2025-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/208634/kaz/31.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208634/rus/31.03.2025
