act_code: '130853'
requisite: Приказ Первого заместителя Премьер-Министра Республики Казахстан – Министра финансов Республики Казахстан от 22 апреля 2019 года № 370. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 апреля 2019 года № 18583. Утратил силу приказом Министра финансов Республики Казахстан от 28 октября 2025 года № 629 (вводится в действие с 1 января 2026 года)
title:
  rus: Об утверждении Правил выписки счета-фактуры в электронной форме в информационной системе электронных счетов-фактур и его формы
  kaz: Электрондық шот-фактуралардың ақпараттық жүйесінде шот-фактураны электронды нысанда жазып беру қағидаларын және оның нысандарын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2019-04-22
approved_by:
- '103002000000'
version_date:
  kaz: 2024-09-11
  rus: 2024-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/130853/kaz/11.09.2024
  rus: https://zan.gov.kz/client/#!/doc/130853/rus/11.09.2024
caused_by:
  code: '200665'
repealed_on: 2026-01-01
repealed_by:
  code: '216146'
  requisite: Приказ Министра финансов Республики Казахстан от 28 октября 2025 года № 629. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 октября 2025 года № 37241
  title:
    rus: Об утверждении Правил выписки счета-фактуры и его формы
    kaz: Шот-фактураны жазып беру қағидаларын және оның нысанын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/216146/rus
