act_code: '86967'
requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 31 декабря 2014 года № 437ДСП. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 февраля 2015 года № 10328
title:
  rus: Об утверждении Правил проведения военно-врачебной экспертизы в специальных государственных органах Республики Казахстан и Положения об органах военно-врачебной экспертизы органов национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасының ұлттық қауіпсіздік органдаранда, сыртқы барлау саласындағы уәкілетті органдарында әскери-дәрігерлік сараптаманы жүргізу қағидаларын және Қазақстан Республикасы ұлттық қауіпсіздік органдарының әскери-дәрігерлік сараптама органдары туралы ережені бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2014-12-31
approved_by:
- '108000000000'
version_date:
  kaz: 2016-03-29
  rus: 2016-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/86967/kaz/29.03.2016
  rus: https://zan.gov.kz/client/#!/doc/86967/rus/29.03.2016
caused_by:
  code: '101857'
  requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 29 марта 2016 года № 30 ДСП. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 апреля 2016 года № 13669
  title:
    rus: О внесении изменений в приказ Председателя Комитета национальной безопасности Республики Казахстан от 31 декабря 2014 года № 437/ДСП «Об утверждении Правил проведения военно-врачебной экспертизы в специальных государственных органах Республики Казахстан и Положения об органах военно-врачебной экспертизы органов национальной безопасности Республики Казахстан»
    kaz: «Қазақстан Республикасының арнаулы мемлекеттік органдарында әскери-дәрігерлік сараптаманы жүргізу қағидаларын және Қазақстан Республикасы ұлттық қауіпсіздік органдарының әскери-дәрігерлік сараптама органдары туралы ережені бекіту туралы» Қазақстан Республикасы Ұлттық қауіпсіздік комитеті Төрағасының 2014 жылғы 31 желтоқсандағы № 437/ҚБП бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101857/rus
