act_code: '200149'
requisite: Приказ и.о. Министра труда и социальной защиты населения Республики Казахстан от 26 августа 2024 года № 331
title:
  rus: Об утверждении межотраслевых норм времени на работы по переводу с русского языка на государственный язык и с государственного языка на русский язык документов
  kaz: Құжаттарды орыс тілінен мемлекеттік тілге және мемлекеттік тілден орыс тіліне аудару жұмыстарына кететін уақыттың салааралық нормаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2024-08-26
approved_by:
- '103016000000'
version_date:
  kaz: 2024-08-26
  rus: 2024-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/200149/kaz/26.08.2024
  rus: https://zan.gov.kz/client/#!/doc/200149/rus/26.08.2024
