act_code: '147949'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 28 октября 2020 года № 416. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 октября 2020 года № 21542
title:
  rus: Об утверждении формы сообщения о случаях профессиональных заболеваний и (или) отравлений, связанных с выполнением работником своих трудовых (служебных) обязанностей либо иных действий по собственной инициативе в интересах работодателя
  kaz: Жұмыскердің өз еңбек (қызметтік) міндеттерін не жұмыс берушінің мүддесі үшін өз бастамасы бойынша өзге де әрекеттерді орындауымен байланысты кәсіптік аурулар және (немесе) улану оқиғалары туралы хабарлау нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2020-10-28
approved_by:
- '103016000000'
version_date:
  kaz: 2020-10-28
  rus: 2020-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/147949/kaz/28.10.2020
  rus: https://zan.gov.kz/client/#!/doc/147949/rus/28.10.2020
