act_code: '54687'
requisite: Приказ Председателя Агентства Республики Казахстан по статистике от 9 июля 2010 года № 174. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 сентября 2010 года № 6460
title:
  rus: Об утверждении Правил утверждения статистических форм для проведения общегосударственных и ведомственных статистических наблюдений, инструкций по их заполнению
  kaz: Жалпымемлекеттік және ведомстволық статистикалық байқаулар жүргізу үшін статистикалық нысандарды, оларды толтыру жөніндегі нұсқаулықтарды бекіту қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2010-07-09
approved_by:
- '119000000000'
version_date:
  kaz: 2010-07-09
  rus: 2010-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/54687/kaz/09.07.2010
  rus: https://zan.gov.kz/client/#!/doc/54687/rus/09.07.2010
