act_code: '151495'
requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 24 декабря 2020 года № ҚР ДСМ-324/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 декабря 2020 года № 21910
title:
  rus: Об утверждении правил формирования перечня закупа лекарственных средств и медицинских изделий в рамках гарантированного объема бесплатной медицинской помощи и (или) в системе обязательного социального медицинского страхования
  kaz: Тегін медициналық көмектің кепілдік берілген көлемі шеңберінде және (немесе) міндетті әлеуметтік медициналық сақтандыру жүйесінде дәрілік заттар мен медициналық бұйымдарды сатып алу тізбесін қалыптастыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-12-24
approved_by:
- '103010000000'
version_date:
  kaz: 2021-12-31
  rus: 2021-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/151495/kaz/31.12.2021
  rus: https://zan.gov.kz/client/#!/doc/151495/rus/31.12.2021
caused_by:
  code: '163000'
  requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 31 декабря 2021 года № ҚР ДСМ-142. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 января 2022 года № 26391
  title:
    rus: О внесении изменений в некоторые приказы Министерства здравоохранения Республики Казахстан
    kaz: Қазақстан Республикасы Денсаулық сақтау министрлігінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/163000/rus
