act_code: '198932'
requisite: Приказ и.о. Министра промышленности и строительства Республики Казахстан от 19 июля 2024 года № 270. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 июля 2024 года № 34774
title:
  rus: Об утверждении Правил оказания государственной услуги «Присвоение/упразднение адреса объекта недвижимости
  kaz: «Жылжымайтын мүлік объектісінің мекенжайын беру/жою» мемлекеттік қызметті көрсету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2024-07-19
approved_by:
- '103052000000'
version_date:
  kaz: 2024-07-19
  rus: 2024-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/198932/kaz/19.07.2024
  rus: https://zan.gov.kz/client/#!/doc/198932/rus/19.07.2024
