act_code: '167497'
requisite: Приказ Министра информации и общественного развития Республики Казахстан от 3 мая 2022 года № 134. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 мая 2022 года № 27955
title:
  rus: Об утверждении Правил избрания общественного медиатора
  kaz: Қоғамдық медиаторды сайлау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-05-03
approved_by:
- '103043000000'
version_date:
  kaz: 2022-05-03
  rus: 2022-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/167497/kaz/03.05.2022
  rus: https://zan.gov.kz/client/#!/doc/167497/rus/03.05.2022
