act_code: '183485'
requisite: Приказ Министра юстиции Республики Казахстан от 29 июня 2023 года № 428. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 июня 2023 года № 32951
title:
  rus: Об утверждении требований к защите свидетельства о рождении
  kaz: Туу туралы куәлікті қорғауға қойылатын талаптарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2023-06-29
approved_by:
- '103001000000'
version_date:
  kaz: 2024-11-06
  rus: 2024-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/183485/kaz/06.11.2024
  rus: https://zan.gov.kz/client/#!/doc/183485/rus/06.11.2024
caused_by:
  code: '202418'
  requisite: Приказ Министра юстиции Республики Казахстан от 6 ноября 2024 года № 922. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 ноября 2024 года № 35341
  title:
    rus: О внесении изменения в приказ Министра юстиции Республики Казахстан от 29 июня 2023 года № 428 «Об утверждении требований к защите свидетельства о рождении»
    kaz: «Туу туралы куәлікті қорғауға қойылатын талаптарды бекіту туралы» Қазақстан Республикасы Әділет министрінің 2023 жылғы 29 маусымдағы № 428 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202418/rus
