act_code: '35621'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 10 октября 2007 года № 604. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 ноября 2007 года № 4983. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 17 января 2012 года № 10-1/18
title:
  rus: Об утверждении перечня и форм документов учета, сроков представления отчетности по вопросам ведения мониторинга хлопкового рынка
  kaz: Мақта нарығының мониторингін жүргізу жөніндегі мәселелері бойынша есеп жүргізу құжаттарының тізбесі мен нысандарын, есеп беру мерзімдерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2007-10-10
approved_by:
- '103012000000'
version_date:
  kaz: 2007-10-10
  rus: 2007-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/35621/kaz/10.10.2007
  rus: https://zan.gov.kz/client/#!/doc/35621/rus/10.10.2007
