act_code: '200640'
requisite: Приказ Руководителя Бюро национальной статистики Агентства по стратегическому планированию и реформам Республики Казахстан от 29 августа 2024 года № 1
title:
  rus: Об утверждении цен на товары (работы, услуги), производимые и (или) реализуемые субъектом государственной монополии в области государственной статистики
  kaz: Мемлекеттік статистика саласындағы мемлекеттік монополия субъектісі өндіретін және (немесе) өткізетін тауарлардың (жұмыстардың, көрсетілетін қызметтердің) бағаларын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2024-08-29
approved_by:
- '136001000000'
version_date:
  kaz: 2024-08-29
  rus: 2024-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/200640/kaz/29.08.2024
  rus: https://zan.gov.kz/client/#!/doc/200640/rus/29.08.2024
