act_code: '48581'
requisite: Приказ Министра здравоохранения Республики Казахстан от 19 октября 2009 года № 542. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 ноября 2009 года № 5853. Утратил силу приказом Министра здравоохранения Республики Казахстан от 6 июня 2012 года № 394
title:
  rus: Об утверждении Правил оказания восстановительного лечения и медицинской реабилитации
  kaz: Қалпына келтіру емін көрсету және медициналық оңалту ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2009-10-19
approved_by:
- '103010000000'
version_date:
  kaz: 2010-12-09
  rus: 2010-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/48581/kaz/09.12.2010
  rus: https://zan.gov.kz/client/#!/doc/48581/rus/09.12.2010
caused_by:
  code: '56187'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 9 декабря 2010 года № 954. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 декабря 2010 года № 6696. Утратил силу приказом Министра здравоохранения Республики Казахстан от 6 июня 2012 года № 394
  title:
    rus: О внесении дополнений и изменений в приказ Министра здравоохранения Республики Казахстан от 19 октября 2009 года № 542 "Об утверждении Правил оказания восстановительного лечения и медицинской реабилитации"
    kaz: '"Қалпына келтіру емін көрсету және медициналық оңалту ережесін бекіту туралы" Қазақстан Республикасы Денсаулық сақтау министрінің 2009 жылғы 19 қазандағы № 542 бұйрығына толықтырулар мен өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/56187/rus
