act_code: '45580'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 31 марта 2009 года № 186. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 апреля 2009 года № 5645. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 17 января 2012 года № 10-1/18
title:
  rus: Об утверждении критериев безопасности водохозяйственных систем и сооружений
  kaz: Су шаруашылығы жүйелері мен құрылыстарының қауіпсіздік өлшемдерін бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПОЛ
- ПРИК
approved_on: 2009-03-31
approved_by:
- '103012000000'
version_date:
  kaz: 2009-03-31
  rus: 2009-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/45580/kaz/31.03.2009
  rus: https://zan.gov.kz/client/#!/doc/45580/rus/31.03.2009
