act_code: '105071'
requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 24 июня 2016 года № 54. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 июля 2016 года № 13999. Утратил силу приказом Председателя Комитета национальной безопасности Республики Казахстан от 13 мая 2025 года № 49/қе (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении нагрудных знаков Пограничной академии Комитета национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасы Ұлттық қауіпсіздік комитеті Шекара академиясының кеуде белгілерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2016-06-24
approved_by:
- '108000000000'
version_date:
  kaz: 2021-04-14
  rus: 2021-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/105071/kaz/14.04.2021
  rus: https://zan.gov.kz/client/#!/doc/105071/rus/14.04.2021
caused_by:
  code: '154835'
  requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 14 апреля 2021 года № 37/қе. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 апреля 2021 года № 22564. Утратил силу приказом Председателя Комитета национальной безопасности Республики Казахстан от 13 мая 2025 года № 49/қе (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Председателя Комитета национальной безопасности Республики Казахстан от 24 июня 2016 года № 54 «Об утверждении нагрудных знаков Академии Пограничной службы Комитета национальной безопасности Республики Казахстан»
    kaz: «Қазақстан Республикасы Ұлттық қауіпсіздік комитеті Шекара қызметі академиясының кеуде белгілерін бекіту туралы» Қазақстан Республикасы Ұлттық қауіпсіздік комитеті Төрағасының 2016 жылғы 24 маусымдағы № 54 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154835/rus
