act_code: '225161'
requisite: Приказ Руководителя Судебной администрации Республики Казахстан от 30 апреля 2026 года № 6001-26-7-6/120
title:
  rus: Об утверждении Перечня персональных данных, необходимых и достаточных для выполнения осуществляемых задач судебными органами
  kaz: Сот органдары жүзеге асыратын міндеттерді орындау үшін қажетті және жеткілікті дербес деректердің тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2026-04-30
approved_by:
- '105002000000'
version_date:
  kaz: 2026-04-30
  rus: 2026-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/225161/kaz/30.04.2026
  rus: https://zan.gov.kz/client/#!/doc/225161/rus/30.04.2026
