act_code: '201579'
requisite: Приказ Министра транспорта Республики Казахстан от 27 июня 2024 года № 224. Отменен приказом и.о. Министра транспорта Республики Казахстан от 12 ноября 2025 года № 374 (вводится в действие со дня его подписания)
title:
  rus: Об утверждении Концепции развития железнодорожного транспорта Республики Казахстан до 2029 года
  kaz: Қазақстан Республикасының теміржол көлігін дамытудың 2029 жылға дейінгі тұжырымдасын бекіту туралы
form: ПРИК
type_codes:
- КОНЦ
- ПРИК
approved_on: 2024-06-27
approved_by:
- '103051000000'
version_date:
  kaz: 2024-06-27
  rus: 2024-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/201579/kaz/27.06.2024
  rus: https://zan.gov.kz/client/#!/doc/201579/rus/27.06.2024
