act_code: '195547'
requisite: Приказ Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 9 апреля 2024 года № 214/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 апреля 2024 года № 34250
title:
  rus: Об утверждении требований к субъекту предпринимательства для заключения партнерского соглашения
  kaz: Әріптестік келісім жасасу үшін кәсіпкерлік субъектісіне қойылатын талаптарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2024-04-09
approved_by:
- '103045000000'
version_date:
  kaz: 2024-04-09
  rus: 2024-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/195547/kaz/09.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195547/rus/09.04.2024
