act_code: '14287'
requisite: Приказ Министра образования и науки Республики Казахстан от 10 января 2003 года № 16. Зарегистрирован в  Министерстве юстиции Республики Казахстан 29 января 2003 года № 2141. Утратил силу приказом Министра образования и науки Республики Казахстан от 31 марта 2011 года № 127
title:
  rus: Об утверждении Правил присуждения ученых степеней
  kaz: Ғылыми дәрежелер беру ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2003-01-10
approved_by:
- '103006000000'
version_date:
  kaz: 2004-06-08
  rus: 2004-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/14287/kaz/08.06.2004
  rus: https://zan.gov.kz/client/#!/doc/14287/rus/08.06.2004
caused_by:
  code: '20234'
  requisite: Приказ Министра образования и науки Республики Казахстан от 9 июня 2004 года № 535. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 июня 2004 года № 2906. Утратил силу приказом Министра образования и науки Республики Казахстан от 31 марта 2011 года № 127
  title:
    rus: О внесении изменений и дополнений в приказ Министра образования и науки Республики Казахстан от 10 января 2003 года № 16 "Об утверждении Правил присуждения ученых степеней", зарегистрированный за № 2141
    kaz: N 2141 тіркелген "Ғылыми дәрежелер беру ережелерін бекіту туралы" Қазақстан Республикасы Білім және ғылым министрінің 2003 жылғы 10 қаңтардағы N 16 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/20234/rus
