act_code: '149760'
requisite: Приказ Министра здравоохранения Республики Казахстан от 11 декабря 2020 года № ҚР ДСМ-251/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 декабря 2020 года № 21770
title:
  rus: Об утверждении правил осуществления деятельности банка тканей
  kaz: Тіндер банкінің қызметін жүзеге асыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-12-11
approved_by:
- '103010000000'
version_date:
  kaz: 2021-07-30
  rus: 2021-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/149760/kaz/30.07.2021
  rus: https://zan.gov.kz/client/#!/doc/149760/rus/30.07.2021
caused_by:
  code: '157576'
  requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 30 июля 2021 года № ҚР ДСМ-71. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 августа 2021 года № 23826
  title:
    rus: О внесении изменений в приказ Министра здравоохранения Республики Казахстан от 11 декабря 2020 года № ҚР ДСМ-251/2020 «Об утверждении правил осуществления деятельности банка тканей»
    kaz: «Тіндер банкінің қызметін жүзеге асыру қағидаларын бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2020 жылғы 11 желтоқсандағы № ҚР ДСМ-251/2020 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157576/rus
