act_code: '108383'
requisite: Приказ Председателя Комитета по водным ресурсам Министерства сельского хозяйства Республики Казахстан от 15 декабря 2016 года № 175. Отменен приказом Председателя Комитета по водным ресурсам Министерства экологии, геологии и природных ресурсов Республики Казахстан от 13 августа 2019 года № 170
title:
  rus: '"Об утверждении положений бассейновых инспекций по регулированию использования и охране водных ресурсов Комитета по водным ресурсам Министерства сельского хозяйства Республики Казахстан"'
  kaz: '"Қазақстан Республикасы Ауыл шаруашылығы министрлігі Су ресурстары комитетінің Су ресурстарын пайдалануды реттеу және қорғау жөніндегі бассейндік инспекцияларының ережелерін бекіту туралы"'
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2016-12-15
approved_by:
- '103012002000'
version_date:
  kaz: 2016-12-15
  rus: 2016-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/108383/kaz/15.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108383/rus/15.12.2016
