act_code: '24325'
requisite: Приказ Министра финансов Республики Казахстан от 28 апреля 2005 года № 162. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 июня 2005 года № 3659. Утратило силу - приказом Министра финансов Республики Казахстан от 25 апреля 2007 года № 143
title:
  rus: Об утверждении перечня расходов по экономической классификации расходов, требующих регистрации заключенных договоров
  kaz: Жасалған шарттарды тіркеуді талап ететін шығыстардың экономикалық сыныптамасы бойынша шығыстардың тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2005-04-28
approved_by:
- '103002000000'
version_date:
  kaz: 2006-01-28
  rus: 2006-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/24325/kaz/28.01.2006
  rus: https://zan.gov.kz/client/#!/doc/24325/rus/28.01.2006
caused_by:
  code: '26570'
  requisite: Приказ Министра финансов Республики Казахстан от 28 января 2006 года № 34. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 февраля 2006 года № 4081
  title:
    rus: О внесении изменений и дополнений в приказ Министра финансов Республики Казахстан от 28 апреля 2005 года № 162 "Об утверждении перечня расходов по экономической классификации расходов, требующих регистрации заключенных договоров"
    kaz: '"Жасалған шарттарды тiркеудi талап ететiн шығыстардың экономикалық сыныптамасы бойынша шығыстардың тiзбесiн бекiту туралы" Қазақстан Республикасы Қаржы министрiнiң 2005 жылғы 28 сәуiрдегi № 162 бұйрығына өзгерiстер мен толықтырулар енгiзу туралы'
  link: https://zan.gov.kz/client/#!/doc/26570/rus
