act_code: '74440'
requisite: Приказ Министра здравоохранения Республики Казахстан от 29 августа 2013 года № 494. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 сентября 2013 года № 8688. Утратил силу приказом Министра здравоохранения Республики Казахстан от 27 октября 2017 года № 795 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня видов судебных экспертиз в области здравоохранения
  kaz: Денсаулық сақтау саласындағы сот сараптамалары түрлерінің тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2013-08-29
approved_by:
- '103010000000'
version_date:
  kaz: 2013-08-29
  rus: 2013-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/74440/kaz/29.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74440/rus/29.08.2013
