act_code: '94572'
requisite: Приказ Министра здравоохранения и социального развития Республики Казахстан от 14 сентября 2015 года № 713. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 октября 2015 года № 12169. Утратил силу приказом Министра здравоохранения Республики Казахстан от 17 сентября 2020 года № ҚР ДСМ-104/2020 (вводится в действие по истечении десяти календарных дней со дня первого официального опубликования)
title:
  rus: Об утверждении Правил оптовой и розничной реализации лекарственных средств и медицинских изделий
  kaz: Дәрілік заттар мен медициналық бұйымдарды көтерме және бөлшек саудада өткізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-09-14
approved_by:
- '103037000000'
version_date:
  kaz: 2015-09-14
  rus: 2015-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/94572/kaz/14.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94572/rus/14.09.2015
