act_code: '172754'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 11 октября 2022 года № 297. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 октября 2022 года № 30119
title:
  rus: Об утверждении статистической формы для проведения ведомственных статистических наблюдений и инструкции по ее заполнению
  kaz: Ведомстволық статистикалық байқауларды жүргізу үшін статистикалық нысанды және оны толтыру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2022-10-11
approved_by:
- '103034000000'
version_date:
  kaz: 2024-11-18
  rus: 2024-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/172754/kaz/18.11.2024
  rus: https://zan.gov.kz/client/#!/doc/172754/rus/18.11.2024
caused_by:
  code: '202860'
  requisite: Приказ и.о. Министра туризма и спорта Республики Казахстан от 18 ноября 2024 года № 204. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 ноября 2024 года № 35375
  title:
    rus: О внесении изменений и дополнения в приказ Министра культуры и спорта Республики Казахстан от 11 октября 2022 года № 297 «Об утверждении формы ведомственных статистических наблюдений»
    kaz: «Ведомстволық статистикалық байқаулардың нысандарын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің 2022 жылғы 11 қазандағы № 297 бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202860/rus
