act_code: '224899'
requisite: Приказ Министра просвещения Республики Казахстан от 29 апреля 2026 года № 104-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 мая 2026 года № 38628
title:
  rus: Об утверждении Правил педагогического сопровождения несовершеннолетних, требующих повышенного внимания, в организациях образования
  kaz: Білім беру ұйымдарында баса назар аударуды талап ететін кәмелетке толмағандарды педагогикалық сүйемелдеу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2026-04-29
approved_by:
- '103048000000'
version_date:
  kaz: 2026-08-31
  rus: 2026-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/224899/kaz/31.08.2026
  rus: https://zan.gov.kz/client/#!/doc/224899/rus/31.08.2026
caused_by:
  code: '229709'
  requisite: Приказ и.о. Министра просвещения Республики Казахстан от 31 августа 2026 года № 233-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 сентября 2026 года № 39801
  title:
    rus: О внесении изменения и дополнений в приказ Министра просвещения Республики Казахстан от 29 апреля 2026 года № 104-НҚ «Об утверждении Правил педагогического сопровождения несовершеннолетних, требующих повышенного внимания, в организациях образования»
    kaz: «Білім беру ұйымдарында баса назар аударуды талап ететін кәмелетке толмағандарды педагогикалық сүйемелдеу қағидаларын бекіту туралы» Қазақстан Республикасы Оқу-ағарту министрінің 2026 жылғы 29 сәуірдегі № 104-НҚ бұйрығына өзгеріс пен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229709/rus
