act_code: '179130'
requisite: Приказ Министра национальной экономики Республики Казахстан от 15 марта 2023 года № 33. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 марта 2023 года № 32083
title:
  rus: Об утверждении лимитов государственных обязательств по проектам государственно-частного партнерства, в том числе государственных концессионных обязательств, местных исполнительных органов на 2023-2025 годы
  kaz: Жергілікті атқарушы органдардың 2023-2025 жылдарға арналған мемлекеттік-жекешелік әріптестік жобалары бойынша мемлекеттік міндеттемелерінің, оның ішінде мемлекеттік концессиялық міндеттемелерінің лимиттерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2023-03-15
approved_by:
- '103033000000'
version_date:
  kaz: 2023-03-15
  rus: 2023-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/179130/kaz/15.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179130/rus/15.03.2023
