act_code: '71486'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 9 ноября 2012 года № 17-02/566. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 декабря 2012 года № 8181
title:
  rus: Об утверждении Инструкции проведения лесоустройства
  kaz: Орман орналастыруды жүргізу нұсқаулығын бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2012-11-09
approved_by:
- '103012000000'
version_date:
  kaz: 2024-09-06
  rus: 2024-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/71486/kaz/06.09.2024
  rus: https://zan.gov.kz/client/#!/doc/71486/rus/06.09.2024
caused_by:
  code: '200606'
  requisite: Приказ и.о. Министра экологии и природных ресурсов Республики Казахстан от 6 сентября 2024 года № 203. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 сентября 2024 года № 35060
  title:
    rus: О внесении изменений в приказ Министра сельского хозяйства Республики Казахстан от 9 ноября 2012 года № 17-02/566 «Об утверждении Инструкции проведения лесоустройства»
    kaz: «Орман орналастыруды жүргізу нұсқаулығын бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің 2012 жылғы 9 қарашадағы № 17-02/566 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200606/rus
