act_code: '73213'
requisite: Приказ Генерального прокурора Республики Казахстан от 19 июня 2013 года № 63. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 июня 2013 года № 8518. Утратил силу приказом Генерального прокурора Республики Казахстан от 29 мая 2015 года № 67
title:
  rus: Об утверждении Правил регистрации актов о назначении проверок, уведомлений о приостановлении, возобновлении, продлении сроков проверок, об изменении состава участников и предоставлении информационных учетных документов о проверках и их результатах
  kaz: '"Тексерулер тағайындау туралы актілерді, тоқтату, қайта жаңғырту, тексеру мерзімдерін ұзарту туралы хабарлауларды, қатысушылардың құрамын өзгерту туралы актілерді тіркеу және тексеру мен оның нәтижелері жөніндегі ақпараттың есепке алу құжаттарын ұсыну ережесін бекіту туралы"'
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2013-06-19
approved_by:
- '107000000000'
version_date:
  kaz: 2013-06-19
  rus: 2013-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/73213/kaz/19.06.2013
  rus: https://zan.gov.kz/client/#!/doc/73213/rus/19.06.2013
