act_code: '33572'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 14 мая 2007 года № 316. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 июня 2007 года № 4707. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 20 октября 2020 года № 321 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики определения площадей гибели посевов
  kaz: Егістіктің жойылған алқаптарын анықтау әдістемесін бекіту туралы
form: ПРИК
type_codes:
- МЕТ
- ПРИК
approved_on: 2007-05-14
approved_by:
- '103012000000'
version_date:
  rus: 2007-05-14
source:
  rus: https://zan.gov.kz/client/#!/doc/33572/rus/14.05.2007
