act_code: '37313'
requisite: Приказ и.о. Министра образования и науки Республики Казахстан от 26 декабря 2007 года № 657. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 января 2008 года № 5116. Утратил силу приказом Министра образования и науки Республики Казахстан от 21 февраля 2012 года № 57
title:
  rus: Об утверждении Правил конкурсного замещения руководителей государственных организаций среднего образования
  kaz: Мемлекеттік орта білім беру ұйымдарының басшыларын конкурстық орналастыру ережесін бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2007-12-26
approved_by:
- '103006000000'
version_date:
  kaz: 2007-12-26
  rus: 2007-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/37313/kaz/26.12.2007
  rus: https://zan.gov.kz/client/#!/doc/37313/rus/26.12.2007
