act_code: '145586'
requisite: Приказ Министра иностранных дел Республики Казахстан от 17 августа 2020 года № 11-1-4/227. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 августа 2020 года № 21109
title:
  rus: Об утверждении Правил ротации персонала дипломатической службы Республики Казахстан
  kaz: Қазақстан Республикасының дипломатиялық қызмет персоналын ротациялау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-08-17
approved_by:
- '103004000000'
version_date:
  kaz: 2021-03-30
  rus: 2021-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/145586/kaz/30.03.2021
  rus: https://zan.gov.kz/client/#!/doc/145586/rus/30.03.2021
caused_by:
  code: '153939'
  requisite: Приказ и.о. Министра иностранных дел Республики Казахстан от 30 марта 2021 года № 11-1-4/112. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 марта 2021 года № 22427
  title:
    rus: О внесении изменений в некоторые приказы Министра иностранных дел Республики Казахстан
    kaz: Қазақстан Республикасы Сыртқы істер министрінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/153939/rus
