act_code: '88695'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 29 января 2015 года № 66. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 марта 2015 года № 10465. Утратил силу приказом Председателя Комитета национальной безопасности Республики Казахстан от 27 марта 2018 года № 25/нс (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Единых правил взаимодействия и централизованного управления сетями телекоммуникаций
  kaz: Телекоммуникациялар желілерінің өзара іс-қимыл жасауы мен орталықтан басқарудың бірыңғай қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-01-29
approved_by:
- '103035000000'
version_date:
  kaz: 2015-01-29
  rus: 2015-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/88695/kaz/29.01.2015
  rus: https://zan.gov.kz/client/#!/doc/88695/rus/29.01.2015
