act_code: '106258'
requisite: Приказ и.о. Министра энергетики Республики Казахстан от 29 июля 2016 года № 361. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 сентября 2016 года № 14210
title:
  rus: Об утверждении Правил формирования и использования резервного фонда
  kaz: Резервтік қорды қалыптастыру және пайдалану қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2016-07-29
approved_by:
- '103036000000'
version_date:
  kaz: 2024-09-23
  rus: 2024-09-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/106258/kaz/23.09.2024
  rus: https://zan.gov.kz/client/#!/doc/106258/rus/23.09.2024
caused_by:
  code: '200923'
  requisite: Приказ Министра энергетики Республики Казахстан от 23 сентября 2024 года № 334. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 сентября 2024 года № 35105
  title:
    rus: О внесении изменений и дополнения в некоторые приказы Министерства энергетики Республики Казахстан
    kaz: Қазақстан Республикасы Энергетика министрінің кейбір бұйрықтарына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200923/rus
