act_code: '183186'
requisite: Приказ Министра юстиции Республики Казахстан от 22 июня 2023 года № 401. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 июня 2023 года № 32873
title:
  rus: Об утверждении минимальных ставок вознаграждения исполнителям и производителям фонограмм
  kaz: Орындаушыларға және фонограммалар шығарушыларға берілетін сыйақының ең төмен мөлшерлемелерін бекiту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2023-06-22
approved_by:
- '103001000000'
version_date:
  kaz: 2026-01-28
  rus: 2026-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/183186/kaz/28.01.2026
  rus: https://zan.gov.kz/client/#!/doc/183186/rus/28.01.2026
caused_by:
  code: '221677'
  requisite: Приказ Министра юстиции Республики Казахстан от 28 января 2026 года № 84. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 января 2026 года № 37914
  title:
    rus: О внесении изменений в некоторые приказы Министра юстиции Республики Казахстан по вопросам авторского права и смежных прав
    kaz: Қазақстан Республикасы Әділет министрінің кейбір бұйрықтарына авторлық құқық және сабақтас құқықтар мәселелері бойынша өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/221677/rus
