act_code: '91279'
requisite: Приказ Министра здравоохранения и социального развития Республики Казахстан от 28 мая 2015 года № 407. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 июня 2015 года № 11503. Утратил силу приказом Министра труда и социальной защиты населения Республики Казахстан от 25 марта 2021 года № 84 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов оказания государственных услуг в сфере социальной защиты населения
  kaz: Халықты әлеуметтік қорғау саласында мемлекеттік қызметті көрсетурегламенттерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2015-05-28
approved_by:
- '103037000000'
version_date:
  kaz: 2015-12-25
  rus: 2015-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/91279/kaz/25.12.2015
  rus: https://zan.gov.kz/client/#!/doc/91279/rus/25.12.2015
caused_by:
  code: '98688'
  requisite: Приказ Министра здравоохранения и социального развития Республики Казахстан от 25 декабря 2015 года № 1024. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 февраля 2016 года № 13008. Утратил силу приказом Министра труда и социальной защиты населения Республики Казахстан от 25 марта 2021 года № 84 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в приказ Министра здравоохранения и социального развития Республики Казахстан от 28 мая 2015 года № 407 «Об утверждении регламентов оказания государственных услуг в сфере социальной защиты населения»
    kaz: «Халықты әлеуметтік қорғау саласында мемлекеттік қызметті көрсету регламенттерін бекіту туралы» Қазақстан Республикасы Денсаулық сақтау және әлеуметтік даму Министрінің 2015 жылғы 28 мамырдағы № 407 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/98688/rus
