act_code: '189804'
requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 7 декабря 2023 года № 92/қе. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 декабря 2023 года № 33747
title:
  rus: Об утверждении Типового положения о постоянно действующей комиссии по защите государственных секретов государственных органов и организаций Республики Казахстан
  kaz: Қазақстан Республикасы мемлекеттік органдары мен ұйымдарының мемлекеттік құпияларды қорғау жөніндегі тұрақты жұмыс істейтін комиссиясы туралы үлгілік ережені бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2023-12-07
approved_by:
- '108000000000'
version_date:
  kaz: 2023-12-07
  rus: 2023-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/189804/kaz/07.12.2023
  rus: https://zan.gov.kz/client/#!/doc/189804/rus/07.12.2023
