act_code: '193085'
requisite: Приказ и.о. Министра промышленности и строительства Республики Казахстан от 5 февраля 2024 года № 46. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 февраля 2024 года № 33973
title:
  rus: Об утверждении форм, предназначенных для сбора административных данных в сфере системы жилищных строительных сбережений
  kaz: Тұрғын үй құрылыс жинақтары жүйесі саласындағы әкімшілік деректерді жинауға арналған нысандарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2024-02-05
approved_by:
- '103052000000'
version_date:
  kaz: 2024-02-05
  rus: 2024-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/193085/kaz/05.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193085/rus/05.02.2024
