act_code: '144229'
requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 26 июня 2020 года № 374. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 июня 2020 года № 20907
title:
  rus: Об утверждении Правил оказания государственной услуги «Выдача лицензии на импорт и (или) экспорт отдельных видов товаров»
  kaz: «Тауарлардың жекелеген түрлерінің импортына және (немесе) экспортына лицензия беру» мемлекеттік қызмет көрсету ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-06-26
approved_by:
- '103042000000'
version_date:
  kaz: 2024-07-31
  rus: 2024-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/144229/kaz/31.07.2024
  rus: https://zan.gov.kz/client/#!/doc/144229/rus/31.07.2024
caused_by:
  code: '201384'
  requisite: Приказ Министра промышленности и строительства Республики Казахстан от 31 июля 2024 года № 286. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 июля 2024 года № 34870
  title:
    rus: О внесении изменений в приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 26 июня 2020 года № 374 «Об утверждении Правил оказания государственной услуги «Выдача лицензии на импорт и (или) экспорт отдельных видов товаров»
    kaz: «Тауарлардың жекелеген түрлерінің импортына және (немесе) экспортына лицензия беру» мемлекеттік қызмет көрсету ережесін бекіту туралы» Қазақстан Республикасы Индустрия және инфрақұрылымдық даму министрінің 2020 жылғы 26 маусымдағы № 374 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201384/rus
