act_code: '100754'
requisite: Приказ Министра по делам государственной службы Республики Казахстан от 3 марта 2016 года № 51. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 апреля 2016 года № 13564. Утратил силу приказом Председателя Агентства Республики Казахстан по делам государственной службы и противодействию коррупции от 11 ноября 2016 года № 53
title:
  rus: Об утверждении натуральных норм обеспечения форменной одеждой (без погон) сотрудников Национального бюро по противодействию коррупции (Антикоррупционной службы) Министерства по делам государственной службы Республики Казахстан
  kaz: Қазақстан Республикасының Мемлекеттік қызмет істері министрлігі Сыбайлас жемқорлыққа қарсы іс-қимыл ұлттық бюросының (Сыбайлас жемқорлыққа қарсы қызмет) қызметкерлерін нысанды киіммен (погонсыз) қамтамасыз етудің заттай нормаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2016-03-03
approved_by:
- '103038000000'
version_date:
  kaz: 2016-03-03
  rus: 2016-03-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/100754/kaz/03.03.2016
  rus: https://zan.gov.kz/client/#!/doc/100754/rus/03.03.2016
