act_code: '93323'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 17 июля 2015 года № 249. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 августа 2015 года № 11948
title:
  rus: Об утверждении формы представления отчетности организатора игорного бизнеса, Правил осуществления сбора и анализа отчетности, представляемой организатором игорного бизнеса
  kaz: Ойын бизнесін ұйымдастырушының есептілікті ұсыну нысанын, Ойын бизнесін ұйымдастырушы ұсынатын есептілікті жинауды және талдауды жүзеге асыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2015-07-17
approved_by:
- '103034000000'
version_date:
  kaz: 2024-10-01
  rus: 2024-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/93323/kaz/01.10.2024
  rus: https://zan.gov.kz/client/#!/doc/93323/rus/01.10.2024
caused_by:
  code: '201266'
  requisite: Приказ Министра туризма и спорта Республики Казахстан от 1 октября 2024 года № 169. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 октября 2024 года № 35197
  title:
    rus: О внесении изменений в приказ Министра культуры и спорта Республики Казахстан от 17 июля 2015 года № 249 «Об утверждении формы представления отчетности организатора игорного бизнеса, Правил осуществления сбора и анализа отчетности, представляемой организатором игорного бизнеса»
    kaz: «Ойын бизнесін ұйымдастырушының есептілікті ұсыну нысанын, Ойын бизнесін ұйымдастырушы ұсынатын есептілікті жинауды және талдауды жүзеге асыру қағидаларын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің 2015 жылғы 17 шілдедегі № 249 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201266/rus
