act_code: '44443'
requisite: Приказ Министра финансов Республики Казахстан от 30 января 2009 года N 38. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 февраля 2009 года N 5559. Утратил силу приказом Заместителя Премьер-Министра Республики Казахстан - Министра финансов Республики Казахстан от 28 декабря 2013 года № 588
title:
  rus: Об утверждении формы распоряжения налогового органа о приостановлении расходных операций по кассе агента
  kaz: Агенттiң кассасы бойынша шығыс операцияларын тоқтата тұру туралы салық органы әкімінің нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2009-01-30
approved_by:
- '103002000000'
version_date:
  kaz: 2009-01-30
  rus: 2009-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/44443/kaz/30.01.2009
  rus: https://zan.gov.kz/client/#!/doc/44443/rus/30.01.2009
