act_code: '178536'
requisite: Приказ и.о. Министра экологии и природных ресурсов Республики Казахстан от 3 февраля 2023 года № 32-Ө
title:
  rus: Об утверждении Положения о республиканском государственном учреждении «Комитет лесного хозяйства и животного мира Министерства экологии и природных ресурсов Республики Казахстан»
  kaz: Қазақстан Республикасы Экология және табиғи ресурстар министрлігінің «Орман шаруашылығы және жануарлар дүниесі комитеті» республикалық мемлекеттік мекемесінің ережесін бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2023-02-03
approved_by:
- '103047000000'
version_date:
  kaz: 2024-04-04
  rus: 2024-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/178536/kaz/04.04.2024
  rus: https://zan.gov.kz/client/#!/doc/178536/rus/04.04.2024
caused_by:
  code: '195638'
  requisite: Приказ Министра экологии и природных ресурсов Республики Казахстан от 4 апреля 2024 года № 73-Ө
  title:
    rus: О внесении изменения в приказ исполнящего обязанности Министра экологии и природных ресурсов Республики Казахстан от 3 февраля 2023 года № 32-Ө «Об утверждении Положения о республиканском государственном учреждении «Комитет лесного хозяйства и животного мира Министерства экологии и природных ресурсов Республики Казахстан»
    kaz: «Қазақстан Республикасы Экология және табиғи ресурстар министрлігінің «Орман шаруашылығы және жануарлар дүниесі комитеті» республикалық мемлекеттік мекемесінің ережесін бекіту туралы» Қазақстан Республикасы Экология және табиғи ресурстар министрі міндетін атқарушысының 2023 жылғы 3 ақпандағы № 32-Ө бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/195638/rus
