act_code: '215301'
requisite: Приказ Министра внутренних дел Республики Казахстан от 3 октября 2025 года № 746
title:
  rus: Об утверждении служебного регламента - Правил разработки, принятия, регистрации, учета, изменения, пересмотра, отмены, издания, распространения, применения, стандартов для подразделений Министерства внутренних дел Республики Казахстан
  kaz: Қазақстан Республикасы Ішкі істер министрлігінің бөлімшелері үшін стандарттарды әзірлеу, қабылдау, тіркеу, есепке алу, өзгерту, қайта қарау, күшін жою, басып шығару, тарату, қолдану қағидалары - қызметтік регламентін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2025-10-03
approved_by:
- '103003000000'
version_date:
  kaz: 2025-10-03
  rus: 2025-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/215301/kaz/03.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215301/rus/03.10.2025
