act_code: '65378'
requisite: Приказ Министра финансов Республики Казахстан от 30 марта 2012 года № 180. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 мая 2012 года № 7621. Утратил силу приказом Министра финансов Республики Казахстан от 13 января 2016 года № 13
title:
  rus: Об утверждении Классификатора нарушений, выявляемых на объектах государственного финансового контроля
  kaz: Мемлекеттік қаржылық бақылау объектілерінде анықталатын бұзушылықтар сыныптауышын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2012-03-30
approved_by:
- '103002000000'
version_date:
  kaz: 2015-04-08
  rus: 2015-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/65378/kaz/08.04.2015
  rus: https://zan.gov.kz/client/#!/doc/65378/rus/08.04.2015
caused_by:
  code: '89884'
  requisite: Приказ от 08.04.2015 № 263, Министерство финансов Республики Казахстан. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 апреля 2015 года № 10910. Утратил силу приказом Министра финансов Республики Казахстан от 13 января 2016 года № 13
  title:
    rus: О внесении изменения в приказ Министра финансов Республики Казахстан от 30 марта 2012 года № 180 «Об утверждении Классификатора нарушений, выявляемых на объектах государственного финансового контроля»
    kaz: Қазақстан Республикасы Қаржы министрінің 2012 жылғы 30 наурыздағы № 180 «Мемлекеттiк қаржылық бақылау объектілерінде айқындалған бұзушылықтардың сыныптауышын бекіту туралы» бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/89884/rus
