act_code: '162923'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 29 декабря 2021 года № 407. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 января 2022 года № 26382
title:
  rus: Об утверждении Правил возмещения части затрат субъектов предпринимательства по приобретению оборудования и техники для горнолыжных курортов
  kaz: Кәсіпкерлік субъектілерінің тау шаңғысы курорттарына арналған жабдықтар мен техника сатып алу бойынша шығындарының бір бөлігін өтеу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2021-12-29
approved_by:
- '103034000000'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/162923/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162923/rus/29.12.2021
