act_code: '95536'
requisite: Приказ Министра финансов Республики Казахстан от 29 сентября 2015 года № 498. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 октября 2015 года № 12219
title:
  rus: Об утверждении Правил оснащения технологических линий производства этилового спирта и (или) алкогольной продукции контрольными приборами учета, их функционирования и осуществления учета, кроме производства вина наливом (виноматериала), а также пивоваренной продукции, производственные мощности которых ниже четырехсот тысяч декалитров в год
  kaz: Толысылған шарап (шарап материалы), сондай-ақ өндiрiстiк қуаты жылына төрт жүз мың декалитрден төмен сыра қайнату өнімі өндiрiсiнен басқа, этил спиртiн және (немесе) алкоголь өнiмiн өндiрудiң технологиялық желiлерiн есепке алудың бақылау аспаптарымен жарақтандыру, олардың жұмыс iстеу және есепке алынуын жүзеге асыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-09-29
approved_by:
- '103002000000'
version_date:
  kaz: 2015-12-14
  rus: 2015-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/95536/kaz/14.12.2015
  rus: https://zan.gov.kz/client/#!/doc/95536/rus/14.12.2015
caused_by:
  code: '97819'
  requisite: Приказ Министра финансов Республики Казахстан от 14 декабря 2015 года № 653. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 декабря 2015 года № 12628
  title:
    rus: О внесении изменений в приказ Министра финансов Республики Казахстан от 29 сентября 2015 года № 498 "Об утверждении Правил оснащения технологических линий производства этилового спирта и (или) алкогольной продукции контрольными приборами учета, их функционирования и осуществления учета, кроме производства виноматериала, а также пива, производственные мощности которых ниже четырехсот тысяч декалитров в год"
    kaz: '"Шарап материалы, сондай-ақ өндiрiстiк қуаты жылына төрт жүз мың декалитрден төмен сыра өндiрiсiнен басқа, этил спиртiн және (немесе) алкоголь өнiмiн өндiрудiң технологиялық желiлерiн есепке алудың бақылау аспаптарымен жарақтандыру, олардың жұмыс iстеу және есепке алынуын жүзеге асыру қағидаларын бекіту туралы" Қазақстан Республикасының Қаржы Министрінің 2015 жылғы 29 қыркүйегіндегі № 498 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/97819/rus
