act_code: '14233'
requisite: Приказ Министра внутренних дел Республики Казахстан от 16 января 2003 года N 22. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 января 2003 года N 2137. Утратил силу приказом Министра внутренних дел Республики Казахстан от 2 апреля 2013 года N 217
title:
  rus: Об утверждении Инструкции по организации функционирования автоматизированной информационно-поисковой системы "Технадзор"
  kaz: '"Технадзор" автоматтандырылған ақпараттық-іздестіру жүйесінің жұмыс істеуін ұйымдастыру жөніндегі нұсқаулықты бекіту туралы'
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2003-01-16
approved_by:
- '103003000000'
version_date:
  kaz: 2007-02-26
  rus: 2007-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/14233/kaz/26.02.2007
  rus: https://zan.gov.kz/client/#!/doc/14233/rus/26.02.2007
caused_by:
  code: '32476'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 26 февраля 2007 года № 83. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 марта 2007 года № 4587. Утратил силу приказом Министра внутренних дел Республики Казахстан от 2 апреля 2013 года № 217
  title:
    rus: О внесении изменений и дополнений в некоторые приказы Министра внутренних дел Республики Казахстан
    kaz: Қазақстан Республикасы Ішкі іcтep министрінің кейбір бұйрықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/32476/rus
