act_code: '125859'
requisite: Приказ Заместителя Премьер-Министра Республики Казахстан - Министра сельского хозяйства Республики Казахстан от 26 октября 2018 года № 436. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 ноября 2018 года № 17741
title:
  rus: Об утверждении Правил субсидирования ставок вознаграждения при кредитовании субъектов агропромышленного комплекса, а также лизинге на приобретение сельскохозяйственных животных, техники и технологического оборудования
  kaz: Агроөнеркәсіптік кешен субъектілеріне кредит беру, сондай-ақ ауыл шаруашылығы жануарларын, техникасы мен технологиялық жабдығын сатып алуға лизинг кезінде сыйақы мөлшерлемелерін субсидиялау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-10-26
approved_by:
- '103012000000'
version_date:
  kaz: 2025-02-24
  rus: 2025-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/125859/kaz/24.02.2025
  rus: https://zan.gov.kz/client/#!/doc/125859/rus/24.02.2025
caused_by:
  code: '207546'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 24 февраля 2025 года № 60. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 февраля 2025 года № 35758
  title:
    rus: О внесении изменений и дополнения в приказ Заместителя Премьер-Министра Республики Казахстан – Министра сельского хозяйства Республики Казахстан от 26 октября 2018 года № 436 «Об утверждении Правил субсидирования ставок вознаграждения при кредитовании субъектов агропромышленного комплекса, а также лизинге на приобретение сельскохозяйственных животных, техники и технологического оборудования»
    kaz: «Агроөнеркәсіптік кешен субъектілеріне кредит беру, сондай-ақ ауыл шаруашылығы жануарларын, техникасы мен технологиялық жабдығын сатып алуға лизинг кезінде сыйақы мөлшерлемелерін субсидиялау қағидаларын бекіту туралы» Қазақстан Республикасы Премьер-Министрінің орынбасары – Қазақстан Республикасы Ауыл шаруашылығы министрінің 2018 жылғы 26 қазандағы № 436 бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207546/rus
