act_code: '93330'
requisite: Совместный приказ Министра по инвестициям и развитию Республики Казахстан от 29 июня 2015 года № 739 и Министра национальной экономики Республики Казахстан от 20 июля 2015 года № 543. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 августа 2015 года № 11914. Утратил силу совместным приказом и.о. Министра по инвестициям и развитию Республики Казахстан от 14 декабря 2015 года № 1205 и Министра национальной экономики Республики Казахстан от 29 декабря 2015 года № 823
title:
  rus: Об утверждении критериев оценки степени риска и форм проверочных листов в области автомобильного, железнодорожного, внутреннего водного транспорта и торгового мореплавания
  kaz: Автомобиль, теміржол, ішкі су көлігі және сауда мақсатында теңізде жүзу саласындағы тәуекел дәрежесін бағалау критерийлері мен тексеру парақтарының нысандарын бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПРИК
approved_on: 2015-06-29
approved_by:
- '103033000000'
- '103035000000'
version_date:
  kaz: 2015-06-29
  rus: 2015-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/93330/kaz/29.06.2015
  rus: https://zan.gov.kz/client/#!/doc/93330/rus/29.06.2015
