act_code: '95680'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 29 мая 2015 года № 671. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 июля 2015 года № 11760. Утратил силу приказом и.о. Министра индустрии и инфраструктурного развития Республики Казахстан от 15 октября 2020 года № 531 (вводится по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в сфере автомобильного транспорта
  kaz: Автомобиль көлігі саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2015-05-29
approved_by:
- '103035000000'
version_date:
  kaz: 2016-02-25
  rus: 2016-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/95680/kaz/25.02.2016
  rus: https://zan.gov.kz/client/#!/doc/95680/rus/25.02.2016
caused_by:
  code: '104485'
  requisite: Приказ и.о. Министра по инвестициям и развитию Республики Казахстан от 25 февраля 2016 года № 231. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 июля 2016 года № 13536. Утратил силу приказом и.о. Министра индустрии и инфраструктурного развития Республики Казахстан от 15 октября 2020 года № 531 (вводится по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра по инвестициям и развитию Республики Казахстан от 29 мая 2015 года № 671 "Об утверждении регламентов государственных услуг в сфере автомобильного транспорта"
    kaz: '"Автомобиль көлігі саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы" Қазақстан Республикасы Инвестициялар және даму Министрінің 2015 жылғы 29 мамырдағы № 671 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/104485/rus
