act_code: '217776'
requisite: Приказ и.о. Министра сельского хозяйства Республики Казахстан от 28 ноября 2025 года № 441. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 декабря 2025 года № 37513. Действовал до 31 декабря 2025 года в соответствии с пунктом 7 настоящего приказа
title:
  rus: О некоторых вопросах вывоза мяса крупного-рогатого скота с территории Республики Казахстан
  kaz: Ірі қара мал етін Қазақстан Республикасының аумағынан әкетудің кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-11-28
approved_by:
- '103012000000'
version_date:
  kaz: 2025-11-28
  rus: 2025-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/217776/kaz/28.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217776/rus/28.11.2025
