act_code: '18334'
requisite: Приказ Министра финансов Республики Казахстан от 16 января 2004 года N 21. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 января 2004 года N 2683. Утратил силу - приказом Министра финансов РК от 03.06.2005г. N 211
title:
  rus: Об утверждении Таблицы перехода кодов Функциональной бюджетной классификации расходов бюджетов в шифры Справочников бюджетной классификации, используемой в программном обеспечении "Автоматизированная система областного управления казначейства" ("Баск-М")
  kaz: Республикалық бюджет шығыстарының функционалдық бюджеттік сыныптамасы кодтарының Облыстық қазынашылық басқармасының автоматтандырылған жүйесі (Баск-М) бағдарламалық қамтамасыз етуінде пайдаланылатын Бюджеттік сыныптама анықтамалықтарының шифрларына көшу кестесін бекіту туралы
form: ПРИК
type_codes:
- КЛАС
- ПРИК
approved_on: 2004-01-16
approved_by:
- '103002000000'
version_date:
  kaz: 2004-01-16
  rus: 2004-01-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/18334/kaz/16.01.2004
  rus: https://zan.gov.kz/client/#!/doc/18334/rus/16.01.2004
