act_code: '140147'
requisite: Приказ Министра национальной экономики Республики Казахстан от 10 марта 2020 года № 14. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 марта 2020 года № 20106
title:
  rus: Об утверждении Правил отбора и координации проектов по содействию устойчивому развитию и росту Республики Казахстан, осуществляемых совместно с международными финансовыми организациями в рамках рамочных соглашений о партнерстве между Правительством Республики Казахстан и международными финансовыми организациями
  kaz: Қазақстан Республикасының Үкіметі мен халықаралық қаржы ұйымдары арасындағы әріптестік туралы негіздемелік келісімдер шеңберінде халықаралық қаржы ұйымдарымен бірлесіп жүзеге асырылатын Қазақстан Республикасының орнықты дамуы мен өсуіне жәрдемдесу жөніндегі жобаларды іріктеу және үйлестіру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-03-10
approved_by:
- '103033000000'
version_date:
  kaz: 2021-05-24
  rus: 2021-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/140147/kaz/24.05.2021
  rus: https://zan.gov.kz/client/#!/doc/140147/rus/24.05.2021
caused_by:
  code: '156180'
  requisite: Приказ Министра национальной экономики Республики Казахстан от 24 мая 2021 года № 52. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 мая 2021 года № 22845
  title:
    rus: О внесении изменений и дополнения в приказ Министра национальной экономики Республики Казахстан от 10 марта 2020 года № 14 «Об утверждении Правил отбора и координации проектов по содействию устойчивому развитию и росту Республики Казахстан, осуществляемых совместно с международными финансовыми организациями в рамках рамочных соглашений о партнерстве между Правительством Республики Казахстан и международными финансовыми организациями»
    kaz: «Қазақстан Республикасының Үкіметі мен халықаралық қаржы ұйымдары арасындағы әріптестік туралы негіздемелік келісімдер шеңберінде халықаралық қаржы ұйымдарымен бірлесіп жүзеге асырылатын Қазақстан Республикасының орнықты дамуына және өсуіне жәрдемдесу жөніндегі жобаларды іріктеу және үйлестіру қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық экономика министрінің 2020 жылғы 10 наурыздағы № 14 бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156180/rus
