act_code: '15970'
requisite: Приказ Председателя Комитета гражданской авиации Министерства транспорта и коммуникаций Республики Казахстан от 14 мая 2003 года № 218. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 июня 2003 года № 2363. Утратил силу приказом Министра транспорта и коммуникаций Республики Казахстан от 30 июня 2010 года № 299
title:
  rus: Об утверждении Правил по авиационной электросвязи гражданской авиации Республики Казахстан
  kaz: Қазақстан Республикасы азаматтық авиациясының авиациялық электрбайланыс туралы ережелерiн бекiту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2003-05-13
approved_by:
- '103013003000'
version_date:
  kaz: 2003-05-13
  rus: 2003-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/15970/kaz/13.05.2003
  rus: https://zan.gov.kz/client/#!/doc/15970/rus/13.05.2003
