act_code: '109841'
requisite: Совместный приказ Министра национальной экономики Республики Казахстан от 30 декабря 2016 года № 540 и Министра финансов Республики Казахстан от 30 декабря 2016 года № 706. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 февраля 2017 года № 14781. Утратило силу совместным нормативным постановлением Счетного комитета по контролю за исполнением республиканского бюджета от 8 февраля 2022 года № 1-НҚ и приказом Министра финансов Республики Казахстан от 8 февраля 2022 года № 141 (вводится в действие по истечении десяти календарных дней после дня их первого официального опубликования)
title:
  rus: Об утверждении Методики по оценке эффективности достижения целей
  kaz: Мақсаттарға қол жеткізу тиімділігін бағалау бойынша әдістемені бекіту туралы
form: ПРИК
type_codes:
- МЕТ
- ПРИК
approved_on: 2016-12-30
approved_by:
- '103002000000'
- '103033000000'
version_date:
  kaz: 2016-12-30
  rus: 2016-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/109841/kaz/30.12.2016
  rus: https://zan.gov.kz/client/#!/doc/109841/rus/30.12.2016
