act_code: '71689'
requisite: Приказ Председателя Агентства Республики Казахстан по делам государственной службы от 19 марта 2013 года № 06-7/32. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 марта 2013 года № 8380. Утратил силу приказом Министра по делам государственной службы Республики Казахстан от 29 декабря 2015 года № 12
title:
  rus: Об утверждении Правил проведения конкурса на занятие административной государственной должности и формирования конкурсной комиссии
  kaz: Бос әкімшілік мемлекеттік лауазымға орналасуға конкурс өткізу және конкурс комиссиясын қалыптастыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2013-03-19
approved_by:
- '120000000000'
version_date:
  kaz: 2013-12-11
  rus: 2013-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/71689/kaz/11.12.2013
  rus: https://zan.gov.kz/client/#!/doc/71689/rus/11.12.2013
caused_by:
  code: '77138'
  requisite: Приказ Председателя Агентства Республики Казахстан по делам государственной службы от 11 декабря 2013 года № 06-7/179. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 января 2014 года № 9076. Утратил силу приказом Министра по делам государственной службы Республики Казахстан от 29 декабря 2015 года № 12
  title:
    rus: О внесении изменений и дополнения в некоторые приказы Председателя Агентства Республики Казахстан по делам государственной службы
    kaz: Қазақстан Республикасы Мемлекеттік қызмет істері агенттігі Төрағасының кейбір бұйрықтарына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/77138/rus
