act_code: '184120'
requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 14 июля 2023 года № 508. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 июля 2023 года № 33119
title:
  rus: Об утверждении инструкции по организации антитеррористической защиты объектов питьевого водоснабжения населенных пунктов, уязвимых в террористическом отношении
  kaz: Террористік тұрғыдан осал елді мекендерді ауызсумен жабдықтау объектілерін терроризмге қарсы қорғалуын ұйымдастыру жөніндегі нұсқаулығын бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2023-07-14
approved_by:
- '103042000000'
version_date:
  kaz: 2024-08-15
  rus: 2024-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/184120/kaz/15.08.2024
  rus: https://zan.gov.kz/client/#!/doc/184120/rus/15.08.2024
caused_by:
  code: '199797'
  requisite: Приказ и.о. Министра промышленности и строительства Республики Казахстан от 15 августа 2024 года № 297. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 августа 2024 года № 34937
  title:
    rus: О внесении изменений в приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 14 июля 2023 года № 508 «Об утверждении инструкции по организации антитеррористической защиты объектов питьевого водоснабжения населенных пунктов, уязвимых в террористическом отношении»
    kaz: «Террористік тұрғыдан осал елді мекендерді ауызсумен жабдықтау объектілерін терроризмге қарсы қорғалуын ұйымдастыру жөніндегі нұсқаулығын бекіту туралы» Қазақстан Республикасы Индустрия және инфрақұрылымдық даму министрінің 2023 жылғы 14 шілдедегі № 508 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199797/rus
