act_code: '222530'
requisite: Приказ Министра юстиции Республики Казахстан от 23 февраля 2026 года № 180
title:
  rus: Об утверждении натуральных норм площадей специфических помещений для органов юстиции
  kaz: Әділет органдарының ерекше үй-жайларына арналған алаңдардың заттай нормаларын бекiту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2026-02-23
approved_by:
- '103001000000'
version_date:
  kaz: 2026-02-23
  rus: 2026-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/222530/kaz/23.02.2026
  rus: https://zan.gov.kz/client/#!/doc/222530/rus/23.02.2026
