act_code: '184050'
requisite: Приказ Министра внутренних дел Республики Казахстан от 14 июля 2023 года № 575. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 июля 2023 года № 33086
title:
  rus: Об утверждении образцов формы одежды осужденных
  kaz: Сотталғандардың киім нысанының үлгілерін бекіту туралы
form: ПРИК
type_codes:
- ОБРА
- ПРИК
approved_on: 2023-07-14
approved_by:
- '103003000000'
version_date:
  kaz: 2023-07-14
  rus: 2023-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/184050/kaz/14.07.2023
  rus: https://zan.gov.kz/client/#!/doc/184050/rus/14.07.2023
