act_code: '219316'
requisite: Приказ и.о. Министра туризма и спорта Республики Казахстан от 19 декабря 2025 года № 250. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 декабря 2025 года № 37648
title:
  rus: Об утверждении Требований к правилам внутреннего контроля в целях противодействия легализации (отмыванию) доходов, полученных преступным путем, финансированию терроризма и финансированию распространения оружия массового уничтожения для организаторов игорного бизнеса и лотереи
  kaz: Ойын бизнесі мен лотереяларды ұйымдастырушылар үшін қылмыстық жолмен алынған кірістерді заңдастыруға (жылыстатуға), терроризмді қаржыландыруға және жаппай қырып-жою қаруын таратуды қаржыландыруға қарсы іс-қимыл жасау мақсатында ішкі бақылау қағидаларына қойылатын талаптарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2025-12-19
approved_by:
- '103014000000'
version_date:
  kaz: 2025-12-19
  rus: 2025-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/219316/kaz/19.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219316/rus/19.12.2025
