act_code: '131348'
requisite: Совместный приказ Министра сельского хозяйства Республики Казахстан от 5 апреля 2019 года № 135 и Министра национальной экономики Республики Казахстан от 24 апреля 2019 года № 30. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 мая 2019 года № 18616
title:
  rus: Об утверждении критериев оценки степени рисков и проверочных листов в области охраны и использования водного фонда Республики Казахстан
  kaz: Қазақстан Республикасының су қорын қорғау және пайдалану саласындағы тәуекел дәрежесін бағалау өлшемшарттарын және тексеру парақтарын бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПРИК
approved_on: 2019-04-05
approved_by:
- '103012000000'
- '103033000000'
version_date:
  kaz: 2025-12-05
  rus: 2025-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/131348/kaz/05.12.2025
  rus: https://zan.gov.kz/client/#!/doc/131348/rus/05.12.2025
caused_by:
  code: '218750'
  requisite: Совместный приказ и.о. Министра водных ресурсов и ирригации Республики Казахстан от 5 декабря 2025 года № 315-НҚ и Заместителя Премьер-Министра – Министра национальной экономики Республики Казахстан от 9 декабря 2025 года № 130. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 декабря 2025 года № 37592
  title:
    rus: О внесении изменений в совместный приказ Министра сельского хозяйства Республики Казахстан от 5 апреля 2019 года № 135 и Министра национальной экономики Республики Казахстан от 24 апреля 2019 года № 30 «Об утверждении критериев оценки степени рисков и проверочных листов в области использования и охраны водного фонда Республики Казахстан, безопасности плотин»
    kaz: «Қазақстан Республикасының су қорын пайдалану және қорғау, бөгеттердің қауіпсіздігі саласындағы тәуекел дәрежесін бағалау өлшемшарттарын және тексеру парақтарын бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің 2019 жылғы 5 сәуірдегі № 135 және Қазақстан Республикасы Ұлттық экономика министрінің 2019 жылғы 24 сәуірдегі № 30 бірлескен бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218750/rus
