act_code: '61387'
requisite: Приказ Министра связи и информации Республики Казахстан от 20 октября 2011 года № 317. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 ноября 2011 года № 7296. Утратил силу приказом Министра культуры и информации Республики Казахстан от 7 ноября 2012 года № 178
title:
  rus: Об утверждении регламентов государственных услуг
  kaz: Мемлекеттік қызмет регламенттерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2011-10-20
approved_by:
- '103020000000'
version_date:
  kaz: 2011-10-20
  rus: 2011-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/61387/kaz/20.10.2011
  rus: https://zan.gov.kz/client/#!/doc/61387/rus/20.10.2011
