act_code: '188370'
requisite: Приказ Министра культуры и информации Республики Казахстан от 15 ноября 2023 года № 448-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 ноября 2023 года № 33647
title:
  rus: Об определении интернет-ресурса для подачи петиции
  kaz: Петиция беру үшін интернет-ресурсты айқындау туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2023-11-15
approved_by:
- '103053000000'
version_date:
  kaz: 2023-11-15
  rus: 2023-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/188370/kaz/15.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188370/rus/15.11.2023
