act_code: '85343'
requisite: Приказ Министра энергетики Республики Казахстан от 13 ноября 2014 года № 121. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 декабря 2014 года № 9958
title:
  rus: Об утверждении Правил определения цены сырого и товарного газа, приобретаемого национальным оператором в рамках преимущественного права государства
  kaz: Мемлекеттің артықшылықты құқығы шеңберінде ұлттық оператор сатып алатын шикі және тауарлық газдың бағасын айқындау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2014-11-13
approved_by:
- '103036000000'
version_date:
  kaz: 2018-07-31
  rus: 2018-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/85343/kaz/31.07.2018
  rus: https://zan.gov.kz/client/#!/doc/85343/rus/31.07.2018
caused_by:
  code: '124216'
  requisite: Приказ и.о. Министра энергетики Республики Казахстан от 31 июля 2018 года № 297. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 августа 2018 года № 17293
  title:
    rus: О внесении изменений в приказ Министра энергетики Республики Казахстан от 13 ноября 2014 года № 121 «Об утверждении Правил определения цены сырого и товарного газа, приобретаемого национальным оператором в рамках преимущественного права государства»
    kaz: «Мемлекеттің артықшылықты құқығы шеңберінде ұлттық оператор сатып алатын шикі және тауарлық газдың бағасын айқындау қағидаларын бекіту туралы» Қазақстан Республикасы Энергетика министрінің 2014 жылғы 13 қарашадағы № 121 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124216/rus
