act_code: '19100'
requisite: Приказ Председателя Комитета транспортного контроля Министерства транспорта и коммуникаций Республики Казахстан от 23 февраля 2004 года № 13-2-П. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 марта 2004 года № 2748. Утратил силу приказом и.о. Министра по инвестициям и развитию Республики Казахстан от 28 июля 2015 года № 809
title:
  rus: Об утверждении Инструкции по производству дел об административных правонарушениях Комитетом транспортного контроля Министерства транспорта и коммуникаций Республики Казахстан и его территориальными органами
  kaz: Қазақстан Республикасы Көлік және коммуникациялар министрлігінің Көліктік бақылау комитеті және оның аумақтық органдарының әкімшілік құқық бұзушылықтар туралы іс жүргізу жөніндегі нұсқаулығын бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2004-02-23
approved_by:
- '103013004000'
version_date:
  kaz: 2012-01-01
  rus: 2012-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/19100/kaz/01.01.2012
  rus: https://zan.gov.kz/client/#!/doc/19100/rus/01.01.2012
caused_by:
  code: '55322'
  requisite: Приказ и.о. Министра транспорта и коммуникаций Республики Казахстан от 29 сентября 2010 года № 440. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 октября 2010 года № 6605
  title:
    rus: О внесении изменений в некоторые приказы Министерства транспорта и коммуникаций Республики Казахстан
    kaz: Қазақстан Республикасы Көлік және коммуникация министрлігінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/55322/rus
