act_code: '171200'
requisite: Приказ Министра просвещения Республики Казахстан от 31 августа 2022 года № 385. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 августа 2022 года № 29329
title:
  rus: Об утверждении Типовых правил деятельности организаций образования соответствующих типов и видов, за исключением организаций высшего и послевузовского образования
  kaz: Жоғары және жоғары оқу орнынан кейінгі білім беру ұйымдарын қоспағанда, тиісті типтердегі және түрлердегі білім беру ұйымдары қызметінің үлгілік қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-08-31
approved_by:
- '103048000000'
version_date:
  kaz: 2024-07-31
  rus: 2024-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/171200/kaz/31.07.2024
  rus: https://zan.gov.kz/client/#!/doc/171200/rus/31.07.2024
caused_by:
  code: '199405'
  requisite: Приказ и.о. Министра просвещения Республики Казахстан от 31 июля 2024 года № 196. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 июля 2024 года № 34866
  title:
    rus: О внесении изменений в приказ Министра просвещения Республики Казахстан от 31 августа 2022 года № 385 «Об утверждении Типовых правил деятельности организаций дошкольного, среднего, технического и профессионального, послесреднего образования, дополнительного образования соответствующих типов и видов»
    kaz: «Тиісті типтердегі және түрлердегі мектепке дейінгі, орта, техникалық және кәсіптік, орта білімнен кейінгі, қосымша білім беру ұйымдары қызметінің үлгілік қағидаларын бекіту туралы» Қазақстан Республикасы Оқу-ағарту министрінің 2022 жылғы 31 тамыздағы № 385 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199405/rus
