act_code: '89132'
requisite: Приказ Министра национальной экономики Республики Казахстан от 19 марта 2015 года № 231. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 апреля 2015 года № 10766. Утратил силу приказом Министра промышленности и строительства Республики Казахстан от 12 февраля 2026 года № 51 (вводится в действие с 1 июля 2026 года)
title:
  rus: Об утверждении Перечня видов работ (услуг) в составе строительно-монтажных работ
  kaz: Құрылыс-монтаждау жұмыстары құрамындағы жұмыстар (көрсетілетін қызметтер) түрлерінің тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2015-03-19
approved_by:
- '103033000000'
version_date:
  kaz: 2015-03-19
  rus: 2015-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/89132/kaz/19.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89132/rus/19.03.2015
repealed_on: 2026-07-01
repealed_by:
  code: '222100'
  requisite: Приказ Министра промышленности и строительства Республики Казахстан от 12 февраля 2026 года № 51. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 февраля 2026 года № 37982
  title:
    rus: О признании утратившим силу приказа Министра национальной экономики Республики Казахстан от 19 марта 2015 года № 231 «Об утверждении Перечня видов работ (услуг) в составе строительно-монтажных работ»
    kaz: «Құрылыс-монтаждау жұмыстары құрамындағы жұмыстар (көрсетілетін  қызметтер) түрлерінің тізбесін бекіту туралы» Қазақстан Республикасы Ұлттық экономика министрінің 2015 жылғы 9 наурыздағы № 231 бұйрығының күшін жою туралы
  link: https://zan.gov.kz/client/#!/doc/222100/rus
