act_code: '61102'
requisite: Приказ Министра финансов Республики Казахстан от 29 сентября 2011 года № 491. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 октября 2011 года № 7235. Утратил силу приказом и.о. Министра финансов Республики Казахстан от 19 февраля 2016 года № 75 (вводится в действие со дня подписания)
title:
  rus: Об утверждении Положения о дегустационной комиссии, правил дегустации
  kaz: Дәмін айыру комиссиясының ережесін, дәмін айыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2011-09-29
approved_by:
- '103002000000'
version_date:
  kaz: 2012-11-30
  rus: 2012-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/61102/kaz/30.11.2012
  rus: https://zan.gov.kz/client/#!/doc/61102/rus/30.11.2012
caused_by:
  code: '69468'
  requisite: Приказ Министра финансов Республики Казахстан от 30 ноября 2012 года № 528. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 декабря 2012 года № 8129. Утратил силу приказом и.о. Министра финансов Республики Казахстан от 19 февраля 2016 года № 75 (вводится в действие со дня подписания)
  title:
    rus: О внесении изменении в приказ Министра финансов Республики Казахстан от 29 сентября 2011 года № 491 "Об утверждении Положения о дегустационной комиссии, правил дегустации"
    kaz: '"Дәмін айыру комиссиясының ережесін, дәмін айыру қағидаларын бекіту туралы" Қазақстан Республикасы Қаржы министрінің 2011 жылғы 29 қыркүйектегі № 491 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/69468/rus
