act_code: '185186'
requisite: Совместный приказ Председателя Агентства по стратегическому планированию и реформам Республики Казахстан от 15 августа 2023 года № 5 и Министра национальной экономики Республики Казахстан от 15 августа 2023 года № 152. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 августа 2023 года № 33301. Утратил силу совместным приказом Председателя Агентства по стратегическому планированию и реформам Республики Казахстан от 26 июня 2024 года № 2 и и.о. Министра национальной экономики Республики Казахстан от 26 июня 2024 года № 43 (вводится в действие 1 июля 2024 года)
title:
  rus: Об утверждении критериев оценки степени риска и проверочного листа в области государственной статистики
  kaz: Мемлекеттік статистика саласындағы тәуекел дәрежесін бағалау өлшемшарттарын және тексеру парағын бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПРИК
approved_on: 2023-08-15
approved_by:
- '103033000000'
- '136000000000'
version_date:
  kaz: 2023-08-15
  rus: 2023-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/185186/kaz/15.08.2023
  rus: https://zan.gov.kz/client/#!/doc/185186/rus/15.08.2023
