act_code: '189424'
requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 30 ноября 2023 года № 169. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 декабря 2023 года № 33715
title:
  rus: Об утверждении методики распределения объемов услуг и (или) средств субъектам здравоохранения по оказанию медицинской помощи в рамках гарантированного объема бесплатной медицинской помощи и (или) в системе обязательного социального медицинского страхования
  kaz: Тегін медициналық көмектің кепілдік берілген көлемі шеңберінде және (немесе) міндетті әлеуметтік медициналық сақтандыру жүйесінде медициналық көмек көрсету жөніндегі денсаулық сақтау субъектілеріне көрсетілетін қызметтердің және (немесе) қаражаттың көлемдерін бөлу әдістемесін бекіту туралы
form: ПРИК
type_codes:
- МЕТ
- ПРИК
approved_on: 2023-11-30
approved_by:
- '103010000000'
version_date:
  kaz: 2024-11-22
  rus: 2024-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/189424/kaz/22.11.2024
  rus: https://zan.gov.kz/client/#!/doc/189424/rus/22.11.2024
caused_by:
  code: '203215'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 22 ноября 2024 года № 96. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 ноября 2024 года № 35400
  title:
    rus: О внесении изменений и дополнений в некоторые приказы Министерства здравоохранения Республики Казахстан
    kaz: Қазақстан Республикасы Денсаулық сақтау министрлігінің кейбір бұйрықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203215/rus
