act_code: '193537'
requisite: Приказ Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 21 февраля 2024 года № 83/НҚ
title:
  rus: Об установлении нормативов положенности специальных транспортных средств и определении критериев отнесения автотранспорта к специальным транспортным средствам в республиканском государственном предприятии на праве хозяйственного ведения «Национальный центр геодезии и пространственной информации» Комитета геодезии и картографии Министерства цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан
  kaz: Қазақстан Республикасы Цифрлық даму, инновациялар және аэроғарыш өнеркәсібі министрлігі Геодезия және картография комитеті «Ұлттық геодезия және кеңістіктік ақпарат орталығы» шаруашылық жүргізу құқығындағы республикалық мемлекеттік кәсіпорнында автокөлікті арнайы көлік құралдарына жатқызу өлшемшарттарын белгілеу және көлік құралдарын арнайы көлік құралдарына жатқызу өлшемшарттарын айқындау туралы
form: ПРИК
type_codes:
- КРИТ
- НОРМ
- ПРИК
approved_on: 2024-02-21
approved_by:
- '103045000000'
version_date:
  kaz: 2024-02-21
  rus: 2024-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/193537/kaz/21.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193537/rus/21.02.2024
