act_code: '124092'
requisite: Приказ и.о. Министра внутренних дел Республики Казахстан от 24 июля 2018 года № 531. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 августа 2018 года № 17283
title:
  rus: Об утверждении Правил организации деятельности специальных помещений и Типовых правил внутреннего распорядка специального помещения
  kaz: Арнаулы үй-жайлардың қызметін ұйымдастыру қағидаларын және арнаулы үй-жайдың үлгілік ішкі тәртіптеме қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-07-24
approved_by:
- '103003000000'
version_date:
  kaz: 2020-05-12
  rus: 2020-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/124092/kaz/12.05.2020
  rus: https://zan.gov.kz/client/#!/doc/124092/rus/12.05.2020
caused_by:
  code: '142782'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 12 мая 2020 года № 386. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 мая 2020 года № 20629
  title:
    rus: О внесении изменений и дополнений в приказ Министра внутренних дел Республики Казахстан от 24 июля 2018 года № 531 «Об утверждении Правил организации деятельности специальных помещений и Типовых правил внутреннего распорядка специального помещения»
    kaz: «Арнаулы үй-жайлардың қызметін ұйымдастыру қағидаларын және арнаулы үй-жайлардың үлгілік ішкі тәртіптемесі қағидаларын бекіту туралы» Қазақстан Республикасы Ішкі істер министрінің 2018 жылғы 24 шілдедегі № 531 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142782/rus
