act_code: '164586'
requisite: Приказ и.о. Министра труда и социальной защиты населения Республики Казахстан от 16 февраля 2022 года № 60. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 февраля 2022 года № 26834. Утратил силу приказом Заместителя Премьер-Министра - Министра труда и социальной защиты населения Республики Казахстан от 30 июня 2023 года № 285 (вводится в действие с 1 июля 2023 года)
title:
  rus: Об утверждении Правил допуска поставщиков товаров и (или) услуг на портал социальных услуг, их регистрации или снятия с регистрации на портале социальных услуг
  kaz: Тауарларды және (немесе) көрсетілетін қызметтерді берушілерді әлеуметтік көрсетілетін қызметтер порталына жіберу, оларды әлеуметтік көрсетілетін қызметтер порталында тіркеу немесе тіркеуден шығару қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-02-16
approved_by:
- '103016000000'
version_date:
  kaz: 2023-01-20
  rus: 2023-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/164586/kaz/20.01.2023
  rus: https://zan.gov.kz/client/#!/doc/164586/rus/20.01.2023
caused_by:
  code: '178201'
repealed_on: 2023-07-01
repealed_by:
  code: '183498'
  requisite: Приказ Заместителя Премьер-Министра - Министра труда и социальной защиты населения Республики Казахстан от 30 июня 2023 года № 285. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 июня 2023 года № 32989
  title:
    rus: Об утверждении Правил регистрации поставщиков товаров и (или) услуг, услуг по перевозке лиц с инвалидностью на инватакси или их снятия с регистрации на портале социальных услуг, а также допуска товаров и (или) услуг на портал социальных услуг
    kaz: Тауарларды және (немесе) көрсетілетін қызметтерді, мүгедектігі бар адамдарды инватаксимен тасымалдау жөніндегі көрсетілетін қызметтерді берушілерді әлеуметтік көрсетілетін қызметтер порталында тіркеу немесе оларды тіркеуден шығару, сондай-ақ тауарларды және (немесе) көрсетілетін қызметтерді әлеуметтік көрсетілетін қызметтер порталына жіберу қағидаларын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/183498/rus
