act_code: '216337'
requisite: Приказ и.о. Министра финансов Республики Казахстан от 31 октября 2025 года № 652. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 октября 2025 года № 37304. Действовал по 31 декабря 2025 года включительно в соответствии с пунктом 3 настоящего приказа
title:
  rus: Об утверждении Правил и формы представления участником Международного финансового центра «Астана», имеющим лицензию на осуществление деятельности по управлению заемной краудфандинговой платформой, в орган государственных доходов сведений о заключенных договорах на краудфандинговых платформах, а также выплаченных вознаграждениях резидентам и нерезидентам
  kaz: Қарыз краудфандингтік платформаны басқару жөніндегі қызметті жүзеге асыруға лицензиясы бар «Астана» халықаралық қаржы орталығының қатысушысымен краудфандингтік платформаларда жасалған шарттар, сондай-ақ резиденттер мен бейрезиденттерге төленген сыйақылар туралы мәліметтерді мемлекеттік кірістер органдарына ұсыну қағидалары мен нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2025-10-31
approved_by:
- '103002000000'
version_date:
  kaz: 2025-10-31
  rus: 2025-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/216337/kaz/31.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216337/rus/31.10.2025
