act_code: '106650'
requisite: Приказ и.о Министра здравоохранения и социального развития Республики Казахстан от 2 августа 2016 года № 685. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 сентября 2016 года № 14205
title:
  rus: Об утверждении Правил и условий исчисления стажа работы по специальности для гражданских служащих, работников организаций, содержащихся за счет средств государственного бюджета, работников казенных предприятий в сфере здравоохранения
  kaz: Азаматтық қызметшілерге, мемлекеттік бюджет қаражаты есебінен ұсталатын ұйымдардың қызметкерлері, денсаулық сақтау саласындағы қазыналық кәсіпорындардың қызметкерлері үшін мамандығы бойынша жұмыс өтiлiн есептеу қағидалары мен шарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2016-08-02
approved_by:
- '103037000000'
version_date:
  kaz: 2016-08-02
  rus: 2016-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/106650/kaz/02.08.2016
  rus: https://zan.gov.kz/client/#!/doc/106650/rus/02.08.2016
