act_code: '75305'
requisite: Приказ Министра образования и науки Республики Казахстан от 7 октября 2013 года № 413. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 ноября 2013 года № 8880
title:
  rus: О некоторых мерах по реализации международной стипендии «Болашак»
  kaz: '"Болашақ" халықаралық стипендиясын іске асыру бойынша кейбір шаралар туралы'
form: ПРИК
type_codes:
- МРП
- ПРИК
approved_on: 2013-10-07
approved_by:
- '103006000000'
version_date:
  kaz: 2014-02-25
  rus: 2014-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/75305/kaz/25.02.2014
  rus: https://zan.gov.kz/client/#!/doc/75305/rus/25.02.2014
caused_by:
  code: '78531'
  requisite: Приказ Министра образования и науки Республики Казахстан от 25 февраля 2014 года № 55. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 марта 2014 года № 9214
  title:
    rus: О внесении изменений в приказ Министра образования и науки Республики Казахстан от 7 октября 2013 года № 413 "О некоторых мерах по реализации международной стипендии "Болашак"
    kaz: '"Болашақ" халықаралық стипендиясын іске асыру бойынша кейбір шаралар туралы" Қазақстан Республикасы Білім және ғылым министрінің 2013 жылғы 7 қазандағы № 413 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/78531/rus
