act_code: '120735'
requisite: Приказ Министра оборонной и аэрокосмической промышленности Республики Казахстан от 28 марта 2018 года № 53/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 апреля 2018 года № 16750. Утратил силу приказом Заместителя Премьер-Министра – Министра искусственного интеллекта и цифрового развития Республики Казахстан от 2 июня 2026 года № 279/НҚ (вводится в действие с 12 июля 2026 года)
title:
  rus: Об утверждении Правил формирования и ведения реестра доверенного программного обеспечения и продукции электронной промышленности, а также критериев по включению программного обеспечения и продукции электронной промышленности в реестр доверенного программного обеспечения и продукции электронной промышленности
  kaz: Электрондық өнеркәсіп пен бағдарламалық қамтылымның сенім білдірілген өнімінің тізілімін қалыптастыру және жүргізу қағидаларын, сондай-ақ электрондық өнеркәсіп пен бағдарламалық қамтылымның өнімін электрондық өнеркәсіп пен бағдарламалық қамтылымның сенім білдірілген өнімінің тізіліміне енгізу өлшемшарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-03-28
approved_by:
- '103041000000'
version_date:
  kaz: 2020-04-22
  rus: 2020-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/120735/kaz/22.04.2020
  rus: https://zan.gov.kz/client/#!/doc/120735/rus/22.04.2020
caused_by:
  code: '142057'
  requisite: Приказ Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 22 апреля 2020 года № 152/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 апреля 2020 года № 20459. Утратил силу приказом Заместителя Премьер-Министра – Министра искусственного интеллекта и цифрового развития Республики Казахстан от 2 июня 2026 года № 279/НҚ (вводится в действие с 12 июля 2026 года)
  title:
    rus: О внесении изменений и дополнений в приказ Министра оборонной и аэрокосмической промышленности Республики Казахстан от 28 марта 2018 года № 53/НҚ «Об утверждении Правил формирования и ведения реестра доверенного программного обеспечения и продукции электронной промышленности, а также критериев по включению программного обеспечения и продукции электронной промышленности в реестр доверенного программного обеспечения и продукции электронной промышленности»
    kaz: «Электрондық өнеркәсіп пен бағдарламалық қамтылымның сенім білдірілген өнімінің тізілімін қалыптастыру және жүргізу қағидаларын, сондай-ақ электрондық өнеркәсіп пен бағдарламалық қамтылымның өнімін электрондық өнеркәсіп пен бағдарламалық қамтылымның сенім білдірілген өнімінің тізіліміне енгізу өлшемшарттарын бекіту туралы» Қазақстан Республикасы Қорғаныс және аэроғарыш өнеркәсібі министрінің 2018 жылғы 28 наурыздағы № 53/НҚ бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142057/rus
