act_code: '145854'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 27 августа 2020 года № 340. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 августа 2020 года № 21140
title:
  rus: Об утверждении Типового положения о системе управления охраной труда
  kaz: Еңбекті қорғауды басқару жүйесі туралы үлгілік ережені бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2020-08-27
approved_by:
- '103016000000'
version_date:
  kaz: 2020-08-27
  rus: 2020-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/145854/kaz/27.08.2020
  rus: https://zan.gov.kz/client/#!/doc/145854/rus/27.08.2020
