act_code: '11072'
requisite: Совместный приказ Министра юстиции Республики Казахстан от 6 декабря 2001 года № 140, Министра внутренних дел Республики Казахстан от 7 декабря 2001 года № 862, Министра здравоохранения Республики Казахстан от 10 декабря 2001 года № 1122. Зарегистрирован Министерством юстиции Республики Казахстан 29 декабря 2001 года № 1717. Утратил силу совместным приказом Министра юстиции Республики Казахстан от 20 ноября 2002 года № 169, Министра внутренних дел Республики Казахстан от 20 ноября 2002 года № 728, Министра здравоохранения Республики Казахстан от 25 сентября 2002 года № 893
title:
  rus: О мерах по предупреждению распространения ВИЧ/СПИДа среди прикрепленного контингента МВД и Министерства юстиции Республики Казахстан
  kaz: Қазақстан Республикасы Iшкіісминi мен Әдiлет министрлiгiне бекiтiлген контингентi арасында ВИЧ/ЖҚТБ инфекциясы таралуын ескерту жөнiндегi шаралар туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2001-12-06
approved_by:
- '103001000000'
- '103003000000'
- '103010000000'
version_date:
  rus: 2002-11-20
source:
  rus: https://zan.gov.kz/client/#!/doc/11072/rus/20.11.2002
