act_code: '149892'
requisite: Совместный приказ Министра внутренних дел Республики Казахстан от 3 сентября 2020 года № 146дсп и Министра здравоохранения Республики Казахстан от 7 октября 2020 года № 641дсп. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 октября 2020 года № 21524
title:
  rus: Об утверждении Правил охраны государственной психиатрической организации специализированного типа с интенсивным наблюдением
  kaz: Қарқынды байқау жасалатын мамандандырылған үлгідегі мемлекеттік психиатриялық ұйымды күзету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-09-03
approved_by:
- '103003000000'
- '103010000000'
version_date:
  kaz: 2020-09-03
  rus: 2020-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/149892/kaz/03.09.2020
  rus: https://zan.gov.kz/client/#!/doc/149892/rus/03.09.2020
