act_code: '85535'
requisite: Приказ Министра энергетики Республики Казахстан от 8 декабря 2014 года № 184. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 декабря 2014 года № 9960
title:
  rus: Об утверждении Правил определения предельной цены на розничную реализацию нефтепродуктов через стационарные автозаправочные станции, на которые установлено государственное регулирование цен, а также на оптовую реализацию для стационарных автозаправочных станций нефтепродуктов, на которые установлено государственное регулирование цен
  kaz: Бағаларына мемлекеттік реттеу белгіленген стационарлық автожанармай құю станциялары арқылы мұнай өнімдерін бөлшек саудада өткізудің, сондай-ақ бағаларына мемлекеттік реттеу белгіленген мұнай өнімдерін стационарлық автожанармай құю станциялары үшін көтерме саудада өткізудің шекті бағаларын айқындау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2014-12-08
approved_by:
- '103036000000'
version_date:
  kaz: 2014-12-08
  rus: 2014-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/85535/kaz/08.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85535/rus/08.12.2014
