act_code: '125153'
requisite: Приказ Министра образования и науки Республики Казахстан от 8 октября 2018 года № 548. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 октября 2018 года № 17520
title:
  rus: Об утверждении Правил отбора претендентов для участия в стипендиальных программах
  kaz: Cтипендиялық бағдарламаларға қатысу үшін үміткерлерді іріктеу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-10-08
approved_by:
- '103006000000'
version_date:
  kaz: 2019-08-29
  rus: 2019-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/125153/kaz/29.08.2019
  rus: https://zan.gov.kz/client/#!/doc/125153/rus/29.08.2019
caused_by:
  code: '134404'
  requisite: Приказ Министра образования и науки Республики Казахстан от 29 августа 2019 года № 389. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 августа 2019 года № 19311
  title:
    rus: О внесении изменения в приказ Министра образования и науки Республики Казахстан от 8 октября 2018 года № 548 «Об утверждении Правил отбора претендентов для участия в стипендиальных программах»
    kaz: «Cтипендиялық бағдарламаларға қатысу үшін үміткерлерді іріктеу қағидаларын бекіту туралы» Қазақстан Республикасы Білім және ғылым министрінің 2018 жылғы 8 қазандағы № 548 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134404/rus
