act_code: '97488'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 2 декабря 2015 года № 19-2/1053. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 декабря 2015 года № 12635. Утратил силу приказом Министра водных ресурсов и ирригации Республики Казахстан от 9 июня 2025 года № 119-НҚ (вводится в действие с 10 июня 2025 года и подлежит официальному опубликованию)
title:
  rus: Об утверждении требований, предъявляемых к организациям, аттестуемым на право проведения работ в области безопасности плотин
  kaz: Бөгеттердің қауіпсіздігі саласындағы жұмыстарды жүргізу құқығына аттестатталатын ұйымдарға қойылатын талаптарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2015-12-02
approved_by:
- '103012000000'
version_date:
  kaz: 2015-12-02
  rus: 2015-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/97488/kaz/02.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97488/rus/02.12.2015
