act_code: '226290'
requisite: Приказ Заместителя Премьер-Министра - Министра культуры и информации Республики Казахстан от 9 июня 2026 года № 279-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 июня 2026 года № 38935
title:
  rus: Об утверждении Типовых правил присвоения звания «Почетный гражданин области (города, района)»
  kaz: «Облыстың (қаланың, ауданның) құрметті азаматы» атағын берудің үлгілік қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2026-06-09
approved_by:
- '103053000000'
version_date:
  kaz: 2026-06-09
  rus: 2026-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/226290/kaz/09.06.2026
  rus: https://zan.gov.kz/client/#!/doc/226290/rus/09.06.2026
