act_code: '88943'
requisite: Приказ Министра финансов Республики Казахстан от 26 ноября 2014 года № 523 и постановление Правления Национального Банка Республики Казахстан от 24 декабря 2014 года № 238. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 февраля 2015 года № 10214. Утратили силу совместным постановлением Правления Агентства Республики Казахстан по регулированию и развитию финансового рынка от 29 октября 2020 года № 104 и приказом Министра финансов Республики Казахстан от 30 октября 2020 года № 1055 (вводятся в действие с 15 ноября 2020 года)
title:
  rus: Об утверждении Требований к Правилам внутреннего контроля в целях противодействия легализации (отмыванию) доходов, полученных преступным путем, и финансированию терроризма для страховых (перестраховочных) организаций и страховых брокеров
  kaz: Қылмыстық жолмен алынған кiрiстердi заңдастыруға (жылыстатуға) және терроризмдi қаржыландыруға қарсы iс-қимыл жасау мақсатында сақтандыру (қайта сақтандыру) ұйымдары және сақтандыру брокерлері үшін ішкі бақылау қағидаларына қойылатын талаптарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2014-11-26
approved_by:
- '103002000000'
- '117000000000'
version_date:
  kaz: 2014-11-26
  rus: 2014-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/88943/kaz/26.11.2014
  rus: https://zan.gov.kz/client/#!/doc/88943/rus/26.11.2014
