act_code: '85823'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 22 ноября 2014 года № 106. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 декабря 2014 года № 10012
title:
  rus: Об утверждении перечня видов физкультурно-спортивных организаций и правил их деятельности, в которых осуществляется учебно-тренировочный процесс по подготовке спортивного резерва и спортсменов высокого класса
  kaz: Спорт резерві мен жоғары дәрежелі спортшыларды даярлау жөніндегі оқу-жаттығу процесі жүзеге асырылатын дене шынықтыру-спорт ұйымдары түрлерінің тізбесін және олардың қызметі қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2014-11-22
approved_by:
- '103034000000'
version_date:
  kaz: 2025-09-18
  rus: 2025-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/85823/kaz/18.09.2025
  rus: https://zan.gov.kz/client/#!/doc/85823/rus/18.09.2025
caused_by:
  code: '214535'
  requisite: Приказ Министра туризма и спорта Республики Казахстан от 18 сентября 2025 года № 177. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 сентября 2025 года № 36892
  title:
    rus: О внесении изменений и дополнений в приказ Министра культуры и спорта Республики Казахстан от 22 ноября 2014 года № 106 «Об утверждении перечня видов физкультурно-спортивных организаций и правил их деятельности, в которых осуществляется учебно-тренировочный процесс по подготовке спортивного резерва и спортсменов высокого класса»
    kaz: «Спорт резерві мен жоғары дәрежелі спортшыларды даярлау жөніндегі оқу-жаттығу үдерісін жүзеге асыратын түрлі дене шынықтыру-спорттық ұйымдарының тізбесін және олардың қызмет қағидаларын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің 2014 жылғы 22 қарашадағы № 106 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214535/rus
