act_code: '32838'
requisite: Приказ Министра транспорта и коммуникаций Республики Казахстан от 28 марта 2007 года N 70. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 апреля 2007 года N 4619
title:
  rus: Об утверждении Правил предоставления услуг локомотивной тяги
  kaz: Локомотивтік тартқыш қызметтерін көрсету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2007-03-28
approved_by:
- '103013000000'
version_date:
  kaz: 2013-08-09
  rus: 2013-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/32838/kaz/09.08.2013
  rus: https://zan.gov.kz/client/#!/doc/32838/rus/09.08.2013
caused_by:
  code: '74329'
  requisite: Приказ и.о. Министра транспорта и коммуникаций Республики Казахстан от 9 августа 2013 года № 626. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 августа 2013 года № 8674
  title:
    rus: О внесении изменения в приказ Министра транспорта и коммуникаций Республики Казахстан от 28 марта 2007 года № 70 "Об утверждении Правил предоставления услуг локомотивной тяги"
    kaz: '"Локомотивтік тартқыш қызметтерін көрсетуді ұсыну ережесін бекіту туралы" Қазақстан Республикасы Көлік және коммуникация министрінің 2007 жылғы 28 наурыздағы № 70 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/74329/rus
