act_code: '51125'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 22 февраля 2010 года № 107. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 марта 2010 года № 6097
title:
  rus: Об утверждении формы обязательства о представлении органам государственной статистики достоверной государственной статистической отчетности о валовом сборе полученного урожая и ежемесячных его расходах
  kaz: Мемлекеттік статистика органдарына алынған өнімнің жалпы түсімі және оның ай сайынғы жұмсалуы туралы дәйекті мемлекеттік статистикалық есептілікті беру туралы міндеттеме нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2010-02-22
approved_by:
- '103012000000'
version_date:
  kaz: 2010-02-22
  rus: 2010-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/51125/kaz/22.02.2010
  rus: https://zan.gov.kz/client/#!/doc/51125/rus/22.02.2010
