act_code: '158085'
requisite: Приказ Министра здравоохранения Республики Казахстан от 20 августа 2021 года № ҚР ДСМ-88. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 августа 2021 года № 24078
title:
  rus: Об определении перечня лекарственных средств и медицинских изделий, закупаемых у единого дистрибьютора
  kaz: Бірыңғай дистрибьютордан сатып алынатын дәрілік заттар мен медициналық бұйымдардың тізбесін айқындау туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2021-08-20
approved_by:
- '103010000000'
version_date:
  kaz: 2025-11-26
  rus: 2025-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/158085/kaz/26.11.2025
  rus: https://zan.gov.kz/client/#!/doc/158085/rus/26.11.2025
caused_by:
  code: '217638'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 26 ноября 2025 года № 155
  title:
    rus: О внесении дополнений в приказ Министра здравоохранения  Республики Казахстан от 20 августа 2021 года № ҚР ДСМ-88  «Об определении перечня лекарственных средств и медицинских изделий, закупаемых у единого дистрибьютора»
    kaz: «Бірыңғай дистрибьютордан сатып алынатын дәрілік заттар мен медициналық бұйымдардың тізбесін айқындау туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2021 жылғы 20 тамыздағы № ҚР ДСМ-88 бұйрығына толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217638/rus
