act_code: '148190'
requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 31 октября 2020 года № ҚР ДСМ-176/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 ноября 2020 года № 21590
title:
  rus: Об утверждении правил обогащения (фортификации) и обращения на рынке пищевой продукции, подлежащей обязательной фортификации
  kaz: Міндетті фортификациялауға жататын тағамдық өнімді байыту (фортификациялау) және оның нарығындағы айналысы қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-10-31
approved_by:
- '103010000000'
version_date:
  kaz: 2020-10-31
  rus: 2020-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/148190/kaz/31.10.2020
  rus: https://zan.gov.kz/client/#!/doc/148190/rus/31.10.2020
