act_code: '174576'
requisite: Приказ Заместителя Премьер-Министра - Министра финансов Республики Казахстан от 28 ноября 2022 года № 1203. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 ноября 2022 года № 30855. Утратил силу приказом Министра финансов Республики Казахстан от 16 августа 2024 года № 552 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении перечня товаров, работ, услуг, по которым государственные закупки осуществляются способом конкурса с использованием расчета стоимости жизненного цикла приобретаемых товаров, работ, услуг
  kaz: Сатып алынатын тауарлардың, жұмыстардың, көрсетілетін қызметтердің өмірлік циклі құнының есептемесі пайдаланылатын конкурс тәсілімен мемлекеттік сатып алу жүзеге асырылатын тауарлардың, жұмыстардың, көрсетілетін қызметтердің тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2022-11-28
approved_by:
- '103002000000'
version_date:
  kaz: 2022-11-28
  rus: 2022-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/174576/kaz/28.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174576/rus/28.11.2022
