act_code: '113340'
requisite: Приказ Министра внутренних дел Республики Казахстан от 6 июня 2017 года № 95 дсп. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 июля 2017 года № 15310
title:
  rus: Об утверждении Содержания и Правил организации профессиональной служебной и физической подготовки сотрудников органов внутренних дел Республики Казахстан
  kaz: Қазақстан Республикасының ішкі істер органдары қызметкерлерінің кәсіби қызметтік және дене шынықтыру даярлығы мазмұнын және ұйымдастыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2017-06-06
approved_by:
- '103003000000'
version_date:
  kaz: 2023-05-11
  rus: 2023-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/113340/kaz/11.05.2023
  rus: https://zan.gov.kz/client/#!/doc/113340/rus/11.05.2023
caused_by:
  code: '182053'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 11 мая 2023 года № 81 дсп
  title:
    rus: О внесении изменений в приказ Министра внутренних дел Республики Казахстан от 6 июня 2017 года № 95 дсп «Об утверждении Содержания и Правил организации профессиональной служебной и физической подготовки сотрудников органов внутренних дел Республики Казахстан»
    kaz: «Қазақстан Республикасының ішкі істер органдары қызметкерлерінің кәсіби қызметтік және дене шынықтыру даярлығы мазмұнын және ұйымдастыру қағидаларын бекіту туралы» Қазақстан Республикасы Ішкі істер министрінің 2017 жылғы 6 маусымдағы № 95 қбпү бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182053/rus
