act_code: '61732'
requisite: Приказ Министра внутренних дел Республики Казахстан от 7 ноября 2011 года № 585. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 ноября 2011 года № 7318. Утратил силу приказом Министра внутренних дел Республики Казахстан от 2 декабря 2015 года № 980
title:
  rus: Об утверждении Инструкции о возмещении затрат на обучение военнослужащим Внутренних войск, проходящим воинскую службу по контракту на должностях солдат, сержантов (старшин) и прослужившим не менее восьми лет в календарном исчислении, в высших учебных заведениях Республики Казахстан на платной основе в размере пятидесяти процентов от стоимости обучения за счет бюджетных средств
  kaz: Ішкі әскерлердің солдаттар, сержанттар (старшиналар) лауазымдарында келісім-шарт бойынша әскери қызмет өткеретін және күнтізбелік есеппен кемінде сегіз жыл қызмет өткерген әскери қызметшілерді Қазақстан Республикасының жоғары оқу орындарында ақылы негізде оқытуға арналған шығыстарын бюджет қаражаты есебінен оқу құнының елу пайызы мөлшерінде өтеу туралы нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2011-11-07
approved_by:
- '103003000000'
version_date:
  kaz: 2011-11-07
  rus: 2011-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/61732/kaz/07.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61732/rus/07.11.2011
