act_code: '158504'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 10 сентября 2021 года № 282. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 сентября 2021 года № 24320
title:
  rus: Об утверждении Правил осуществления систематического сбора информации и анализа содержания интернет-ресурсов на предмет наличия признаков интернет-казино, иностранных букмекерских контор и (или) тотализаторов, не имеющих лицензий на право занятия деятельностью в сфере игорного бизнеса в Республике Казахстан
  kaz: Ақпаратты жүйелі түрде жинауды және интернет-ресурстардың мазмұнын интернет-казино, Қазақстан Республикасында ойын бизнесі саласындағы қызметпен айналысу құқығына лицензиялары жоқ шетелдік букмекерлік кеңселер және (немесе) тотализаторлар белгілерінің болуы-болмауы тұрғысынан талдауды жүзеге асыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2021-09-10
approved_by:
- '103034000000'
version_date:
  kaz: 2024-10-15
  rus: 2024-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/158504/kaz/15.10.2024
  rus: https://zan.gov.kz/client/#!/doc/158504/rus/15.10.2024
caused_by:
  code: '201729'
  requisite: Приказ Министра туризма и спорта Республики Казахстан от 15 октября 2024 года № 181. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 октября 2024 года № 35263
  title:
    rus: О внесении изменений в приказ Министра культуры и спорта Республики Казахстан от 10 сентября 2021 года № 282 «Об утверждении Правил осуществления систематического сбора информации и анализа содержания интернет-ресурсов на предмет наличия признаков интернет-казино»
    kaz: «Ақпаратты жүйелі түрде жинауды және интернет-ресурстардың мазмұнын интернет-казино белгілерінің болуы-болмауы тұрғысынан талдауды жүзеге асыру қағидаларын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің 2021 жылғы 10 қыркүйектегі № 282 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201729/rus
