act_code: '50682'
requisite: Приказ Министра здравоохранения Республики Казахстан от 13 января 2010 года № 13. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 февраля 2010 года № 6048. Отменен приказом Министра здравоохранения Республики Казахстан от 18 мая 2012 года № 362
title:
  rus: Об утверждении санитарных правил "Санитарно-эпидемиологические требования к содержанию и эксплуатации дошкольных организаций образования"
  kaz: '"Білім берудің мектепке дейінгі ұйымдарын күтіп ұстауға және пайдалануға қойылатын санитариялық-эпидемиологиялық талаптар" санитариялық ережесін бекіту туралы'
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2010-01-13
approved_by:
- '103010000000'
version_date:
  kaz: 2010-10-25
  rus: 2010-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50682/kaz/25.10.2010
  rus: https://zan.gov.kz/client/#!/doc/50682/rus/25.10.2010
caused_by:
  code: '55304'
  requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 25 октября 2010 года № 833. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 октября 2010 года № 6597. Отменен приказом Министра здравоохранения Республики Казахстан от 18 мая 2012 года № 362
  title:
    rus: О внесении изменений и дополнения в приказ Министра здравоохранения Республики Казахстан от 13 января 2010 года № 13 "Об утверждении санитарных правил "Санитарно-эпидемиологические требования к содержанию и эксплуатации дошкольных организаций образования"
    kaz: '"Білім берудің мектепке дейінгі ұйымдарын күтіп ұстауға және пайдалануға қойылатын санитариялық-эпидемиологиялық талаптар" санитариялық ережесін бекіту туралы" Қазақстан Республикасы Денсаулық сақтау министрінің 2010 жылғы 13 қаңтардағы № 13 бұйрығына өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/55304/rus
