act_code: '90880'
requisite: Приказ и.о. Министра внутренних дел Республики Казахстан от 19 мая 2015 года № 462. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 июня 2015 года № 11394. Утратил силу приказом Министра внутренних дел Республики Казахстан от 31 марта 2020 года № 276 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в сфере оборота наркотических средств, психотропных веществ и их прекурсоров
  kaz: Есірткі құралдарының, психотроптық заттар мен олардың прекурсорларының айналымы саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2015-05-19
approved_by:
- '103003000000'
version_date:
  kaz: 2015-05-19
  rus: 2015-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/90880/kaz/19.05.2015
  rus: https://zan.gov.kz/client/#!/doc/90880/rus/19.05.2015
