act_code: '168893'
requisite: Приказ и.о. Министра индустрии и инфраструктурного развития Республики Казахстан от 15 июня 2022 года № 342. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 июня 2022 года № 28504
title:
  rus: Об утверждении Правил оказания мер государственного стимулирования промышленности, направленных на продвижение обработанных товаров, работ и услуг казахстанского происхождения на внутренний рынок
  kaz: Қазақстанда шығарылған өңделген тауарларды, жұмыстар мен көрсетілетін қызметтерді ішкі нарыққа ілгерілетуге бағытталған өнеркәсіпті мемлекеттік ынталандыру шараларын көрсету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-06-15
approved_by:
- '103042000000'
version_date:
  kaz: 2022-06-15
  rus: 2022-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/168893/kaz/15.06.2022
  rus: https://zan.gov.kz/client/#!/doc/168893/rus/15.06.2022
