act_code: '21380'
requisite: Приказ и.о. Председателя Агентства Республики Казахстан по регулированию естественных монополий и защите конкуренций от 8 сентября 2004 года N 375-ОД. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 сентября 2004 года № 3092. Утратил силу приказом и.о. Министра национальной экономики Республики Казахстан от 31 июля 2015 года № 580
title:
  rus: О Правилах утверждения временных понижающих коэффициентов к тарифам (ценам, ставкам сборов) на регулируемые услуги магистральной железнодорожной сети и железнодорожных путей с объектами железнодорожного транспорта по договорам концессии
  kaz: Магистральдық темір жол желісінің және концессия шарттары бойынша темір жол көлігінің объектілері бар темір жолдардың реттеліп көрсетілетін қызметтерінің тарифтеріне (бағаларына, алым ставкаларына) уақытша төмендету коэффициенттерін бекіту ережесі туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2004-09-07
approved_by:
- '113000000000'
version_date:
  kaz: 2014-05-14
  rus: 2014-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/21380/kaz/14.05.2014
  rus: https://zan.gov.kz/client/#!/doc/21380/rus/14.05.2014
caused_by:
  code: '80546'
  requisite: Приказ Председателя Агентства Республики Казахстан по регулированию естественных монополий от 14 мая 2014 года № 102-ОД. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 июня 2014 года № 9477. Утратил силу приказом и.о. Министра национальной экономики Республики Казахстан от 31 июля 2015 года № 580
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Председателя Агентства Республики Казахстан по регулированию естественных монополий и защите конкуренции от 8 сентября 2004 года № 375-ОД "О Правилах утверждения временных понижающих коэффициентов к тарифам (ценам, ставкам сборов) на регулируемые услуги магистральной железнодорожной сети и железнодорожных путей с объектами железнодорожного транспорта по договорам концессии"
    kaz: '"Магистральдық темір жол желісінің және концессия шарттары бойынша темір жол көлігінің объектілері бар темір жолдардың реттеліп көрсетілетін қызметтерінің тарифтеріне (бағаларына, алым ставкаларына) уақытша төмендету коэффициенттерін бекіту ережесі туралы" Қазақстан Республикасының Табиғи монополияларды реттеу және бәсекелестікті қорғау жөніндегі агенттігі төрағасының міндетін атқарушының 2004 жылғы 8 қыркүйектегі № 375-НҚ бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/80546/rus
