act_code: '92604'
requisite: Приказ Министра энергетики Республики Казахстан от 9 июня 2015 года № 393. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 июля 2015 года № 11815. Утратил силу приказом и.о. Министра энергетики Республики Казахстан от 7 декабря 2018 года № 483 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в сфере недропользования
  kaz: Жер қойнауын пайдалану саласындағы мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2015-06-09
approved_by:
- '103036000000'
version_date:
  kaz: 2015-06-09
  rus: 2015-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/92604/kaz/09.06.2015
  rus: https://zan.gov.kz/client/#!/doc/92604/rus/09.06.2015
