act_code: '93642'
requisite: Приказ Министра обороны Республики Казахстан от 13 июля 2015 года № 404ДСП. Зарегистрирован в Министерстве юстиции Республики Казахстан  09 сентября 2015 года № 12037
title:
  rus: Об утверждении Норм снабжения органов военной полиции специальной техникой, средствами, оборудованием и имуществом, а также иным имуществом для воинских частей и учреждений, обеспечиваемых Главным управлением военной полиции Вооруженных Сил Республики Казахстан
  kaz: Әскери полиция органдарын арнайы техникамен, құралдармен, жабдықпен және мүлікпен, сондай-ақ Қазақстан Республикасы Қарулы Күштерінің Әскери полициясы бас басқармасы қамтамасыз ететін әскери бөлімдер мен мекемелерге арналған өзге де  мүлікпен жабдықтау нормаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2015-07-13
approved_by:
- '103008000000'
version_date:
  kaz: 2015-07-13
  rus: 2015-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/93642/kaz/13.07.2015
  rus: https://zan.gov.kz/client/#!/doc/93642/rus/13.07.2015
