act_code: '202313'
requisite: Приказ и.о. Министра водных ресурсов и ирригации Республики Казахстан от 31 октября 2024 года № 172-нқ
title:
  rus: Об утверждении Положения о научно-техническом совете
  kaz: Ғылыми-техникалық кеңес туралы ережені бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2024-10-31
approved_by:
- '103050000000'
version_date:
  kaz: 2025-03-11
  rus: 2025-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/202313/kaz/11.03.2025
  rus: https://zan.gov.kz/client/#!/doc/202313/rus/11.03.2025
caused_by:
  code: '208168'
  requisite: Приказ Министра водных ресурсов и ирригации Республики Казахстан от 11 марта 2025 года № 42-нқ
  title:
    rus: О внесении изменения и дополнения в приказ исполняющего обязанности Министра водных ресурсов и ирригации Республики Казахстан от 31 октября 2024 года № 172-НҚ «Об утверждении Положения о научно-техническом совете»
    kaz: «Ғылыми-техникалық кеңес туралы ережені бекіту туралы» Қазақстан Республикасы Су ресурстары және ирригация министрі міндетін атқарушының 2024 жылғы 31 қазандағы № 172-НҚ бұйрығына өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208168/rus
