act_code: '88790'
requisite: Приказ Министра национальной экономики Республики Казахстан от 6 марта 2015 года № 188. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 апреля 2015 года № 10672
title:
  rus: Об утверждении Перечня кодов, присваиваемых областям, городам республиканского значения, столице, районам и городам областного (районного) значения для целей формирования кадастровых номеров земельных участков
  kaz: Жер учаскелерiнiң кадастрлық нөмiрлерiн қалыптастыру мақсаттары үшін облыстарға, республикалық маңызы бар қалаларға, астанаға, аудандарға және облыстық (аудандық) маңызы бар қалаларға берiлетiн кодтардың тiзбесiн бекiту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2015-03-06
approved_by:
- '103033000000'
version_date:
  kaz: 2015-03-06
  rus: 2015-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/88790/kaz/06.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88790/rus/06.03.2015
