act_code: '90994'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 6 апреля 2015 года № 4-4/305. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 мая 2015 года № 11223. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 25 мая 2020 года № 181 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил субсидирования стоимости удобрений (за исключением органических)
  kaz: Тыңайтқыштардың құнын (органикалық тыңайтқыштарды қоспағанда) субсидиялау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-04-06
approved_by:
- '103012000000'
version_date:
  kaz: 2019-05-27
  rus: 2019-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/90994/kaz/27.05.2019
  rus: https://zan.gov.kz/client/#!/doc/90994/rus/27.05.2019
caused_by:
  code: '131898'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 27 мая 2019 года № 211. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 мая 2019 года № 18742. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 25 мая 2020 года № 181 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра сельского хозяйства Республики Казахстан от 6 апреля 2015 года № 4-4/305 «Об утверждении Правил субсидирования стоимости удобрений (за исключением органических)»
    kaz: «Тыңайтқыштардың құнын (органикалық тыңайтқыштарды қоспағанда) субсидиялау қағидаларын бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің 2015 жылғы 6 сәуірдегі № 4-4/305 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131898/rus
