act_code: '103994'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 26 мая 2016 года № 236
title:
  rus: Об утверждении Положения Комитета по управлению земельными ресурсами Министерства сельского хозяйства Республики Казахстан
  kaz: Қазақстан Республикасы Ауыл шаруашылығы министрлігінің Жер ресурстарын басқару комитетінің ережесін бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2016-05-26
approved_by:
- '103012000000'
version_date:
  kaz: 2026-02-04
  rus: 2026-02-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/103994/kaz/04.02.2026
  rus: https://zan.gov.kz/client/#!/doc/103994/rus/04.02.2026
caused_by:
  code: '221930'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 4 февраля 2026 года № 45
  title:
    rus: О внесении изменения и дополнения в приказ Министра сельского хозяйства Республики Казахстан от 26 мая 2016 года № 236 «Об утверждении Положения о Комитете по управлению земельными ресурсами Министерства сельского хозяйства Республики Казахстан»
    kaz: «Қазақстан Республикасы Ауыл шаруашылығы министрлігінің Жер ресурстарын басқару комитетінің ережесін бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің 2016 жылғы 26 мамырдағы № 236 бұйрығына өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/221930/rus
