act_code: '54293'
requisite: Приказ и.о. Министра экономического развития и торговли Республики Казахстан от 6 августа 2010 года № 136. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 августа 2010 года № 6402. Утратил силу приказом Заместителя Премьер-Министра - Министра национальной экономики Республики Казахстан от 23 декабря 2025 года № 133 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Требований к разработке или корректировке, а также проведению необходимых экспертиз технико-экономического обоснования инвестиционного проекта для предоставления государственных гарантий
  kaz: Мемлекеттік кепілдіктер беру үшін инвестициялық жобаның техникалық-экономикалық негіздемесін әзірлеуге немесе түзетуге, сондай-ақ қажетті сараптамалар жүргізуге қойылатын талаптарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2010-08-06
approved_by:
- '103005000000'
version_date:
  kaz: 2010-08-06
  rus: 2010-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/54293/kaz/06.08.2010
  rus: https://zan.gov.kz/client/#!/doc/54293/rus/06.08.2010
