act_code: '31687'
requisite: Приказ Генерального Прокурора Республики Казахстан от 28 декабря 2006 года № 79. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 января 2007 года № 4530. Утратил силу приказом Генерального Прокурора Республики Казахстан от 20 апреля 2016 года № 79
title:
  rus: Об утверждении статистического отчета формы № 1-У "Сведения об усыновлении и удочерении детей, в том числе иностранными гражданами" и Инструкции по его составлению
  kaz: '"Бала асырап алу, соның ішінде шетел азаматтарының бала асырап алуы туралы мәліметтер" № 1-У нысанды статистикалық есепті және оны құру бойынша Нұсқаулықты бекіту туралы'
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2006-12-28
approved_by:
- '107000000000'
version_date:
  kaz: 2006-12-28
  rus: 2006-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/31687/kaz/28.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31687/rus/28.12.2006
