act_code: '67424'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 24 июля 2012 года № 294-ө-м. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 августа 2012 года № 7883. Утратил силу приказом Министра труда и социальной защиты населения Республики Казахстан от 18 марта 2020 года № 102 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Единого тарифно-квалификационного справочника работ и профессий рабочих (выпуск 61)
  kaz: Жұмысшылардың жұмыстары мен кәсіптерінің бірыңғай тарифтік-біліктілік анықтамалығын (61-шығарылым) бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- СПРА
approved_on: 2012-07-24
approved_by:
- '103016000000'
version_date:
  kaz: 2012-07-24
  rus: 2012-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/67424/kaz/24.07.2012
  rus: https://zan.gov.kz/client/#!/doc/67424/rus/24.07.2012
