act_code: '91324'
requisite: Приказ от 22.06.2015 № 499, Министерство здравоохранения и социального развития Республики Казахстан. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 июня 2015 года № 11513. Утратил силу приказом Министра здравоохранения и социального развития РК от 18.09.2015 № 732
title:
  rus: Об определении размера черты бедности на 3 квартал 2015 года
  kaz: 2015 жылғы 3-тоқсанға арналған кедейлік шегінің мөлшерін айқындау туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2015-06-22
approved_by:
- '103037000000'
version_date:
  kaz: 2015-06-22
  rus: 2015-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/91324/kaz/22.06.2015
  rus: https://zan.gov.kz/client/#!/doc/91324/rus/22.06.2015
