act_code: '143348'
requisite: Приказ Министра образования и науки Республики Казахстан от 11 мая 2020 года № 191. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 мая 2020 года № 20622
title:
  rus: Об утверждении Правил исчисления заработной платы педагогов государственных организаций
  kaz: Мемлекеттік ұйымдар Педагогтарінің жалақысын есептеу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-05-11
approved_by:
- '103006000000'
version_date:
  kaz: 2020-05-11
  rus: 2020-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/143348/kaz/11.05.2020
  rus: https://zan.gov.kz/client/#!/doc/143348/rus/11.05.2020
