act_code: '349'
requisite: Приказ Министра финансов Республики Казахстан от 18 сентября 1995 г. N 239. Зарегистрирован в Министерстве юстиции РК 10.10.1995г. N 109. Отменен - постановлением Правительства РК от 9 февраля 2005 года N 124 (P050124)
title:
  rus: Об утверждении Инструкции по составлению финансового плана и прогнозированию потока наличности
  kaz: Қаржы жоспарын жасау және қолма-қол ақша тасқынын болжамдау жөнiндегi нұсқаулықты бекiту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 1995-09-17
approved_by:
- '103002000000'
version_date:
  kaz: 2002-02-19
  rus: 2002-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/349/kaz/19.02.2002
  rus: https://zan.gov.kz/client/#!/doc/349/rus/19.02.2002
caused_by:
  code: '11533'
  requisite: Приказ Министра финансов Республики Казахстан от 19 февраля 2002 года N 71. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 марта 2002 года N 1792. Утратил силу приказом Министра финансов Республики Казахстан от 16 августа 2006 года N 304
  title:
    rus: О внесении изменений и дополнений в некоторые приказы Министра финансов Республики Казахстан
    kaz: Қазақстан Республикасы Қаржы министрлігінің кейбір бұйрықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/11533/rus
