act_code: '2188'
requisite: Приказ Национального пенсионного агентства Министерства труда и социальной защиты населения Республики Казахстан от 13 октября 1997 года N 10-П. Зарегистрирован в Министерстве юстиции Республики Казахстан 13.11.1997 г. за N 417. Утратил силу - постановлением Правления Нацбанка РК от 4 июля 2003 г. N 213
title:
  rus: Об утверждении Правил ведения бухгалтерского учета в накопительных пенсионных фондах и представления финансовой отчетности
  kaz: Жинақтаушы зейнетақы қорларында бухгалтерлiк есеп жүргiзу және қаржылық есеп тапсыру ережелерi
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 1997-10-12
approved_by:
- '103016001000'
version_date:
  rus: 1998-12-18
source:
  rus: https://zan.gov.kz/client/#!/doc/2188/rus/18.12.1998
caused_by:
  code: '2154'
  requisite: Приказ Национального пенсионного агентства Министерства труда и социальной защиты населения Республики Казахстан от 18 декабря 1998 года № 175-П. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 января 1999 года № 670. Утратил силу постановлением Правления Нацбанка Республики Казахстан от 4 июля 2003 года № 213
  title:
    rus: Об утверждении изменений и дополнений в "Положение по ведению бухгалтерского учета и финансовой отчетности в накопительных пенсионных фондах", утвержденное приказом Национального пенсионного агентства Министерства труда и социальной защиты населения Республики Казахстан от 13 октября 1997 года № 10-П (Государственная регистрация от 13 ноября 1997 года № 417)
    kaz: Қазақстан Республикасының Еңбек және халықты әлеуметтік қорғау министрлiгi Ұлттық зейнетақы агенттiгiнiң 1997 жылғы 13 қазандағы № 10-ө бұйрығымен бекiтiлген (1997 жылғы 13 қарашадағы мемлекеттік тiркеу № 417) "Жинақтаушы зейнетақы қорларындағы бухгалтерлiк есеп жүргiзу және қаржылық есеп беру жөніндегi ережеге" өзгерiстер мен толықтырулар енгiзу туралы
  link: https://zan.gov.kz/client/#!/doc/2154/rus
