act_code: '213765'
requisite: Приказ Министра по чрезвычайным ситуациям Республики Казахстан от 29 августа 2025 года № 379. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 августа 2025 года № 36745
title:
  rus: Об утверждении перечня объектов с массовым пребыванием людей с площадью более двух тысяч квадратных метров, подлежащих страхованию в области пожарной безопасности, а также типового договора вмененного страхования гражданско-правовой ответственности владельцев объектов с массовым пребыванием людей за причинение вреда жизни, здоровью и имуществу третьих лиц
  kaz: Өрт қауіпсіздігі саласында сақтандырылуға жататын, алаңы екі мың шаршы метрден асатын, адамдар жаппай болатын объектілердің тізбесін, сондай-ақ үшінші тұлғалардың өміріне, денсаулығына және мүлкіне зиян келтіргені үшін адамдар жаппай болатын объектілер иелерінің азаматтық-құқықтық жауапкершілігін жүктелген сақтандырудың үлгілік шартын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2025-08-29
approved_by:
- '103007000000'
version_date:
  kaz: 2025-08-29
  rus: 2025-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/213765/kaz/29.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213765/rus/29.08.2025
