act_code: '87998'
requisite: Приказ Министра энергетики Республики Казахстан от 20 февраля 2015 года № 111. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 марта 2015 года № 10533
title:
  rus: Об утверждении Правил организации и функционирования розничного рынка электрической энергии, а также предоставления услуг на данном рынке
  kaz: Электр энергиясының бөлшек сауда нарығын ұйымдастыру және оның жұмыс істеуі, сондай-ақ осы нарықта қызмет көрсету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-02-20
approved_by:
- '103036000000'
version_date:
  kaz: 2016-05-17
  rus: 2016-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/87998/kaz/17.05.2016
  rus: https://zan.gov.kz/client/#!/doc/87998/rus/17.05.2016
caused_by:
  code: '104483'
  requisite: Приказ Министра энергетики Республики Казахстан от 17 мая 2016 года № 209. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 июля 2016 года № 13805
  title:
    rus: О внесении изменений и дополнения в некоторые приказы Министра энергетики Республики Казахстан
    kaz: Қазақстан Республикасы Энергетика министрінің кейбір бұйрықтарына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104483/rus
