act_code: '114577'
requisite: Приказ Министра национальной экономики Республики Казахстан от 7 августа 2017 года № 295. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 сентября 2017 года № 15630
title:
  rus: Об утверждении Типового регламента собрания местного сообщества
  kaz: Жергілікті қоғамдастық жиналысының үлгі регламентін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2017-08-07
approved_by:
- '103033000000'
version_date:
  kaz: 2021-06-21
  rus: 2021-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/114577/kaz/21.06.2021
  rus: https://zan.gov.kz/client/#!/doc/114577/rus/21.06.2021
caused_by:
  code: '156604'
  requisite: Приказ Министра национальной экономики Республики Казахстан от 21 июня 2021 года № 65. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 июня 2021 года № 23187
  title:
    rus: О внесении изменений в приказ Министра национальной экономики Республики Казахстан от 7 августа 2017 года № 295 «Об утверждении Типового регламента собрания местного сообщества»
    kaz: «Жергілікті қоғамдастық жиналысының үлгі регламентін бекіту туралы» Қазақстан Республикасы Ұлттық экономика министрінің 2017 жылғы 7 тамыздағы № 295 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156604/rus
