act_code: '4850'
requisite: Совместный приказ Министерства внутренних дел Республики Казахстан от 13 мая 1997 года № 132 и Государственного Таможенного комитета Республики Казахстан от 13 мая 1997 года № 125. Зарегистрирован в Министерстве юстиции Республики Казахстан 24.08.1998 г. за № 583. Утратил силу - приказом Председателя Агентства таможенного контроля Республики Казахстан от 9 января 2004 года N 6
title:
  rus: '"О порядке ввоза на территорию Республики Казахстан систем безопасности, аппаратуры, оборудования, других технических средств для охраны объектов и обособленных помещений"'
  kaz: Қазақстан Республикасының аумағына қауіпсіздік жүйелерін, аппаратураларды, жабдықтарды, объектілер мен оқшауландырылған үй-жайларды күзетуге арналған басқBа да техникалық құралдарды әкелудің тәртібі туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 1997-05-12
approved_by:
- '103002004000'
- '103003000000'
version_date:
  kaz: 1997-05-12
  rus: 1997-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/4850/kaz/12.05.1997
  rus: https://zan.gov.kz/client/#!/doc/4850/rus/12.05.1997
