act_code: '49044'
requisite: Приказ Министра здравоохранения Республики Казахстан от 18 ноября 2009 года № 737. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 ноября 2009 года № 5931. Утратил силу приказом Министра здравоохранения Республики Казахстан от 20 марта 2013 года № 167
title:
  rus: О некоторых вопросах выдачи разрешения на рекламу
  kaz: Жарнамалауға рұқсат берудің кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2009-11-18
approved_by:
- '103010000000'
version_date:
  kaz: 2009-11-18
  rus: 2009-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/49044/kaz/18.11.2009
  rus: https://zan.gov.kz/client/#!/doc/49044/rus/18.11.2009
