act_code: '160672'
requisite: Приказ Министра финансов Республики Казахстан от 24 ноября 2021 года № 1216. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 ноября 2021 года № 25414
title:
  rus: Об утверждении Правил работы веб-порталов закупок отдельных субъектов квазигосударственного сектора, за исключением Фонда национального благосостояния и организаций Фонда национального благосостояния, в том числе в случае возникновения технических сбоев в работе веб-порталов
  kaz: Ұлттық әл-ауқат қорын және Ұлттық әл-ауқат қорының ұйымдарын қоспағанда, квазимемлекеттік сектордың жекелеген субъектілерінің сатып алу веб-порталдарының жұмыс істеу, оның ішінде веб-порталдар жұмысында техникалық іркілістер туындаған жағдайда жұмыс істеу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2021-11-24
approved_by:
- '103002000000'
version_date:
  kaz: 2024-06-21
  rus: 2024-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/160672/kaz/21.06.2024
  rus: https://zan.gov.kz/client/#!/doc/160672/rus/21.06.2024
caused_by:
  code: '197948'
  requisite: Приказ Министра финансов Республики Казахстан от 21 июня 2024 года № 385. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 июня 2024 года № 34544
  title:
    rus: О внесении изменений в некоторые приказы Министра финансов Республики Казахстан
    kaz: Қазақстан Республикасы Қаржы министрінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/197948/rus
