act_code: '97450'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 30 ноября 2015 года № 19-1/1051. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 декабря 2015 года № 12626. Утратил силу приказом Министра водных ресурсов и ирригации Республики Казахстан от 4 июня 2025 года № 106-НҚ (вводится в действие с 10 июня 2025 года)
title:
  rus: Об утверждении формы заявления на получение разрешения на специальное водопользование и формы разрешения на специальное водопользование
  kaz: Арнайы су пайдалануға рұқсат алуға өтініштің нысанын және арнайы су пайдалануға рұқсаттың нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2015-11-30
approved_by:
- '103012000000'
version_date:
  kaz: 2015-11-30
  rus: 2015-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/97450/kaz/30.11.2015
  rus: https://zan.gov.kz/client/#!/doc/97450/rus/30.11.2015
