act_code: '21957'
requisite: Приказ Председателя Комитета по делам строительства и жилищно-коммунального хозяйства Министерства индустрии и торговли Республики Казахстан от 20 октября 2004 года N 406. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 ноября 2004 года N 3213. Утратил силу приказом и.о. Министра национальной экономики Республики Казахстан от 17 апреля 2015 года № 342
title:
  rus: Об утверждении Правил организации и ведения авторского надзора
  kaz: Авторлық қадағалауды ұйымдастыру және жүргізу ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2004-10-19
approved_by:
- '103017003000'
version_date:
  kaz: 2004-10-19
  rus: 2004-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/21957/kaz/19.10.2004
  rus: https://zan.gov.kz/client/#!/doc/21957/rus/19.10.2004
