act_code: '126259'
requisite: Приказ Заместителя Премьер-Министра Республики Казахстан - Министра сельского хозяйства Республики Казахстан от 27 ноября 2018 года № 477. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 ноября 2018 года № 17812. Утратил силу приказом и.о. Министра сельского хозяйства Республики Казахстан от 2 декабря 2024 года № 389 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О некоторых мерах по реализации Государственной программы развития продуктивной занятости и массового предпринимательства на 2017-2021 годы «Еңбек»
  kaz: «Еңбек» нәтижелі жұмыспен қамтуды және жаппай кәсіпкерлікті дамытудың 2017-2021 жылдарға арналған мемлекеттік бағдарламасын іске асыру жөніндегі кейбір шаралар туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-11-27
approved_by:
- '103012000000'
version_date:
  kaz: 2021-09-15
  rus: 2021-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/126259/kaz/15.09.2021
  rus: https://zan.gov.kz/client/#!/doc/126259/rus/15.09.2021
caused_by:
  code: '158994'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 15 сентября 2021 года № 273. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 сентября 2021 года № 24427. Утратил силу приказом и.о. Министра сельского хозяйства Республики Казахстан от 2 декабря 2024 года № 389 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Заместителя Премьер-Министра Республики Казахстан – Министра сельского хозяйства Республики Казахстан от 27 ноября 2018 года № 477 «О некоторых мерах по реализации Государственной программы развития продуктивной занятости и массового предпринимательства на 2017-2021 годы «Еңбек»
    kaz: «Еңбек» нәтижелі жұмыспен қамтуды және жаппай кәсіпкерлікті дамытудың 2017-2021 жылдарға арналған мемлекеттік бағдарламасын іске асыру жөніндегі кейбір шаралар туралы» Қазақстан Республикасы Премьер-Министрінің орынбасары – Қазақстан Республикасы Ауыл шаруашылығы министрінің 2018 жылғы 27 қарашадағы № 477 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158994/rus
