act_code: '93409'
requisite: Приказ от 30.07.2015 № 263, Министерство культуры и спорта Республики Казахстан. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 сентября 2015 года № 11996
title:
  rus: О распределении стипендии Президента Республики Казахстан по высшим учебным заведениям на 2015 год
  kaz: Қазақстан Республикасы Президентінің 2015 жылға арналған стипендиясын жоғары оқу орындары бойынша бөлу туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2015-07-30
approved_by:
- '103034000000'
version_date:
  kaz: 2015-07-30
  rus: 2015-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/93409/kaz/30.07.2015
  rus: https://zan.gov.kz/client/#!/doc/93409/rus/30.07.2015
