act_code: '24574'
requisite: Приказ и.о. Министра внутренних дел Республики Казахстан от 23 апреля 2005 года № 242. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 июня 2005 года за № 3680. Утратил силу приказом Министра внутренних дел Республики Казахстан от 22 октября 2011 года № 559
title:
  rus: Об утверждении Правил хранения, учета, использования, перевозки, уничтожения, ввоза, вывоза гражданских пиротехнических веществ и изделий с их применением
  kaz: Азаматтық пиротехникалық заттарды және олардың қолданылуымен жасалған бұйымдарды сақтау, есепке алу, пайдалану, тасымалдау, жою, әкелу, әкету ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2005-04-23
approved_by:
- '103003000000'
version_date:
  kaz: 2005-04-23
  rus: 2005-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/24574/kaz/23.04.2005
  rus: https://zan.gov.kz/client/#!/doc/24574/rus/23.04.2005
