act_code: '108626'
requisite: Приказ Министра финансов Республики Казахстан от 30 ноября 2016 года № 629. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 декабря 2016 года № 14623. Утратил силу приказом Министра финансов Республики Казахстан от 9 июня 2025 года № 290 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Инструкции по проведению бюджетного мониторинга
  kaz: Бюджеттік мониторинг жүргізу нұсқаулығын бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2016-11-30
approved_by:
- '103002000000'
version_date:
  kaz: 2022-02-14
  rus: 2022-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/108626/kaz/14.02.2022
  rus: https://zan.gov.kz/client/#!/doc/108626/rus/14.02.2022
caused_by:
  code: '164670'
  requisite: Приказ Министра финансов Республики Казахстан от 14 февраля 2022 года № 164. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 февраля 2022 года № 26862. Утратил силу приказом Министра финансов Республики Казахстан от 9 июня 2025 года № 290 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра финансов Республики Казахстан от 30 ноября 2016 года № 629 «Об утверждении Инструкции по проведению бюджетного мониторинга»
    kaz: «Бюджеттік мониторинг жүргізу нұсқаулығын бекіту туралы» Қазақстан Республикасы Қаржы министрінің 2016 жылғы 30 қарашадағы № 629 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164670/rus
