act_code: '66511'
requisite: Приказ Министра здравоохранения Республики Казахстан от 25 мая 2012 года № 374. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 июня 2012 года № 7748. Утратил силу приказом и.о. Министра здравоохранения Республики Казахстан от 30 сентября 2022 года № ҚР ДСМ-106 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Положения о деятельности организаций здравоохранения, оказывающих медицинскую помощь по профессиональной патологии населению Республики Казахстан
  kaz: Қазақстан Республикасының халқына кәсіптік патология бойынша медициналық көмек көрсететін денсаулық сақтау ұйымдарының қызметі туралы ережені бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2012-05-25
approved_by:
- '103010000000'
version_date:
  kaz: 2012-05-25
  rus: 2012-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/66511/kaz/25.05.2012
  rus: https://zan.gov.kz/client/#!/doc/66511/rus/25.05.2012
