act_code: '184810'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 2 августа 2023 года № 212. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 августа 2023 года № 33251
title:
  rus: Об утверждении Правил функционирования системы гарантирования прав граждан Республики Казахстан в сфере выездного туризма, суммы денег, подлежащих обеспечению банковской гарантией для туроператоров и туроператоров-фрахтователей, осуществляющих деятельность в сфере выездного туризма, суммы денег, подлежащих перечислению на банковский счет, открытый специально для администратора системы гарантирования прав граждан Республики Казахстан в сфере выездного туризма
  kaz: Қазақстан Республикасы азаматтарының шығу туризмі саласындағы құқықтарына кепілдік беру жүйесінің жұмыс істеу қағидаларын, шығу туризмі саласында қызметті жүзеге асыратын туроператорлар мен туроператорлар-әуе кемесімен жалданушылар үшін банктік кепілдікпен қамтамасыз етуге жататын ақша сомасын, Қазақстан Республикасы азаматтарының шығу туризм саласындағы құқықтарына кепілдік беру жүйесінің әкімшісі үшін арнаулы ашылған банктік шотқа аударылуға жататын ақша сомасын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2023-08-02
approved_by:
- '103034000000'
version_date:
  kaz: 2023-08-02
  rus: 2023-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/184810/kaz/02.08.2023
  rus: https://zan.gov.kz/client/#!/doc/184810/rus/02.08.2023
