act_code: '90410'
requisite: Приказ Министра национальной экономики Республики Казахстан от 24 апреля 2015 года № 355. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 июня 2015 года № 11251. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 1 октября 2020 года № 301 (вводится в действие по истечении двадцати одного календарного дня после дня его первого официального опубликования)
title:
  rus: Об утверждении регламентов государственных услуг в сфере земельных отношений
  kaz: Жер қатынастары саласында мемлекеттік көрсетілетін қызметтер регламенттерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2015-04-24
approved_by:
- '103033000000'
version_date:
  kaz: 2019-06-10
  rus: 2019-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/90410/kaz/10.06.2019
  rus: https://zan.gov.kz/client/#!/doc/90410/rus/10.06.2019
caused_by:
  code: '132533'
repealed_on: 2020-10-31
repealed_by:
  code: '147086'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 1 октября 2020 года № 301. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 октября 2020 года № 21366
  title:
    rus: Об утверждении Правил по оказанию государственных услуг в сфере земельных отношений
    kaz: Жер қатынастары саласындағы мемлекеттік қызметтерді көрсету жөніндегі қағидаларды бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/147086/rus
