act_code: '35108'
requisite: Приказ и.о. Министра юстиции Республики Казахстан от 24 августа 2007 года № 244. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 сентября 2007 года № 4939
title:
  rus: Об утверждении Правил выдачи дубликата и аннулирования подлинника (удостоверенной копии) утраченного или поврежденного правоустанавливающего документа
  kaz: Жоғалған немесе бүлінген құқық белгілейтін құжаттың телнұсқасын беру және түпнұсқасының (куәландырылған көшірмесінің) күшін жою қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2007-08-24
approved_by:
- '103001000000'
version_date:
  kaz: 2008-10-01
  rus: 2008-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/35108/kaz/01.10.2008
  rus: https://zan.gov.kz/client/#!/doc/35108/rus/01.10.2008
caused_by:
  code: '42010'
  requisite: Приказ Министра юстиции Республики Казахстан от 1 октября 2008 года № 258. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 октября 2008 года № 5337
  title:
    rus: О внесении изменений и дополнений в приказ и.о. Министра юстиции Республики Казахстан от 24 августа 2007 года № 244 "Об утверждении Правил выдачи дубликата и аннулирования подлинника (удостоверенной копии) утраченного или поврежденного правоустанавливающего документа"
    kaz: Қазақстан Республикасы Әділет министрінің м.а. "Жоғалған немесе бүлінген құқық белгілейтін құжаттың телнұсқасын беру және түпнұсқасының (куәландырылған көшірмесінің) күшін жою ережесін бекіту туралы" 2007 жылғы 24 тамыздағы N 244 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/42010/rus
