act_code: '90820'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 30 апреля 2015 года № 529. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 июня 2015 года № 11327. Утратил силу приказом Министра индустрии и инфраструктурного развития Республики Казахстан от 13 мая 2020 года № 286 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении стандартов государственных услуг в области автомобильных дорог
  kaz: Автомобиль жолдары саласындағы мемлекеттік көрсетілетін қызмет стандарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2015-04-30
approved_by:
- '103035000000'
version_date:
  kaz: 2018-06-22
  rus: 2018-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/90820/kaz/22.06.2018
  rus: https://zan.gov.kz/client/#!/doc/90820/rus/22.06.2018
caused_by:
  code: '121994'
  requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 12 января 2018 года № 23. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 мая 2018 года № 16931. Утратил силу приказом Министра индустрии и инфраструктурного развития Республики Казахстан от 6 июня 2019 года № 371 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в некоторые приказы Министра по инвестициям и развитию Республики Казахстан в области автомобильных дорог
    kaz: Автомобиль жолдары саласындағы Қазақстан Республикасы Инвестициялар және даму министрінің кейбір бұйрықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/121994/rus
