act_code: '81528'
requisite: Приказ Заместителя Премьер-Министра Республики Казахстан - Министра индустрии и новых технологий Республики Казахстан от 13 июня 2014 года № 215. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 июля 2014 года № 9582
title:
  rus: Об утверждении Правил изготовления, хранения и применения поверительных клейм
  kaz: Салыстырып тексеру таңбаларын дайындау, сақтау және қолдану қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2014-06-13
approved_by:
- '103021000000'
version_date:
  kaz: 2014-06-13
  rus: 2014-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/81528/kaz/13.06.2014
  rus: https://zan.gov.kz/client/#!/doc/81528/rus/13.06.2014
