act_code: '86046'
requisite: Приказ Министра здравоохранения и социального развития Республики Казахстан от 11 декабря 2014 года № 312. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 января 2015 года № 10090
title:
  rus: Об утверждении форм, предназначенных для сбора административных данных и пояснений по их заполнению
  kaz: Әкiмшiлiк деректердi жинауға арналған нысандарды және оларды толтыру бойынша түсіндірмелерді бекiту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2014-12-11
approved_by:
- '103037000000'
version_date:
  kaz: 2014-12-11
  rus: 2014-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/86046/kaz/11.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86046/rus/11.12.2014
