act_code: '68800'
requisite: Приказ и.о Министра индустрии и новых технологий Республики Казахстан от 10 октября 2012 года № 376. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 ноября 2012 года № 8087. Утратил силу приказом Заместителя Премьер-Министра Республики Казахстан - Министра индустрии и новых технологий Республики Казахстан от 6 мая 2014 года № 156
title:
  rus: Об утверждении Регламента оказания государственной услуги "Согласование проектирования и строительства дублирующих (шунтирующих) линий электропередачи и подстанций"
  kaz: '"Қосалқы (шунтталатын) электр беру желілері мен шағын станцияларды жобалауды және салуды келісу" мемлекеттік қызметін көрсету регламентін бекіту туралы'
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2012-10-10
approved_by:
- '103017000000'
version_date:
  kaz: 2012-10-10
  rus: 2012-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/68800/kaz/10.10.2012
  rus: https://zan.gov.kz/client/#!/doc/68800/rus/10.10.2012
