act_code: '212433'
requisite: Приказ и.о. Министра науки и высшего образования Республики Казахстан от 16 июля 2025 года № 381
title:
  rus: О размещении государственного образовательного заказа на обучение слушателей подготовительных отделений организаций высшего и (или) послевузовского образования Республики Казахстан на 2025-2026 учебный год
  kaz: 2025-2026 оқу жылына Қазақстан Республикасы жоғары және (немесе) жоғары оқу орнынан кейінгі білім беру ұйымдарының дайындық бөлімдерінің тыңдаушыларын оқытуға мемлекеттік білім беру тапсырысын орналастыру туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-07-16
approved_by:
- '103049000000'
version_date:
  kaz: 2025-07-16
  rus: 2025-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/212433/kaz/16.07.2025
  rus: https://zan.gov.kz/client/#!/doc/212433/rus/16.07.2025
