act_code: '57816'
requisite: Совместный приказ Министра здравоохранения Республики Казахстан от 31 января 2011 года № 60 и Министра экономического развития и торговли Республики Казахстан от 25 февраля 2011 года № 44. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 марта 2011 года № 6815. Утратил силу совместным приказом Министра здравоохранения Республики Казахстан от 29 октября 2012 года № 744 и Министра экономического развития и торговли Республики Казахстан от 29 ноября 2012 года № 322
title:
  rus: Об утверждении форм проверочных листов в сфере частного предпринимательства в области санитарно-эпидемиологического благополучия населения
  kaz: Халықтың санитариялық-эпидемиологиялық салауаттылығы саласында жеке кәсіпкерлік аясындағы тексеру парақтарының нысандарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2011-01-31
approved_by:
- '103005000000'
- '103010000000'
version_date:
  kaz: 2011-01-31
  rus: 2011-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/57816/kaz/31.01.2011
  rus: https://zan.gov.kz/client/#!/doc/57816/rus/31.01.2011
