act_code: '65770'
requisite: Приказ И.о. Министра образования и науки Республики Казахстан от 14 мая 2012 года № 211. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 мая 2012 года № 7674. Утратил силу приказом Министра образования и науки Республики Казахстан от 13 сентября 2017 года № 460 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении перечня специальностей высшего образования, по которым для лиц, окончивших сельские организации образования, установлена квота приема в высшие учебные заведения Республики Казахстан, и перечня специальностей с указанием предметов по выбору и профильных предметов единого национального тестирования и комплексного тестирования
  kaz: Ауылдық оқу орындарын бітірген тұлғалар үшін Қазақстан Республикасы жоғары оқу орындарына қабылдау квотасы белгіленген жоғары білім беру мамандықтарының тізбесiн және ұлттық бірыңғай тестілеу және кешенді тестілеу жүргізілетін таңдау пәндері мен бейінді пәндер көрсетілген мамандықтар тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2012-05-14
approved_by:
- '103006000000'
version_date:
  rus: 2012-05-14
source:
  rus: https://zan.gov.kz/client/#!/doc/65770/rus/14.05.2012
