act_code: '158084'
requisite: Приказ Министра здравоохранения Республики Казахстан от 20 августа 2021 года № ҚР ДСМ-83. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 августа 2021 года № 24077
title:
  rus: Об утверждении Санитарных правил «Санитарно-эпидемиологические требования к объектам производства кондитерских изделий, условиям производства, расфасовки, транспортировки, хранения, реализации, утилизации и уничтожения кондитерских изделий»
  kaz: «Кондитерлік өнімдерді өндіру объектілеріне, кондитерлік өнімдерді өндіру, өлшеп-орау, тасымалдау, сақтау, өткізу, кәдеге жарату және жою шарттарына қойылатын санитариялық-эпидемиологиялық талаптар» санитариялық қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2021-08-20
approved_by:
- '103010000000'
version_date:
  kaz: 2021-08-20
  rus: 2021-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/158084/kaz/20.08.2021
  rus: https://zan.gov.kz/client/#!/doc/158084/rus/20.08.2021
