act_code: '32894'
requisite: Приказ Министра юстиции Республики Казахстан от 12 апреля 2007 года № 112. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 апреля 2007 года № 4625. Утратил силу приказом Министра юстиции Республики Казахстан от 11 апреля 2019 года № 184 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Инструкции по государственной регистрации юридических лиц и учетной регистрации филиалов и представительств
  kaz: Заңды тұлғаларды мемлекеттік тіркеу және филиалдар мен өкілдіктерді есептік тіркеу жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2007-04-12
approved_by:
- '103001000000'
version_date:
  kaz: 2009-03-30
  rus: 2009-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/32894/kaz/30.03.2009
  rus: https://zan.gov.kz/client/#!/doc/32894/rus/30.03.2009
caused_by:
  code: '45169'
  requisite: Приказ Министра юстиции Республики Казахстан от 30 марта 2009 года N 32. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 марта 2009 года N 5613. Утратил силу приказом Министра юстиции Республики Казахстан от 11 апреля 2019 года № 184 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в приказ Министра юстиции Республики Казахстан от 12 апреля 2007 года № 112 "Об утверждении Инструкции по государственной регистрации юридических лиц и учетной регистрации филиалов и представительств"
    kaz: '"Заңды тұлғаларды мемлекеттік тіркеу және филиалдар мен өкілдіктерді есептік тіркеу жөніндегі нұсқаулықты бекіту туралы" Қазақстан Республикасы Әділет министрінің 2007 жылғы 12 сәуірдегі N 112 бұйрығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/45169/rus
