act_code: '122669'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 24 мая 2018 года № 381. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 июня 2018 года № 17068
title:
  rus: Об утверждении Правил хранения и учета недропользователями геологической информации и ее носителей, полученных в результате проведения операций по недропользованию
  kaz: Жер қойнауын пайдаланушылардың жер қойнауын пайдалану жөніндегі операцияларды жүргізу нәтижесінде алынған геологиялық ақпаратты және оның жеткізгіштерін сақтау және есепке алу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-05-24
approved_by:
- '103035000000'
version_date:
  kaz: 2019-04-19
  rus: 2019-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/122669/kaz/19.04.2019
  rus: https://zan.gov.kz/client/#!/doc/122669/rus/19.04.2019
caused_by:
  code: '130895'
  requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 19 апреля 2019 года № 236. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 апреля 2019 года № 18570
  title:
    rus: О внесении изменений и дополнений в некоторые приказы Министерства по инвестициям и развитию Республики Казахстан
    kaz: Қазақстан Республикасы Инвестициялар және даму министрлігінің кейбір бұйрықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130895/rus
