act_code: '219259'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 19 декабря 2025 года № 477
title:
  rus: Об утверждении профессиональных стандартов «Производство сахаристых кондитерских изделий и какао порошка», «Производство макаронных изделий», «Производство питьевой бутилированной воды», «Производство фасованного чая», «Производство напитков», «Производство дрожжей», «Производство хлебобулочных и мучных кондитерских изделий», «Менеджмент в реализации произведенных продуктов питания», «Производство продуктов общественного питания», «Производство приготовленных пищевых продуктов и полуфабрикатов»
  kaz: «Қантты кондитерлік өнімдер мен какао ұнтағын өндіру», «Макарон өнімдерін өндіру», «Бөтелкедегі ауыз суды өндіру», «Өлшеп оралған шәй өндіру», «Сусындар өндіру», «Ашытқы өндіру», «Нан-тоқаш және ұннан жасалған кондитерлік өнімдерді өндіру», «Өндірілген тамақ өнімдерін өткізу менеджменті», «Қоғамдық тамақ өнімдерін өндіру», «Дайындалған тамақ өнімдері мен жартылай фабрикаттарды өндіру» кәсіптік стандарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2025-12-19
approved_by:
- '103012000000'
version_date:
  kaz: 2025-12-19
  rus: 2025-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/219259/kaz/19.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219259/rus/19.12.2025
