act_code: '81121'
requisite: Приказ Министра обороны Республики Казахстан от 20 мая 2014 года № 218. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 июня 2014 года № 9527.
title:
  rus: Об утверждении Инструкции по назначению и осуществлению пенсионных выплат военнослужащим
  kaz: Әскери қызметшілерге зейнетақы төлемдерін тағайындау және оларды жүзеге асыру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2014-05-20
approved_by:
- '103008000000'
version_date:
  kaz: 2019-01-17
  rus: 2019-01-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/81121/kaz/17.01.2019
  rus: https://zan.gov.kz/client/#!/doc/81121/rus/17.01.2019
caused_by:
  code: '128740'
  requisite: Приказ Министра обороны Республики Казахстан от 17 января 2019 года № 27. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 января 2019 года № 18216. Утратил силу приказом Министра обороны Республики Казахстан от 23 сентября 2022 года № 827 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: Об утверждении Инструкции по организации исчисления выслуги лет военнослужащим Вооруженных Сил Республики Казахстан и о внесении изменений в приказ Министра обороны Республики Казахстан от 20 мая 2014 года № 218 «Об утверждении Инструкции по назначению и осуществлению пенсионных выплат военнослужащим»
    kaz: Қазақстан Республикасы Қарулы Күштерінің әскери қызметшілеріне еңбек сіңірген жылдарын есептеуді ұйымдастыру жөніндегі нұсқаулықты бекіту туралы және «Әскери қызметшілерге зейнетақы төлемдерін тағайындау және оларды жүзеге асыру жөніндегі нұсқаулықты бекіту туралы» Қазақстан Республикасы Қорғаныс министрінің 2014 жылғы 20 мамырдағы № 218 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/128740/rus
