act_code: '85294'
requisite: Приказ Министра здравоохранения и социального развития Республики Казахстан от 15 декабря 2014 года № 326. Зарегистрирован в Министерстве юстиции 25 декабря 2014 года № 10016. Утратил силу приказом Министра здравоохранения и социального развития Республики Казахстан от 13 марта 2015 года № 131
title:
  rus: Об определении черты бедности на 1 квартал 2015 года
  kaz: 2015 жылғы 1 тоқсанға арналған кедейлік шегін анықтау туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2014-12-15
approved_by:
- '103037000000'
version_date:
  kaz: 2014-12-15
  rus: 2014-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/85294/kaz/15.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85294/rus/15.12.2014
