act_code: '86339'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 30 декабря 2014 года № 162. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 февраля 2015 года № 10184
title:
  rus: Об утверждении Правил проведения религиоведческой экспертизы
  kaz: Дінтану сараптамасын жүргізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2014-12-30
approved_by:
- '103034000000'
version_date:
  kaz: 2019-07-12
  rus: 2019-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/86339/kaz/12.07.2019
  rus: https://zan.gov.kz/client/#!/doc/86339/rus/12.07.2019
caused_by:
  code: '133303'
  requisite: Приказ Министра информации и общественного развития Республики Казахстан от 12 июля 2019 года № 207. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 июля 2019 года № 19064
  title:
    rus: О внесении изменений и дополнения в приказ Министра культуры и спорта Республики Казахстан от 30 декабря 2014 года № 162 «Об утверждении Правил проведения религиоведческой экспертизы»
    kaz: «Дінтану сараптамасын жүргізу қағидаларын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің 2014 жылғы 30 желтоқсандағы № 162 бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133303/rus
