act_code: '149351'
requisite: Приказ Министра здравоохранения Республики Казахстан от 3 декабря 2020 года № ҚР ДСМ-231/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 декабря 2020 года № 21725
title:
  rus: Об утверждении правил расследования случаев заражения ВИЧ-инфекцией среди населения
  kaz: Халық арасында АИТВ инфекциясын жұқтыру жағдайларын тергеп-тексеру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-12-03
approved_by:
- '103010000000'
version_date:
  kaz: 2025-09-03
  rus: 2025-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/149351/kaz/03.09.2025
  rus: https://zan.gov.kz/client/#!/doc/149351/rus/03.09.2025
caused_by:
  code: '213951'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 3 сентября 2025 года № 87. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 сентября 2025 года № 36793
  title:
    rus: О внесении изменений в приказ Министра здравоохранения Республики Казахстан от 3 декабря 2020 года № ҚР ДСМ-231/2020 «Об утверждении правил расследования случаев заражения ВИЧ-инфекцией среди населения»
    kaz: «Халық арасында АИТВ инфекциясын жұқтыру жағдайларын тергеп-тексеру қағидаларын бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің 2020 жылғы 3 желтоқсандағы № ҚР ДСМ-231/2020 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213951/rus
