act_code: '171510'
requisite: Приказ Министра информации и общественного развития Республики Казахстан от 12 сентября 2022 года № 383. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 сентября 2022 года № 29542
title:
  rus: Об утверждении Правил присуждения почетного звания в сфере благотворительности
  kaz: Қайырымдылық саласындағы құрметті атақ беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-09-12
approved_by:
- '103043000000'
version_date:
  kaz: 2024-07-17
  rus: 2024-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/171510/kaz/17.07.2024
  rus: https://zan.gov.kz/client/#!/doc/171510/rus/17.07.2024
caused_by:
  code: '198962'
  requisite: Приказ Министра культуры и информации Республики Казахстан от 17 июля 2024 года № 318-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 июля 2024 года № 34785
  title:
    rus: О внесении изменений в приказ Министра информации и общественного развития Республики Казахстан от 12 сентября 2022 года № 383 «Об утверждении Правил присуждения почетного звания в сфере благотворительности»
    kaz: «Қайырымдылық саласындағы құрметті атақ беру қағидаларын бекіту туралы» Қазақстан Республикасы Ақпарат және қоғамдық даму министрінің 2022 жылғы 12 қыркүйектегі № 383 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198962/rus
