act_code: '88563'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 28 января 2015 года № 18-02/45. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 марта 2015 года № 10481
title:
  rus: 'Об утверждении Правил перевода из категории земель лесного фонда в земли других категорий для целей, не связанных с ведением лесного хозяйства '
  kaz: Орман қоры жерi санатынан орман шаруашылығын жүргiзуге байланысты емес мақсаттар үшiн басқа санаттардағы жерге ауыстыру қағидасын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-01-28
approved_by:
- '103012000000'
version_date:
  kaz: 2020-04-29
  rus: 2020-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/88563/kaz/29.04.2020
  rus: https://zan.gov.kz/client/#!/doc/88563/rus/29.04.2020
caused_by:
  code: '142410'
  requisite: Приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 29 апреля 2020 года № 101. Зарегистрирован в Министерстве юстиции Республики Казахстан 30 апреля 2020 года № 20541
  title:
    rus: О внесении изменений в приказы Министра сельского хозяйства Республики Казахстан от 28 января 2015 года № 18-02/45 «Об утверждении Правил перевода из категории земель лесного фонда в земли других категорий для целей, не связанных с ведением лесного хозяйства» и исполняющего обязанности Министра сельского хозяйства Республики Казахстан от 27 февраля 2015 года № 18-02/163 «Об утверждении Правил ведения государственного учета лесного фонда, государственного лесного кадастра, государственного мониторинга лесов и лесоустройства на территории государственного лесного фонда»
    kaz: «Орман қоры жері санатынан орман шаруашылығын жүргізуге байланысты емес мақсаттар үшін басқа санаттардағы жерге ауыстыру қағидасын бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің 2015 жылғы 28 қаңтардағы № 18-02/45 және «Мемлекеттік орман қоры аумағында орман қорының мемлекеттік есебін, мемлекеттік орман кадастрын, ормандардың мемлекеттік мониторингін және орман орналастыруды жүргізу қағидаларын бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің міндетін атқарушының 2015 жылғы 27 ақпандағы № 18-02/163 бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142410/rus
