act_code: '186940'
requisite: Приказ Министра культуры и информации Республики Казахстан от 5 октября 2023 года № 391-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 октября 2023 года № 33516
title:
  rus: Об утверждении профессионального стандарта «Деятельность в области религии»
  kaz: «Дін саласындағы қызмет» кәсіптік стандартын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2023-10-05
approved_by:
- '103053000000'
version_date:
  kaz: 2026-04-13
  rus: 2026-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/186940/kaz/13.04.2026
  rus: https://zan.gov.kz/client/#!/doc/186940/rus/13.04.2026
caused_by:
  code: '224287'
  requisite: Приказ Заместителя Премьер-Министра - Министра культуры и информации Республики Казахстан от 13 апреля 2026 года № 184-НҚ
  title:
    rus: О внесении изменения в приказ Министра культуры и информации Республики Казахстан от 5 октября 2023 года № 391-НҚ «Об утверждении профессионального стандарта «Деятельность в области религии»
    kaz: «Дін саласындағы қызмет» кәсіптік стандартын бекіту туралы» Қазақстан Республикасы Мәдениет және ақпарат министрінің 2023 жылғы 5 қазандағы № 391-НҚ бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224287/rus
