act_code: '93928'
requisite: Совместный приказ Председателя Агентства Республики Казахстан по делам государственной службы и противодействию коррупции от 30 июня 2015 года № 203 и Министра национальной экономики Республики Казахстан от 8 июля 2015 года № 506. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 августа 2015 года № 11852. Утратил силу совместным приказом Министра по делам государственной службы РК от 11.02.2016 № 32 и Министра национальной экономики РК от 19.02.2016 № 89
title:
  rus: Об утверждении форм проверочных листов и критериев оценки степени рисков деятельности государственных органов по соблюдению законодательства в сфере оказания государственных услуг, государственной службы, служебной этики и антикоррупционного законодательства в сфере оказания государственных услуг и государственной службы
  kaz: Мемлекеттік қызметтер көрсету, мемлекеттік қызмет саласындағы заңнаманың, қызмет этикасының және мемлекеттік қызметтер көрсету және мемлекеттік қызмет саласында сыбайлас жемқорлыққа қарсы заңнаманың сақталуы бойынша тексеру парақтарының нысандарын және мемлекеттік органдар қызметінің тәуекел дәрежесін бағалау критерийлерін бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПРИК
approved_on: 2015-06-30
approved_by:
- '103033000000'
- '133000000000'
version_date:
  kaz: 2015-06-30
  rus: 2015-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/93928/kaz/30.06.2015
  rus: https://zan.gov.kz/client/#!/doc/93928/rus/30.06.2015
