act_code: '64786'
requisite: Постановление Правления Национального Банка Республики Казахстан от 24 февраля 2012 года № 95. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 апреля 2012 года № 7561. Утратило силу постановлением Правления Национального Банка Республики Казахстан от 26 декабря 2016 года № 305
title:
  rus: Об утверждении Правил выдачи согласия на назначение (избрание) руководящих работников финансовых организаций, банковских, страховых холдингов и перечня документов, необходимых для получения согласия
  kaz: Қаржы ұйымдарының, банк, сақтандыру холдингтерінің басшы қызметкерлерін тағайындауға (сайлауға) келісім беру қағидаларын және келісім алу үшін қажетті құжаттар тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2012-02-24
approved_by:
- '117000000000'
version_date:
  kaz: 2014-12-24
  rus: 2014-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/64786/kaz/24.12.2014
  rus: https://zan.gov.kz/client/#!/doc/64786/rus/24.12.2014
caused_by:
  code: '86563'
  requisite: Постановление Правления Национального Банка Республики Казахстан от 24 декабря 2014 года № 261. Зарегистрировано в Министерстве юстиции Республики Казахстан 10 февраля 2015 года № 10211
  title:
    rus: О внесении изменений и дополнений в некоторые нормативные правовые акты Республики Казахстан по вопросам оптимизации и автоматизации бизнес - процессов государственных услуг, оказываемых Национальным Банком Республики Казахстан
    kaz: Қазақстан Республикасының кейбір нормативтік құқықтық актілеріне Қазақстан Республикасының Ұлттық Банкі көрсететін мемлекеттік қызметтердің бизнес-процестерін оңтайландыру және автоматтандыру мәселелері бойынша өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86563/rus
