act_code: '114664'
requisite: Приказ Министра обороны Республики Казахстан от 27 июля 2017 года № 393. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 сентября 2017 года № 15651
title:
  rus: Об утверждении Инструкции по организации обеспечения качества авиационных горюче-смазочных материалов и специальных жидкостей в государственной авиации
  kaz: Мемлекеттік авиацияда авиациялық жанар-жағар май материалдарының және арнайы сұйықтықтардың сапасын қамтамасыз етуді ұйымдастыру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2017-07-27
approved_by:
- '103008000000'
version_date:
  kaz: 2021-04-19
  rus: 2021-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/114664/kaz/19.04.2021
  rus: https://zan.gov.kz/client/#!/doc/114664/rus/19.04.2021
caused_by:
  code: '155113'
  requisite: Приказ Министра обороны Республики Казахстан от 19 апреля 2021 года № 237. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 апреля 2021 года № 22598
  title:
    rus: О внесении изменений и дополнения в приказ Министра обороны Республики Казахстан от 27 июля 2017 года № 393 «Об утверждении Инструкции по организации обеспечения качества авиационных горюче-смазочных материалов и специальных жидкостей в государственной авиации»
    kaz: «Мемлекеттік авиацияда авиациялық жанар-жағар май материалдарының және арнайы сұйықтықтардың сапасын қамтамасыз етуді ұйымдастыру жөніндегі нұсқаулықты бекіту туралы» Қазақстан Республикасы Қорғаныс министрінің 2017 жылғы 27 шілдедегі № 393 бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155113/rus
