act_code: '49076'
requisite: Приказ Министра здравоохранения Республики Казахстан от 12 ноября 2009 года № 705. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 ноября 2009 года № 5907. Утратил силу приказом Министра национальной экономики Республики Казахстан от 23 июня 2015 года № 440
title:
  rus: Об установлении Правил расследования случаев инфекционных и паразитарных, профессиональных заболеваний и отравлений населения
  kaz: Халықтың инфекциялық және паразиттік, кәсіптік аурулары мен улану жағдайларын тексеру ережесін бекіту туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2009-11-12
approved_by:
- '103010000000'
version_date:
  kaz: 2009-11-12
  rus: 2009-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/49076/kaz/12.11.2009
  rus: https://zan.gov.kz/client/#!/doc/49076/rus/12.11.2009
