act_code: '155161'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 22 апреля 2021 года № 105. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 апреля 2021 года № 22609. Утратил силу приказом Министра культуры и информации Республики Казахстан от 31 марта 2025 года № 131-НҚ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил пользования сводным электронным каталогом библиотек Казахстана
  kaz: Қазақстан кітапханаларының жиынтық электрондық каталогын пайдалану қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2021-04-22
approved_by:
- '103034000000'
version_date:
  kaz: 2021-04-22
  rus: 2021-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/155161/kaz/22.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155161/rus/22.04.2021
