act_code: '59407'
requisite: Приказ и.о. Министра транспорта и коммуникаций Республики Казахстан от 16 мая 2011 года № 279. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 июня 2011 года № 7006
title:
  rus: Об утверждении Инструкции по организации и обслуживанию воздушного движения
  kaz: Әуе қозғалысын ұйымдастыру және оған қызмет көрсету жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2011-05-16
approved_by:
- '103013000000'
version_date:
  kaz: 2013-09-20
  rus: 2013-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/59407/kaz/20.09.2013
  rus: https://zan.gov.kz/client/#!/doc/59407/rus/20.09.2013
caused_by:
  code: '75225'
  requisite: Приказ Министра транспорта и коммуникаций Республики Казахстан от 20 сентября 2013 года № 733. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 октября 2013 года № 8824
  title:
    rus: О внесении изменений в некоторые приказы Министерства транспорта и коммуникаций Республики Казахстан
    kaz: Қазақстан Республикасы Көлік және коммуникация министрлігінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75225/rus
