act_code: '84971'
requisite: Приказ и.о. Министра культуры и спорта Республики Казахстан от 28 октября 2014 года № 55. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 ноября 2014 года № 9912
title:
  rus: Об утверждении Правил признания видов спорта, спортивных дисциплин и формирования реестра видов спорта
  kaz: Спорт түрлерін, спорт салаларын тану және спорт түрлерінің тізілімін қалыптастыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2014-10-28
approved_by:
- '103034000000'
version_date:
  kaz: 2025-07-02
  rus: 2025-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/84971/kaz/02.07.2025
  rus: https://zan.gov.kz/client/#!/doc/84971/rus/02.07.2025
caused_by:
  code: '212208'
  requisite: Приказ Министра туризма и спорта Республики Казахстан от 2 июля 2025 года № 118. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 июля 2025 года № 36422
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра культуры и спорта Республики Казахстан от 28 октября 2014 года № 55 «Об утверждении Правил признания видов спорта, спортивных дисциплин и формирования реестра видов спорта»
    kaz: «Спорт түрлерін, спорт салаларын тану және спорт түрлерінің тізілімін қалыптастыру қағидаларын бекіту туралы» Қазақстан Республикасы Мәдениет және спорт министрінің міндетін атқарушының 2014 жылғы 28 қазандағы № 55 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212208/rus
