act_code: '6335'
requisite: Совместный приказ Министра обороны Республики Казахстан от 1 марта 2000 года № 46 и Министра образования и науки Республики Казахстан от 7 марта 2000 года № 202. Зарегистрирован в Министерстве юстиции 24 июня 2000 года N 1172. Утратил силу совместным приказом Министра обороны Республики Казахстан от 18 октября 2010 года № 808 и Министра образования и науки Республики Казахстан от 19 октября 2010 года № 488
title:
  rus: Об утверждении и вводе в действие Инструкции по организации и проведению учебного процесса на военных кафедрах при высших учебных заведениях
  kaz: Жоғары оқу орындарының әскери кафедраларында оқу процесін ұйымдастыру және өткізу жөніндегі Нұсқаулықты бекіту және жүзеге асыру туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2000-03-01
approved_by:
- '103006000000'
- '103008000000'
version_date:
  kaz: 2000-03-01
  rus: 2000-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/6335/kaz/01.03.2000
  rus: https://zan.gov.kz/client/#!/doc/6335/rus/01.03.2000
