act_code: '89484'
requisite: Приказ Министра национальной экономики Республики Казахстан от 20 марта 2015 года № 235. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 апреля 2015 года № 10886
title:
  rus: Об утверждении Правил оказания государственной услуги «Выдача разрешения на вырубку деревьев»
  kaz: «Ағаштарды кесуге рұқсат беру» мемлекеттік қызмет көрсету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-03-20
approved_by:
- '103033000000'
version_date:
  kaz: 2025-09-24
  rus: 2025-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/89484/kaz/24.09.2025
  rus: https://zan.gov.kz/client/#!/doc/89484/rus/24.09.2025
caused_by:
  code: '215589'
  requisite: Приказ Министра промышленности и строительства Республики Казахстан от 24 сентября 2025 года № 388. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 октября 2025 года № 37119. Утратил силу приказом Министра промышленности и строительства Республики Казахстан от 3 июня 2026 года № 282 (вводится в действие с 1 июля 2026 года)
  title:
    rus: О внесении изменений в приказ Министра национальной экономики Республики Казахстан от 20 марта 2015 года № 235 «Об утверждении Типовых правил благоустройства территорий городов и населенных пунктов и Правил оказания государственной услуги «Выдача разрешения на вырубку деревьев»
    kaz: Қалалар мен елді мекендердің аумақтарын абаттандырудың үлгілік қағидаларын және «Ағаштарды кесуге рұқсат беру» мемлекеттік қызмет көрсету қағидаларын бекіту туралы» Қазақстан Республикасы Ұлттық экономика министрінің 2015 жылғы 20 наурыздағы № 235 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215589/rus
