act_code: '102478'
requisite: Приказ Министра внутренних дел Республики Казахстан от 29 марта 2016 года № 313. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 мая 2016 года № 13694
title:
  rus: Об утверждении Инструкции по организации деятельности подразделений органов внутренних дел по контролю в сфере оборота гражданского и служебного оружия
  kaz: Ішкі істер органдарының азаматтық және қызметтік қару айналымы саласындағы бақылау жөніндегі бөлімшелерінің қызметін ұйымдастыру туралы нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
- ПРЧ
approved_on: 2016-03-29
approved_by:
- '103003000000'
version_date:
  kaz: 2021-07-27
  rus: 2021-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/102478/kaz/27.07.2021
  rus: https://zan.gov.kz/client/#!/doc/102478/rus/27.07.2021
caused_by:
  code: '157491'
  requisite: Приказ и.о. Министра внутренних дел Республики Казахстан от 27 июля 2021 года № 442. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 июля 2021 года № 23740
  title:
    rus: О внесении изменений в приказ Министра внутренних дел Республики Казахстан от 29 марта 2016 года № 313 «Об утверждении Инструкции по организации деятельности подразделений органов внутренних дел по контролю в сфере оборота гражданского и служебного оружия»
    kaz: «Ішкі істер органдарының азаматтық және қызметтік қару айналымы саласындағы бақылау жөніндегі бөлімшелерінің қызметін ұйымдастыру туралы нұсқаулықты бекіту туралы» Қазақстан Республикасы Ішкі істер министрінің 2016 жылғы 29 наурыздағы № 313 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157491/rus
