act_code: '63572'
requisite: Приказ Министра внутренних дел Республики Казахстан от 9 января 2012 года № 10. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 февраля 2012 года № 7417
title:
  rus: Об утверждении Правил внутреннего распорядка приемников-распределителей органов внутренних дел
  kaz: Ішкі істер органдары қабылдау-бөлу орнындағы ішкі тәртіп қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2012-01-09
approved_by:
- '103003000000'
version_date:
  kaz: 2024-01-24
  rus: 2024-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/63572/kaz/24.01.2024
  rus: https://zan.gov.kz/client/#!/doc/63572/rus/24.01.2024
caused_by:
  code: '192916'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 24 января 2024 года № 65. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 января 2024 года № 33939
  title:
    rus: О внесении изменений и дополнений в некоторые приказы Министра внутренних дел Республики Казахстан
    kaz: Қазақстан Республикасы Ішкі істер министрінің кейбір бұйрықтарға өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/192916/rus
