act_code: '133881'
requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 3 июля 2019 года № 476. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 июля 2019 года № 19009
title:
  rus: Об утверждении формы сертификата безопасности
  kaz: Қауіпсіздік сертификатының нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2019-07-03
approved_by:
- '103042000000'
version_date:
  kaz: 2019-07-03
  rus: 2019-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/133881/kaz/03.07.2019
  rus: https://zan.gov.kz/client/#!/doc/133881/rus/03.07.2019
