act_code: '90875'
requisite: Приказ Министра финансов Республики Казахстан от 27 апреля 2015 года № 285. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 мая 2015 года № 11154. Утратил силу приказом Первого заместителя Премьер-Министра Республики Казахстан – Министра финансов Республики Казахстан от 7 апреля 2020 года № 362 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении стандартов государственных услуг в сфере учета государственного имущества
  kaz: Мемлекеттік мүлікті есепке алу саласында мемлекеттік көрсетілетін қызметтердің стандарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2015-04-27
approved_by:
- '103002000000'
version_date:
  kaz: 2019-09-05
  rus: 2019-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/90875/kaz/05.09.2019
  rus: https://zan.gov.kz/client/#!/doc/90875/rus/05.09.2019
caused_by:
  code: '134594'
  requisite: Приказ Первого заместителя Премьер-Министра Республики Казахстан – Министра финансов Республики Казахстан от 5 сентября 2019 года № 963. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 сентября 2019 года № 19359. Утратил силу приказом Первого заместителя Премьер-Министра Республики Казахстан – Министра финансов Республики Казахстан от 7 апреля 2020 года № 362 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в приказ Министра финансов Республики Казахстан от 27 апреля 2015 года № 285 «Об утверждении стандартов государственных услуг в сфере учета государственного имущества»
    kaz: Мемлекеттік мүлікті есепке алу саласында мемлекеттік көрсетілетін қызметтердің стандарттарын бекіту туралы» Қазақстан Республикасы Қаржы министрінің 2015 жылғы 27 сәуірдегі № 285 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134594/rus
