act_code: '25674'
requisite: Приказ Руководителя Канцелярии Премьер-Министра Республики Казахстан от 1 октября 2005 года N 25-1-86 дсп. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 октября 2005 года N 3899
title:
  rus: Об утверждении Инструкции о порядке подготовки и представления планов и отчетов по вопросам защиты государственных секретов в государственных органах и организациях Республики Казахстан
  kaz: Қазақстан Республикасының мемлекеттік органдары мен ұйымдарында мемлекеттік құпияларды қорғау мәселелері жөніндегі жоспарлар мен есептерді дайындау және ұсыну тәртібі туралы нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2005-10-01
approved_by:
- '103031000000'
version_date:
  kaz: 2005-10-01
  rus: 2005-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/25674/kaz/01.10.2005
  rus: https://zan.gov.kz/client/#!/doc/25674/rus/01.10.2005
