act_code: '212244'
requisite: Приказ Министра культуры и информации Республики Казахстан от 4 июля 2025 года № 307-НҚ
title:
  rus: Об установлении цен на товары (работы, услуги), производимые и реализуемые республиканскими государственными казенными предприятиями Министерства культуры и информации Республики Казахстан
  kaz: Қазақстан Республикасы Мәдениет және ақпарат министрлігінің республикалық мемлекеттік қазыналық кәсіпорындары өндіретін және сататын тауарларға (жұмыстарға, көрсетілетін қызметтерге) бағаларды белгілеу туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-07-04
approved_by:
- '103053000000'
version_date:
  kaz: 2025-07-04
  rus: 2025-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/212244/kaz/04.07.2025
  rus: https://zan.gov.kz/client/#!/doc/212244/rus/04.07.2025
