act_code: '128152'
requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 25 декабря 2018 года № 108/қбп. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 января 2019 года № 18150
title:
  rus: Об утверждении Правил организации морально-психологического обеспечения служебно-боевой деятельности Пограничной службы Комитета национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасы Ұлттық қауіпсіздік комитеті Шекара қызметінің қызметтік-жауынгерлік іс-қимылын моральдық-психологиялық қамтамасыз етуді ұйымдастыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-12-25
approved_by:
- '108000000000'
version_date:
  kaz: 2018-12-25
  rus: 2018-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/128152/kaz/25.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128152/rus/25.12.2018
