act_code: '198419'
requisite: Приказ Министра культуры и информации Республики Казахстан от 27 июня 2024 года № 274-НҚ
title:
  rus: Об утверждении Типовой квалификационной характеристики руководителя (ректор) организации высшего и (или) послевузовского образования
  kaz: Жоғары және (немесе) жоғары оқу орнынан кейінгі білім беру ұйымы басшысының (ректор) үлгілік біліктілік сипаттамасын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2024-06-27
approved_by:
- '103053000000'
version_date:
  kaz: 2024-06-27
  rus: 2024-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/198419/kaz/27.06.2024
  rus: https://zan.gov.kz/client/#!/doc/198419/rus/27.06.2024
