act_code: '21566'
requisite: Приказ Председателя Агентства Республики Казахстан по статистике от 7 сентября 2004 года N 127. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 октября 2004 года за N 3127. Утратил силу приказом Председателя Агентства Республики Казахстан по статистике от 29 апреля 2010 года № 100
title:
  rus: Об утверждении Инструкции по производству дел об административных правонарушениях органами государственной статистики
  kaz: Мемлекеттік статистика органдарының әкімшілік құқық бұзушылық туралы іс жүргізуі жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2004-09-06
approved_by:
- '119000000000'
version_date:
  kaz: 2004-09-06
  rus: 2004-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/21566/kaz/06.09.2004
  rus: https://zan.gov.kz/client/#!/doc/21566/rus/06.09.2004
