act_code: '22111'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 5 ноября 2004 года № 629. Зарегистрирован Министерством юстиции Республики Казахстан 23 ноября 2004 года № 3217. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 23 ноября 2012 года № 18-03/591
title:
  rus: Об утверждении Перечня хозяйственных целей для использования объектов животного мира (кроме охоты и рыболовства) и Правил использования в хозяйственных целях животных, не относящихся к объектам охоты и рыболовства, а также их полезных свойств и продуктов жизнедеятельности
  kaz: Жануарлар дүниесі объектілерін пайдалануға (аң аулау мен балық аулаудан басқа) арналған шаруашылық мақсаттардың тізбесін және Аң аулау мен балық аулау объектілеріне жатпайтын жануарларды, сондай-ақ олардың пайдалы қасиеттері мен тіршілік ету өнімдерін шаруашылық мақсаттарда пайдалану ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
- ПРЧ
approved_on: 2004-11-05
approved_by:
- '103012000000'
version_date:
  kaz: 2004-11-05
  rus: 2004-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/22111/kaz/05.11.2004
  rus: https://zan.gov.kz/client/#!/doc/22111/rus/05.11.2004
