act_code: '215387'
requisite: Приказ Министра финансов Республики Казахстан от 6 октября 2025 года № 573. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 октября 2025 года № 37084
title:
  rus: Об утверждении форм решений органа государственных доходов по вопросам сопоставительного контроля выписки электронных счетов-фактур
  kaz: Электрондық шот-фактураларды жазып беруді салыстырмалы бақылау мәселелері бойынша мемлекеттік кірістер органының шешімдері нысандарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-10-06
approved_by:
- '103002000000'
version_date:
  kaz: 2025-10-06
  rus: 2025-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/215387/kaz/06.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215387/rus/06.10.2025
