act_code: '158725'
requisite: Приказ Министра экологии, геологии и природных ресурсов Республики Казахстан от 14 сентября 2021 года № 378. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 сентября 2021 года № 24417
title:
  rus: Об утверждении Методики по проведению газового мониторинга при эксплуатации полигона
  kaz: Полигонды пайдалану кезінде газ мониторингін жүргізу әдістемесін бекіту туралы
form: ПРИК
type_codes:
- МЕТ
- ПРИК
approved_on: 2021-09-14
approved_by:
- '103047000000'
version_date:
  kaz: 2021-09-14
  rus: 2021-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/158725/kaz/14.09.2021
  rus: https://zan.gov.kz/client/#!/doc/158725/rus/14.09.2021
