act_code: '21809'
requisite: Совместный приказ Председателя Комитета национальной безопасности Республики Казахстан от 20 сентября 2004 года N 179 и и.о. Председателя Агентства Республики Казахстан по информатизации и связи от 20 сентября 2004 года N 199-п. Зарегистрирован Министерством юстиции Республики Казахстан 5 ноября 2004 года N 3187. Утратил силу совместным приказом Министра транспорта и коммуникаций Республики Казахстан от 23 апреля 2012 года № 196 и Председателя Комитета национальной безопасности Республики Казахстан от 28 апреля 2012 года № 194
title:
  rus: Об утверждении Правил взаимодействия государственных органов и организаций при внедрении и эксплуатации аппаратно-программных и технических средств проведения оперативно-розыскных мероприятий на сетях телекоммуникаций Республики Казахстан
  kaz: Қазақстан Республикасының телекоммуникация желілерінде жедел-іздестіру іс-шараларын жүргізетін аппараттық-бағдарламалық және техникалық құралдарды енгізу және пайдалану кезіндегі мемлекеттік органдар мен ұйымдардың өзара іс-қимыл ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2004-09-19
approved_by:
- '108000000000'
- '110000000000'
version_date:
  kaz: 2004-09-19
  rus: 2004-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/21809/kaz/19.09.2004
  rus: https://zan.gov.kz/client/#!/doc/21809/rus/19.09.2004
