act_code: '97966'
requisite: Совместный приказ и.о. Министра национальной экономики Республики Казахстан от 30 декабря 2015 года № 835 и Министра энергетики Республики Казахстан от 15 декабря 2015 года № 721. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 декабря 2015 года № 12779
title:
  rus: Об утверждении критериев оценки степени риска и проверочных листов в области охраны окружающей среды, воспроизводства и использования природных ресурсов
  kaz: Қоршаған ортаны қорғау, табиғи ресурстарды молайту мен пайдалану саласындағы тәуекел дәрежесін бағалау өлшемшарттарын және тексеру парақтарын бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПРИК
approved_on: 2015-12-15
approved_by:
- '103033000000'
- '103036000000'
version_date:
  kaz: 2015-12-15
  rus: 2015-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/97966/kaz/15.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97966/rus/15.12.2015
