act_code: '23773'
requisite: Совместный приказ Министра здравоохранения Республики Казахстан от 9 марта 2005 года № 105 и Министра сельского хозяйства Республики Казахстан от 18 марта 2005 года № 214. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 апреля 2005 года № 3575. Утратил силу совместным приказом Министра здравоохранения Республики Казахстан от 30 июня 2010 года № 484 и Министра сельского хозяйства Республики Казахстан от 19 июля 2010 года № 454
title:
  rus: Об утверждении санитарно-эпидемиологических и ветеринарно-санитарных правил и норм "Санитарно-эпидемиологические и ветеринарно-санитарные требования к содержанию и эксплуатации объектов, предназначенных для заготовки молока"
  kaz: '"Сүт тағамдарын дайындауға арналған объектілерді ұстап-күтуге және пайдалануға қойылатын санитарлық-эпидемиологиялық және ветеринарлық-санитарлық талаптар" санитарлық-эпидемиологиялық және ветеринарлық-санитарлық ережелер мен нормаларды бекіту туралы'
form: ПРИК
type_codes:
- НОРМ
- ПРАВ
- ПРИК
approved_on: 2005-03-09
approved_by:
- '103010000000'
- '103012000000'
version_date:
  kaz: 2005-03-09
  rus: 2005-03-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/23773/kaz/09.03.2005
  rus: https://zan.gov.kz/client/#!/doc/23773/rus/09.03.2005
