act_code: '168302'
requisite: Приказ Министра внутренних дел Республики Казахстан от 30 мая 2022 года № 403. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 мая 2022 года № 28273
title:
  rus: Об утверждении Правил формирования и ведения дакто-, фотоучетов трудового иммигранта
  kaz: Еңбекші көшіп келушінің дакто-, фотоесептерін қалыптастыру және жүргізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-05-30
approved_by:
- '103003000000'
version_date:
  kaz: 2022-05-30
  rus: 2022-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/168302/kaz/30.05.2022
  rus: https://zan.gov.kz/client/#!/doc/168302/rus/30.05.2022
