act_code: '122338'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 19 апреля 2018 года № 255. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 июня 2018 года № 17009
title:
  rus: Об утверждении формы отчетности, предусмотренную стандартом Инициативы прозрачности добывающих отраслей в Республике Казахстан и руководства по ее заполнению
  kaz: Қазақстан Республикасындағы Өндіруші салалардың ашықтығы бастамасы стандартында көзделген есептілік нысанын және оны толтыру жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2018-04-19
approved_by:
- '103035000000'
version_date:
  kaz: 2026-06-28
  rus: 2026-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/122338/kaz/28.06.2026
  rus: https://zan.gov.kz/client/#!/doc/122338/rus/28.06.2026
caused_by:
  code: '224532'
  requisite: Приказ и.о. Министра промышленности и строительства Республики Казахстан от 22 апреля 2026 года № 194. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 апреля 2026 года № 38543
  title:
    rus: О внесении изменений в приказ Министра по инвестициям и развитию Республики Казахстан от 19 апреля 2018 года № 255 «Об утверждении формы отчетности, предусмотренную стандартом Инициативы прозрачности добывающих отраслей в Республике Казахстан и руководства по ее заполнению»
    kaz: Қазақстан Республикасы Инвестициялар және даму министрінің 2018 жылғы 19 сәуірдегі № 255 «Қазақстан Республикасында өндіруші салалардың ашықтығы бастамасының стандартымен көзделген есептілік нысанын және оны толтыру жөніндегі нұсқаулықты бекіту туралы» бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224532/rus
