act_code: '226985'
requisite: Приказ Заместителя Премьер-Министра - Министра культуры и информации Республики Казахстан от 25 июня 2026 года № 303-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 июня 2026 года № 39101
title:
  rus: Об утверждении Правил согласования проведения зрелищных культурно-массовых мероприятий с участием зарубежных творческих коллективов и исполнителей на территории Республики Казахстан
  kaz: Қазақстан Республикасының аумағында шетелдік шығармашылық ұжымдар мен орындаушылардың қатысуымен ойын-сауық мәдени-бұқаралық іс-шараларды өткізуді келісу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2026-06-25
approved_by:
- '103053000000'
version_date:
  kaz: 2026-06-25
  rus: 2026-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/226985/kaz/25.06.2026
  rus: https://zan.gov.kz/client/#!/doc/226985/rus/25.06.2026
