act_code: '466'
requisite: Приказ Директора Департамента казначейства Министерства финансов Республики Казахстан от 27 января 1998 года № 30. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 марта 1998 года № 489. Утратил силу приказом Министра финансов Республики Казахстан от 4 августа 2010 года № 395
title:
  rus: Об утверждении Инструкции по бухгалтерскому учету в государственных учреждениях
  kaz: Мемлекеттік мекемелердегі бухгалтерлік есеп жөніндегі нұсқаулық бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 1998-01-27
approved_by:
- '103002005000'
version_date:
  rus: 1999-05-24
source:
  rus: https://zan.gov.kz/client/#!/doc/466/rus/24.05.1999
caused_by:
  code: '3369'
  requisite: Приказ Министра финансов Республики Казахстан от 25 мая 1999 года N 242  Зарегистрирован в Министерстве юстиции Республики Казахстан 18.06.1999г. за N 810. Утратил силу приказом Министра финансов Республики Казахстан от 31 июля 2009 года № 328.
  title:
    rus: Об утверждении Правил возмещения расходов работодателей на выплату работающим гражданам пособий по обязательному социальному обеспечению
    kaz: Жұмыс істейтін азаматтарға міндетті әлеуметтік қамсыздандыру жөніндегі жәрдемақыларды төлеуге жұмсалған жұмыс берушілердің шығыстарын мемлекеттік бюджеттің қаражаты есебінен өтеудің қағидасын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/3369/rus
