act_code: '167428'
requisite: Приказ Министра информации и общественного развития Республики Казахстан от 4 мая 2022 года № 135. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 мая 2022 года № 27917. Утратил силу приказом и.о. Министра культуры и информации Республики Казахстан от 30 июня 2025 года № 297-НҚ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил определения стоимости исследований, консалтинговых услуг и государственных заданий Министерства культуры и информации Республики Казахстан
  kaz: Қазақстан Республикасы Мәдениет және ақпарат министрлігінің зерттеулерінің, консалтингтік көрсетілетін қызметтері мен мемлекеттік тапсырмаларының құнын айқындау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-05-04
approved_by:
- '103043000000'
version_date:
  kaz: 2024-07-03
  rus: 2024-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/167428/kaz/03.07.2024
  rus: https://zan.gov.kz/client/#!/doc/167428/rus/03.07.2024
caused_by:
  code: '198567'
  requisite: Приказ Министра культуры и информации Республики Казахстан от 3 июля 2024 года № 291-НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 июля 2024 года № 34712. Утратил силу приказом и.о. Министра культуры и информации Республики Казахстан от 30 июня 2025 года № 297-НҚ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в приказ Министра информации и общественного развития Республики Казахстан от 4 мая 2022 года № 135 «Об утверждении Правил определения стоимости исследований, консалтинговых услуг и государственных заданий Министерства информации и общественного развития Республики Казахстан»
    kaz: «Қазақстан Республикасы Ақпарат және қоғамдық даму министрлігінің зерттеулерінің, консалтингтік көрсетілетін қызметтер мен мемлекеттік тапсырмаларының құнын айқындау қағидаларын бекіту туралы» Қазақстан Республикасы Ақпарат және қоғамдық даму министрінің 2022 жылғы 4 мамырдағы № 135 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198567/rus
