act_code: '23659'
requisite: Приказ Министра транспорта и коммуникаций Республики Казахстан от 19 марта 2005 года № 129-I. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 апреля 2005 года № 3562. Утратил силу приказом Министра транспорта и коммуникаций Республики Казахстан от 26 июля 2013 года № 571
title:
  rus: Об утверждении Правил осуществления контроля за соблюдением перевозчиками Правил перевозок грузов, утвержденных приказом Министра транспорта и коммуникаций Республики Казахстан от 23 ноября 2004 года N 429-I, зарегистрированных за N 3294
  kaz: Қазақстан Республикасы Көлік және коммуникациялар министрінің N 3294 болып тіркелген 2004 жылғы 23 қарашадағы N 429-І бұйрығымен бекітілген Тасымалдаушылардың жүктерді тасымалдау ережесін сақтауын бақылауды жүзеге асыру ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2005-03-19
approved_by:
- '103013000000'
version_date:
  kaz: 2005-03-19
  rus: 2005-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/23659/kaz/19.03.2005
  rus: https://zan.gov.kz/client/#!/doc/23659/rus/19.03.2005
