act_code: '155690'
requisite: Приказ Министра образования и науки Республики Казахстан от 5 мая 2021 года № 204. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 мая 2021 года № 22711
title:
  rus: Об утверждении Правил проведения мониторинга образовательных достижений обучающихся
  kaz: Білім алушылардың білім жетістіктеріне мониторинг жүргізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2021-05-05
approved_by:
- '103006000000'
version_date:
  kaz: 2021-05-05
  rus: 2021-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/155690/kaz/05.05.2021
  rus: https://zan.gov.kz/client/#!/doc/155690/rus/05.05.2021
