act_code: '225961'
requisite: Приказ Заместителя Премьер-Министра – Министра искусственного интеллекта и цифрового развития Республики Казахстан от 2 июня 2026 года № 272/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 июня 2026 года № 38871
title:
  rus: Об утверждении Правил обеспечения мониторинга развития национальной инновационной системы
  kaz: Ұлттық инновациялық жүйенің даму мониторингін қамтамасыз ету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2026-06-02
approved_by:
- '103054000000'
version_date:
  kaz: 2026-06-02
  rus: 2026-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/225961/kaz/02.06.2026
  rus: https://zan.gov.kz/client/#!/doc/225961/rus/02.06.2026
