act_code: '3756'
requisite: Утверждена приказом Министра юстиции Республики Казахстан от 28 июля 1998 года № 539. Зарегистрирован в Министерстве юстиции Республики Казахстан от 10 августа 1998 года № 564. Утратил силу приказом Министра юстиции Республики Казахстан от 31 января 2012 года № 31
title:
  rus: Инструкция о порядке совершения нотариальных действий в Республике Казахстан
  kaz: Қазақстан Республикасында нотариаттық іс-әрекеттерді жасаудың тәртібі туралы Нұсқаулық
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 1998-07-27
approved_by:
- '103001000000'
version_date:
  rus: 2000-01-29
source:
  rus: https://zan.gov.kz/client/#!/doc/3756/rus/29.01.2000
caused_by:
  code: '5195'
  requisite: Приказ Министра юстиции Республики Казахстан от 29.01.2000 года № 7 Зарегистрирован в Министерстве юстиции Республики Казахстан 1.02.2000г. за № 1036. Утратил силу приказом Министра юстиции Республики Казахстан от 31 января 2012 года № 31
  title:
    rus: О внесении дополнения в Приказ Министра юстиции Республики Казахстан от 28 июля 1998 года № 539
    kaz: Қазақстан Республикасы Әділет министрінің 1998 жылғы 28 шілдедегі N 539 Бұйрығына толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/5195/rus
