act_code: '223280'
requisite: Приказ Министра промышленности и строительства Республики Казахстан от 20 марта 2026 года № 123. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 марта 2026 года № 38184
title:
  rus: Об утверждении Правил приемки, а также формы акта приемки строительного объекта в эксплуатацию заказчиком (собственником, инвестором) самостоятельно
  kaz: Тапсырыс берушінің (меншік иесінің, инвестордың) құрылыс объектісін пайдалануға өз бетінше қабылдау қағидаларын, сондай-ақ пайдалануға қабылдау актісінің нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2026-03-20
approved_by:
- '103052000000'
version_date:
  kaz: 2026-03-20
  rus: 2026-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/223280/kaz/20.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223280/rus/20.03.2026
