act_code: '124743'
requisite: Приказ Министра юстиции Республики Казахстан от 11 сентября 2018 года № 1382. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 сентября 2018 года № 17360
title:
  rus: Об утверждении требований к сопровождению правового кадастра и правил доступа к правовому кадастру
  kaz: Құқықтық кадастрды қолдауға қойылатын талаптарды және құқықтық кадастрға қол жеткізу қағидасын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2018-09-11
approved_by:
- '103001000000'
version_date:
  kaz: 2021-04-08
  rus: 2021-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/124743/kaz/08.04.2021
  rus: https://zan.gov.kz/client/#!/doc/124743/rus/08.04.2021
caused_by:
  code: '154545'
  requisite: Приказ Министра юстиции Республики Казахстан от 8 апреля 2021 года № 278. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 апреля 2021 года № 22526
  title:
    rus: О внесении изменения в приказ Министра юстиции Республики Казахстан от 11 сентября 2018 года № 1382 «Об утверждении требований к сопровождению правового кадастра и правила доступа к правовому кадастру»
    kaz: «Құқықтық кадастрды қолдауға қойылатын талаптарды және құқықтық кадастрға қол жеткізу қағидаларын бекіту туралы» Қазақстан Республикасы Әділет министрінің 2018 жылғы 11 қыркүйектегі № 1382 бұйрығына өзгерту енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154545/rus
