act_code: '88047'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 30 января 2015 года № 18-02/59. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 марта 2015 года № 10426. Утратил силу приказом Заместителя Премьер-Министра Республики Казахстан - Министра сельского хозяйства Республики Казахстан от 31 июля 2018 года № 322 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил по осуществлению государственного контроля и надзора в области охраны, защиты, пользования лесным фондом, воспроизводства лесов и лесоразведения должностными лицами государственной лесной инспекции Республики Казахстан
  kaz: Қазақстан Республикасы мемлекеттік орман инспекциясы лауазымды адамдарының орман қорын күзету, қорғау, пайдалану, ормандарды молықтыру және орман өсіру саласындағы мемлекеттік бақылау мен қадағалауды жүзеге асыруы жөніндегі қағидаларды бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-01-30
approved_by:
- '103012000000'
version_date:
  kaz: 2015-01-30
  rus: 2015-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/88047/kaz/30.01.2015
  rus: https://zan.gov.kz/client/#!/doc/88047/rus/30.01.2015
