act_code: '92681'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 30 марта 2015 года № 4-3/270. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 июля 2015 года № 11711
title:
  rus: Об утверждении Правил приема экзаменов и выдачи удостоверений на право управления тракторами и изготовленными на их базе самоходными шасси и механизмами, самоходными сельскохозяйственными, мелиоративными и дорожно-строительными машинами, а также специальными машинами повышенной проходимости
  kaz: Тракторларды және олардың базасында жасалған өздiгiнен жүретiн шассилер мен механизмдердi, өздiгiнен жүретiн ауылшаруашылық, мелиорациялық және жол-құрылыс машиналарын, сондай-ақ жүрiп өту мүмкiндiгi жоғары арнайы машиналарды басқару құқығына емтихандар қабылдау және куәлiктер беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-03-30
approved_by:
- '103012000000'
version_date:
  kaz: 2020-08-17
  rus: 2020-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/92681/kaz/17.08.2020
  rus: https://zan.gov.kz/client/#!/doc/92681/rus/17.08.2020
caused_by:
  code: '145615'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 17 августа 2020 года № 257. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 августа 2020 года № 21115
  title:
    rus: О внесении изменений в приказ Министра сельского хозяйства Республики Казахстан от 30 марта 2015 года № 4-3/270 «Об утверждении Правил приема экзаменов и выдачи удостоверений на право управления тракторами и изготовленными на их базе самоходными шасси и механизмами, самоходными сельскохозяйственными, мелиоративными и дорожно-строительными машинами, а также специальными машинами повышенной проходимости»
    kaz: «Тракторларды және олардың базасында жасалған өздiгiнен жүретiн шассилер мен механизмдердi, өздiгiнен жүретiн ауылшаруашылық, мелиорациялық және жол-құрылыс машиналарын, сондай-ақ жүрiп өту мүмкiндiгi жоғары арнайы машиналарды басқару құқығына емтихандар қабылдау және куәлiктер беру қағидаларын бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің 2015 жылғы 30 наурыздағы № 4-3/270 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145615/rus
