act_code: '89825'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 31 марта 2015 года № 396. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 мая 2015 года № 11028. Утратил силу приказом и.о. Министра по инвестициям и развитию Республики Казахстан от 31 мая 2018 года № 419 (вводится в действие с 29 июня 2018 года)
title:
  rus: Об утверждении Правил представления недропользователями отчетов о проведении операций по недропользованию
  kaz: Жер қойнауын пайдаланушылардың жер қойнауын пайдалану жөніндегі операцияларды жүргізу туралы есептер беру қағидаларын бекiту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-03-31
approved_by:
- '103035000000'
version_date:
  kaz: 2015-03-31
  rus: 2015-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/89825/kaz/31.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89825/rus/31.03.2015
repealed_on: 2018-06-29
repealed_by:
  code: '122724'
  requisite: Приказ и.о. Министра по инвестициям и развитию Республики Казахстан от 31 мая 2018 года № 419. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 июня 2018 года № 17050
  title:
    rus: Об утверждении форм отчетов по геологическому изучению недр
    kaz: Жер қойнауын геологиялық зерттеу жөніндегі есептердің нысандарын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/122724/rus
