act_code: '121681'
requisite: Приказ Министра оборонной и аэрокосмической промышленности Республики Казахстан от 16 марта 2018 года № 45/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 мая 2018 года № 16883
title:
  rus: Об утверждении Правил передачи резервных копий электронных информационных ресурсов на единую национальную резервную платформу хранения электронных информационных ресурсов
  kaz: Электрондық ақпараттық ресурстардың резервтік көшірмелерін электрондық ақпараттық ресурстарды сақтаудың бірыңғай ұлттық резервтік платформасына беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-03-16
approved_by:
- '103041000000'
version_date:
  kaz: 2023-04-27
  rus: 2023-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/121681/kaz/27.04.2023
  rus: https://zan.gov.kz/client/#!/doc/121681/rus/27.04.2023
caused_by:
  code: '180594'
  requisite: Приказ и.о. Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 27 апреля 2023 года № 83/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 мая 2023 года № 32400
  title:
    rus: О внесении изменения в приказ Министра оборонной и аэрокосмической промышленности Республики Казахстан от 16 марта 2018 года № 45/НҚ «Об утверждении Правил передачи резервных копий электронных информационных ресурсов на единую национальную резервную платформу хранения электронных информационных ресурсов»
    kaz: «Электрондық ақпараттық ресурстардың резервтік көшірмелерін электрондық ақпараттық ресурстарды сақтаудың бірыңғай ұлттық резервтік платформасына беру қағидаларын бекіту туралы» Қазақстан Республикасы Қорғаныс және аэроғарыш өнеркәсібі министрінің 2018 жылғы 16 наурыздағы № 45/НҚ бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180594/rus
