act_code: '219763'
requisite: Приказ Председателя Агентства Республики Казахстан по атомной энергии от 23 декабря 2025 года № 94 - н/қ. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 декабря 2025 года № 37687
title:
  rus: Об утверждении Правил установления стоимости исследований, консалтинговых услуг Агентства Республики Казахстан по атомной энергии
  kaz: Қазақстан Республикасы Атом энергиясы жөніндегі агенттігінің зерттеулерінің, консалтингтік көрсетілетін қызметтерінің құнын белгілеу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2025-12-23
approved_by:
- '131000000000'
version_date:
  kaz: 2025-12-23
  rus: 2025-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/219763/kaz/23.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219763/rus/23.12.2025
