act_code: '121674'
requisite: Приказ Министра оборонной и аэрокосмической промышленности Республики Казахстан от 19 марта 2018 года № 48/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 мая 2018 года № 16886
title:
  rus: Об утверждении Правил обмена информацией, необходимой для обеспечения информационной безопасности, между оперативными центрами обеспечения информационной безопасности и Национальным координационным центром информационной безопасности
  kaz: Ақпараттық қауіпсіздікті қамтамасыз етудің жедел орталықтары мен Ақпараттық қауіпсіздікті ұлттық үйлестіру орталығы арасындағы ақпараттық қауіпсіздікті қамтамасыз ету үшін қажетті ақпарат алмасу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-03-19
approved_by:
- '103041000000'
version_date:
  kaz: 2021-05-12
  rus: 2021-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/121674/kaz/12.05.2021
  rus: https://zan.gov.kz/client/#!/doc/121674/rus/12.05.2021
caused_by:
  code: '155949'
  requisite: Приказ Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 12 мая 2021 года № 164/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 мая 2021 года № 22756
  title:
    rus: О внесении изменений и дополнения в приказ Министра оборонной и аэрокосмической промышленности Республики Казахстан от 19 марта 2018 года № 48/НҚ «Об утверждении Правил обмена информацией, необходимой для обеспечения информационной безопасности, между оперативными центрами обеспечения информационной безопасности и Национальным координационным центром информационной безопасности»
    kaz: «Ақпараттық қауіпсіздікті қамтамасыз етудің жедел орталықтары мен Ақпараттық қауіпсіздікті ұлттық үйлестіру орталығы арасындағы ақпараттық қауіпсіздікті қамтамасыз ету үшін қажетті ақпарат алмасу қағидаларын бекіту туралы» Қазақстан Республикасының Қорғаныс және аэроғарыш өнеркәсібі министрінің 2018 жылғы 19 наурыздағы № 48/НҚ бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155949/rus
