act_code: '60248'
requisite: Приказ Министра внутренних дел Республики Казахстан от 27 мая 2011 года № 246. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 июня 2011 года № 7032. Утратил силу приказом Министра внутренних дел Республики Казахстан от 22 октября 2022 года № 830 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Некоторые вопросы прохождения службы в органах внутренних дел Республики Казахстан
  kaz: Қазақстан Республикасы ішкі істер органдарында қызмет өткерудің кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2011-05-27
approved_by:
- '103003000000'
version_date:
  kaz: 2013-07-19
  rus: 2013-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/60248/kaz/19.07.2013
  rus: https://zan.gov.kz/client/#!/doc/60248/rus/19.07.2013
caused_by:
  code: A13C0003786
