act_code: '70889'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 9 января 2013 года № 12-ө-м. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 января 2013 года № 8297. Утратил силу приказом Министра труда и социальной защиты населения Республики Казахстан от 4 сентября 2019 года № 478 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Единого тарифно-квалификационного справочника работ и профессий рабочих (выпуск 59)
  kaz: Жұмысшылардың жұмыстары мен кәсіптерінің бірыңғай тарифтік-біліктілік анықтамалығын (59-шығарылым) бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2013-01-09
approved_by:
- '103016000000'
version_date:
  kaz: 2013-01-09
  rus: 2013-01-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/70889/kaz/09.01.2013
  rus: https://zan.gov.kz/client/#!/doc/70889/rus/09.01.2013
