act_code: '57210'
requisite: Приказ Министра юстиции Республики Казахстан от 20 января 2011 года № 15. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 января 2011 года № 6754. Утратил силу приказом Министра юстиции Республики Казахстан от 27 августа 2020 года № 302 (вводится в действие по истечении десяти  календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил ведения частным судебным исполнителем книги учета сумм на текущем счете (депозитная книга)
  kaz: Жеке сот орындаушысымен ағымдағы шоттағы сомаларды есепке алу кітабын (депозиттік кітап) жүргізу ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2011-01-20
approved_by:
- '103001000000'
version_date:
  kaz: 2012-05-25
  rus: 2012-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/57210/kaz/25.05.2012
  rus: https://zan.gov.kz/client/#!/doc/57210/rus/25.05.2012
caused_by:
  code: '66405'
  requisite: Приказ Министра юстиции Республики Казахстан от 25 мая 2012 года № 207. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 июня 2012 года № 7764. Утратил силу приказом Министра юстиции Республики Казахстан от 27 августа 2020 года № 302 (вводится в действие по истечении десяти  календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в приказ Министра юстиции Республики Казахстан от 20 января 2011 года № 15 "Об утверждении Правил ведения частным судебным исполнителем книги учета сумм на текущем счете (депозитная книга)"
    kaz: Қазақстан Республика Әділет министрінің "Жеке сот орындаушысының ағымдағы шоттағы сомаларды есепке алу кітабын (депозиттік кітап) жүргізу ережесін бекіту туралы" 2011 жылғы 20 қаңтардағы № 15 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/66405/rus
