act_code: '196132'
requisite: Приказ Министра здравоохранения Республики Казахстан от 26 апреля 2024 года № 15. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 апреля 2024 года № 34307
title:
  rus: Об утверждении перечня заболеваний, являющихся основанием для освобождения от прохождения дактилоскопической регистрации
  kaz: Дактилоскопиялық тіркеуден өтуден босатуға негіз болатын аурулардың тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2024-04-26
approved_by:
- '103010000000'
version_date:
  kaz: 2024-04-26
  rus: 2024-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/196132/kaz/26.04.2024
  rus: https://zan.gov.kz/client/#!/doc/196132/rus/26.04.2024
