act_code: '179460'
requisite: Приказ и.о. Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 31 марта 2023 года № 130/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 апреля 2023 года № 32233
title:
  rus: Об утверждении Правил формирования, сбора, хранения, использования и выдачи сведений Национального фонда пространственных данных
  kaz: Ұлттық кеңістіктік деректер қорының мәліметтерін қалыптастыру, жинау, сақтау, пайдалану және беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2023-03-31
approved_by:
- '103045000000'
version_date:
  kaz: 2026-02-09
  rus: 2026-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/179460/kaz/09.02.2026
  rus: https://zan.gov.kz/client/#!/doc/179460/rus/09.02.2026
caused_by:
  code: '222050'
  requisite: Приказ Заместителя Премьер-Министра – Министра искусственного интеллекта и цифрового развития Республики Казахстан от 9 февраля 2026 года № 61/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 февраля 2026 года № 37970
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра цифрового развития, инноваций и аэрокосмической промышленности Республики Казахстан от 31 марта 2023 года № 130/НҚ «Об утверждении Правил формирования, сбора, хранения, использования и выдачи сведений Национального фонда пространственных данных»
    kaz: «Ұлттық кеңістіктік деректер қорының мәліметтерін қалыптастыру, жинау, сақтау, пайдалану және беру қағидаларын бекіту туралы» Қазақстан Республикасы Цифрлық даму, инновациялар және аэроғарыш өнеркәсібі министрінің міндетін атқарушының 2023 жылғы 31 наурыздағы № 130/НҚ бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222050/rus
