act_code: '97778'
requisite: Приказ и.о. Министра национальной экономики Республики Казахстан от 14 декабря 2015 года № 768. Зарегистрирован в Министерстве юстиции Республики Казахстан 15 января 2016 года № 12874
title:
  rus: Об утверждении объема квоты на беспошлинный ввоз тростникового сахара-сырца на территорию Республики Казахстан на 2016 год
  kaz: Қазақстан Республикасының аумағына шикі құрақ қантты бажсыз әкелуге 2016 жылға арналған квота көлемін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2015-12-14
approved_by:
- '103033000000'
version_date:
  kaz: 2015-12-14
  rus: 2015-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/97778/kaz/14.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97778/rus/14.12.2015
