act_code: '78315'
requisite: Приказ Министра внутренних дел Республики Казахстан от 8 февраля 2014 года № 76. Зарегистрирован в Министерстве юстиции Республики Казахстан от 11 марта 2014 года № 9200. Утратил силу приказом Министра труда и социальной защиты населения Республики Казахстан от 15 апреля 2022 года № 123 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил выдачи, продления и отзыва разрешения трудовому иммигранту, а также формирования и ведения дакто-, фотоучетов трудовых иммигрантов
  kaz: Еңбекші көшіп келушіге рұқсатты беру, ұзарту және кері қайтарып алу, сондай-ақ еңбекші көшіп келушілерді дакто-, фото есепке алуды қалыптастыру және жүргізу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2014-02-08
approved_by:
- '103003000000'
version_date:
  kaz: 2014-02-08
  rus: 2014-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/78315/kaz/08.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78315/rus/08.02.2014
