act_code: '174303'
requisite: Приказ Министра обороны Республики Казахстан от 25 ноября 2022 года № 1111. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 ноября 2022 года № 30756
title:
  rus: Об утверждении Инструкции по работе военных представительств Министерства обороны Республики Казахстан в организациях, независимо от форм собственности
  kaz: Меншік нысанына қарамастан, ұйымдарда Қазақстан Республикасы Қорғаныс министрлігі әскери өкілдіктерінің жұмысы жөніндегі нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2022-11-25
approved_by:
- '103008000000'
version_date:
  kaz: 2022-11-25
  rus: 2022-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/174303/kaz/25.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174303/rus/25.11.2022
