act_code: '48506'
requisite: Приказ Министра здравоохранения Республики Казахстан от 5 октября 2009 года № 493. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 ноября 2009 года № 5845. Утратил силу приказом Министра здравоохранения Республики Казахстан от 23 сентября 2020 года № ҚР ДСМ-110/2020 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Перечня медицинских противопоказаний к помещению детей в дом ребенка и организации образования, организации для детей-сирот и детей, оставшихся без попечения родителей
  kaz: Балаларды балалар үйіне және білім беру ұйымына, жетім балалар мен ата-анасының қамқорлығынсыз қалған балаларға арналған ұйымға орналастыруға медициналық қарсы айғақтар тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2009-10-05
approved_by:
- '103010000000'
version_date:
  kaz: 2009-10-05
  rus: 2009-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/48506/kaz/05.10.2009
  rus: https://zan.gov.kz/client/#!/doc/48506/rus/05.10.2009
