act_code: '60319'
requisite: Приказ Министра юстиции Республики Казахстан от 25 августа 2011 года № 296. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 августа 2011 года № 7146
title:
  rus: Об утверждении образцов удостоверения, личной печати частного судебного исполнителя
  kaz: Жеке сот орындаушысы куәлігінің, жеке мөрінің үлгілерін бекіту туралы
form: ПРИК
type_codes:
- ОБРА
- ПРИК
approved_on: 2011-08-25
approved_by:
- '103001000000'
version_date:
  kaz: 2014-03-07
  rus: 2014-03-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/60319/kaz/07.03.2014
  rus: https://zan.gov.kz/client/#!/doc/60319/rus/07.03.2014
caused_by:
  code: '78773'
  requisite: Приказ и.о. Министра юстиции Республики Казахстан от 7 марта 2014 года № 96. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 марта 2014 года № 9267
  title:
    rus: О внесении изменений в приказ Министра юстиции Республики Казахстан от 25 августа 2011 года № 296 "Об утверждении образцов удостоверения, личной печати и жетона частного судебного исполнителя"
    kaz: '"Жеке сот орындаушысының куәлігінің, жеке мөрі мен жетонының үлгілерін бекіту туралы" Қазақстан Республикасы Әділет министрінің 2011 жылғы 25 тамыздағы № 296 бұйрығына өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/78773/rus
