act_code: '73985'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 22 июля 2013 года № 329-Ө-М Зарегистрирован в Министерстве юстиции Республики Казахстан 16 августа 2013 года № 8624
title:
  rus: Об утверждении Правил присвоения или продления статуса кандаса
  kaz: Қандас мәртебесін беру немесе ұзарту қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2013-07-22
approved_by:
- '103016000000'
version_date:
  kaz: 2025-10-10
  rus: 2025-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/73985/kaz/10.10.2025
  rus: https://zan.gov.kz/client/#!/doc/73985/rus/10.10.2025
caused_by:
  code: '215540'
  requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 10 октября 2025 года № 317. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 октября 2025 года № 37107
  title:
    rus: О внесении изменений и дополнения в приказ Министра труда и социальной защиты населения Республики Казахстан от 22 июля 2013 года № 329-Ө-М «Об утверждении Правил присвоения или продления статуса кандаса»
    kaz: «Қандас мәртебесін беру немесе ұзарту қағидаларын бекіту туралы» Қазақстан Республикасы Еңбек және халықты әлеуметтік қорғау министрінің 2013 жылғы 22 шілдедегі № 329-Ө-М бұйрығына өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215540/rus
