act_code: '140993'
requisite: Приказ Министра внутренних дел Республики Казахстан от 31 марта 2020 года № 276. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 марта 2020 года № 20231
title:
  rus: Об утверждении Правил оказания государственных услуг в сфере оборота наркотических средств, психотропных веществ и прекурсоров
  kaz: Есірткі, психотроптық заттар мен прекурсорлар айналымы саласында мемлекеттік қызмет көрсету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-03-31
approved_by:
- '103003000000'
version_date:
  kaz: 2023-03-08
  rus: 2023-03-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/140993/kaz/08.03.2023
  rus: https://zan.gov.kz/client/#!/doc/140993/rus/08.03.2023
caused_by:
  code: '176550'
  requisite: Приказ Министра внутренних дел Республики Казахстан от 29 декабря 2022 года № 1010. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 декабря 2022 года № 31414
  title:
    rus: О внесении изменений в приказ Министра внутренних дел Республики Казахстан от 31 марта 2020 года № 276 «Об утверждении Правил оказания государственных услуг в сфере оборота наркотических средств, психотропных веществ и прекурсоров»
    kaz: «Есірткі құралдарының, психотроптық заттардың және прекурсорлар айналымы саласында мемлекеттік қызметтер көрсету қағидаларын бекіту туралы» Қазақстан Республикасы Ішкі істер министрінің 2020 жылғы 31 наурыздағы № 276 бұйрығына өзгерістер енгізу туралы»
  link: https://zan.gov.kz/client/#!/doc/176550/rus
