act_code: '125006'
requisite: Приказ Министра национальной экономики Республики Казахстан от 26 сентября 2018 года № 20. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 сентября 2018 года № 17442
title:
  rus: Об установлении лимитов долга местных исполнительных органов на 2019 год
  kaz: Жергілікті атқарушы органдар борышының 2019 жылға арналған лимиттерін белгілеу туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2018-09-26
approved_by:
- '103033000000'
version_date:
  kaz: 2018-09-26
  rus: 2018-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/125006/kaz/26.09.2018
  rus: https://zan.gov.kz/client/#!/doc/125006/rus/26.09.2018
