act_code: '52976'
requisite: Приказ Председателя Комитета по судебному администрированию при Верховном суде Республики Казахстан от 26 апреля 2010 года № 01-01-31/146. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 мая 2010 года № 6247. Утратил силу приказом и.о. Министра юстиции Республики Казахстан от 3 ноября 2010 года № 307
title:
  rus: Об утверждении требований к местонахождению и оборудованию конторы частного судебного исполнителя
  kaz: '"Жеке сот орындаушысы кеңсесінің орналасқан жеріне және жабдықталуына қойылатын талаптарды бекіту туралы"'
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2010-04-26
approved_by:
- '105001000000'
version_date:
  kaz: 2010-04-26
  rus: 2010-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/52976/kaz/26.04.2010
  rus: https://zan.gov.kz/client/#!/doc/52976/rus/26.04.2010
