act_code: '24510'
requisite: Приказ Генерального прокурора Республики Казахстан от 19 мая 2005 года N 18. Зарегистрирован в Министерстве юстиции Республики Казахстан 22 июня 2005 года N 3685. Утратил силу приказом Генерального Прокурора Республики Казахстан от 30 мая 2007 года N 20
title:
  rus: Об утверждении статистического отчета формы N 1-ОГ "О рассмотрении обращений граждан" и Инструкции по его составлению
  kaz: '"Азаматтардың жүгінулерін қарастыру туралы" N1-ОГ нысанды статистикалық есеп және оның құрылуы бойынша Нұсқаулықты бекіту туралы'
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2005-05-19
approved_by:
- '107000000000'
version_date:
  kaz: 2006-12-15
  rus: 2006-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/24510/kaz/15.12.2006
  rus: https://zan.gov.kz/client/#!/doc/24510/rus/15.12.2006
caused_by:
  code: '31029'
  requisite: Приказ Генерального Прокурора Республики Казахстан от 15 декабря 2006 года № 74. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 января 2007 года № 4506. Утратил силу приказом Генерального Прокурора Республики Казахстан от 30 мая 2007 года № 20
  title:
    rus: О внесении изменений и дополнений в приказ Генерального Прокурора Республики Казахстан от 19 мая 2005 года N 18 "Об утверждении статистического отчета формы № 1-ОГ "О рассмотрении обращений граждан" и Инструкции по его составлению"
    kaz: '"Азаматтардың өтініштерін қарау туралы»N1-ОГ нысанды статистикалық есепті және оның құрылуы бойынша Нұсқаулықты бекіту туралы" Қазақстан Республикасы Бас Прокурорының 2005 жылғы 19 мамырдағы № 18 бұйрығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/31029/rus
