act_code: '89315'
requisite: Приказ Министра здравоохранения и социального развития Республики Казахстан от 31 марта 2015 года № 188. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 апреля 2015 года № 10858
title:
  rus: Об утверждении перечня медицинских психиатрических противопоказаний для осуществления отдельных видов профессиональной деятельности, а также работ, с вязанных с источником повышенной опасности
  kaz: Кәсіптік қызметтің жекелеген түрлерін, сондай-ақ жоғары қауіп көзімен байланысты жұмыстарды жүзеге асыруға арналған медициналық психиатриялық қарсы өрсетілімдер  тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2015-03-31
approved_by:
- '103037000000'
version_date:
  kaz: 2015-03-31
  rus: 2015-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/89315/kaz/31.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89315/rus/31.03.2015
