act_code: '15701'
requisite: Приказ Председателя Агентства таможенного контроля Республики Казахстан от 17 мая 2003 года N 214. Зарегистрирован в Министерстве юстиции Республики Казахстан 2 июня 2003 года N 2339. Утратил силу - приказом Председателя Комитета таможенного контроля Министерства финансов РК от 1 марта 2006 года N 87
title:
  rus: О таможенном контроле после выпуска товаров и транспортных средств
  kaz: Тауарлар мен көлік құралдарын шығарғаннан кейін кедендік бақылау жүргізу туралы
form: ПРИК
type_codes:
- ПОЛ
- ПРАВ
- ПРИК
approved_on: 2003-05-16
approved_by:
- '103002004000'
version_date:
  kaz: 2003-05-16
  rus: 2003-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/15701/kaz/16.05.2003
  rus: https://zan.gov.kz/client/#!/doc/15701/rus/16.05.2003
