act_code: '89596'
requisite: Приказ Министра внутренних дел Республики Казахстан от 16 марта 2015 года № 225. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 мая 2015 года № 10974. Утратил силу приказом Министра внутренних дел Республики Казахстан от 18 декабря 2019 года № 1069 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении профессионального стандарта "Деятельность по обеспечению безопасности в чрезвычайных ситуациях"
  kaz: '"Төтенше жағдайларда қауіпсіздікті қамтамасыз ету қызметі" кәсіби стандартын бекіту туралы'
form: ПРИК
type_codes:
- ПРИК
- СТНД
approved_on: 2015-03-16
approved_by:
- '103003000000'
version_date:
  kaz: 2015-03-16
  rus: 2015-03-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/89596/kaz/16.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89596/rus/16.03.2015
