act_code: '59991'
requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 9 июня 2011 года № 380. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 июля 2011 года № 7065. Утратил силу приказом Министра здравоохранения Республики Казахстан от 19 декабря 2012 года № 872
title:
  rus: Об утверждении форм проверочных листов в области санитарно-эпидемиологического благополучия населения
  kaz: Халықтың санитариялық-эпидемиологиялық салауаттылығы саласындағы парақтарының нысандарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2011-06-09
approved_by:
- '103010000000'
version_date:
  kaz: 2011-06-09
  rus: 2011-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/59991/kaz/09.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59991/rus/09.06.2011
