act_code: '175165'
requisite: Приказ Министра обороны Республики Казахстан от 28 ноября 2022 года № 1132 дсп. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 декабря 2022 года № 30953
title:
  rus: «Об утверждении Правил обеспечения пропускного режима в здание Министерства обороны Республики Казахстан»
  kaz: «Қазақстан Республикасы Қорғаныс министрлігінің ғимаратына өткізу режимін қамтамасыз ету қағидаларын бекіту туралы»
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2022-11-28
approved_by:
- '103008000000'
version_date:
  kaz: 2025-11-20
  rus: 2025-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/175165/kaz/20.11.2025
  rus: https://zan.gov.kz/client/#!/doc/175165/rus/20.11.2025
caused_by:
  code: '217578'
  requisite: Приказ Министра обороны Республики Казахстан от 20 ноября 2025 года № 1627 дсп
  title:
    rus: О внесении изменения в приказ Министра обороны Республики Казахстан от 28 ноября 2022 года № 1132 дсп «Об утверждении Правил обеспечения пропускного режима в здание Министерства обороны Республики Казахстан»
    kaz: «Қазақстан Республикасы Қорғаныс министрлігінің ғимаратына өткізу режимін қамтамасыз ету қағидаларын бекіту туралы» Қазақстан Республикасы Қорғаныс министрінің 2022 жылғы 28 қарашадағы № 1132 қбпү бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217578/rus
