act_code: '107020'
requisite: Приказ Министра национальной экономики Республики Казахстан от 30 сентября 2016 года № 432. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 октября 2016 года № 14312
title:
  rus: Об утверждении Правил рассмотрения документов по проекту строительства многоквартирного жилого дома или комплекса индивидуальных жилых домов для заключения договора о предоставлении гарантии или договоров в рамках реновации
  kaz: Кепілдік беру туралы шарт немесе реновациялау шеңберінде шарттар жасасу үшін көппәтерлі тұрғын үй немесе жеке тұрғын үйлер кешені құрылысының жобасы бойынша құжаттарды қарау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2016-09-30
approved_by:
- '103033000000'
version_date:
  kaz: 2025-08-25
  rus: 2025-08-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/107020/kaz/25.08.2025
  rus: https://zan.gov.kz/client/#!/doc/107020/rus/25.08.2025
caused_by:
  code: '213714'
  requisite: Приказ Министра промышленности и строительства Республики Казахстан от 25 августа 2025 года № 315. Зарегистрирован в Министерстве юстиции Республики Казахстан 28 августа 2025 года № 36723
  title:
    rus: О внесении изменений в некоторые приказы
    kaz: Кейбір бұйрықтарға өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213714/rus
