act_code: '68016'
requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 22 сентября 2012 года № 444/дсп. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 октября 2012 года № 7968
title:
  rus: Об утверждении Правил по заключению, продлению, изменению, расторжению и прекращению контракта о прохождении службы в органах национальной безопасности Республики Казахстан
  kaz: Қазақстан Республикасы ұлттық қауіпсіздік органдарында қызмет өткеру туралы келісімшарт жасасу, ұзарту, өзгерту, бұзу және тоқтату бойынша қағидаларды бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2012-09-22
approved_by:
- '108000000000'
version_date:
  kaz: 2020-05-18
  rus: 2020-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/68016/kaz/18.05.2020
  rus: https://zan.gov.kz/client/#!/doc/68016/rus/18.05.2020
caused_by:
  code: '143192'
  requisite: Приказ Председателя Комитета национальной безопасности Республики Казахстан от 18 мая 2020 года № 37/дсп. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 мая 2020 года № 20689
  title:
    rus: О внесении изменения в приказ Председателя Комитета национальной безопасности Республики Казахстан от 22 сентября 2012 года №444/ДСП «Об утверждении Правил по заключению, продлению, изменению, расторжению и прекращению контракта о прохождении службы в органах национальной безопасности Республики Казахстан»
    kaz: «Қазақстан Республикасы ұлттық қауіпсіздік органдарында қызмет өткеру туралы келісімшарт жасасу, ұзарту, өзгерту, бұзу және тоқтату бойынша қағидаларды бекіту туралы» Қазақстан Республикасы Ұлттық қауіпсіздік комитеті Төрағасының 2012 жылғы 22 қыркүйектегі № 444/ҚБП бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143192/rus
