act_code: '172780'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 28 сентября 2022 года № 302. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 29 апреля 2025 года № 134 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об утверждении натуральных норм государственных учреждений в сфере государственного контроля за использованием и охраной земель
  kaz: Жерді пайдалану мен қорғауды мемлекеттік бақылау саласындағы мемлекеттік мекемелердің заттай нормаларын бекіту туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2022-09-28
approved_by:
- '103012000000'
version_date:
  kaz: 2022-09-28
  rus: 2022-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/172780/kaz/28.09.2022
  rus: https://zan.gov.kz/client/#!/doc/172780/rus/28.09.2022
