act_code: '22115'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 3 ноября 2004 года № 626. Зарегистрирован Министерством юстиции Республики Казахстан 26 ноября 2004 года № 3225. Утратил силу приказом Министра сельского хозяйства Республики Казахстан от 17 января 2012 года № 10-1/18
title:
  rus: Об утверждении Ветеринарных правил осуществления мероприятий по профилактике и ликвидации туберкулеза животных и птиц
  kaz: Малдармен құстардың туберкулезінің алдын-алу және жою шараларын жүзеге асырудың ветеринариялық ережелерін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2004-11-03
approved_by:
- '103012000000'
version_date:
  kaz: 2004-11-03
  rus: 2004-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/22115/kaz/03.11.2004
  rus: https://zan.gov.kz/client/#!/doc/22115/rus/03.11.2004
