act_code: '74116'
requisite: Приказ Министра внутренних дел Республики Казахстан от 12 августа 2013 года № 493. Зарегистрирован в Министерстве юстиции Республики Казахстан от 27 августа 2013 года № 8649
title:
  rus: Об утверждении перечня персональных данных, необходимого и достаточного для выполнения осуществляемых задач
  kaz: Жүзеге асырылатын міндеттерді орындау үшін қажетті және жеткілікті дербес деректердің тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2013-08-12
approved_by:
- '103003000000'
version_date:
  kaz: 2013-08-12
  rus: 2013-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/74116/kaz/12.08.2013
  rus: https://zan.gov.kz/client/#!/doc/74116/rus/12.08.2013
