act_code: '78706'
requisite: Приказ исполняющего обязанности Министра индустрии и новых технологий Республики Казахстан от 25 февраля 2014 года № 51. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 марта 2014 года № 9232. Утратил силу приказом Министра по инвестициям и развитию Республики Казахстан от 20 мая 2015 года № 585
title:
  rus: Об утверждении Регламента государственной услуги "Заключение инвестиционного контракта на осуществление инвестиций, предусматривающего инвестиционные преференции"
  kaz: '"Инвестициялық преференцияларды көздейтін инвестицияларды жүзеге асыратын инвестициялық келісімшарт жасау" мемлекеттік қызмет Регламентін бекіту жөнінде'
form: ПРИК
type_codes:
- ПРИК
- РЕГЛ
approved_on: 2014-02-25
approved_by:
- '103017000000'
version_date:
  kaz: 2014-02-25
  rus: 2014-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/78706/kaz/25.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78706/rus/25.02.2014
