act_code: '33741'
requisite: Приказ Министра финансов Республики Казахстан от 28 мая 2007 года № 188. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 июня 2007 года № 4741. Утратил силу приказом Министра финансов Республики Казахстан от 20 декабря 2012 года № 561
title:
  rus: Об утверждении перечня, форм и периодичности представления отчетности аккредитованными профессиональными организациями бухгалтеров и организациями по профессиональной сертификации бухгалтеров
  kaz: Бухгалтерлердің аккредиттелген кәсіптік ұйымдары мен бухгалтерлерді кәсіптік сертификаттау жөніндегі ұйымдардың есептілігі тізбесін, нысандары мен ұсыну мерзімділігін бекіту туралы.
form: ПРИК
type_codes:
- ПРИК
approved_on: 2007-05-28
approved_by:
- '103002000000'
version_date:
  kaz: 2007-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/33741/kaz/07.06.2007
