act_code: '120079'
requisite: Приказ Министра финансов Республики Казахстан от 19 марта 2018 года № 391. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 марта 2018 года № 16669. Утратил силу приказом и.о. Министра финансов Республики Казахстан от 30 октября 2025 года № 649 (вводится в действие с 1 января 2026 года)
title:
  rus: Об утверждении Правил возврата превышения налога на добавленную стоимость и применения системы управления рисками в целях подтверждения достоверности суммы превышения налога на добавленную стоимость, а также критериев степени риска
  kaz: Қосылған құн салығының асып кетуін қайтару және қосылған құн салығының асып кеткен сомасының анықтығын растау мақсатында тәуекелдерді басқару жүйесін қолдану қағидаларын, сондай-ақ тәуекел дәрежесінің өлшемшарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2018-03-19
approved_by:
- '103002000000'
version_date:
  kaz: 2025-01-28
  rus: 2025-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/120079/kaz/28.01.2025
  rus: https://zan.gov.kz/client/#!/doc/120079/rus/28.01.2025
caused_by:
  code: '206834'
repealed_on: 2026-01-01
repealed_by:
  code: '216340'
  requisite: Приказ и.о. Министра финансов Республики Казахстан от 30 октября 2025 года № 649. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 октября 2025 года № 37306
  title:
    rus: Об утверждении Правил возврата суммы превышения налога на добавленную стоимость
    kaz: Қосылған құн салығының асып кету сомасын қайтару қағидаларын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/216340/rus
