act_code: '96433'
requisite: Приказ и.о. Министра по инвестициям и развитию Республики Казахстан от 7 октября 2015 года № 978. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 декабря 2015 года № 12360
title:
  rus: Об утверждении Правил аэродромного обеспечения в гражданской авиации
  kaz: Азаматтық авиацияда әуеайлақтық қамтамасыз ету қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-10-07
approved_by:
- '103035000000'
version_date:
  kaz: 2019-08-01
  rus: 2019-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/96433/kaz/01.08.2019
  rus: https://zan.gov.kz/client/#!/doc/96433/rus/01.08.2019
caused_by:
  code: '133163'
  requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 25 июня 2019 года № 429. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 июля 2019 года № 18965
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра по инвестициям и развитию Республики Казахстан от 7 октября 2015 года № 978 «Об утверждении Правил аэродромного обеспечения в гражданской авиации»
    kaz: «Азаматтық авиацияда әуеайлақтық қамтамасыз ету қағидаларын бекіту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің міндетін атқарушының 2015 жылғы 7 қазандағы № 978 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133163/rus
