act_code: '36234'
requisite: Приказ Министра образования и науки Республики Казахстан от 29 ноября 2007 года N 583. Зарегистрирован в Министерстве юстиции Республики Казахстан 13 декабря 2007 года N 5036
title:
  rus: Об утверждении Правил организации и осуществления учебно-методической и научно-методической работы в организациях образования
  kaz: Білім беру ұйымдарында оқу-әдістемелік және ғылыми-әдістемелік жұмысты ұйымдастыру және жүзеге асыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2007-11-29
approved_by:
- '103006000000'
version_date:
  kaz: 2023-06-08
  rus: 2023-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/36234/kaz/08.06.2023
  rus: https://zan.gov.kz/client/#!/doc/36234/rus/08.06.2023
caused_by:
  code: '182750'
  requisite: Приказ Министра науки и высшего образования Республики Казахстан от 8 июня 2023 года № 263. Зарегистрирован в Министерстве юстиции Республики Казахстан 9 июня 2023 года № 32747
  title:
    rus: «О внесении изменений в Приказ Министра образования и науки Республики Казахстан от 29 ноября 2007 года № 583 «Об утверждении Правил организации и осуществления учебно-методической и научно-методической работы в организациях образования»
    kaz: «Оқу-әдістемелік және ғылыми-әдістемелік жұмысты ұйымдастыру және жүзеге асыру қағидаларын бекіту туралы» Қазақстан Республикасы Білім және ғылым министрінің 2007 жылғы 29 қарашадағы № 583 бұйрығына өгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/182750/rus
