act_code: '108296'
requisite: Приказ Председателя Комитета по статистике Министерства национальной экономики Республики Казахстан от 24 ноября 2016 года № 274. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 декабря 2016 года № 14544
title:
  rus: Об утверждении Методики расчета базового индекса потребительских цен
  kaz: Базалық тұтыну бағасының индексін есептеу әдістемесін бекіту туралы
form: ПРИК
type_codes:
- МЕТ
- ПРИК
approved_on: 2016-11-24
approved_by:
- '103033003000'
version_date:
  kaz: 2025-04-23
  rus: 2025-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/108296/kaz/23.04.2025
  rus: https://zan.gov.kz/client/#!/doc/108296/rus/23.04.2025
caused_by:
  code: '209461'
  requisite: Приказ Руководителя Бюро национальной статистики Агентства по стратегическому планированию и реформам Республики Казахстан от 23 апреля 2025 года № 9. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 апреля 2025 года № 36015
  title:
    rus: О внесении изменений в некоторые приказы
    kaz: Кейбір бұйрықтарға өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209461/rus
