act_code: '50796'
requisite: Совместный приказ Министра внутренних дел Республики Казахстан от 29 декабря 2009 года № 504 и Министра экономики и бюджетного планирования Республики Казахстан от 10 февраля 2010 года № 41. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 февраля 2010 года № 6060. Утратил силу совместным приказом Министра внутренних дел Республики Казахстан от 28 марта 2011 года № 132 и Министра экономического развития и торговли Республики Казахстан от 11 апреля 2011 года № 100
title:
  rus: Об утверждении критериев оценки степени риска субъектов, осуществляющих деятельность по монтажу, наладке и техническому обслуживанию средств охранной сигнализации, за исключением деятельности при выполнении строительно-монтажных работ, субъектов охранной деятельности, а также субъектов с хранением гражданского и служебного оружия и патронов к нему, взрывчатых веществ и материалов, гражданских пиротехнических веществ и изделий с их применением, ядовитых веществ, множительно-копировальной техники цветного изображения и штемпельно-граверных предприятий по изготовлению печатей и штампов
  kaz: Құрылыс-монтаждау жұмысын орындау кезіндегі қызметті қоспағанда, күзет сигнализациясы құралдарын монтаждау, ретке келтіру және оларға техникалық қызмет көрсету жөніндегі қызметті жүзеге асыратын субъектілерді, күзет қызметі субъектілерін, сондай-ақ азаматтық және қызметтік қару мен оның патрондарын, жарылғыш заттар мен материалдарды, азаматтық пиротехникалық заттар мен оларды қолданып жасалған бұйымдарды, улы заттарды, түрлі-түсті көбейту-көшіру техникасын сақтайтын субъектілерді және мөрлер мен мөртаңбаларды дайындау жөніндегі штемпельдік-граверлік кәсіпорындарды тәуекел дәрежесін бағалау критерийлері бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПРИК
approved_on: 2009-12-29
approved_by:
- '103003000000'
- '103005000000'
version_date:
  kaz: 2009-12-29
  rus: 2009-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/50796/kaz/29.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50796/rus/29.12.2009
