act_code: '117714'
requisite: Приказ Министра образования и науки Республики Казахстан от 27 ноября 2017 года № 596. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 декабря 2017 года № 16138
title:
  rus: Об утверждении Правил подушевого нормативного финансирования дошкольного воспитания и обучения, среднего образования, а также технического и профессионального, послесреднего образования с учетом кредитной технологии обучения
  kaz: Мектепке дейінгі тәрбие мен оқытуды, орта білім беруді, сондай-ақ кредиттік оқыту технологиясын ескере отырып, техникалық және кәсіптік, орта білімнен кейінгі білім беруді жан басына шаққандағы нормативтік қаржыландыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2017-11-27
approved_by:
- '103006000000'
version_date:
  kaz: 2018-09-21
  rus: 2018-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/117714/kaz/21.09.2018
  rus: https://zan.gov.kz/client/#!/doc/117714/rus/21.09.2018
caused_by:
  code: '124978'
  requisite: Приказ Министра образования и науки Республики Казахстан от 21 сентября 2018 года № 477. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 октября 2018 года № 17486
  title:
    rus: О внесении изменений в приказ Министра образования и науки Республики Казахстан от 27 ноября 2017 года № 596 «Об утверждении Правил подушевого нормативного финансирования дошкольного воспитания и обучения, среднего, технического и профессионального, послесреднего, высшего и послевузовского образования»
    kaz: «Мектепке дейінгі тәрбие мен оқытудың, орта, техникалық және кәсіптік, орта білімнен кейінгі, жоғары және жоғары оқу орнынан кейінгі білім берудің жан басына шаққандағы нормативтік қаржыландыру қағидаларын бекіту туралы» Қазақстан Республикасы Білім және ғылым министрінің 2017 жылғы 27 қарашадағы № 596 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124978/rus
