act_code: '89474'
requisite: Приказ Министра финансов Республики Казахстан от 30 марта 2015 года № 233. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 апреля 2015 года № 10878. Утратил силу приказом Министра финансов Республики Казахстан от 23 января 2018 года № 47 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении норм расходов на проживание и выплату суммы денег обучаемому лицу
  kaz: Білім алушы тұлғаның тұруына және оған ақша сомасын төлеуге арналған шығыстар нормаларын белгілеу туралы
form: ПРИК
type_codes:
- НОРМ
- ПРИК
approved_on: 2015-03-30
approved_by:
- '103002000000'
version_date:
  kaz: 2015-03-30
  rus: 2015-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/89474/kaz/30.03.2015
  rus: https://zan.gov.kz/client/#!/doc/89474/rus/30.03.2015
