act_code: '209611'
requisite: Приказ Министра финансов Республики Казахстан от 28 апреля 2025 года № 198
title:
  rus: Об утверждении Правил составления прогнозной консолидированной финансовой отчетности по бюджету столицы, областному бюджету, бюджету города республиканского значения
  kaz: Астананың бюджеті, облыстық бюджет, республикалық маңызы бар қаланың бюджеті бойынша болжамды шоғырландырылған қаржылық есептілікті жасау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2025-04-28
approved_by:
- '103002000000'
version_date:
  kaz: 2026-07-01
  rus: 2026-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/209611/kaz/01.07.2026
  rus: https://zan.gov.kz/client/#!/doc/209611/rus/01.07.2026
caused_by:
  code: '226790'
  requisite: Приказ Министра финансов Республики Казахстан от 19 июня 2026 года № 418
  title:
    rus: О внесении изменений в приказ Министра финансов Республики Казахстан от 28 апреля 2025 года № 198 «Об утверждении Правил составления прогнозной консолидированной финансовой отчетности по областному бюджету, бюджету города  республиканского значения, столицы»
    kaz: «Облыстық бюджет, республикалық маңызы бар қаланың, астананың бюджеті бойынша болжамды шоғырландырылған қаржылық есептілікті жасау қағидаларын бекіту туралы» Қазақстан Республикасы Қаржы министрінің 2025 жылғы 28 сәуірдегі № 198 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/226790/rus
