act_code: '228043'
requisite: Приказ Заместителя Премьер-Министра – Министра искусственного интеллекта и цифрового развития Республики Казахстан от 21 июля 2026 года № 428/НҚ. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 июля 2026 года № 39377
title:
  rus: Об утверждении формы, предназначенной для сбора административных данных «Форма отчетной информацию по результатам предоставленной услуги связи и по внедрению субъектом цифрового решения»
  kaz: «Ұсынылған байланыс қызметінің нәтижелері бойынша және субъектінің цифрлық шешімді ендіруі бойынша есепті ақпарат нысаны» әкімшілік деректерді жинауға арналған нысанды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2026-07-21
approved_by:
- '103054000000'
version_date:
  kaz: 2026-07-21
  rus: 2026-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/228043/kaz/21.07.2026
  rus: https://zan.gov.kz/client/#!/doc/228043/rus/21.07.2026
