act_code: '151292'
requisite: Приказ и.о. Министра индустрии и инфраструктурного развития Республики Казахстан от 31 декабря 2020 года № 706. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 января 2021 года № 22031
title:
  rus: Об утверждении Правил использования беспилотных авиационных систем в воздушном пространстве Республики Казахстан
  kaz: Қазақстан Республикасының әуе кеңістігінде пилотсыз авиациялық жүйелерді пайдалану қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-12-31
approved_by:
- '103042000000'
version_date:
  kaz: 2024-01-01
  rus: 2024-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/151292/kaz/01.01.2024
  rus: https://zan.gov.kz/client/#!/doc/151292/rus/01.01.2024
caused_by:
  code: '181230'
  requisite: Приказ Министра индустрии и инфраструктурного развития Республики Казахстан от 12 мая 2023 года № 340. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 мая 2023 года № 32476
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра индустрии и инфраструктурного развития Республики Казахстан от 31 декабря 2020 года № 706 «Об утверждении Правил эксплуатации беспилотных летательных аппаратов в воздушном пространстве Республики Казахстан»
    kaz: «Қазақстан Республикасының әуе кеңістігінде пилотсыз ұшу аппараттарын пайдалану қағидаларын бекіту туралы» Қазақстан Республикасы Индустрия және инфрақұрылымдық даму министрінің міндетін атқарушының 2020 жылғы 31 желтоқсандағы № 706 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181230/rus
