act_code: '75132'
requisite: Приказ Министра труда и социальной защиты населения Республики Казахстан от 26 сентября 2013 года № 462-Ө-М. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 октября 2013 года № 8772. Утратил силу приказом Министра труда и социальной защиты населения Республики Казахстан от 23 декабря 2013 года № 675-Ө-М
title:
  rus: Об определении черты бедности на 4 квартал 2013 года
  kaz: 2013 жылғы 4 тоқсанға арналған кедейлік шегін анықтау туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2013-09-26
approved_by:
- '103016000000'
version_date:
  kaz: 2013-09-26
  rus: 2013-09-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/75132/kaz/26.09.2013
  rus: https://zan.gov.kz/client/#!/doc/75132/rus/26.09.2013
