act_code: '114693'
requisite: Приказ Министра здравоохранения Республики Казахстан от 16 августа 2017 года № 612. Зарегистрирован в Министерстве юстиции Республики Казахстан 12 сентября 2017 года № 15661
title:
  rus: Об утверждении форм и сроков представления фондом социального медицинского страхования отчетности по средствам на оказание медицинской помощи
  kaz: Әлеуметтік медициналық сақтандыру қорының медициналық көмек көрсетуге арналған қаражат бойынша есептілікті ұсыну нысандары мен мерзімдерін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2017-08-16
approved_by:
- '103010000000'
version_date:
  kaz: 2022-08-25
  rus: 2022-08-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/114693/kaz/25.08.2022
  rus: https://zan.gov.kz/client/#!/doc/114693/rus/25.08.2022
caused_by:
  code: '171058'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 25 августа 2022 года № ҚР ДСМ-92. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 августа 2022 года № 29310
  title:
    rus: О внесении изменений и дополнения в приказы Министра здравоохранения Республики Казахстан от 30 июня 2017 года № 478 «Об утверждении Правил и сроков исчисления (удержания) и перечисления отчислений и (или) взносов на обязательное социальное медицинское страхование и Правил осуществления возврата плательщикам излишне (ошибочно) зачисленных сумм отчислений, взносов и (или) пени за несвоевременную и (или) неполную уплату отчислений и (или) взносов» и от 16 августа 2017 года № 612 «Об утверждении перечня, форм, сроков представления финансовой и иной отчетности фондом социального медицинского страхования для обеспечения контрольных функций»
    kaz: Қазақстан Республикасы Денсаулық сақтау министрінің «Міндетті әлеуметтік медициналық сақтандыруға аударымдарды және (немесе) жарналарды есептеу (ұстап қалу) және аудару қағидалары мен мерзімдерін және аударымдардың, жарналардың және (немесе) аударымдарды және (немесе) жарналарды уақтылы және (немесе) толық төлемегені үшін өсімпұлдың артық (қате) есепке жатқызылған сомаларын төлеушілерге қайтаруды жүзеге асыру қағидаларын бекіту туралы» 2017 жылғы 30 маусымдағы № 478 және «Бақылау функцияларын қамтамасыз ету үшін әлеуметтік медициналық сақтандыру қорының қаржылық және өзге де есептілігінің тізбесін, нысандарын, оларды ұсыну мерзімдерін бекіту туралы» 2017 жылғы 16 тамыздағы № 612 бұйрықтарына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171058/rus
