act_code: '88651'
requisite: Приказ и.о. Министра сельского хозяйства Республики Казахстан от 27 февраля 2015 года № 18-03/145. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 апреля 2015 года № 10702
title:
  rus: Об утверждении типовой формы путевки, а также Правил ее выдачи
  kaz: Жолдаманың үлгілік нысанын, сондай-ақ оны беру қағидасын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-02-27
approved_by:
- '103012000000'
version_date:
  kaz: 2024-01-15
  rus: 2024-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/88651/kaz/15.01.2024
  rus: https://zan.gov.kz/client/#!/doc/88651/rus/15.01.2024
caused_by:
  code: '192666'
  requisite: Приказ Министра экологии и природных ресурсов Республики Казахстан от 15 января 2024 года № 6. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 января 2024 года № 33913
  title:
    rus: О внесении изменений и дополнений в приказ исполняющего обязанности Министра сельского хозяйства Республики Казахстан от 27 февраля 2015 года № 18-03/145 «Об утверждении типовой формы путевки, а также Правил ее выдачи»
    kaz: «Жолдаманың үлгілік нысанын, сондай-ақ оны беру қағидасын бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің міндетін атқарушының 2015 жылғы 27 ақпандағы № 18-03/145 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/192666/rus
