act_code: '96693'
requisite: Приказ Министра по инвестициям и развитию Республики Казахстан от 30 октября 2015 года № 1024. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 декабря 2015 года № 12511
title:
  rus: Об утверждении Правил допуска эксплуатанта к авиационным работам
  kaz: Пайдаланушыны авиациялық жұмыстарға рұқсат беру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-10-30
approved_by:
- '103035000000'
version_date:
  kaz: 2025-11-05
  rus: 2025-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/96693/kaz/05.11.2025
  rus: https://zan.gov.kz/client/#!/doc/96693/rus/05.11.2025
caused_by:
  code: '216609'
  requisite: Приказ Министра транспорта Республики Казахстан от 5 ноября 2025 года № 360. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 ноября 2025 года № 37355
  title:
    rus: О внесении изменений в приказ Министра по инвестициям и развитию Республики Казахстан от 30 октября 2015 года № 1024 «Об утверждении Правил допуска эксплуатанта к авиационным работам»
    kaz: «Пайдаланушыны авиациялық жұмыстарға рұқсат беру қағидаларын бекіту туралы» Қазақстан Республикасы Инвестициялар және даму министрінің 2015 жылғы 30 қазандағы № 1024 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/216609/rus
