act_code: '49921'
requisite: Приказ Председателя Агентства Республики Казахстан по информатизации и связи от 4 декабря 2009 года № 491. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 января 2010 года № 5982. Утратил силу приказом и.о. Министра информации и коммуникаций Республики Казахстан от 12 августа 2016 года № 87
title:
  rus: Об утверждении Инструкции по осуществлению транзакционных сервисов "электронного правительства" Республики Казахстан
  kaz: Қазақстан Республикасы "Электрондық үкімет" транзакциялық сервистерін жүзеге асыру бойынша Нұсқаулықты бекіту туралы
form: ПРИК
type_codes:
- ИНСТ
- ПРИК
approved_on: 2009-12-04
approved_by:
- '110000000000'
version_date:
  kaz: 2009-12-04
  rus: 2009-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/49921/kaz/04.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49921/rus/04.12.2009
