act_code: '126430'
requisite: Приказ Министра финансов Республики Казахстан от 19 ноября 2018 года № 1016. Зарегистрирован в Министерстве юстиции Республики Казахстан 26 ноября 2018 года № 17786
title:
  rus: Об определении условий, объема и целевого назначения выпуска государственных ценных бумаг местным исполнительным органом Атырауской области
  kaz: Атырау облысы жергілікті атқарушы органының мемлекеттік бағалы қағаздар шығаруының шарттарын, көлемін және нысаналы мақсатын айқындау туралы
form: ПРИК
type_codes:
- ПРИК
- УСЛ
approved_on: 2018-11-19
approved_by:
- '103002000000'
version_date:
  kaz: 2018-11-19
  rus: 2018-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/126430/kaz/19.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126430/rus/19.11.2018
