act_code: '215075'
requisite: Совместные приказ Министра финансов Республики Казахстан от 18 сентября 2025 года № 508 и постановление Правления Национального Банка Республики Казахстан от 26 сентября 2025 года № 55. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 октября 2025 года № 37016
title:
  rus: Об утверждении Правил определения налогооблагаемого дохода по банковской деятельности, осуществляемой банками второго уровня
  kaz: Екінші деңгейдегі банктер жүзеге асыратын банк қызметі бойынша салық салынатын кірісті айқындау қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2025-09-18
approved_by:
- '103002000000'
- '117000000000'
version_date:
  kaz: 2025-09-18
  rus: 2025-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/215075/kaz/18.09.2025
  rus: https://zan.gov.kz/client/#!/doc/215075/rus/18.09.2025
