act_code: '90093'
requisite: Приказ Министра финансов Республики Казахстан от 31 марта 2015 года № 247. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 мая 2015 года № 10968. Утратил силу приказом Первого заместителя Премьер-Министра Республики Казахстан – Министра финансов Республики Казахстан от 16 января 2020 года № 22 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил рассмотрения и отбора бюджетных инвестиций, направленных на реализацию особо важных и требующих оперативной реализации задач, имеющих положительные предложения Республиканской бюджетной комиссии
  kaz: Аса маңызды және жедел іске асыруды талап ететін міндеттерді іске асыруға бағытталған, Республикалық бюджет комиссиясының оң ұсыныстары бар бюджеттік инвестицияларды қарау және іріктеу қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2015-03-31
approved_by:
- '103002000000'
version_date:
  kaz: 2015-03-31
  rus: 2015-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/90093/kaz/31.03.2015
  rus: https://zan.gov.kz/client/#!/doc/90093/rus/31.03.2015
