act_code: '2949'
requisite: Приказ Председателя Комитета регистрационной службы Министерства юстиции Республики Казахстан от 23 апреля 1999 года N 66. Зарегистрирован в Министерстве юстиции Республики Казахстан 19 мая 1999 года N 768. Утратило силу - приказом Председателя Комитета регистрационной службы Министерства юстиции Республики Казахстан от 25 июля 2007 года N 84
title:
  rus: Об утверждении Правил государственной регистрации юридических лиц и учетной регистрации филиалов и представительств
  kaz: Заңды тұлғаларды мемлекеттік тіркеудің және филиалдар мен өкілдіктерді есептік тіркеудің Ережесі туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 1999-04-22
approved_by:
- '103001001000'
version_date:
  rus: 1999-09-20
source:
  rus: https://zan.gov.kz/client/#!/doc/2949/rus/20.09.1999
caused_by:
  code: '4201'
  requisite: Приказ Председателя Комитета регистрационной службы Министерства юстиции Республики Казахстан от 21 сентября 1999 года N 202. Зарегистрирован в Министерстве юстиции Республики Казахстан 30.09.99г. за N 917. Утратило силу - приказом Председателя Комитета регистрационной службы Министерства юстиции Республики Казахстан от 25 июля 2007 года N 84
  title:
    rus: О внесении изменений и дополнений в приказ председателя Комитета регистрационной службы Министерства юстиции Республики Казахстан от 23 апреля 1999 года N 66
    kaz: Қазақстан Республикасы Әділет министрлігінің Тіркеу қызметі комитеті төрағасының 1999 жылғы 23 сәуірдегі N 66 бұйрығына өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/4201/rus
