act_code: '93652'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 6 мая 2015 года № 19-1/422. Зарегистрирован в Министерстве юстиции 24 июля 2015 года № 11765. Утратил силу приказом Министра экологии, геологии и природных ресурсов Республики Казахстан от 16 ноября 2020 года № 286 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении стандартов государственных услуг в области регулирования использования водного фонда
  kaz: Су қорын пайдалануды реттеу саласындағы мемлекеттік көрсетілетін қызметтердің стандарттарын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2015-05-06
approved_by:
- '103012000000'
version_date:
  kaz: 2018-04-26
  rus: 2018-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/93652/kaz/26.04.2018
  rus: https://zan.gov.kz/client/#!/doc/93652/rus/26.04.2018
caused_by:
  code: '120051'
  requisite: Приказ Заместителя Премьер-Министра Республики Казахстан - Министра сельского хозяйства Республики Казахстан от 15 января 2018 года № 27. Зарегистрирован в Министерстве юстиции Республики Казахстан 27 марта 2018 года № 16656. Утратил силу приказом Министра экологии, геологии и природных ресурсов Республики Казахстан от 16 ноября 2020 года № 286 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в приказ Министра сельского хозяйства Республики Казахстан от 6 мая 2015 года № 19-1/422 «Об утверждении стандартов государственных услуг в области регулирования использования водного фонда»
    kaz: «Су қорын пайдалануды реттеу саласындағы мемлекеттік көрсетілетін қызметтердің стандарттарын бекіту туралы» Қазақстан Республикасы Ауыл шаруашылығы министрінің 2015 жылғы 6 мамырдағы № 19-1/422 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/120051/rus
