act_code: '114201'
requisite: Приказ и.о. Министра образования и науки Республики Казахстан от 11 июля 2017 года № 324. Зарегистрирован в Министерстве юстиции Республики Казахстан 18 августа 2017 года № 15514
title:
  rus: Об утверждении Правил организации учета детей дошкольного и школьного возраста до получения ими среднего образования
  kaz: Мектепке дейінгі жастағы және мектеп жасындағы балалар орта білім алғанға дейін оларды есепке алуды ұйымдастыру қағидаларын бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2017-07-11
approved_by:
- '103006000000'
version_date:
  kaz: 2025-08-29
  rus: 2025-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/114201/kaz/29.08.2025
  rus: https://zan.gov.kz/client/#!/doc/114201/rus/29.08.2025
caused_by:
  code: '213807'
  requisite: Приказ Министра просвещения Республики Казахстан от 29 августа 2025 года № 198. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 августа 2025 года № 36767
  title:
    rus: О внесении изменений и дополнений в некоторые приказы
    kaz: Кейбір бұйрықтарға өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213807/rus
