act_code: '199876'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 19 августа 2024 года № 278. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 августа 2024 года № 34956. Действовал до 31 декабря 2024 года в соответствии с пунктом 6 настоящего приказа
title:
  rus: О некоторых вопросах ввоза пшеницы на территорию Республики Казахстан
  kaz: Қазақстан Республикасының аумағына бидай әкелудің кейбір мәселелері туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2024-08-19
approved_by:
- '103012000000'
version_date:
  kaz: 2024-08-19
  rus: 2024-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/199876/kaz/19.08.2024
  rus: https://zan.gov.kz/client/#!/doc/199876/rus/19.08.2024
repealed_on: 2024-12-31
repealed_by:
  code: '199876'
  requisite: Приказ Министра сельского хозяйства Республики Казахстан от 19 августа 2024 года № 278. Зарегистрирован в Министерстве юстиции Республики Казахстан 20 августа 2024 года № 34956. Действовал до 31 декабря 2024 года в соответствии с пунктом 6 настоящего приказа
  title:
    rus: О некоторых вопросах ввоза пшеницы на территорию Республики Казахстан
    kaz: Қазақстан Республикасының аумағына бидай әкелудің кейбір мәселелері туралы
  link: https://zan.gov.kz/client/#!/doc/199876/rus
