act_code: '55600'
requisite: Приказ и.о. Министра юстиции Республики Казахстан от 3 ноября 2010 года № 302. Зарегистрирован в Министерстве юстиции Республики Казахстан 9 ноября 2010 года № 6624. Утратил силу приказом и.о. Министра юстиции Республики Казахстан от 7 марта 2014 года № 94
title:
  rus: Об утверждении Положения о квалификационных экзаменах
  kaz: '"Біліктілік емтихандары туралы ережені бекіту туралы"'
form: ПРИК
type_codes:
- ПОЛ
- ПРИК
approved_on: 2010-11-03
approved_by:
- '103001000000'
version_date:
  kaz: 2013-10-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/55600/kaz/02.10.2013
caused_by:
  code: '75306'
  requisite: Приказ Министра юстиции Республики Казахстан от 2 октября 2013 года № 309. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 ноября 2013 года № 8882. Утратил силу приказом и.о. Министра юстиции Республики Казахстан от 7 марта 2014 года № 94
  title:
    rus: О внесении изменения в приказ и.о. Министра юстиции Республики Казахстан от 3 ноября 2010 года № 302 "Об утверждении Положения о квалификационных экзаменах"
    kaz: Қазақстан Республикасы Әділет министрінің міндетін атқарушының «Біліктілік емтихандары туралы ережені бекіту туралы» 2010 жылғы 3 қарашадағы № 302 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/75306/rus
