act_code: '30145'
requisite: Приказ Министра охраны окружающей среды Республики Казахстан от 4 октября 2006 года № 295-п. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 ноября 2006 года № 4443. Утратил силу приказом Министра охраны окружающей среды Республики Казахстан от 2 апреля 2010 года № 81-Ө
title:
  rus: Об утверждении базовых ставок платы за загрязнение окружающей среды на 2007 год
  kaz: Қоршаған ортаны ластағаны үшін 2007 жылға арналған төлемдердің базалық ставкаларын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2006-10-04
approved_by:
- '103015000000'
version_date:
  kaz: 2006-10-04
  rus: 2006-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/30145/kaz/04.10.2006
  rus: https://zan.gov.kz/client/#!/doc/30145/rus/04.10.2006
