act_code: '119408'
requisite: Приказ Министра финансов Республики Казахстан от 16 февраля 2018 года № 203. Зарегистрирован в Министерстве юстиции Республики Казахстан 3 марта 2018 года № 16486
title:
  rus: Об определении уполномоченных органов на принятие предварительных решений о классификации товара и о происхождении товара, а также случая принятия территориальным органом государственных доходов решения о классификации товара в несобранном или разобранном виде, в том числе в некомплектном или незавершенном виде, ввоз которого предполагается различными товарными партиями в течение определенного периода времени
  kaz: Тауарды сыныптау туралы және тауардың шығарылған жері туралы алдын ала шешімдерді қабылдауға уәкілетті органдарды, сондай-ақ аумақтық мемлекеттік кірістер органдары белгілі бір уақыт кезеңі ішінде әртүрлі тауар партияларымен әкелінуі болжанатын, құрастырылмаған немесе бөлшектелген түрдегі, оның ішінде жасақталмаған немесе жасалып бітпеген түрдегі тауарды сыныптау туралы шешімді қабылдау жағдайын айқындау туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2018-02-16
approved_by:
- '103002000000'
version_date:
  kaz: 2019-09-18
  rus: 2019-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/119408/kaz/18.09.2019
  rus: https://zan.gov.kz/client/#!/doc/119408/rus/18.09.2019
caused_by:
  code: '134849'
  requisite: Приказ Первого заместителя Премьер-Министра Республики Казахстан – Министра финансов Республики Казахстан от 18 сентября 2019 года № 1015. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 сентября 2019 года № 19407
  title:
    rus: О внесении изменения в приказ Министра финансов Республики Казахстан от 16 февраля 2018 года № 203 «Об определении уполномоченных органов на принятие предварительных решений о классификации товара и о происхождении товара, а также случая принятия территориальным органом государственных доходов решения о классификации товара в несобранном или разобранном виде, в том числе в некомплектном или незавершенном виде, ввоз которого предполагается различными товарными партиями в течение определенного периода времени»
    kaz: «Тауарды сыныптау туралы және тауардың шығарылған жері туралы алдын ала шешімдерді қабылдауға уәкілетті органдарды, сондай-ақ аумақтық мемлекеттік кірістер органдары белгілі бір уақыт кезеңі ішінде әртүрлі тауар партияларымен әкелінуі болжанатын, құрастырылмаған немесе бөлшектелген түрдегі, оның ішінде жасақталмаған немесе жасалып бітпеген түрдегі тауарды сыныптау туралы шешімді қабылдау жағдайын айқындау туралы» Қазақстан Республикасы Қаржы министрінің 2018 жылғы 16 ақпандағы № 203 бұйрығына өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134849/rus
