act_code: '147884'
requisite: Приказ и.о. Министра здравоохранения Республики Казахстан от 27 октября 2020 года № ҚР ДСМ-159/2020. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 октября 2020 года № 21528
title:
  rus: Об утверждении правил определения иммунологической совместимости тканей при трансплантации органов (части органа) и(или) тканей (части ткани) и положения о деятельности HLA-лаборатории
  kaz: Ағзаларды (ағзаның бөлігін) және(немесе) тіндерді (тіннің бөлігін) транспланттау кезінде иммунологиялық үйлесімділігін айқындау қағидаларын және HLA-зертханасының қызметі туралы ережені бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2020-10-27
approved_by:
- '103010000000'
version_date:
  kaz: 2021-09-30
  rus: 2021-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/147884/kaz/30.09.2021
  rus: https://zan.gov.kz/client/#!/doc/147884/rus/30.09.2021
caused_by:
  code: '159179'
  requisite: Приказ Министра здравоохранения Республики Казахстан от 30 сентября 2021 года № КР ДСМ -101. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 октября 2021 года № 24615
  title:
    rus: О внесении изменений в приказ исполняющего обязанности Министра здравоохранения Республики Казахстан от 27 октября 2020 года № ҚР ДСМ-159/2020 «Об утверждении правил определения иммунологической совместимости тканей при трансплантации органов (части органа) и (или) тканей (части ткани) и положения о деятельности HLA-лаборатории»
    kaz: «Ағзаларды (ағзаның бөлігін) және (немесе) тіндерді (тіннің бөлігін) транспланттау кезінде иммунологиялық үйлесімділігін айқындау қағидаларын және HLA-зертханасының қызметі туралы ережені бекіту туралы» Қазақстан Республикасы Денсаулық сақтау министрінің міндетін атқарушының 2020 жылғы 27 қазандағы № ҚР ДСМ-159/2020 бұйрығына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159179/rus
