act_code: '21307'
requisite: Приказ Министра транспорта и коммуникаций Республики Казахстан от 31 августа 2004 года № 324-I. Зарегистрирован в Министерстве юстиции Республики Казахстан 16 сентября 2004 года № 3069. Утратил силу приказом и.о. Министра по инвестициям и развитию Республики Казахстан от 5 февраля 2015 года № 110
title:
  rus: Об утверждении Правил осуществления контроля за соблюдением перевозчиками Правил перевозок пассажиров, багажа и грузобагажа железнодорожным транспортом Республики Казахстан, утвержденных постановлением Правительства Республики Казахстан от 14 июля 2011 года № 799 "Об утверждении Правил перевозок пассажиров, багажа и грузобагажа железнодорожным транспортом"
  kaz: '"Жолаушыларды, багажды және жүк-багажды темір жол көлігімен тасымалдау қағидасын бекіту туралы" Қазақстан Республикасы Үкіметінің 2011 жылғы 14 шілдедегі № 799 қаулысымен бекітілген Қазақстан Республикасында темір жол көлігімен жолаушыларды, багажды және жүк-багажын тасымалдау қағидаларын тасымалдаушылардың сақтауын бақылауды жүзеге асыру қағидаларын бекіту туралы'
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2004-08-30
approved_by:
- '103013000000'
version_date:
  kaz: 2006-03-09
  rus: 2006-03-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/21307/kaz/09.03.2006
  rus: https://zan.gov.kz/client/#!/doc/21307/rus/09.03.2006
caused_by:
  code: '27036'
  requisite: Приказ Министра транспорта и коммуникаций Республики Казахстан от 9 марта 2006 года N 70. Зарегистрирован в Министерстве юстиции Республики Казахстан от 3 апреля 2006 года N 4169. Утратил силу приказом и.о. Министра по инвестициям и развитию Республики Казахстан от 5 февраля 2015 года № 110
  title:
    rus: О внесении дополнения и изменения в приказ Министра транспорта и коммуникаций Республики Казахстан от 31 августа 2004 года N 324-I "Об утверждении Правил осуществления контроля за соблюдением перевозчиками Правил перевозок пассажиров, багажа и грузобагажа железнодорожным транспортом Республики Казахстан, утвержденных приказом Министра транспорта и коммуникаций Республики Казахстан от 18 марта 2004 года N 122-I, зарегистрированных за N 2810"
    kaz: '"Қазақстан Республикасы Көлік және коммуникациялар министрінің 2004 жылғы 18 наурыздағы N 122-І бұйрығымен бекітілген, 2810 нөмірмен тіркелген" Қазақстан Республикасында темір жол көлігімен жолаушыларды, багажды және жүк-багажды тасымалдау ережесін тасымалдаушылардың сақтауын бақылауды жүзеге асыру ережесін бекіту туралы" Қазақстан Республикасы Көлік және коммуникациялар министрінің 2004 жылғы 31 тамыздағы N 324-І бұйрығына толықтыру мен өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/27036/rus
