act_code: '159873'
requisite: Приказ Министра культуры и спорта Республики Казахстан от 27 октября 2021 года № 332. Зарегистрирован в Министерстве юстиции Республики Казахстан 29 октября 2021 года № 24950. Утратил силу приказом Министра туризма и спорта Республики Казахстан от 9 июня 2026 года № 97 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении карты туристификации
  kaz: Туристендіру картасын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2021-10-27
approved_by:
- '103034000000'
version_date:
  kaz: 2025-07-15
  rus: 2025-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/159873/kaz/15.07.2025
  rus: https://zan.gov.kz/client/#!/doc/159873/rus/15.07.2025
caused_by:
  code: '212432'
  requisite: Приказ Министра туризма и спорта Республики Казахстан от 15 июля 2025 года № 131. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 июля 2025 года № 36457
  title:
    rus: О внесении изменений в некоторые приказы Министра туризма и спорта Республики Казахстан
    kaz: Қазақстан Республикасы Туризм және спорт министрінің кейбір бұйрықтарына өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212432/rus
