act_code: '214656'
requisite: Приказ Министра сельского хозяйства Республики Казахстан от 22 сентября 2025 года № 312. Зарегистрирован в Министерстве юстиции Республики Казахстан 23 сентября 2025 года № 36909
title:
  rus: Об утверждении типовой формы договора на осуществление садковой хозяйственной деятельности на участках рыбохозяйственных водоемов международного и (или) республиканского значения для реализации проекта
  kaz: Жобаны іске асыру үшін халықаралық және (немесе) республикалық маңызы бар балық шаруашылығы су айдындарының учаскелерінде  тор қоршама шаруашылық қызметін жүзеге асыруға арналған шарттың үлгілік нысанын бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2025-09-22
approved_by:
- '103012000000'
version_date:
  kaz: 2025-09-22
  rus: 2025-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/214656/kaz/22.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214656/rus/22.09.2025
