act_code: '125256'
requisite: Приказ Министра образования и науки Республики Казахстан от 13 октября 2018 года № 569. Зарегистрирован в Министерстве юстиции Республики Казахстан 17 октября 2018 года № 17565
title:
  rus: Об утверждении Классификатора направлений подготовки кадров с высшим и послевузовским образованием
  kaz: Жоғары және жоғары оқу орнынан кейінгі білімі бар кадрларды даярлау бағыттарының сыныптауышын бекіту туралы
form: ПРИК
type_codes:
- КЛАС
- ПРИК
approved_on: 2018-10-13
approved_by:
- '103006000000'
version_date:
  kaz: 2019-06-03
  rus: 2019-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/125256/kaz/03.06.2019
  rus: https://zan.gov.kz/client/#!/doc/125256/rus/03.06.2019
caused_by:
  code: '132245'
  requisite: Приказ Министра образования и науки Республики Казахстан от 3 июня 2019 года № 252. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 июня 2019 года № 18794
  title:
    rus: О внесении изменений и дополнений в приказ Министра образования и науки Республики Казахстан от 13 октября 2018 года № 569 «Об утверждении Классификатора направлений подготовки кадров с высшим и послевузовским образованием»
    kaz: «Жоғары және жоғары оқу орнынан кейінгі білімі бар кадрларды даярлау бағыттарының сыныптауышын бекіту туралы» Қазақстан Республикасы Білім және ғылым министрінің 2018 жылғы 13 қазандағы № 569 бұйрығына өзгерістер және толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132245/rus
