act_code: '131269'
requisite: Приказ Первого заместителя Премьер-Министра Республики Казахстан – Министра финансов Республики Казахстан от 30 апреля 2019 года № 411. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 мая 2019 года № 18633. Утратил силу приказом Министра финансов Республики Казахстан от 6 октября 2025 года № 573 (вводится в действие с 1 января 2026 года)
title:
  rus: Об утверждении формы решения о признании уведомления об устранении нарушений, выявленных органами государственных доходов по результатам камерального контроля, не исполненным, и сроков его вынесения
  kaz: Камералдық бақылау нәтижелерi бойынша мемлекеттік кірістер органдары анықтаған бұзушылықтарды жою туралы хабарламаны орындалмаған деп тану туралы шешімнің нысанын және оны шығару мерзімін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
approved_on: 2019-04-30
approved_by:
- '103002000000'
version_date:
  kaz: 2024-03-01
  rus: 2024-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/131269/kaz/01.03.2024
  rus: https://zan.gov.kz/client/#!/doc/131269/rus/01.03.2024
caused_by:
  code: '193937'
repealed_on: 2026-01-01
repealed_by:
  code: '215387'
  requisite: Приказ Министра финансов Республики Казахстан от 6 октября 2025 года № 573. Зарегистрирован в Министерстве юстиции Республики Казахстан 8 октября 2025 года № 37084
  title:
    rus: Об утверждении форм решений органа государственных доходов по вопросам сопоставительного контроля выписки электронных счетов-фактур
    kaz: Электрондық шот-фактураларды жазып беруді салыстырмалы бақылау мәселелері бойынша мемлекеттік кірістер органының шешімдері нысандарын бекіту туралы
  link: https://zan.gov.kz/client/#!/doc/215387/rus
