act_code: '35288'
requisite: Приказ и.о. Министра труда и социальной защиты населения Республики Казахстан от 27 сентября 2007 года № 223-п. Зарегистрирован в Министерстве юстиции Республики Казахстан 10 октября 2007 года № 4963. Утратил силу приказом Министра внутренних дел Республики Казахстан от 30 марта 2011 года № 134
title:
  rus: Об утверждении Правил пребывания лиц и членов их семей, ходатайствующих о признании их оралманами, в Центре временного размещения
  kaz: Өздерін оралман деп тануға ұсынған адамдар мен олардың отбасы мүшелерінің уақытша орналастыру орталығында болу Ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2007-09-27
approved_by:
- '103016000000'
version_date:
  kaz: 2007-09-27
  rus: 2007-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/35288/kaz/27.09.2007
  rus: https://zan.gov.kz/client/#!/doc/35288/rus/27.09.2007
