act_code: '98739'
requisite: Совместный приказ Министра по инвестициям и развитию Республики Казахстан от 23 декабря 2015 года № 1230 и Министра национальной экономики Республики Казахстан от 30 декабря 2015 года № 837. Зарегистрирован в Министерстве юстиции Республики Казахстан 31 декабря 2015 года № 12793
title:
  rus: Об утверждении критериев оценки степени риска для отбора субъектов (объектов) контроля, проверочных листов в области энергосбережения и повышения энергоэффективности
  kaz: Энергия үнемдеу және энергия тиімділігін арттыру саласындағы бақылау субъектілерін (объектілерін) іріктеу үшін тәуекел дәрежесін бағалау өлшемшарттарын, тексеру парақтарын бекіту туралы
form: ПРИК
type_codes:
- КРИТ
- ПРИК
approved_on: 2015-12-23
approved_by:
- '103035000000'
version_date:
  kaz: 2016-05-31
  rus: 2016-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/98739/kaz/31.05.2016
  rus: https://zan.gov.kz/client/#!/doc/98739/rus/31.05.2016
caused_by:
  code: '104752'
  requisite: Совместный приказ Министра по инвестициям и развитию Республики Казахстан от 31 мая 2016 года № 454 и Министра национальной экономики Республики Казахстан от 9 июня 2016 года № 248. Зарегистрирован в Министерстве юстиции Республики Казахстан 11 июля 2016 года № 13899
  title:
    rus: О внесении изменений и дополнений в совместный приказ Министра по инвестициям и развитию Республики Казахстан от 23 декабря 2015 года № 1230 и исполняющего обязанности Министра национальной экономики Республики Казахстан от 30 декабря 2015 года № 837 "Об утверждении критериев оценки степени риска и проверочных листов в области энергосбережения и повышения энергоэффективности"
    kaz: '"Энергия үнемдеу және энергия тиімділігін арттыру саласындағы тәуекел дәрежесін бағалау өлшемшарттары мен тексеру парақтарын бекіту туралы" Қазақстан Республикасы Инвестициялар және даму министрінің 2015 жылғы 23 желтоқсандағы № 1230 және Қазақстан Республикасы Ұлттық экономика министрінің міндетін атқарушының 2015 жылғы 30 желтоқсандағы № 837 бірлескен бұйрығына өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/104752/rus
