act_code: '218577'
requisite: Приказ Министра экологии и природных ресурсов Республики Казахстан от 4 декабря 2025 года № 328-П
title:
  rus: Об утверждении перечня персональных данных необходимого и достаточного для выполнения осуществляемых задач
  kaz: Жүзеге асырылатын міндеттерді орындау үшін қажетті және жеткілікті дербес деректердің тізбесін бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ПРЧ
approved_on: 2025-12-04
approved_by:
- '103047000000'
version_date:
  kaz: 2025-12-04
  rus: 2025-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/218577/kaz/04.12.2025
  rus: https://zan.gov.kz/client/#!/doc/218577/rus/04.12.2025
