act_code: '13053'
requisite: Приказ Председателя Агентства Республики Казахстан по туризму и спорту от 26 июля 2002 года № 06-2-2/163. Зарегистрирован в Министерстве юстиции Республики Казахстан 24 августа 2002 года № 1961. Утратил силу приказом и.о. Министра туризма и спорта Республики Казахстан от 5 марта 2011 года № 02-02-18/29
title:
  rus: Об утверждении Правил присвоения квалификационных категорий тренерско-преподавательскому составу
  kaz: Жаттықтырушы-оқытушылар құрамына біліктілік санаттарын берудің Ережесін бекіту туралы
form: ПРИК
type_codes:
- ПРАВ
- ПРИК
approved_on: 2002-07-25
approved_by:
- '103014000000'
version_date:
  kaz: 2002-07-25
  rus: 2002-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/13053/kaz/25.07.2002
  rus: https://zan.gov.kz/client/#!/doc/13053/rus/25.07.2002
