act_code: '50748'
requisite: Приказ Министра обороны Республики Казахстан от 28 декабря 2009 года № 498. Зарегистрирован в Министерстве юстиции Республики Казахстан 5 февраля 2010 года № 6033. Утратил силу приказом Министра обороны Республики Казахстан от 29 января 2013 года № 37
title:
  rus: Об утверждении требований, предъявляемых к соответствию состояния здоровья лиц для службы в Вооруженных Силах, других войсках и воинских формированиях Республики Казахстан
  kaz: Қазақстан Республикасының Қарулы Күштерінде, басқа да әскерлері мен әскери құралымдарында қызмет ету үшін адамдар денсаулық жағдайының сәйкес келуіне қойылатын талаптарды бекіту туралы
form: ПРИК
type_codes:
- ПРИК
- ТРЕБ
approved_on: 2009-12-28
approved_by:
- '103008000000'
version_date:
  kaz: 2009-12-28
  rus: 2009-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/50748/kaz/28.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50748/rus/28.12.2009
